### ISSUE TITLE
Add filter for attributes in Google Analytics

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1002]
Requested here: https://wordpress.org/support/topic/plugin-not-capturing-ecommerce/#post-9343731
This specifically is for cloudflare support.

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/add-attribute-to-google-analytics/

**Comment by michaeltorbert** [comment]
@wpsmort In testing, make sure that a) I didn't break anything and that b) the filter hook works.

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and is good.  I had to make some changes to the documentation for the filter hook in order for that to work as it was missing a semicolon and the return $attributes.
