### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1004]
From private PM

"I've also found integration of Travis with GitHub to be extremely useful and it is free for public repositories."

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1532

Steps to enable travis on the repo:
1. Go to the profile and enable the repo for Travis (e.g. https://travis-ci.org/profile/contactashish13)
![image](https://user-images.githubusercontent.com/12953439/35511512-37203c9c-0522-11e8-95e9-573f9e214226.png)

2. Go to the repo's settings and configure specifics (e.g. https://travis-ci.org/contactashish13/all-in-one-seo-pack/settings)

![image](https://user-images.githubusercontent.com/12953439/35511488-2124ee9c-0522-11e8-99e6-2f392d9506fd.png)

3. Done!

Every PR will now fire the build.

This is how the build looks once it succeeds (e.g. https://travis-ci.org/contactashish13/all-in-one-seo-pack/builds/334685598?utm_source=github_status&utm_medium=notification)

![image](https://user-images.githubusercontent.com/12953439/35511545-5a17d8e0-0522-11e8-8b87-ae0c286e4576.png)

Thanks to Travis, I uncovered that **another** of my changes had resulted in bumping up the minimum supported WP version to 4.4 so it has already proved useful.

**Comment by michaeltorbert** [comment]
@contactashish13 I think this has been done correctly.

**Comment by contactashish13** [comment]
Note: The build will show 5.2 and 5.3 as successful but that's a false positive because Travis configuration makes us specify php 5.2 and 5.3 only in the "precise" distro of Travis. I don't know if its paid - https://docs.travis-ci.com/user/reference/precise/

**Comment by contactashish13** [comment]
closing this as this is now complete
