### ISSUE TITLE
Remove capitalize categories functionality

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1006]
In version 2.3.10 we removed the option for Capitalize Category Titles and replaced it with a filter hook.  Issue #531 refers.

We should now remove the code associated with capitalizing category titles.

See also #530 for removing the same functionality for Capitalize Tag and Search Titles.

**Comment by michaeltorbert** [comment]
Notes for posterity:

These options
a) added little to no SEO value
b) caused more problems than they were worth (mostly they would just override what people wanted, and at best would do nothing)... AIOSEOP isn't the grammar/capitalization police
c) When searching .org support and our own support... every single mention (over the past 9 years) of the feature was of a user having problems with it except for one person

**Comment by wpsmort** [comment]
This is tested and is good.
