### ISSUE TITLE
Social Meta module - Remove Facebook Object Type option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1011]
Remove the Facebook Object Type option under Social Meta > Facebook Settings.

Instead we'll default to Website for the homepage regardless of whether it's a static home page or dynamic homepage.  

The aiosp_opengraph_meta filter can be used for those who want to change the og:type value.

**Comment by michaeltorbert** [comment]
We're also removing the hometags options, as that only showed up when the homepage was set to article.

**Comment by wpsmort** [comment]
This is tested and is good.
