### ISSUE TITLE
Social Meta module - Remove Blog from Object Type drop downs

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1013]
Blog is no longer a valid og:type (http://ogp.me/#types) so we should remove it from the drop downs found under Social Meta > Facebook Settings > Object Type (there are drop downs for each post type). 

https://semperplugins.com/documentation/social-meta-module/#content-object-types

**Comment by wpsmort** [comment]
Blog also needs to be removed from the Facebook Object Type drop down on the Social Settings tab of the Edit Post screen.

**Comment by wpsmort** [comment]
@michaeltorbert I was hoping this was a simple change of just removing Blog from the drop down array in aioseop_opengraph.php.  However, we need to account for anyone who has selected Blog as their Object Type.  

If I have set one of the Object Type drop downs under Social Meta > Facebook Settings to Blog then removing that as a selection means that the Object Type reverts to the first available type which is Activity.  This is incorrect, if someone had selected Blog then we should change it to Article.

If I set the Object Type on the Social Settings tab of the Edit Post screen to Blog and we remove it then it changes to nothing and I get a PHP Notice:

PHP Notice:  Undefined index: blog in/wp-content/plugins/all-in-one-seo-pack-2.3.15/modules/aioseop_opengraph.php on line 733

Instead we should revert them to Article. 

I'm pushing this to the next release as it doesn't need to hold up this release.

**Comment by michaeltorbert** [comment]
This will probably require a db migration for the entry and/or we may want to just check for that and use website if they have blog.

**Comment by amostajo** [comment]
@wpsmort ready for testing. I have added the migration for when version switches to `2.3.17`. Haven't changed version on code though,

**Comment by michaeltorbert** [comment]
@amostajo What does "Haven't changed version on code though" mean?

**Comment by amostajo** [comment]
Means that I have not changed/pish the version of the plugin to 2.3.17, cuz I thing this is something you usually do.

**Comment by wpsmort** [comment]
@amostajo I tested PR #1112 and found three issues:

1). When I update to this version I get the following error during the DB migration:

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''s:35:\"aioseop_opengraph_settings_category\"' at line 2 for query UPDATE wp_postmeta
SET meta_value = replace(meta_value,'s:35:\"aioseop_opengraph_settings_category\" made by require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, AIOSEOP_Updates->version_updates, AIOSEOP_Updates->do_version_updates, AIOSEOP_Updates->db_migrate_og_type_201708, dbDelta

2). When I edit a post in a post type where the Object Type was previously set to Blog and click on the Social Settings tab I get this notice:

PHP Notice:  Undefined index: blog in /all-in-one-seo-pack/modules/aioseop_opengraph.php on line 737

3). If an Object Type was previously set to Blog under Social Meta > Facebook Settings then it now defaults to Activity because that's the very first type in the drop down.  Instead it should default to Article.

Let me know if you need steps to reproduce any of these.

**Comment by amostajo** [comment]
@wpsmort I have tested and validated that the migration is working and it is modifying the `og:type`. Please test this again.

I have also added update notices, so the plugin informs the user about the update done.

**NOTE:** To test this PR, change plugin to version 2.4

**Comment by michaeltorbert** [comment]
@amostajo  This needs to be tested on sites with a lot of posts (there should be post-generator plugins) and not a ton of memory.
Can you determine how much memory per x posts this consumes?

Also, do we we want to have the update user-initiated? ie "click here to do the database update"

**Comment by wpsmort** [comment]
@michaeltorbert I don't think we want to make the update user initiated.  If they are using Blog as their OG type then it should be changed as Blog is no longer valid and they may not realize this.

**Comment by michaeltorbert** [comment]
That's fine, we can just add it to our normal db upgrades

**Comment by contactashish13** [comment]
@wpsmort I'm closing PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1112 in favor of a new PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2232 as I'm not sure a db migration is the right way to do this. I'm instead in favor of what Michael suggested: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1013#issuecomment-320063342
