### ISSUE TITLE
Two array keys for setcard

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1016]
In /modules/aioseop_opengraph.php lines 160 and 178 in the help_anchors array, we have setcard twice. Any idea if that was on purpose or a mistake?

**Comment by wpsmort** [comment]
@michaeltorbert I have tested this and it doesn't look like the setcard on line 170 is used at all.  The setcard on line 188 is used for the documentation link on the Social Settings tab of the Edit Post screen
