### ISSUE TITLE
Never Shorten Long Descriptions no longer works

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1022]
Auto generated meta descriptions are still being shortened even when you enable the Never Shorten Long Descriptions option and the Use Content For Autogenerated Descriptions options together under Advanced Settings.

If you don't enable the Use Content For Autogenerated Descriptions option then auto generated meta descriptions are not shortened.

I tested back through the versions and found that this has never worked.

**Comment by amostajo** [comment]
Ready for testing. [PR1083](https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1083)

**Comment by wpsmort** [comment]
This is tested and is good.  PR #1083 is ready for code review.

**Comment by amostajo** [comment]
@wpsmort changes made for #951 fixes this issue as well. Please re-test this using PR 1031
https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1031

**Comment by wpsmort** [comment]
PR #1031 is tested and is good.

Enabling the Never Shorten Long Descriptions option now works regardless of whether you are using the excerpt or the content as the auto generated meta description.
