### ISSUE TITLE
Video XML Sitemap - Improve appearance of thumbnails

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1028]
In Issue https://github.com/semperfiwebdesign/aioseop-pro/issues/289 we added thumbnails for videos in the Video XML Sitemap.  We should improve the appearance of the videos, especially when they span multiple rows.  

I originally made this commit https://github.com/semperfiwebdesign/aioseop-pro/commit/d97198d0f791152409eb84eb527772972e68d3b9 to add some CSS but I committed to Pro when this code should be in free.

**Comment by wpsmort** [comment]
This is done and tested.  PR #1065 is ready for final review.

**Comment by michaeltorbert** [comment]
Done.
