### ISSUE TITLE
Improve handling of shortcodes in manually entered descriptions

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1035]
This was originally reported by a user in issue #943.

We attempted to resolve this in Version 2.3.15.  

However, the solution caused a fatal timeout on many sites, see issue #1032 so we rolled back the changes.

We need to allow users to use brackets in manually entered SEO and OG Descriptions and leave auto generated descriptions alone.

**Comment by amostajo** [comment]
@wpsmort I have removed the line that was replacing brackets as a whole.

I have tested this solution on the breaking WP that was mounted yesterday due to a little line in the regex related to this issue.

We might need extensive testing on this with more breaking environments.., I would suggest if there is a possibility of mounting more breaking environments from other users as well.

**Comment by michaeltorbert** [comment]
"we don't intend to change anything with autogenerated descriptions, we just want to fix a bug with outputting shortcodes manually entered in the SEO and OG description fields." - @wpsmort

**Comment by wpsmort** [comment]
We should allow users to enter text that contains brackets in the SEO and OG description fields.  Currently we strip out the brackets and anything inside them.

To test, manually enter an SEO and OG description that has brackets and check that this is correctly output in the source code.  

Autogenerated Descriptions should be unaffected by this.

**Comment by amostajo** [comment]
Also... if setting to "run shortcodes" is on, I am not wiping out brackets. What do you think?

**Comment by amostajo** [comment]
Well. title always allows brackets.

**Comment by amostajo** [comment]
@wpsmort ready for testing

**Comment by wpsmort** [comment]
@amostajo I tested PR #1039 and found one minor issue.  The placeholder text in the OG Description field does not match what is output in the source code.  This happens when you enter an SEO description with brackets and leave the OG description empty.  In this instance, the OG description should be taken from the SEO description so the placeholder text should match exactly what's typed in the SEO description field.  See screenshots:

<img width="1176" alt="screen shot 2017-09-25 at 4 20 49 pm" src="https://user-images.githubusercontent.com/17548525/30829449-c897039e-a20e-11e7-89ae-9ff5f98241bd.png">

<img width="1173" alt="screen shot 2017-09-25 at 4 22 26 pm" src="https://user-images.githubusercontent.com/17548525/30829448-c86175d0-a20e-11e7-93af-c3a3eb25d44f.png">

**Comment by contactashish13** [comment]
@wpsmort @arnaudbroes WP considers any text within [ ] to be a shortcode, so is this minor issue a valid test case?

**Comment by dan-at-unkubed** [comment]
I went searching for some help with shortcodes inside of AIOSP fields, and I found this issue. Sounds like it's still in active development. Would it be possible to allow for the parsing of shortcodes within manual title and description fields?  Might need a setting on the plugin options page to still allow for square brackets in these fields that don't get parsed for shortcodes.  Probably defaulting in that direction, actually as that is the current functionality.  Shortcodes are, after all, core Wordpress functionality.  I'm trying to find a solution for when we want to update the current year in these seo fields without having to manually change every single one for hundreds of pages. Would be of significant help in this instance.

**Comment by michaeltorbert** [comment]
WP considers any text within [] to be a shortcode, but, we're talking about manually entered descriptions. We need to assume that brackets manually entered in (OG) descriptions are meant to be brackets, not shortcodes. 
Anyone with the edge case of wanting to run shortcodes in their manually entered descriptions should be using our description filter hooks.

**Comment by Garconis** [comment]
I think a simple "Allow shortcodes in descriptions?" would have been more ideal here.
