### ISSUE TITLE
500 Server Error when attempting to load All in Once SEO sitemap

### ISSUE THREAD

**Issue by efalquero** [semperfiwebdesign/all-in-one-seo-pack#1038]
Hello,

Yesterday, I updated All in One SEO Pack on my organization's website. We've used the plugin in for a long time for SEO only. But before the long-deferred update, I started reading your documentation and learned of all the other great things in the pack: social meta, xml sitemap, etc.

I configured the sitemap, but have not yet been able to get it to work correctly. Whenever I follow the hyperlink from the plugin or type in the address directly (http://streetsense.org/sitemap.xml) I received a 500 Server Error.

After some more reading today, I thought the issue may be related to an update your team dealt with yesterday (https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1032).

But I just updated again with no luck. I also, just in case, disabled the auto descriptions that were helping alleviate the issue for others yesterday. Now I receive a slightly different internal server error, that notes an additional 500 Server Error.

![internal server error august 4](https://user-images.githubusercontent.com/30736330/28987467-5f94d158-7939-11e7-80a4-67cfccae3ac2.JPG)

I also double-checked our permalink settings and, based on the documentation on your site, believe they comply. They generate pretty permalinks, albeit dynamically.

![permalink settings](https://user-images.githubusercontent.com/30736330/28987550-ad95c934-7939-11e7-9698-916ec107e547.JPG)

Thank you so much for any and all guidance.

**Comment by michaeltorbert** [comment]
@efalquero This isn't a support forum. The others were reporting a bug, unrelated to the issue you're having.
Premium support is available for Pro customers: https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by efalquero** [comment]
Got it. I was just thinking maybe there was a bug causing this too since I was receiving a similar message to those other users. Thank you.

**Comment by michaeltorbert** [comment]
@efalquero If you're still getting this error, please submit your login information here and we'll look into it https://semperplugins.com/contact/submit-login-information/ 
Make sure to reference this issue URL.

**Comment by efalquero** [comment]
Hi Michael,

Thank you very much for the offer - especially reaching out on the weekend.

I didn't know where to begin yesterday on isolating a configuration error or finding a plug-in conflict if this wasn't a bug. So I tried disabled the XML feature on AIO and installing Google XML Sitemap, which resolved the error.

I can revert to our earlier state and share access if it's worth checking on to you. But we'll be okay if not.

Thank you,
Eric

**Comment by michaeltorbert** [comment]
@efalquero We'd definitely like to discover what the problem is, for the sake of your blogs as well as for other users if it's not isolated to you.

**Comment by wpsmort** [comment]
@efalquero This is an out of memory issue when trying to load anything to do with your Articles custom post type.  The 500 error also happens occasionally when you try to go to the All Articles screen here - http://streetsense.org/wp-admin/edit.php?post_type=article.  You need to increase the memory allocated to PHP (https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP) and then use Sitemap Indexes and the pagination settings to resolve this.

**Comment by efalquero** [comment]
Got it - and I see you addressed that directly in the AIO performance tab pushing the memory to 258MB. Thank you for you help! Glad to be using AIO for all of this.

**Comment by wpsmort** [comment]
@efalquero You still need to increase the memory allocated to PHP and if that doesn't work then you'll need to contact your hosting provider to have them increase the memory allocated to PHP.

**Comment by efalquero** [comment]
Got it - I just tried the wp-config amendment you linked me to, raising the limit to 158 and the max/admin limit to 256, but it remains at 90 (streetsense.org/myphpinfo.php). Probably because we're on a shared server plan. I'll contact the host. You'd gone above and beyond in your guidance on this. Thank you!
