### ISSUE TITLE
Social Meta Module - Add support for the og:locale tag

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#104]
Add support for og:locale - https://developers.facebook.com/docs/opengraph/guides/internationalization

We could take the og:locale from the Site Language setting in WordPress and offer a drop down to select a different locale.  We could also consider including an advanced option to select multiple locales as og:locale:alternate.

**Comment by michaeltorbert** [comment]
Closing as a dupe of #737
