### ISSUE TITLE
Bug in date templates

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1050]
Reported here: https://www.facebook.com/captain.alexlion/posts/1873947676187857

Regarding our new date template tags... 

I *think he's saying that either a) the help text is wrong and/or b) the functionality is wrong... 

All in One SEO Pack 的開發者，在英文介面的撰寫能力上，有待加強。
新增的四條，其中一條是之前他漏的，剩下三條除了變數名稱變了之外，說明文字全是錯的。
Current Date 是之前另一個變數的說明，現在全部複製給新的三個變數，變成這三個變數的說明是錯的。
我怎麼知道的？因為我有測試知道正確結果啊...

From Bing translate:
_All in one SEO Pack, in the writing capacity of the English interface, needs to be strengthened.
The new four articles, one of which was before he left, and the remaining three, except for variable names, were all wrong.
Current date is a description of the previous variable, which is now fully copied to the new three variables, and the description of these three variables is wrong.
How do I know? Because I have a test to know the right results..._

From Google translate:

_All in One SEO Pack developers, in the English language writing ability, to be strengthened.
The addition of four, one of which is before he missed, the remaining three in addition to variable name changed, the description of the text is wrong.
Current Date is a description of another variable before, and now all copied to the new three variables, the description of these three variables is wrong.
How do i know Because i have the test to know the correct result ah ..._

**Comment by michaeltorbert** [comment]
Ok yep we definitely missed the help text descriptions for the new 3 tags.

**Comment by wpsmort** [comment]
@michaeltorbert I've updated the inline help - PR #1057.  I tested thoroughly and each post date format worked fine in every format field where it is supported.

**Comment by michaeltorbert** [comment]
This is good.
