### ISSUE TITLE
PHP Fatal Error: Uncaught Error: [] operator not supported for strings (version 2.4.15.3)

### ISSUE THREAD

**Issue by leehblue** [semperfiwebdesign/all-in-one-seo-pack#1051]
After upgrading to version 2.4.15.3 our entire site was taken down by a 500 server error.

[error] 8335#8335: *161441 "PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /www/wp-content/plugins/all-in-one-seo-pack-pro/pro/functions_general.php:211
Stack trace:
#0 /www/wp-includes/class-wp-hook.php(298): aioseop_opengraph_display('')
#1 /www/wp-includes/plugin.php(203): WP_Hook->apply_filters('', Array)
#2 /www/wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_opengraph.php(557): apply_filters('aioseop_opengra...', '')
#3 /www/wp-includes/class-wp-hook.php(298): All_in_One_SEO_Pack_Opengraph->init('')
#4 /www/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#5 /www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /www/wp-settings.php(451): do_action('init')
#7 /www/wp-config.php(87): require_once('/www/wp-setting...')
#8 /www/wp-load.php(37): require_once('/www/wp-config....')
#9 /www/wp-admin/admin.php(31): require_once('/www/wp-load.ph...')
#10 /www/wp-admin/plugin-install.php(15): require_once('/www/wp-admin/a...')

**Comment by michaeltorbert** [comment]
@leehblue Thanks for reporting this. We're looking into it now.

**Comment by michaeltorbert** [comment]
@leehblue Thanks for reporting this. We're looking into it now. 
What version of PHP are you running?

**Comment by leehblue** [comment]
We're running on FlyWheel and it looks like their running PHP 7.1 based on this FAQ https://getflywheel.com/wordpress-support/php-7-faq/

I'm not sure how to check the exact version of PHP myself as they seem to block `phpinfo()` output on their servers.

**Comment by michaeltorbert** [comment]
@leehblue I've just set up a new site on Flywheel's Local app now for testing.

Does the Performance module tell you the PHP version?
This is almost certainly a PHP 7 issue, but it's nice to have confirmation. :)

**Comment by leehblue** [comment]
Ah! Great idea! Yes, it does. PHP 7.1 Confirmed.
PHP Version: 7.1.7-1+ubuntu16.04.1+deb.sury.org+1

**Comment by michaeltorbert** [comment]
@leehblue 
I'm pretty sure I know the problem and fix, but I can't test without being able to reproduce it. On my dev site with 7.1.3 I don't get the error, and I even signed up for a flywheel account and even that site doesn't get the error.
Do you have a test/dev site with the problem we take take a look at? https://semperplugins.com/contact/submit-login-information/

**Comment by leehblue** [comment]
I don't actually have a test/dev site with the problem. I have not upgraded any of the other sites we have on flywheel using the plugin.

**Comment by michaeltorbert** [comment]
@leehblue Unfortunately we need to be able to reproduce it. 
I've spent hours in every PHP 7.x version I can in various environments, including getting a Flywheel account, but I can't make reproduce the error.
If you're able to create a test environment that has the issue that would be very helpful.

**Comment by EkoJr** [comment]
This has been rather interesting, and took some digging around, but I was only able to get the wp-admin side to crash.

To reproduce the issue...

PHP Version: 7.1.7 & 7.1.8

1. Go to All in One SEO -> General Settings, and locate the `Custom Post Type Settings` box.
2. Uncheck all `SEO on only these post types:`.
3. Check at least ONE taxonomy in `SEO on only these taxonomies:`.
4. Enable `Enable Advanced Options:`.
5. Check `Custom titles:`.
6. Save, and then refresh.

At this point you may have the issue. If not, continue...

7. Then go to All in One SEO -> Social Meta, and location `Facebook Settings`.
8. Uncheck all `Enable Facebook Meta for Post Types:` NOTE: Having at least 1 selected will cause a seperate issue. PHP Error below.
9. Save, and then refresh.

Now you should have the issue, however, it may only be on the wp-admin side, and the frontend may still be unaffected. I suspect this if from the old post meta data differing from the global settings.

	( ! ) Fatal error: Uncaught Error: [] operator not supported for strings in C:\wamp64\www\aioseop\wp-content\plugins\aioseop-pro\aioseop_class.php on line 4711
	( ! ) Error: [] operator not supported for strings in C:\wamp64\www\aioseop\wp-content\plugins\aioseop-pro\aioseop_class.php on line 4711
	Call Stack
	#	Time	Memory	Function	Location
	1	0.0010	429504	{main}( )	...\admin.php:0
	2	0.5130	56540000	require( 'C:\wamp64\www\aioseop\wp-admin\menu.php' )	...\admin.php:138
	3	0.5190	56616896	require_once( 'C:\wamp64\www\aioseop\wp-admin\includes\menu.php' )	...\menu.php:283
	4	0.5220	56620808	do_action( )	...\menu.php:149
	5	0.5220	56621184	WP_Hook->do_action( )	...\plugin.php:453
	6	0.5230	56621184	WP_Hook->apply_filters( )	...\class-wp-hook.php:323
	7	0.5300	56677440	All_in_One_SEO_Pack->admin_menu( )	...\class-wp-hook.php:298

**Comment by EkoJr** [comment]
I believe when the Settings are being saved in General Settings. The variable within the array is being set as an empty string, **OR rather**, WP is setting it as an empty string if there is no value; which would include empty arrays. I may be wrong, but I believe that was the same issue I recently had with APL 0.4.alpha

**Comment by michaeltorbert** [comment]
@leehblue Can you shed some light on your settings from these two screenshots?

**Comment by michaeltorbert** [comment]
Closing in favor of the two issues in the Pro repository.
