### ISSUE TITLE
Social Settings Tab not activated by default for Posts/Pages

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1053]
The Social Settings tab isn't appearing by default for Posts & Pages when the Social Meta module is activated for the first time.

**Comment by michaeltorbert** [comment]
@arnaudbroes Can you determine when this behavior started?

**Comment by arnaudbroes** [comment]
Traced this back to the commits of July 11th, 2017. Couldn't check the the exact commit because those builds break the site. 

It's any of these (chronological order):

https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/56db40c0a932226d9b83276496d7a5ff54b12e25
https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/04184bb79d04998b8304ed12954df71a291b5e78
https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/eaf66d8556d2eaa9c7b398f5c1bd0bc0ff6a6488
https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/c50b65d684a48a4aa111f2e8a832faa13ade9f3b
https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/762f9e390ae4041c7fc69a5c8611e4caf53e2b45

**Comment by michaeltorbert** [comment]
possibly this? https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/eaf66d8556d2eaa9c7b398f5c1bd0bc0ff6a6488

**Comment by wpsmort** [comment]
@michaeltorbert PR #1060 is tested and is good.
