### ISSUE TITLE
SEO meta is output when SEO for Custom Post Types is disabled

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1069]
Related to #1067 

If you uncheck all post type and taxonomy boxes under Custom Post Type Settings and then disable SEO for Custom Post Types then SEO meta is still output in the source of posts and pages.  

This also happens with categories and tags in Pro, specifically where you've previously added SEO meta in the Edit Term screen.

This has been a bug for a while now.

Steps to reproduce this:
1. Go to General Settings > Custom Post Type Settings and uncheck all checkboxes and disable Advanced Options then click Update Options
2. Go back to Custom Post Type Settings and set SEO for Custom Post Types to Disabled
3. View any post or page and you should see SEO meta in the source code

To reproduce for categories or tags:
1. Edit the Uncategorized category and add some SEO meta
2. Follow the steps above then view the Uncategorized category and check the source code

This problem should go away when we remove the SEO for Custom Post Types option - Issue #68

**Comment by arnaudbroes** [comment]
I tested this with two different, fresh local test sites and a few versions of WordPress (ranging from 4.8.1 to 4.0) and All in One SEO Pack (ranging from 2.3.15.3 (FREE) to 2.0 (FREE) and it seems that this never worked in the free version, at least, that's what I'm experiencing. 

Now I'm testing the Pro version because I believe behaviour is different here.

**Comment by wpsmort** [comment]
@arnaudbroes I checked this and confirm that this bug has been present since v2.0 when we added the Custom Post Type Settings section.

**Comment by contactashish13** [comment]
@wpsmort @arnaudbroes PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1379

**Comment by arnaudbroes** [comment]
@contactashish13 All in One SEO Pack is still changing the theme's title tag.

**Comment by contactashish13** [comment]
@arnaudbroes I assume you mean the title tag of the page. I don't see the title being changed except for some special characters being suitably modified e.g. pipe being converted to 
```
&#8211;
```
Can you please check if its not something else?

**Comment by arnaudbroes** [comment]
@contactashish13 I double-checked, looks like it works. Might have been cache.
@michaeltorbert I tested this. Needs code review.

**Comment by wpsmort** [comment]
@contactashish13 I tested this and the title tag and custom canonical URL are still output.  I checked the AMP page and the title tag is output there too.  See screenshots:

<img width="1252" alt="screen shot 2018-05-22 at 6 14 33 pm" src="https://user-images.githubusercontent.com/17548525/40393140-48132cbc-5dec-11e8-898b-048ec10e4445.png">
<img width="1369" alt="screen shot 2018-05-22 at 6 14 48 pm" src="https://user-images.githubusercontent.com/17548525/40393141-482173a8-5dec-11e8-892e-60989c9f0d8b.png">

**Comment by contactashish13** [comment]
@wpsmort have addressed the above observations.
