### ISSUE TITLE
Social Meta module - Pasting an image URL in Custom Image field is broken

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1074]
Reported by Matt @syntax53 here - https://wordpress.org/support/topic/using-incorrect-facebook-ogimage/#post-9398765

In version 2.3.15 the ability to paste an image URL in the Custom Image field stopped working.  You can still paste an image URL in the Custom Twitter Image field.

**Comment by wpsmort** [comment]
@arnaudbroes Can you determine which commit in v2.3.15 broke this.

Steps to reproduce the issue:
1. Create a post and paste an image URL in the Custom Image field. You can use any image URL from any website
2. Save the post and then view the source code and see if the image URL is shown in the og:image meta tag

**Comment by arnaudbroes** [comment]
On it.

**Comment by michaeltorbert** [comment]
This works for me. Did you select it in the radio button?

**Comment by amostajo** [comment]
Ready for testing

**Comment by wpsmort** [comment]
@amostajo This works fine until you try to paste in a new image URL.  When you paste in a new URL it doesn't change the image in the og:image meta tag.

Steps to reproduce:
1. Edit a post and paste in the URL for an image in the Custom Image field then click Update.  The image should be correctly reflected in the og:image tag in the source code
2. Edit the post again and paste a new URL in the Custom Image field, replacing what was there from step 1 and click Update.  The image in the source code should still be what was set in step 1

**Comment by amostajo** [comment]
@wpsmort It did work for me. Make sure you force refresh of assets by pressing F5 on your browser.

**Comment by wpsmort** [comment]
@amostajo It's working for me now too.  I cannot reproduce the issue I was seeing on Friday at all.
PR #1078 is ready for code review
