### ISSUE TITLE
Upgrading to Pro problematic

### ISSUE THREAD

**Issue by tilopa** [semperfiwebdesign/all-in-one-seo-pack#1075]
I really want to upgrade to SEO pro, and have tried twice, but the whole purchasing process is so broken that I simply gave up. I simply don't have the time to jump through PayPal and other hoops to make it work.

**Comment by michaeltorbert** [comment]
@tilopa What specifically is broken?

**Comment by tilopa** [comment]
Actually so sorry, I think that the bank had frozen our credit card, suspecting fraud. No error messages informed me of exact issue, just failed silently.

We have spent most of this morning clearing up this issue with the bank.  Is there any chance that in addition to the $68 charge for the plugin, another $20 was assessed by PayPal?

**Comment by michaeltorbert** [comment]
No, and as this is a development repository, not a support forum, I'm closing this issue.
You can contact support here: https://semperplugins.com/contact/
