### ISSUE TITLE
Social Meta module - PHP Warning array_flip with image in custom field

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1079]
When you save/update a post with an image URL in a custom field, the following PHP warning is returned: 

PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /wp-content/plugins/all-in-one-seo-pack/modules/aioseop_opengraph.php on line 1549

To reproduce this:
1. Go to All in One SEO > Social Meta > Image Settings > Use Custom Field For Image and enter a field name, i.e. image
2. Edit a post and in the Custom Fields section click the Enter new link.  Enter the field name you used in step 1 and in the Value field paste the URL for an image then click the Add Custom Field button
3. Click the Update button and you should see the PHP warning in the debug log and in the Social Settings tab of All in One SEO.

**Comment by wpsmort** [comment]
@arnaudbroes This does not appear to be a new bug.  Can you trace back to when it started.  We added this feature in v2.1.3

**Comment by arnaudbroes** [comment]
@wpsmort 
I've tested this with two different, fresh local test sites, two different versions of WordPress (4.8.1 & 4.0.0) and All in One SEO Pack (ranging from 2.3.15.3 to 2.1.3) and traced this back to version 2.2.0.

**Comment by amostajo** [comment]
Ready for testing

**Comment by wpsmort** [comment]
I have tested PR #1109 and confirmed that it fixes the PHP notice and doesn't break anything.
