### ISSUE TITLE
Incorrect Custom Canonical URL when homepage set to Latest Posts

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1085]
When the homepage is set to Your Latest Posts under Settings > Reading and the latest post has a custom canonical URL then we're using that custom URL as the canonical URL for the homepage.

Steps to reproduce:
1. Under Settings > Reading set Front page displays to Your latest posts
2. Enable Custom Canonical URLs under All in One SEO > General Settings
3. Edit the latest post and set a custom canonical URL
4. Check the source code of the homepage for the canonical URL, it should show the custom canonical URL you entered in the latest post

**Comment by wpsmort** [comment]
@arnaudbroes Can you check when this bug first started please.

**Comment by arnaudbroes** [comment]
@wpsmort 
This feature was introduced in 2.2.4 and the above issue started occurring from 2.2.4.2.

**Comment by michaeltorbert** [comment]
@wpsmort @arnaudbroes  I'm getting this behavior in 2.2.4.

**Comment by wpsmort** [comment]
@michaeltorbert I can confirm that this bug has existed since v2.2.4 when the Enable Custom Canonical URLs option was first added.

**Comment by wpsmort** [comment]
PR #1089 has been tested and is good.
