### ISSUE TITLE
Bug with title tag and meta description

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1087]
Reported here: https://wordpress.org/support/topic/bug-with-title-tag-and-meta-desc/

_Since I’ve added the “Portfolio” on the type of page I want to do SEO , it has created a strange bug on the pages of my website.

Each time I edit a title tag or a meta description of a page and hit the update button, it’s got automatically replace by the title tag / meta description of the latest portfolio item I’ve created.

Here is a screenshot of my settings: https://goo.gl/tgzxqC
_

We need to see if we can verify this.

**Comment by arnaudbroes** [comment]
User reported that the issue lies with the theme and he's looking into it with their support.
