### ISSUE TITLE
Move AIOSEOP metabox up

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1090]

**Comment by michaeltorbert** [comment]
For testing, we need to 
1) make sure they're moved up for all post types where they should show up (try this with a of selected post types, and with social on or off for that post type
2) it's not broken for taxonomies

**Comment by wpsmort** [comment]
PR #1092 is tested and is good.  I tested with different post types from different plugins and with plugins that add meta boxes as well.  I tested the code with free and Pro.
