### ISSUE TITLE
Post starting with <img> and &nbsp; causes auto-generate of description to fail

### ISSUE THREAD

**Issue by iangeek** [semperfiwebdesign/all-in-one-seo-pack#1103]
Any posts that begin with an image and subsequently followed by a non-breaking space fail to populate the auto-generated descriptions (e.g screen below)

![screen1](https://user-images.githubusercontent.com/1556882/29625898-ff1936ac-8824-11e7-80d1-ee0e189aa28e.jpg)

Removal of the `&nbsp;` reverts back to the expected behaviour (see below).

![screen2](https://user-images.githubusercontent.com/1556882/29625925-0d3302c2-8825-11e7-9351-633516f13d48.jpg)

This appears to have started a few months back, so wondering if its related in some way to any work done on https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/899 ?

**Comment by wpsmort** [comment]
@arnaudbroes Can you test and confirm this behavior and if you're able to reproduce this then please see if you can trace back to when it started.

**Comment by arnaudbroes** [comment]
@wpsmort This works fine with multiple versions of the plugin up to 2.3.16 and with a few WordPress versions ranging from 4.0 to 4.8.1.
![image](https://user-images.githubusercontent.com/18156697/29662501-d9072c6e-88c7-11e7-9bf8-41e40d997d8d.png)

**Comment by iangeek** [comment]
@arnaudbroes @wpsmort  Stripped right back to vanilla plugin-wise, and the theme is just based on Automattic's Underscores, but the issue still persists. Odd.

OK, thanks for checking anyway, and sorry if it was a timewaster. Will let you know if I'm ever able to track down the cause, just for reference.

**Comment by michaeltorbert** [comment]
@iangeek Please use the default theme (Twenty Seventeen) instead of your custom theme. You also may want to try turning on debug error logging.

**Comment by iangeek** [comment]
@michaeltorbert Sorry, should have clarified... I'd already tried default themes and all basic settings before posting the issue.

Will set WP_DEBUG_LOG going and see if it shows anything more.

**Comment by michaeltorbert** [comment]
@iangeek  Export your AIOSEOP settings and send it to us.

**Comment by aleks683** [comment]
The problem is urgent. It's not about plugins. And not in the subject. Removal of the `&nbsp;` does not help either. Autogenerated OG Descriptions works perfectly. What to do?

**Comment by wpsmort** [comment]
PR #1420 fixes this.
