### ISSUE TITLE
PHP Notices: Undefined variable term_id and featured_tag_id

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#111]
Please fix the two PHP notices below:

Notice: Undefined variable: term_id in /Users/stevemortiboy/Sites/termmeta43/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php on line 979

Notice: Undefined variable: featured_tag_id in /Users/stevemortiboy/Sites/termmeta43/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php on line 981

**Comment by dougalcampbell** [comment]
@mrtorbert We talked about this a little bit on Slack about a week ago. I've been looking over this section of the code (Lines 977-989 of `aioseop_class.php`), and I'm not really sure what it's supposed to be *doing*. It just looks really out of place there. And the `split_shared_term()` method should have already copied the meta for any terms that were split.

**Comment by dougalcampbell** [comment]
Okay, after letting it percolate in the back of my mind for a while last night, I realized that this is probably intended to catch metadata for terms that were split by WordPress before AIOSEOP had a handler in place. But I'm pretty sure that the `custom_output_option` method wouldn't be the best place to handle that. If that *is* what we're trying to do, then it probably belongs in our new version updates handler?

**Comment by wpsmort** [comment]
I have tested this and the errors are no longer appearing on the Edit Category / Edit Tag screen.
