### ISSUE TITLE
Add extra help to Robots.txt module

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1127]
I wonder if we shouldn't add some more info for the help buttons of these fields -
it's rather useless at the moment:

![image](https://user-images.githubusercontent.com/18156697/30087112-09f3c70c-929f-11e7-8968-c2eff37a096e.png)

**Comment by michaeltorbert** [comment]
@arnaudbroes What do you have in mind?

**Comment by wpsmort** [comment]
We can do three things here:

1. Improve this text to make it clearer how to use the rule builder: "Use the rule builder below to add/delete rules."
2. Improve the help text for each field
3. Add a heading above the window that displays the robots.txt to state what that window does.  See mockup below:

<img width="688" alt="Screen Shot 2019-06-11 at 8 14 45 PM" src="https://user-images.githubusercontent.com/17548525/59315049-017d3580-8c86-11e9-9f4d-65a23d0e16e7.png">

@arnaudbroes Do you have anything to add?  

I'm assigning this to me for v3.2 as this should be a quick and easy change.

**Comment by arnaudbroes** [comment]
@wpsmort looks good! Nothing to add.
