### ISSUE TITLE
Prominently feature images in sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1132]
-Something in Sitemap Status could mention that images are being included
-Readme should mention images included automatically in the sitemap
-?

**Comment by michaeltorbert** [comment]
The wording of this should be reviewed. Any other suggestions to make it clear images are included in the sitemap?

**Comment by wpsmort** [comment]
@michaeltorbert The wording added here is good.  The only additional items I can think of are:

- We should feature this on the Welcome screen for v2.4 - Issue #1133 refers

- Do we want to add a checkbox to XML Sitemap > Post Types for Images in case users don't want their images submitted to Google?  We do occasionally get users asking whether they can stop Google indexing their images.

**Comment by michaeltorbert** [comment]
@wpsmort 

Personally, I don't think we should add a checkbox... I think we should add some indicator like I discuss in #1164, but I'm open to ideas.
What do you think?

**Comment by wpsmort** [comment]
@michaeltorbert I think the idea of an indicator is a good one.
