### ISSUE TITLE
Google + Problem

### ISSUE THREAD

**Issue by Ahmetamca** [semperfiwebdesign/all-in-one-seo-pack#1148]
Hi again,

I am not sure if i still have pro support chance but i want to ask an other question.

Previously when i was sending a post to Google + the featured image and the post title was coming with that. But as you can see in my last post in Google + only the featured image and author is coming.

I do not face the same problem with Facebook?

What do you think the problem is?

Best Regards,
Ahmet
![2017-09-15](https://user-images.githubusercontent.com/32037745/30522181-92c0a53a-9bd4-11e7-99cf-df52e278d582.png)

**Comment by michaeltorbert** [comment]
@Ahmetamca 

This isn't a support forum. If you'd like support, you can purchase a license here. https://semperplugins.com/all-in-one-seo-pack-pro-version/ and use the support forum here: https://semperplugins.com/support/

**Comment by Ahmetamca** [comment]
Hi,

 

I go to forum and i cannot log in…

It says i am locked…

**Comment by michaeltorbert** [comment]
@Ahmetamca Please stop posting support requests here. This is a development site, not a support forum.
If you'd like support, you can purchase a license here. https://semperplugins.com/all-in-one-seo-pack-pro-version/ and use the support forum here: https://semperplugins.com/support/

You can not access the support forum unless you're a customer.
