### ISSUE TITLE
XML Sitemap redirecting to home page

### ISSUE THREAD

**Issue by shaneohare3107** [semperfiwebdesign/all-in-one-seo-pack#1161]
I disabled all plugins for a few days while fixing an issue on my site. After re-activating, I've noticed the XML sitemap URL is redirecting to home page. I have tried the following to fix, with no luck:

- Disable the XML sitemap feature, and re-enable.

- Restore the XML sitemap settings to default.

The site is https://www.simplifyprivacy.com

Thanks

Shane

**Comment by michaeltorbert** [comment]
Looks fine to me. https://www.simplifyprivacy.com/sitemap.xml
