### ISSUE TITLE
Remove link from virtual robots.txt option

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1164]
Is there any reason we want this to be optional? 
If we remove it, we just need to make it clear it happens... or do we?

I'm thinking something like:

[green light] Added to virtual robots.txt
[green light] Some other thing we do
etc

**Comment by wpsmort** [comment]
@michaeltorbert We have issue #535 open for this.  

I don't think this should be optional.  I think the idea of the green light is good.  Whatever we do for the XML Sitemap module will have to be repeated for the Video XML Sitemap module.
