### ISSUE TITLE
Home Page Title Format grayed out

### ISSUE THREAD

**Issue by ceeportnews** [semperfiwebdesign/all-in-one-seo-pack#1167]
Hi - 

I've been troubleshooting last three days to fix the URL of the home page rendering properly in text messaging. It will not pull the right title and description! Tried every combination under the sun. Works on every other site correctly. Works fine on all other site pages. Just not the home page! The favicon/site image is the image pulling into the text message description, and not the social image that is selected for feature.

Under General Settings > Title Settings, the Home Page Title field is blank but inaccessible to add any format code.

I am using All In One SEO on several other sites, with the same theme (Divi) and this field is accessible. Using the home page in a text message renders the site properly. So I'm not sure if this field is anything that matters, but it's the only thing left that might be the issue?

Any help will be appreciated!
![image](https://user-images.githubusercontent.com/31048680/30830529-e5e89f98-a209-11e7-8385-63d5bc0fc477.png)

**Comment by michaeltorbert** [comment]
@ceeportnews If this is working on all other sites, and just not that one, that indicates a settings issue, server issue, or a plugin/theme conflict. 
This isn't a support forum, but you can find basic troubleshooting steps here: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
If you would like access to support, you can purchase the premium upgrade here: https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by ceeportnews** [comment]
Okay, yes, so that grayed out issue is a settings issue?

**Comment by michaeltorbert** [comment]
This is a development repository. If you need support you can purchase the premium upgrade here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
