### ISSUE TITLE
Improve edit post AIOSEOP section

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1168]
This could/should probably be multiple issues. It doesn't all have to happen at once.

find all the ways it can be made to look better… 
improve look of snippet area… 
get rid of all the extra whitespace… 
line things up better… 
let’s do what we can for this version… but have a designer look at it for the next

**Comment by wpsmort** [comment]
#1172 opened to improve the preview snippet
#1174 opened to improve spacing and gutters
