### ISSUE TITLE
woocommerce

### ISSUE THREAD

**Issue by nicvalencia** [semperfiwebdesign/all-in-one-seo-pack#1170]
al guardar las opciones de ceo del producto no se guardan las de la pagina funcionan perfecto pero las de los producto no se guardan

**Comment by michaeltorbert** [comment]
I'm not sure what this says. If you're looking for support, you can get it buy purchasing All in One SEO Pack Pro: https://semperplugins.com/all-in-one-seo-pack-pro-version/
