### ISSUE TITLE
PHP Notices for Undefined index

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#118]
Please review and fix these PHP Notices:

~~PHP Notice:  Undefined index: aiosp_generate_descriptions in /home3/wordpre1/public_html/stevemortiboy/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php on line 2457~~

PHP Notice:  Undefined index: aiosp_can in /home3/wordpre1/public_html/stevemortiboy/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php on line 1557

~~PHP Notice:  Undefined index: aiosp_use_categories in /home3/wordpre1/public_html/stevemortiboy/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php on line 3207~~

PHP Notice:  Undefined index: aiosp_can in /home3/wordpre1/public_html/stevemortiboy/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php on line 2055

~~Notice: Undefined index: last_active_version in /home3/wordpre1/public_html/stevemortiboy/wp-content/plugins/all-in-one-seo-pack-pro/inc/aioseop_updates_class.php on line 33~~

**Comment by michaeltorbert** [comment]
@wpsmort Any idea what version these were found in? Those line numbers don't mean anything anymore. :)

**Comment by wpsmort** [comment]
@michaeltorbert: I tested everything and only had one issue as follows:

Updating from v2.3.4 (old free version prior to Yandex update) to v2.3.6 (latest dev) I got the following error when I clicked on the Robots.txt menu item:

PHP Notice:  Undefined index: aiosp_sitemap_options in /wp-content/plugins/all-in-one-seo-pack/modules/aioseop_robots.php on line 227

**Comment by michaeltorbert** [comment]
Ok try it now.

**Comment by wpsmort** [comment]
@michaeltorbert Now I get a 403 Forbidden error when trying to click any menu item with the exception of General Settings and Performance.

**Comment by michaeltorbert** [comment]
@wpsmort Ok it's in development now

**Comment by wpsmort** [comment]
@michaeltorbert Same 403 Forbidden error when using the latest from dev branch.

**Comment by wpsmort** [comment]
NOTE: The 403 Forbidden error only affected one MAMP site.  It could not be replicated on any other site or server.  There was nothing in the logs to indicate what originally caused this 403 error. 

All other testing was successful
