### ISSUE TITLE
Feature request - cache-control or filtering the header

### ISSUE THREAD

**Issue by dtheme101** [semperfiwebdesign/all-in-one-seo-pack#1181]
Adding a filter hook for either cache-control or just filtering the header (better) would be useful for anyone using heavy caching and needs a cache header to set rules. eg. Expiry date - 12 hours - 24 hours etc

**Comment by michaeltorbert** [comment]
Source: https://wordpress.org/support/topic/dynamically-generate-sitemap-and-cpu-headers/#post-9531800

**Comment by contactashish13** [comment]
@michaeltorbert have added an action hook which is more generic. PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1429
