### ISSUE TITLE
Reduce spacing between fields and help text

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1185]
See screenshot:

<img width="740" alt="screen shot 2017-09-27 at 11 32 44 am" src="https://user-images.githubusercontent.com/17548525/30922872-688ec7d2-a378-11e7-899b-7eed755ce5cb.png">

**Comment by michaeltorbert** [comment]
@wpsmort I still feel like this could be better, but it's an improvement.
