### ISSUE TITLE
Conflict with WP Affiliate View

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1187]
For some reason, WP Affiliate View has a css file loading at the top of the xml sitemap.

**Comment by michaeltorbert** [comment]
Tracing back the function calls, it originates with: 

add_shortcode('wp_affiliate_view', 'wp_affiliate_view_handler');

**Comment by wpsmort** [comment]
@michaeltorbert This started with this commit from PR #978 - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/978/commits/732c399ea47240b35c7baf21c1cf4a8688a7639c

**Comment by michaeltorbert** [comment]
It seems to be coming from $posts = get_posts( apply_filters( $this->prefix . 'post_query', $args ) );
When the get_posts there runs, it looks at the last 10k or whatever... if the WP Affiliate shortcode is in one of the pages we're getting, it runs for some reason.

**Comment by michaeltorbert** [comment]
Steps to reproduce, install WP Affiliate Platform, add the shortcode [wp_affiliate_view] to a post, and view your sitemap. You should get the "This page contains the following errors" error due to the affiliate css being loaded at the top.

**Comment by michaeltorbert** [comment]
Also, I don't know if I'm missing something, but it seems strange that get_posts has two arguments here. https://developer.wordpress.org/reference/functions/get_posts/ says only $args
