### ISSUE TITLE
Import/Export Module - CSV export/import feature for SEO meta data

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#119]
Users have been asking for the ability to export SEO meta data to a CSV file and import back in from CSV.  This is so they can manipulate SEO meta in a spreadsheet for thousands of posts at a time.

The CSV will need to include the following data/settings:

Post ID
SEO title
SEO description
SEO keywords
Custom canonical URL
Noindex, Nofollow, NoODP, NoYDIR options
Exclude from Sitemap option
OG title
OG description
OG image URL
OG image width and height
Custom video URL
Facebook object type
Article section
Article tags
Twitter card type

**Comment by wpsmort** [comment]
Requested again here - https://semperplugins.com/support/optimizing-all-in-one-seo-pack-pro/exporter-module/#p6688#spEditFormAnchor

**Comment by wpsmort** [comment]
Requested again by email from Ruth

**Comment by michaeltorbert** [comment]
This seems like an unnecessary complexity added to the plugin for very edge cases. A separate add-on plugin/script should handle it.
