### ISSUE TITLE
XML Sitemap - Add filter to disable images in sitemap

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1192]
As discussed today, we should add a filter so that users can disable the images in XML Sitemap we added in Issue #386.

**Comment by michaeltorbert** [comment]
The filter is aioseo_include_images_in_sitemap, just __return_false on it.

**Comment by wpsmort** [comment]
@michaeltorbert I tested PR #1194 and got two errors in the debug log which resulted in a broken sitemap:

PHP Warning:  Missing argument 2 for apply_filters(), called in /wp-content/plugins/all-in-one-seo-pack-issue-1192/modules/aioseop_sitemap.php on line 2663 and defined in /wp-includes/plugin.php on line 176

PHP Notice:  Undefined variable: value in /wp-includes/plugin.php on line 191

**Comment by michaeltorbert** [comment]
Fixed.
