### ISSUE TITLE
Add Product Page Issue After Installing the Plugin

### ISSUE THREAD

**Issue by MobeenKhan22** [semperfiwebdesign/all-in-one-seo-pack#1201]
Hello,

After installing this plugin and it is messing up the product page alignments. I have pasted the screenshot.

Let me know once this is fixed. I will be deactivating the plugin in mean-time.

Thanks,
Mobeen 

![image](https://user-images.githubusercontent.com/32375529/30992862-7cc2d1cc-a471-11e7-8dd2-ba51ff2aa5ec.png)

**Comment by michaeltorbert** [comment]
Unfortunately, this is not a bug, but a support request.
This isn't something that's broken or has changed. Just uncheck the columns you don't want in screen options.

**Comment by MobeenKhan22** [comment]
Sure this would be a support issue. But broken when installed the app. Thanks anyways.

**Comment by michaeltorbert** [comment]
Nothing is broken. That is the intended behavior, hence why it's a support issue.
