### ISSUE TITLE
i had enabled auto create description but not description in page.

### ISSUE THREAD

**Issue by wp1113** [semperfiwebdesign/all-in-one-seo-pack#1205]
http://mkv.cn/12200/happy-death-day-2017-trailer-2

--
  | <meta name="keywords"  content="happy death day,忌日快乐,预告片" />
  |  
  | <link rel="canonical" href="http://mkv.cn/12200/happy-death-day-2017-trailer-2" />

**Comment by wpsmort** [comment]
This is not a support forum.  If you need support then please post in our support forum here - https://semperplugins.com/support/
