### ISSUE TITLE
check if dom module exists

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1206]
We should do something like class_exists( 'DOMDocument' ) in the sitemap module.

Reported here: https://wordpress.org/support/topic/php-dom-module/

**Comment by contactashish13** [comment]
@michaeltorbert @wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1216

If domdocument does not exist, I'm logging an error message and falling back to regex.
