### ISSUE TITLE
Google Search Console parsing errors in sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1209]
Reported here: https://wordpress.org/support/topic/version-2-4-broke-sitemap/#post-9542902
and here: https://wordpress.org/support/topic/version-2-4-broke-my-sitemap/#post-9542883
and here: http://filmcutting.com/sitemap.xml
and here: https://wordpress.org/support/topic/version-2-4-broke-sitemap/#post-9542902

**Comment by wpsmort** [comment]
See issue #1212

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1215 (didn't know if I should post on #1212)
