### ISSUE TITLE
XML Sitemap - Embeds and other code being picked up as images

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1212]
Reported by Nick M. here - https://wordpress.org/support/topic/version-2-4-broke-my-sitemap/#post-9542883

Sitemap URL: http://filmcutting.com/sitemap_post_3.xml
Error: Invalid URL error appears in Google Webmaster Tools under Sitemap details.  The line in question is 109 which looks like this:

```
<image:image>
  <image:loc></image:loc>
</image:image>
```

Note the missing image location tag.

This is coming from an embed in this post - http://filmcutting.com/spectre-adds-stephanie-sigman-as-a-new-bond-girl/

This is the embed code from that post:

```
<div class="visually_embed">
<img class="visually_embed_infographic" alt="Shaken, Not Stirred - How Much Does James Bond Drink?" />
<div class="visually_embed_cycle">by <a href="http://www.designbysoap.co.uk?utm_source=visually_embed" target="_blank" rel="noopener">Designbysoap</a>.</div>
<script type='text/javascript' src='http://a.visual.ly/api/embed/212831?width=540' class='visually_embed_script' id='visually_embed_script_212831'></script>
</div>
```

As soon as that code is removed, the sitemap validates fine.  We need to determine why we can't extract an image location from this.

**Comment by wpsmort** [comment]
We've have two reports related to this for embeds from Amazon.  

One of these, reported by Derek H. here - https://wordpress.org/support/topic/version-2-4-broke-my-sitemap/#post-9542883.  In this case this is a text link to Amazon which can be seen on this page - https://www.whizbuzzbooks.com/another-summer-sue-lilley/.  The code in question is this:

```
<a href="http://amzn.to/2enLCQF" target="_blank" rel="nofollow">On Amazon</a><img style="border: none !important; margin: 0px !important;" src="https://ir-na.amazon-adsystem.com/e/ir?t=whizbuzwp-20&amp;l=as2&amp;o=1&amp;a=B00R9S9TFI" alt="" width="1" height="1" border="0" />
```

The image tag in that code is being picked up as an image in our sitemap which is then creating a parse error on Google Webmaster Tools.

**Comment by wpsmort** [comment]
The second report of an issue with Amazon code is from Matt H. by email.

In this instance the problem comes from this post - http://www.entertainmentbuddha.com/reviews/the-art-of-titanfall-review/.  Here's there's a thumbnail image under the text "Buy The Art of Titanfall today!".   The code for this image looks like this:

```
<a href="http://www.amazon.com/gp/product/178329194X/ref=as_li_qf_sp_asin_il?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=178329194X&amp;linkCode=as2&amp;tag=entertbuddha-20"><img alt="" src="http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&amp;ASIN=178329194X&amp;Format=_SL160_&amp;ID=AsinImage&amp;MarketPlace=US&amp;ServiceVersion=20070822&amp;WS=1&amp;tag=entertbuddha-20" border="0" /></a><img style="border: none !important; margin: 0px !important;" alt="" src="http://ir-na.amazon-adsystem.com/e/ir?t=entertbuddha-20&amp;l=as2&amp;o=1&amp;a=178329194X" width="1" height="1" border="0" />
```

Same problem here, we're picking up the image tag inside that affiliate embed code and it's not a valid image so Google returns an error in Google Webmaster Tools.

**Comment by FilmCutting** [comment]
If I understand correctly, the issue is caused by a single embed. Whether the problem with the embeded image will be resolved if I simply remove it and leave only the clickable link?

**Comment by wpsmort** [comment]
@FilmCutting Yes, it's just that one embed.  If you delete it the parse error in Google Webmaster Tools will go away.

**Comment by FilmCutting** [comment]
Alrighty then, I sure will. Thanks for being so helpful.

**Comment by FilmCutting** [comment]
Issue resolved! https://screenshots.firefox.com/5fCFkAFDsfuCn3CY/www.google.com

**Comment by contactashish13** [comment]
@wpsmort it looks like google does not like if an image URL does not have an extension. Will add a patch for that

**Comment by wpsmort** [comment]
@michaeltorbert I have tested PR #1215 on the three sites where this problem was reported.  On each site it resolves the problem of picking up embeds that are not valid images.  It also resolves the issue of the blank XML Sitemap page.  

This is ready for code review.

**Comment by michaeltorbert** [comment]
@wpsmort The blank screen is from running out of memory, and should be unrelated to this. You can test by seeing how much a sitemap uses (on sites that use a lot of memory) with and without this patch.

**Comment by wpsmort** [comment]
@michaeltorbert: I tested on the four customer cloned sites and there was little to no difference in the memory usage between v2.4 and the v.2.4.1 I tested for the embed code fix.
