### ISSUE TITLE
Ecommerce data missing

### ISSUE THREAD

**Issue by dotcominfo** [semperfiwebdesign/all-in-one-seo-pack#1213]
I've integrated Google Analytics into a customer site recently, using the google analytics setting All In One SEO Pack to do it. Traffic data is showing up just fine, but no ecommerce data is showing up in the analytics at all. I've made sure that my view in the GA profile has ecommerce turned on, and I've enabled all the usual (advanced ecommerce tracking) stuff. I've done this more times than I can remember, but this is the first time I'm using your plugin to do it, so that's why I'm suspecting the problem has something to do with your plugin. 

Can you tell me what to do in order to get ecommerce data into the analytics?

**Comment by michaeltorbert** [comment]
@dotcominfo What is the URL to your site?
