### ISSUE TITLE
add capability to work with "fabulous fluid"  your system says 0 compatibility with my files

### ISSUE THREAD

**Issue by dhenzler** [semperfiwebdesign/all-in-one-seo-pack#1218]
:o(

**Comment by michaeltorbert** [comment]
I don't know what you're asking for. From Google, I see that there's a "Fabulous Fluid" theme https://wordpress.org/themes/fabulous-fluid/. 
Where do you see "o compatibility" with your files?

**Comment by dhenzler** [comment]
after I run the plugin... it shows 5 things were looked at 0 were changed.  the top selection box looked like different apps for doing SEO, and the bottom box seemed like Theme's  Am I wrong?  Maybe I need to RTFM

**Comment by dhenzler** [comment]
I chose Infinate SEO Compatible data:

    Custom Doctitle
    META Description
    META Keywords
    Canonical URI

**Comment by michaeltorbert** [comment]
I don't know what any of this means:

> it shows 5 things were looked at 0 were changed. the top selection box looked like different apps for doing SEO, and the bottom box seemed like Theme's

Please provide some screenshots and a clear explanation about what is telling you our software has no compatibility with something.

**Comment by dhenzler** [comment]
0 Records were updated

5 Records were ignored

**Comment by michaeltorbert** [comment]
Ok what you want is support, which isn't provided here. This is a development system.
Support is for customers who purchase a Pro subscription here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
