### ISSUE TITLE
compare sitemap memory

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1224]
Compare sitemap memory for x posts vs other plugins

**Comment by contactashish13** [comment]
@michaeltorbert here is the comparison while generating sitemap for only posts, including images and using sitemap indexes. I'm taking the average of the post sitemaps that are created without including the memory used for generating the sitemap index (which is usually negligible). I cannot disable images on yoast so have not compared without images.

number of URLs per sitemap: yoast (average memory in MB), AIOSEO (average memory in MB)

5,000: 35.08, 43.78
10,000: 63.21, 80.38
15,000: 63.01, 79.41
20,000: 124.58, 153.27

PS: interestingly, I also see "The plugin All-In-One-SEO has been detected. Do you want to import its settings?" in the yoast settings page.  Something like this would be useful too?

**Comment by michaeltorbert** [comment]
@contactashish13 You should see two of those notices. One for importing their settings as well.
