### ISSUE TITLE
Change sitemap pagination documentation from 50,000 URLs to 1000

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1229]
We need to do this for the website documentation as well.

**Comment by wpsmort** [comment]
@michaeltorbert I totally agree with this.

**Comment by michaeltorbert** [comment]
We should also make it clear that while we default to 1000, users can try lowering it in case of memory issues (usually indicated by a blank screen on their sitemap). We may even want to have this show up without someone clicking on the help icon.

**Comment by wpsmort** [comment]
The documentation has been updated.
