### ISSUE TITLE
XML Sitemap - Add support for images in JetPack galleries

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1230]
In Issue #1191 we added support for images in the built in WordPress galleries.  We now need to add support for images in JetPack galleries and slideshows.

**Comment by contactashish13** [comment]
@michaeltorbert while making changes for this issue I saw that the merged code seems to be missing my changes for #1200. Can you please check?

My commit: https://github.com/contactashish13/all-in-one-seo-pack/commit/fbe11c81cad0645f21bd125f96bb8f9ab4555db2

relevant lines: https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/2.4.2/modules/aioseop_sitemap.php#L2732 and https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/2.4.2/modules/aioseop_sitemap.php#L2748

**Comment by contactashish13** [comment]
@wpsmort for jetpack, is this the feature that needs to be supported?

![image](https://user-images.githubusercontent.com/12953439/31173188-385cfdb6-a924-11e7-95d9-a1cf9c75356f.png)

**Comment by wpsmort** [comment]
@contactashish13 Yes, I believe that's it.  Here are the steps to reproduce this:

1. Activate JetPack and create a new post
2. Click the Add Media button and then click Create Gallery
3. Select the images for the gallery and then click the Create new gallery button
4. In the Type dropdown select Slideshow (this is added by JetPack)

You should see a shortcode that looks like this:

`[gallery size="medium" link="file" columns="5" type="slideshow" ids="553,551,552,550"]`

**Comment by contactashish13** [comment]
@michaeltorbert while making changes for this issue I saw that the merged code seems to be missing my changes for #1200. Can you please check?

My commit: contactashish13/all-in-one-seo-pack@fbe11c8

relevant lines: https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/2.4.2/modules/aioseop_sitemap.php#L2732 and https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/2.4.2/modules/aioseop_sitemap.php#L2748

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1279

**Comment by contactashish13** [comment]
@wpsmort while creating the test case for jetpack gallery, it appears the gallery shortcode is processed by core WP not jetpack. So my changes are valid for the gallery short code not specifically for jetpack support. Can you please verify this and let me know how to proceed to add support for jetpack?

**Comment by wpsmort** [comment]
@contactashish13 I have confirmed that PR #1279 adds support for the WordPress gallery shortcode which is what Jetpack uses.  I tested using the Jetpack slideshow.  

I've opened a separate issue #1546 for adding support for NextGen Gallery images.

**Comment by wpsmort** [comment]
@contactashish13 The shortcode is this:

**[gallery size="medium" link="file" columns="5" type="slideshow" ids="553,551,552,550"]**

Note that it's the shortcode parameter type="", when that is set to slideshow this works fine but if it's set to one of the other options below it doesn't work:

rectangular, square, circle, columns

**Comment by contactashish13** [comment]
@wpsmort all options seem to work on my dev instance. This is probably because I do not get the jetpack options while creating the gallery and thus all options default to `slideshow`. Can you share the test site credentials?

**Comment by wpsmort** [comment]
@contactashish13 I have sent the credentials to you via Slack.  The code from the PR is active and so is Jetpack.

**Comment by contactashish13** [comment]
@wpsmort I've concluded that the problem occurs because you have checked that you want to use JetPack's CDN. This means that images are included from an external domain and that is only allowed if the `aioseop_images_allowed_from_hosts` filter is used to specifically allow this domain. To verify this, you can disable the JetPack CDN and generate the sitemap and it will correctly parse the images no matter what `type` argument is used.
