### ISSUE TITLE
Warning: array_sum() expects parameter 1 to be array

### ISSUE THREAD

**Issue by ocdevops** [semperfiwebdesign/all-in-one-seo-pack#1243]
After I installed the Version 2.4.1, I get this PHP warning on my admin site:

>  Warning: array_sum() expects parameter 1 to be array, null given in /home/***/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php on line 345

**Comment by michaeltorbert** [comment]
@ocdevops Thank you for reporting this. We'll release a fix, but this is just a warning. Make sure to disable error logging on production sites.

**Comment by michaeltorbert** [comment]
@ocdevops Does this fix it for you?

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and the URL notice still works.

**Comment by ocdevops** [comment]
@michaeltorbert I added these lines to my wp-config.php,and it solve the issue:

> ini_set('log_errors','On');
> ini_set('display_errors','Off');
> ini_set('error_reporting', E_ALL );
> define('WP_DEBUG', false);
> define('WP_DEBUG_LOG', true);
> define('WP_DEBUG_DISPLAY', false);
