### ISSUE TITLE
XML Sitemap - Exclude images from external sites

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1245]
Reported by Matt H. by email today.

Google Webmaster Tools can return warnings about URLs blocked by robots.txt when the image is on an external site and the robots.txt on that external site is blocking them.

We should consider not including external images in our sitemap.

**Comment by contactashish13** [comment]
@wpsmort @michaeltorbert https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1281 takes care of this if the filter 'aioseop_images_allowed_from_hosts' does not exist or if it returns an empty array.

**Comment by wpsmort** [comment]
This is a dupe of #1258.  We implemented this in v2.4.2.
