### ISSUE TITLE
XML Sitemap - Don't include images without FQDN

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1246]
Reported by Matt H. by email today.

Matt had some images which showed up in his sitemap without the http://domain.com part of the URL.  This caused Google to return an Invalid URL error.  The way the images appeared in the source code was without the http://domain.com so that's what was listed in our sitemap.  

We should consider ignoring images without a full URL including protocol and domain name.

**Comment by contactashish13** [comment]
@michaeltorbert this has already been patched as part of a previous PR
