### ISSUE TITLE
Yandex support for images in sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1247]
Reported by Alex via email 

> I see what in the sitemap.xml adds new column - IMAGES (near the PRIORITY). And Yandex SEO robots cant read it. So can a generate file Sitemap without the column IMAGES ?

Reference: https://yandex.com/support/webmaster/controlling-robot/sitemap.html

Related to #1248

**Comment by contactashish13** [comment]
@michaeltorbert there could be a couple of ways to address this:

1) sitemap URL contains a parameter that indicates which search engine this is for (by default empty) e.g. engine=yandex which is used to exclude the image information
2) detect the user agent of yandex and exclude the image information

I would prefer the 2nd approach. Let me know your thoughts.

Also, I see in https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.html#robot-in-logs that they have separate image and video indexer bots. Do you think if that user agent is encountered, images should be NOT be excluded?

**Comment by michaeltorbert** [comment]
Offhand I don't like either of these. 
At a minimum, we should allow users to disable the image functionality via filter https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1248
Potentially then they could use this filter conditionally when it's yandex, or all the time, whichever they prefer.
Perhaps there's another way... do other plugins have the same issue?

**Comment by michaeltorbert** [comment]
@wpsmort Can you check if other plugins have the same issue?

**Comment by wpsmort** [comment]
@michaeltorbert I've been to reproduce this with the Yandex Sitemap Validator.  I have confirmed that our filter (https://semperplugins.com/documentation/disable-images-in-xml-sitemap/) resolves this.

**Comment by michaeltorbert** [comment]
Ok great, I'll close this issue now, but we'll still want to improve the filter.
