### ISSUE TITLE
Blank Sitemap_post.xml 

### ISSUE THREAD

**Issue by blogxkomo** [semperfiwebdesign/all-in-one-seo-pack#1249]
you can see on https://xkomo.com/sitemap_post.xml 
if you visit you will see blank page

**Comment by michaeltorbert** [comment]
Follow the instructions here https://semperplugins.com/documentation/this-page-contains-the-following-errors/ and here https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

**Comment by michaeltorbert** [comment]
Update: for moviesweed, the sitemap is blank: https://moviesweed.com/sitemap_post_1.xml but when I did a clone of their site to our server, it works fine http://wordpress-119458-341044.cloudwaysapps.com/sitemap_post_1.xml

**Comment by contactashish13** [comment]
@michaeltorbert we parse using the domdocument and iterate over the elements found to get the 'src'. for some strange reason that src is not found. Even if I use the hasAttribute function it misinforms that 'src' attribute exists. But it does not throw any error

the problematic line is https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L2851

**Comment by wpsmort** [comment]
@contactashish13 Part of the problem with the https://xkomo.com/sitemap_post.xml sitemap is that we're picking up Facebook links as images.  This is the code in question that we see as an image:

```
<a href="https://scontent-sin.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/10492216_766557356701076_6278933958430330593_n.jpg?oh=abd9f6df2dd4dd65c6216bf486ee8f61&amp;oe=55D93B66" style="margin-left: 1em; margin-right: 1em;"><img alt="Cara Membuat Cover FB Responsive" height="236" src="https://scontent-sin.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/10492216_766557356701076_6278933958430330593_n.jpg?oh=abd9f6df2dd4dd65c6216bf486ee8f61&amp;oe=55D93B66" width="640" /></a>
```

This is just like Issue #1212 where we picked up Amazon links as images.  I've opened issue #1258 for this.

**Comment by wpsmort** [comment]
Note: The issue reported by blogxkomo is related to Issue #1250 where there are images that have URL parameters separated by an &.  This causes a blank sitemap and it causes parsing errors in GWT.  

There is a secondary problem whereby the specific images that are causing this are actually Facebook links.  Issue #1258 has been opened for us to remove these from our sitemap.

**Comment by wpsmort** [comment]
See PR #1256
