### ISSUE TITLE
Broke options in Divi theme in 2.4.1.1 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1251]
The version should be verified.

The report is that options don't work.

Reported here: https://wordpress.org/support/topic/version-2-4-1-1-broke-divi-theme/

**Comment by EkoJr** [comment]
@wpsmort The Sitemap Indexes will need to be retested.

There was a `global $options` that Divi was using, which AIOSEO started using with a recent update to handle its options, which was intended as a local variable. Removing the global variable fixes the issue.

**Comment by michaeltorbert** [comment]
@wpsmort He means to test that we haven't broken the sitemap index notice we added in 2.4.1 with this commit.

**Comment by wpsmort** [comment]
@michaeltorbert PR #1260 is tested and is good.  I've confirmed that the Divi options page works and that our Sitemap Indexes notice works.  PR is ready for code review.
