### ISSUE TITLE
Conflict with Members plugin

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1255]
Reported here: https://wordpress.org/support/topic/version-2-4-1-1/#post-9552966

Plugin conflict – MEMBERS Version 2.0.1 | By Justin Tadlock 

When Members is activated, the report is that AIOSEOP can not be.

**Comment by justintadlock** [comment]
Just making sure I get notifications on this.  Let me know if there's an issue on Members end.

**Comment by michaeltorbert** [comment]
Thanks @justintadlock Will do.

**Comment by michaeltorbert** [comment]
User reports this as resolved. 

> ALL IN ONE SEO and MEMBERS plugins are great plugins in and of themselves and have always played well with each other in the past. Also, everything is running as it should after reactivating both plugins.
