### ISSUE TITLE
Noindex for Author Archives

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1257]
Reported here: https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/noindex-for-author-archives-isnt-working

> When checking this box, the noindex tag is not added to the page. 
I narrowed this down to is_page_included() in all-in-one-seo-pack-pro/aioseop_class.php:
The highlighted block is where it falls out:
https://www.dropbox.com/s/ujdqryffxu36kvw/Screenshot%202017-10-03%2014.33.10.png?dl=0

![screenshot 2017-10-03 14 33 10](https://user-images.githubusercontent.com/17364998/31143054-0ee2b992-a84a-11e7-9fa7-10fb79545b75.png)

**Comment by clifgriffin** [comment]
@michaeltorbert This may also be affecting media items.  Though, I'm not sure why attachment wouldn't be in `$wp_post_types`.

**Comment by michaeltorbert** [comment]
Hi @clifgriffin 
Thank you for letting us know. We'll take a look at this at some point, or if you find out anything, you're welcome to submit a PR in the meantime.

**Comment by arnaudbroes** [comment]
I'm not able to reproduce in free nor Pro. 

@wpsmort can you see if you're still able to reproduce this? If not, feel free to close the issue.

**Comment by wpsmort** [comment]
I am not able to reproduce this either.  I tested back to versions of Pro from around October 2017 as well as with the current version of free and Pro.
