### ISSUE TITLE
XML Sitemap - Facebook links picked up as images

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1258]
Related to issue #1212 

Reported by @blogxkomo in issue #1249.

In the sitemap here https://xkomo.com/sitemap_post.xml we are picking up Facebook links as images.  

This is the code in question that we see as an image:

```
<a href="https://scontent-sin.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/10492216_766557356701076_6278933958430330593_n.jpg?oh=abd9f6df2dd4dd65c6216bf486ee8f61&amp;oe=55D93B66" style="margin-left: 1em; margin-right: 1em;"><img alt="Cara Membuat Cover FB Responsive" height="236" src="https://scontent-sin.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/10492216_766557356701076_6278933958430330593_n.jpg?oh=abd9f6df2dd4dd65c6216bf486ee8f61&amp;oe=55D93B66" width="640" /></a>
```

We need to not list these as images, they are actually links.

**Comment by michaeltorbert** [comment]
@contactashish13  Let's just exclude all external images.

**Comment by wpsmort** [comment]
@contactashish13 I tested this and it works fine but there's  one problem.  It doesn't pick up images with a relative URL.  For example, this image is not picked up:

`<img src="/wp-content/uploads/2017/05/venice.jpg" />`

**Comment by wpsmort** [comment]
@contactashish13 If there's no easy way to detect images added with a relative URL then we'll leave that for a future version to look at adding support for this.  We shouldn't hold up this bug fix release unless this is an easy fix.

**Comment by contactashish13** [comment]
@wpsmort added a fix for that.

**Comment by michaeltorbert** [comment]
@contactashish13 @wpsmort I think there would just be no hostname or it would return false or an error something when attempting to parse the URL.

**Comment by contactashish13** [comment]
@michaeltorbert i'm checking the url to see if its relative and if it is, make it absolute by prefixing it with home_url. It works fine for me.

**Comment by wpsmort** [comment]
@contactashish13 I've confirmed we're now picking up images with relative URLs but we're outputting the relative URL in the image:loc tag in the sitemap which results in a parsing error in Google Webmaster Tools.  Google needs a full URL so we need to take the relative URL and turn it into a full URL.

For example, this image in a post

`<img src="/wp-content/uploads/2017/01/venice.jpg" />`

becomes this URL in the sitemap:

`<image:loc>http://stevemortiboy.com/wp-content/uploads/2017/01/venice.jpg</image:loc>`

**Comment by contactashish13** [comment]
@wpsmort @michaeltorbert have moved absolutize_url to the clean_url function so that its applicable to all image URLs

**Comment by wpsmort** [comment]
@michaeltorbert PR #1265 is tested and is good.  I tested on two very large sites and submitted the sitemaps to Google and there were no errors reported.
