### ISSUE TITLE
Option to remove images from sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1262]
Related to #1247

**Comment by michaeltorbert** [comment]
When testing, we need to make sure that the option defaults to on for new installs as well as for people updating

**Comment by wpsmort** [comment]
@michaeltorbert @contactashish13  The new Include Images option does not default to enabled for new installs.

**Comment by michaeltorbert** [comment]
@wpsmort  It should default to on _for new installs_ now.

**Comment by wpsmort** [comment]
@michaeltorbert I have confirmed that the option is now checked by default on a new install, however, images don't appear in the sitemap until you click Update Options.  I checked in the database and none of the sitemap module options are shown in the database until you click Update Options.

**Comment by wpsmort** [comment]
@michaeltorbert PR #1267 is tested and is good.  I've tested with all the different configurations that we discussed.
