### ISSUE TITLE
Improve Filter hook to remove images from sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1263]
We currently have a filter hook aioseo_include_images_in_sitemap to remove images from the xml sitemap (this is helpful for sites that need yandex, which doesn't accept images in the sitemap).

While it's currently sufficient to make it work, we should improve it so that not even the column shows up, as well as refactor it into its own function along with the option check.

Related to #1247

**Comment by wpsmort** [comment]
@michaeltorbert PR #1267 is tested and is good.
