### ISSUE TITLE
Images\media in Sitemap even if unchecked the option

### ISSUE THREAD

**Issue by SimonCCCe** [semperfiwebdesign/all-in-one-seo-pack#1272]
Hi,
after updating to 2.4.1.1 my sitemap now include 17.000 images\media even if I uncheck the option on the Sitemap setting page. Before the update I had 0 images\media in the sitemap..

**Comment by michaeltorbert** [comment]
@SimonCCCe  What is the URL to your sitemap?

**Comment by SimonCCCe** [comment]
http://www.lafune.eu/sitemap.xml

**Comment by michaeltorbert** [comment]
@SimonCCCe  in 2.4 we added images to the sitemap, are you saying you don't want them, or that there's a problem with the way they show up?

**Comment by SimonCCCe** [comment]
I mean I don't want them. I unchecked them in the sitemap setting by they are in the sitemap anyway


![schermata 2017-10-04 alle 17 40 57](https://user-images.githubusercontent.com/32519291/31185014-3e34cb0e-a92b-11e7-95d4-9f46b9893390.png)

**Comment by michaeltorbert** [comment]
That is for the attachment post type, not for images (they aren't exactly the same thing).

We’ll have an option in the next release to remove them, but in the meantime you can use our aioseo_include_images_in_sitemap filter hook.

To do this, just paste the following code in your theme’s functions.php:

https://gist.github.com/michaeltorbert/56af2d944c01b571ee42ca7fad31279c

`add_filter( 'aioseo_include_images_in_sitemap', '__return_false' );`

**Comment by SimonCCCe** [comment]
Thank you.
