### ISSUE TITLE
Add a Welcome screen

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#128]
https://premium.wpmudev.org/blog/tabbed-interface/
https://premium.wpmudev.org/blog/plugin-welcome-screen/
http://www.wpmayor.com/how-to-create-a-welcome-screen-for-your-plugin/
http://wpeden.com/how-to-create-a-welcome-screen-for-wordpress-plugin/

**Comment by michaeltorbert** [comment]
It should be like how WordPress does, where it's a dedicated file (about.php) you can link to at any time.

**Comment by nishant981** [comment]
Hello Michaeltorbert
I have make the Welcome screen page during Activating the plugin.

**Comment by nishant981** [comment]
![1](https://cloud.githubusercontent.com/assets/13958896/14843015/67b30f86-0c6a-11e6-89fc-8f03ab0b9d19.png)

**Comment by arnaudbroes** [comment]
Closing this as this has been implemented already.
