### ISSUE TITLE
Excerpts of posts on facebook destroyed after update

### ISSUE THREAD

**Issue by fernsehwerk** [semperfiwebdesign/all-in-one-seo-pack#1280]
In the past, clean excerts of the post were delivered to facebook, when postig a link of a wp-post on facebook.
afte one of the last updates, some strange content is delivered to fb: the category name, the text of social buttons (e.g.'click here to share post..') and after this the excerpt is delivered.
is this a known bug?

thx,
alex

**Comment by michaeltorbert** [comment]
Hi @fernsehwerk What is the URL to the post?

**Comment by fernsehwerk** [comment]
Link to one example can be found here:

https://www.facebook.com/wettermagazin/

**Comment by michaeltorbert** [comment]
@fernsehwerk No, what is a URL to a post on your website?

**Comment by fernsehwerk** [comment]
One original post can be found here:

http://www.wetter-ruhr.info/2017/10/amelia-brightman-konzert-faellt-aus/

**Comment by michaeltorbert** [comment]
AIOSEOP isn't outputting any social, which probably means you don't have the Social module turned on. This is a development repository, not a support forum.

You can read the documentation here https://semperplugins.com/documentation/ or purchase a license for support here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
