### ISSUE TITLE
Remove Set Preferred Site Name

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1282]
According to https://www.seroundtable.com/google-drops-preferred-site-name-24396.html, this may not be supported anymore.
We should try to verify this and see if we should remove the option.

However, looking at the code, this seems to only be used for the sitelinks search box.

**Comment by wpsmort** [comment]
I've only found one mention of "preferred site name" in Google's docs here - https://support.google.com/webmasters/answer/7358659?hl=en.  I've been through their docs on search features structured data (https://developers.google.com/search/reference/overview) and there's no reference there and there's no example JSON code that shows that specific markup.  

I recommend we remove this when we remove the Google+ options (#2121).
