### ISSUE TITLE
Errors in Google Search console for sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1283]
Reported here: https://wordpress.org/support/topic/the-plugin-causes-errors-in-the-site-map-associated-with-images/

in Google Search Console file sitemap.xml causes errors with images:

http://i.piccy.info/i9/6f912c79e6e8655283db3237c0b69232/1507476681/40106/1179164/2017_10_08_181514.jpg

http://i.piccy.info/i9/9d44e4ac8c5e7623eeaf97e10225f49c/1507476831/74272/1179164/2017_10_08_182705.jpg

 https://vellisa.ru

**Comment by michaeltorbert** [comment]
<img width="1352" alt="sitemap" src="https://user-images.githubusercontent.com/17364998/31319322-0888c6ac-ac2f-11e7-9be0-85d4949edaa2.png">

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1286
