### ISSUE TITLE
Is it possible to display the preview snippet separately.

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [semperfiwebdesign/all-in-one-seo-pack#1293]
I would like to display the preview snippet in a separate metabox just above the metabox it is by default.

Is there anyway, any hook or any idea you can provide me how I should proceed to achieve this.

Also I would like to know how this

`add_action( 'output_option', array( $this, 'custom_output_option' ), 10, 2 );` is working? where is `do_action`?

**Comment by michaeltorbert** [comment]
@PrafullaKumarSahu Unfortunately this isn't something you can easily move. 
It works because add_action calls add_filter.

**Comment by PrafullaKumarSahu** [comment]
Thank you so much for your kind reply, Can you please let me know, how add_action is called without a do_action, I understand "add_action calls add_filter" part from [documentation](https://developer.wordpress.org/reference/functions/add_action/).
