### ISSUE TITLE
Errors found

### ISSUE THREAD

**Issue by sembel60** [semperfiwebdesign/all-in-one-seo-pack#1294]
Hello. I have two sites. With the update of the plug-in All In One SEO Pack up to 2.4.1, the Yandex webmaster system began to write: "One or more Sitemap files have errors that may affect the processing of files by the indexing robot."
Here are the screenshots: http://clip2net.com/s/3OtmDyk, http://clip2net.com/s/3Otn1Cn

There are errors in your Sitemap
One or more Sitemap files encountered errors that could affect the processing of files by the indexing robot.
Review the Sitemap files and make the necessary corrections.

**Comment by arnaudbroes** [comment]
@sembel60 
There are no errors in our sitemap. 
Yandex reports an error because it does not support images in sitemaps at this time.
Please read through our documentation here and exclude the images from the sitemap - https://semperplugins.com/documentation/exclude-images-from-xml-sitemap-for-yandex/

**Comment by sembel60** [comment]
Many thanks!!!


>Четверг, 12 октября 2017, 22:19 +03:00 от Arnaud Broes <notifications@github.com>:
>
>@sembel60
>There are no errors in our sitemap.
>Yandex reports an error because it does not support images in sitemaps at this time.
>Please read through our documentation here and exclude the images from the sitemap -  https://semperplugins.com/documentation/exclude-images-from-xml-sitemap-for-yandex/
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением.
sembel60

**Comment by sembel60** [comment]
Many thanks!!!
