### ISSUE TITLE
Google Search Console errors with compression turned on

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1298]
Reported here: https://wordpress.org/support/topic/sitemap-error-in-google-search-console/#post-9579584 and via email "Google Search Console gives an "exceeding file size" error when submitting a compressed sitemap even though the sitemap isn't that large at all."

See if we can verify this.

**Comment by arnaudbroes** [comment]
We no longer support compression.
