### ISSUE TITLE
robots.txt, google search problem

### ISSUE THREAD

**Issue by chrismazz75** [semperfiwebdesign/all-in-one-seo-pack#1300]
I don't know when or how this started, but I need to make it go away.  When you google search the name of my website you get a message saying "a description for this result is not available because of this site's robots.txt."  I've tried everything I can think of, even contacted my web hosting company who temporarily deleted this file, and nothing can make Google recognize my site. How do I fix this? I'm not sure how you would contact me, please use chrismazz75@icloud.com.  The site I'm referring to is www.tidbitsfromhome.com (also www.tidbitsandcrumbs.com)  Thank you!

**Comment by michaeltorbert** [comment]
@chrismazz75 

That isn't caused by All in One SEO Pack, and this isn't a support forum.
