### ISSUE TITLE
Make contextual help more clear for Exclude Pages setting

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1306]
Let's make this a bit more clearer:

![image](https://user-images.githubusercontent.com/18156697/31579545-de253f3a-b138-11e7-91d9-4ebdcc75e661.png)

Related to #1304.

**Comment by EkoJr** [comment]
Check and improve tooltips documentation #1320

**Comment by wpsmort** [comment]
@arnaudbroes When you do this, please also fix where quotes are being escaped with a backslash, i.e.

\"forum\"

**Comment by arnaudbroes** [comment]
In retrospect, this is quite clear, but the punctuation could be improved and there are two slashes being escaped while they don't have be.
