### ISSUE TITLE
Test nginx sitemap rewrite rules under all conditions

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1310]
specifically with indexes and multiple pages

https://semperplugins.com/documentation/all-in-one-seo-pack-xml-sitemap-404-nginx/

**Comment by wpsmort** [comment]
I have tested the rules thoroughly with all variations of XML Sitemap and Video Sitemap for both v3.1 where we introduced the new naming convention and for versions prior to v3.1.  

I have updated the documentation to reflect the new rules for the new naming convention and added a new doc for Video Sitemap rewrite rules.  Both docs can be found here:

https://semperplugins.com/documentation/xml-sitemap-rewrite-rules-for-nginx/
https://semperplugins.com/documentation/video-sitemap-rewrite-rules-for-nginx/
