### ISSUE TITLE
Google Analytics not working

### ISSUE THREAD

**Issue by bncmattia** [semperfiwebdesign/all-in-one-seo-pack#1317]
Hi, since october 7 the wordpress plugin seems to be not connected with Google Analytics. I have tried to set a new Analytics account with a new ID, but didn't work. As you can see at this link http://italiaincammino.altervista.org/wp-content/analytics-1.pdf Analytics registers no traffic, while at this link http://italiaincammino.altervista.org/wp-content/rivista-camminare-1.pdf you can see on october 10 there was at least 34 visitors.
Please can you let me know how can I fix the problem?
Kind regards
Mattia

**Comment by arnaudbroes** [comment]
Hi Mattia

I'm sorry for our late response, but this is a development repository and not a support forum.
If you'd like to receive support, then you can buy a license here - https://semperplugins.com/all-in-one-seo-pack-pro-version/

Kind regards
