### ISSUE TITLE
Consider whether autotrack.js should be externally hosted

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1318]
In https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/8b1807b117c41093fc3c366cf7ce55b92eac4858#diff-e8642dbdf7f688d3d3edb9fcd9eb3ea5 for #921 we added autotrack.js, but hosted at https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.0/autotrack.js

It's a pretty small file, so I'm just not sure the benefit of using cloudflare.

We should discuss whether this is ideal, versus locally hosting it.

One option is to host it locally in the plugin, but then in our API documentation on the filter hook aiosp_google_autotrack, we can use the cloudflare link as an example, and even have separate documentation specific to that "Use CloudFlare CDN to host autotrack.js".

Requested here: https://wordpress.org/support/topic/cloudflare-24

**Comment by contactashish13** [comment]
advantages of using CDN
1. uses the cache (server side or plugin based and browser cache) in case its a commonly used file and requested by another plugin. 
2. I can't see if it uses edge servers (if its a CDN it typically should) but if it does, it reduces the total transit time too. 

For tiny, not very common files it does not matter whether we use a CDN or not but if it is about following a protocol/dev strategy, it needs to be consistent no matter how light/heavy or common/uncommon the file. Either all files need to be packaged with the plugin or all need to be sourced off the CDN. (By all, I mean all available.)

**Comment by arnaudbroes** [comment]
I agree with @contactashish13 that we should be consistent in this matter. And considering that we have been using a CDN, I would suggest continue doing so in the future. Making changes at this point seems like a waste of resources to me.
