### ISSUE TITLE
Autogenerate Descriptions does not work

### ISSUE THREAD

**Issue by aleks683** [semperfiwebdesign/all-in-one-seo-pack#1324]
I apologize, created before this request. It was closed, referring to #1308 
The problem is not solved. Все записи начинаются с изображений. Description Autogenerate this does not work. All entries were left without description. The problem is serious. Please help to understand or suggest the correct solution. Thank you.

**Comment by michaeltorbert** [comment]
@aleks683 That issue is still open. As you can see, it is being worked on. Please don't open additional issues about it.
