### ISSUE TITLE
SEO keyword field not showing

### ISSUE THREAD

**Issue by mkokc** [semperfiwebdesign/all-in-one-seo-pack#1328]
Have the non-pro version of All in one SEO pack and do not see the field for SEO keywords either when I edit a page or a post.

**Comment by michaeltorbert** [comment]
This is not a support forum. We offer Premium Support for All in One SEO Pack Pro customers which can be purchased here: https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by mkokc** [comment]
It's a bug.
How would you like people who use the non-pro version of your plug-in to fix issues they have?

**Comment by michaeltorbert** [comment]
This isn't a bug.
