### ISSUE TITLE
XML Sitemap - Bug with displaying the XML sitemap on HTTPS sites

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#133]
We get reports of an issue with displaying the human readable XML sitemap when a site is forced to using HTTPS.  Instead you see a blank page but when you check the source code of the page then the XML code is all there.  

Here's an example:

https://www.onlinegamesrun.com/sitemap.xml
view-source:https://www.onlinegamesrun.com/sitemap.xml

If you check the error console in Chrome you'll see an error with loading the XSL stylesheet:

Unsafe attempt to load URL http://www.onlinegamesrun.com/wp-content/plugins/all-in-one-seo-pack/sitemap.xsl from frame with URL https://www.onlinegamesrun.com/sitemap.xml. Domains, protocols and ports must match.

Peter had looked into trying to fix this but didn't find a solution.  This needs to be revisited as a bug.

**Comment by nishant981** [comment]
we are working on displaying the XML sitemap on HTTPS Issue.

**Comment by wpsmort** [comment]
Here's a screenshot of the issue:

<img width="1172" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/16276466/7c8cc6e8-387c-11e6-9819-2971d5795c77.png">

**Comment by wpsmort** [comment]
I have tested and not been able to replicate this issue.  We should ask the person who reported this issue to test when we release v2.3.6.

**Comment by michaeltorbert** [comment]
This may have been fixed with the new way we form the xsl url. Were you able to reproduce it on earlier versions?

**Comment by wpsmort** [comment]
I have emailed this person and advised them this is fixed.
