### ISSUE TITLE
Browser errors calling external autotrack code

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1330]
![image001](https://user-images.githubusercontent.com/17364998/32292293-fdbb5a4c-bf15-11e7-9816-95034165b763.png)

**Comment by contactashish13** [comment]
@michaeltorbert is this only happening in MS Edge? If so, there is a similar problem highlighted here https://stackoverflow.com/questions/33533605/twitter-bootstrap-alpha-4-0-404-403-response-from-cdns-in-ms-edge. There does not seem to a solution to this except to load this file locally.

**Comment by contactashish13** [comment]
@michaeltorbert there are 2 approaches:

we can load this locally only when its MS Edge and otherwise load it from the CDN. This will allow us to remove the local loading when MS Edge fixes the problem.
OR
load this locally for all browsers

Let me know which one would be preferable.

**Comment by arnaudbroes** [comment]
@michaeltorbert I'd use the temp fix considering Edge has a market share of 3.6% but ask Michael first.

**Comment by contactashish13** [comment]
@michaeltorbert I guess we can action this as this will also resolve #1318. Let me know

**Comment by michaeltorbert** [comment]
@contactashish13 Is there any disadvantage to loading locally for all browsers?

**Comment by contactashish13** [comment]
@michaeltorbert the only disadvantage I see is that one additional request will be sent to the user's server which, considering the limited amount of things we load locally, is not a biggie.

**Comment by michaeltorbert** [comment]
That seems like a pretty small request though. My vote is ship it with the plugin if we really need it

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1436
