### ISSUE TITLE
PHP Warning: file_exists(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1332]
People get this warning when open_basedir is enabled on our code that adds the upgrade link to the admin bar.

Is there some way to avoid this?

Reported here: https://wordpress.org/support/topic/open_basedir/

**Comment by contactashish13** [comment]
@michaeltorbert I don't see a reason for this error in the code but maybe I'm looking at the wrong place. Can you please share the exact error message and the stack trace?

**Comment by michaeltorbert** [comment]
@contactashish13 This was reported by a user in the wordpress.org forums (it's been reported multiple times), so I don't personally have it anywhere.

I think the problem is that an absolute path "https://semperplugins.com/all-in-one-seo-pack-pro-version/" is being passed to the code (specifically file_exists) for the admin bar which results in File(C:\Domains\mywebsite.com\wwwroot/wp-content/plugins/https://semperplugins.com/all-in-one-seo-pack-pro-version/) 


`if ( ! empty( $menu_hook ) || ( ( 'index.php' != $sub_item[2] ) && file_exists( WP_PLUGIN_DIR . "/$sub_file" ) && ! file_exists( ABSPATH . "/wp-admin/$sub_file" ) ) ) {
					`

Also, I supposed this is a duplicate of #1123

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1340

**Comment by wpsmort** [comment]
When testing PR #1340 I was unable to reproduce the PHP warning on my local site with the current version of AIO.

**Comment by michaeltorbert** [comment]
I hesitate to move forward with this too much without being able to reproduce it. 

Also, I wonder if just doing an ini_get is the best thing. Maybe there's some way around the file_exists() check that menu.php in WP core does? 
Would satisfying ! empty( $menu_hook ) work?

**Comment by michaeltorbert** [comment]
@arnaudbroes Do you want to try and reproduce this issue on a Windows server?

**Comment by michaeltorbert** [comment]
@arnaudbroes Do you want to try and reproduce this issue on a Windows server?

**Comment by arnaudbroes** [comment]
@michaeltorbert just to confirm, I need AIOSEOP installed on a test site that's hosted on an IIS server?

**Comment by michaeltorbert** [comment]
@arnaudbroes You know all I know, which is that both were using Windows. I don't know whether they were using IIS or Apache.

**Comment by arnaudbroes** [comment]
I set up a IIS web server on Windows Server 2016, installed WordPress 5.2 and All in One SEO Pack v2.12.1 and couldn't reproduce this error. There are no error entries in the log files.

I'm a 100% certain this issue is related to IIS on Windows and is a user configuration issue where the application pool node does not have sufficient access/read permissions. In other words: not an issue on our end.
