### ISSUE TITLE
/sitemap.xml not work

### ISSUE THREAD

**Issue by blogxkomo** [semperfiwebdesign/all-in-one-seo-pack#1333]
i have problem i use All In One SEO Pack 2.4.2 but if i try access : https://xkomo.com/sitemap.xml  still error.
can you help me ?

**Comment by michaeltorbert** [comment]
"This is not a support forum. We offer Premium Support for All in One SEO Pack Pro customers which can be purchased here: https://semperplugins.com/all-in-one-seo-pack-pro-version/"
