### ISSUE TITLE
HTTP vs HTTPS

### ISSUE THREAD

**Issue by web2033** [semperfiwebdesign/all-in-one-seo-pack#1334]
Hi! Any ideas?
![2017-11-02_225120](https://user-images.githubusercontent.com/11320080/32349849-1135d294-c021-11e7-9da6-d83f79e83c33.png)

**Comment by web2033** [comment]
![2017-11-02_225841](https://user-images.githubusercontent.com/11320080/32349935-6ccfec5c-c021-11e7-958d-ea1eb0b78279.png)

**Comment by michaeltorbert** [comment]
Most likely you have set up ssl incorrectly. We offer premium support for customers of All in One SEO Pack Pro: https://semperplugins.com/all-in-one-seo-pack-pro-version/
