### ISSUE TITLE
造成所有文章列表变形

### ISSUE THREAD

**Issue by underlaw** [semperfiwebdesign/all-in-one-seo-pack#1341]
造成所有文章列表变形了

**Comment by dawatorbert** [comment]
@underlaw 为了能更好的帮您解决问题，请提供您遇到的问题的屏幕截图，以及您期望看到的内容。最好能提供问题重现的步骤。谢谢！

**Comment by underlaw** [comment]
<img src="https://image.prntscr.com/image/52uko4DCTzSFLqCIZyM_bw.png">
<img src="https://image.prntscr.com/image/kPYcKV3iT7aPLcfeMkDGvQ.png">

**Comment by underlaw** [comment]
<img src="https://image.prntscr.com/image/52uko4DCTzSFLqCIZyM_bw.png">
<img src="https://image.prntscr.com/image/kPYcKV3iT7aPLcfeMkDGvQ.png">

**Comment by underlaw** [comment]
<img src="https://image.prntscr.com/image/52uko4DCTzSFLqCIZyM_bw.png">
<img src="https://image.prntscr.com/image/kPYcKV3iT7aPLcfeMkDGvQ.png">

**Comment by underlaw** [comment]
<img src="https://image.prntscr.com/image/52uko4DCTzSFLqCIZyM_bw.png">
<img src="https://image.prntscr.com/image/kPYcKV3iT7aPLcfeMkDGvQ.png">

**Comment by underlaw** [comment]
<img src="https://image.prntscr.com/image/52uko4DCTzSFLqCIZyM_bw.png">
<img src="https://image.prntscr.com/image/kPYcKV3iT7aPLcfeMkDGvQ.png">

**Comment by dawatorbert** [comment]
@underlaw 非常感谢您提供的屏幕截图。您所看到的不是由系统缺陷的问题（not a bug)。我们为All in One SEO Pack升级用户提供高端的售后支持服务，请到此链接加入我们的高端客户群体，我们会帮您解决。
https://semperplugins.com/all-in-one-seo-pack-pro-version/
