### ISSUE TITLE
German and Turkish translations should point to credit card (German) page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1342]
https://semperplugins.com/de/all-in-one-seo-pack-pro/ instead of https://semperplugins.com/all-in-one-seo-pack-pro/

This should happen in both German and Turkish translations of the readme as well as the plugin, anywhere the purchase link exists.

We should also probably make a separate issue to add a translator comment in these places for Turkish and German translators.

**Comment by michaeltorbert** [comment]
We have many purchase urls in the plugin... even better would be to simply make them not translatable, but instead filterable with a single filter, and if the locale is set to Turkish or German, to do it then.
We can probably set the purchase URL as a filterable constant early in the plugin and just use that.

**Comment by arnaudbroes** [comment]
@michaeltorbert I would either send them to our new link for credit card purchases (https://semperplugins.com/all-in-one-seo-pack-pro-credit-card-purchase/) or consider looking into WPML once more, see if we encounter and can solve the bugs and set up a German and Turkish page with the translations that we have.

**Comment by michaeltorbert** [comment]
I'm pretty sure WPML fixed the problems in a recent update. I think @wpsmort was going to look into testing it.

**Comment by wpsmort** [comment]
! tested WPML v3.9.2 and updated to this version after confirming that the redirect problem no longer exists.

**Comment by arnaudbroes** [comment]
This is no longer needed after our migration to WooCommerce.
