### ISSUE TITLE
Little mistake on test sample

### ISSUE THREAD

**Issue by vschettino** [semperfiwebdesign/all-in-one-seo-pack#1343]
Hi there,

Just to inform you that there's a little mistake on `tests/test-sample.php`, as you can see here:

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/80ce0cba8e68188064d3d4a9d62124feae24509c/tests/test-sample.php#L25

That should be a  `$this->`, not a `$this-&gt`.

Best Regards,

**Comment by michaeltorbert** [comment]
@vschettino Thank you for pointing that out. Feel free to submit a PR if you like.

**Comment by vschettino** [comment]
It'll be my pleasure :)

**Comment by michaeltorbert** [comment]
@vschettino Merged. Thank you. :)
Feel free to contribute anything else you like.
