### ISSUE TITLE
Date in og:title

### ISSUE THREAD

**Issue by Fabrizio62** [semperfiwebdesign/all-in-one-seo-pack#1346]
When I share an event in FB in the title appears the date of the event with yyyy-mm-dd format.
Very annoying.
How can I change the format in dd-mm-yyyy or hide the date in og:title?
here the link of fb post: https://www.facebook.com/centromaitri/posts/518132475214712
Thank in advance
Fabrizio Maffioletti

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. Premium support is provided to customers of All in One SEO Pack Pro, which can be purchased here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
