### ISSUE TITLE
Make date format filterable

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1347]
For at least current_date, if not post_date as well: https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L2084

Either as a single filter or as multiple filters.

**Comment by contactashish13** [comment]
@michaeltorbert I have 2 questions:

1. Is there a reason https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L2085 uses date_i18n and https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L2087 does not?

2. 
https://codex.wordpress.org/Function_Reference/date_i18n says 

> If the locale specifies the locale month and weekday, then the locale will take over the format for the date. If it isn't, then the date format string will be used instead.

This means if we do
```
date_i18n( apply_filter('filtername', get_option( 'date_format' ) )) 
```
this will end up modifying format w.r.t to the format of the locale (https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/functions.php#L103)

on the other hand, get_the_date() is a lot more straightforward. So the user has to be made aware of the above fact. Alternatively, both functions have their own native filters which users can use. Suggestions?

**Comment by contactashish13** [comment]
@michaeltorbert could you please review my comments and let me know how to proceed?

**Comment by michaeltorbert** [comment]
@contactashish13 

1) Not that I'm aware of. Oversight?
2) Maybe we can just filter the built-in filter?  `apply_filters(add_filter('date_i18n` or something?
What are your thoughts?

**Comment by contactashish13** [comment]
@michaeltorbert I'd prefer to change both form to date_i18n and then add a filter for date_i18n

**Comment by michaeltorbert** [comment]
Ok let's go with that. @contactashish13  You take charge of this

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1417

**Comment by contactashish13** [comment]
@wpsmort you can use this

`
add_filter( 'aioseop_format_date', 'aioseop_format_date', 10, 3);
function aioseop_format_date( $formatted_date, $date, $form ) {
return $formatted_date; // or format the $date using date( 'l jS \of F Y h:i:s A', $date );
}
`
