### ISSUE TITLE
OG Custom Image does not show.

### ISSUE THREAD

**Issue by v-at-dx** [semperfiwebdesign/all-in-one-seo-pack#1348]
ISSUE: Custom social (OG) image - DOES NOT WORK in BLOG POST.

DETAILS: 

I'd like selection for OG image to degrade in this order: 
1. Custom image from posts's Social Settings tab
2. Featured image for the post
3. Default image (from plugins Social Meta Settings)

However, on the social meta tab I don't see a way to set this up so it actually works.

I was expecting that it can be configured in this field: 
- Use Custom Field For Image - 
So, I'v tried this string: "Custom_Image, Custom_Twitter_Image, Featured_Image, post-thumbnail"
(and similar) - it did not work.

The only success I get is if I select (in the Select OG image in Social Meta setting) 
either a DEFAULT or a FEATURED image.

**Comment by arnaudbroes** [comment]
This is a development repository, not a support forum.
Support is available to paid customers. You can purchase the upgrade here - https://semperplugins.com/all-in-one-seo-pack-pro-version/
