### ISSUE TITLE
Unable to get default pic on Twitter Card, Please help

### ISSUE THREAD

**Issue by sumt7** [semperfiwebdesign/all-in-one-seo-pack#1349]
Hi there,
Kindly look at the updated issue on Wordpress Support forum.
Link https://wordpress.org/support/topic/wrong-default-image-for-home-main-url/#post-9665570

**Comment by arnaudbroes** [comment]
Please stop spamming us here, this is not a support forum.

**Comment by sumt7** [comment]
My humble apologies for the inconvenience but in a thread ( a month ago) you've asked to report the issue to Github.

**Comment by arnaudbroes** [comment]
If this were a genuine issue with All in One SEO Pack, which it isn't.

**Comment by sumt7** [comment]
So Sir,
If it isn't then Plz suggest what should I do?

On 11/9/17, Arnaud Broes <notifications@github.com> wrote:
> If this were a genuine issue with All in One SEO Pack, which it isn't.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1349#issuecomment-343113290


-- 
Best Wishes & Regards,

Sumeet Mahendra
www.bit.ly/sumt7p
