### ISSUE TITLE
XML Parsing Error

### ISSUE THREAD

**Issue by cpassero** [semperfiwebdesign/all-in-one-seo-pack#1355]
Sitemap -which has worked fine for years - now has this error

XML Parsing Error: junk after document element
Location: https://www.myremovablestickers.com/sitemap.xml
Line Number 2, Column 1:<b>Warning</b>:  pathinfo() expects parameter 1 to be string, array given in <b>/home/content/56/7854656/html/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php</b> on line <b>2826</b><br />
^

Here's the content of line 2826 inside webroot / wp-content / plugins / all-in-one-seo-pack / modules / aioseop_sitemap.php

$extn       = pathinfo( wp_parse_url( $image, PHP_URL_PATH ), PATHINFO_EXTENSION );

Is there a quick fix I can put in the code line? Any guidance would be appreciated.

**Comment by michaeltorbert** [comment]
The problem you're having is at https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L2826

Offhand I'd say your images don't have a PHP_URL_PATH for some reason.
Disabling the images in the sitemap *may serve as a quick fix.

Longer term things we may look at would be pulling out wp_parse_url and checking if the result is a string, or else something along the lines of 

`$parsed_url = wp_parse_url( $url ); 
if ( isset( $parsed_url[ 'PHP_URL_PATH' ] ) ){
   return false;
}`

**Comment by cpassero** [comment]
We did try to eliminate images in the sitemap but error continued.  We submitted our login info as requested. Thanks.

**Comment by EkoJr** [comment]
By any chance, have you tried saving your permalink structure in Settings > Permalinks?

**Comment by cpassero** [comment]
I just tried.  Saved the same permalink settings and then updated the sitemap.  Still a problem. Also tried changing the permalink display settings to include a date in the string. Rebuilt the sitemap. Error remains.

**Comment by contactashish13** [comment]
@cpassero could you tell us the PHP and WP versions you are using?

**Comment by cpassero** [comment]
Will check and get back.  Might be a couple hours.

**Comment by cpassero** [comment]
WordPress 4.6.8 but I can update to 4.8.3 if you think that will help.  Still checking the PHP version.

**Comment by cpassero** [comment]
PHP 5.3

**Comment by michaeltorbert** [comment]
@cpassero The short version is that you need to update to at least WP 4.7.

For development of this issue: We need to decide if we want to support <4.7, and if so implement a fix like I described above where we take out the component parameter.

**Comment by michaeltorbert** [comment]
PR #1356
