### ISSUE TITLE
Sitemap.xml - <image:image> switch off option

### ISSUE THREAD

**Issue by kulagin-ilya** [semperfiwebdesign/all-in-one-seo-pack#1360]
Hello, I need an option to switch off images in posts in my sitemap.xml . The thing is that Google Webmaster recognise this tag and everything ok with it, but the most popular Russian search engine Yandex doesn't recognise <image:image> tags yet and sends me an allert. While I don't have this option I cannot use Sitemap.xml module by All in one SEO Pack.

Thanks a lot!

**Comment by michaeltorbert** [comment]
This isn't a support forum. Premium support is available for users who purchase a Pro license: https://semperplugins.com/all-in-one-seo-pack-pro-version/
