### ISSUE TITLE
Special Characters Issue

### ISSUE THREAD

**Issue by springtouchweb** [semperfiwebdesign/all-in-one-seo-pack#1363]
In the Social Meta tool of your plugin when entering an ampersand after updating the ampersand is converted to "&amp; " that's how it would display in the social sharing card. 
![special-characters](https://user-images.githubusercontent.com/33703454/32861950-196b49f8-ca1c-11e7-86bc-3b50f94dfb5b.PNG)
![home-title](https://user-images.githubusercontent.com/33703454/32861951-197add0a-ca1c-11e7-858e-e77a4fb74bb9.PNG)

**Comment by springtouchweb** [comment]
It displays as `&amp;` ... "& amp;" not "&". Github autocorrected the entity in the first report, please let me know if you have any questions.

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1372

**Comment by wpsmort** [comment]
@contactashish13 I tested this and it works in that it corrects the OG meta output in the source code.  Is it possible to correct the title and description displayed in the fields under Social Meta > Home Page Settings as well?  The screenshot below shows that we still display the `&amp;`:

<img width="1352" alt="screen shot 2018-03-19 at 6 10 50 pm" src="https://user-images.githubusercontent.com/17548525/37625076-e1491be0-2ba0-11e8-942e-c3f882976f54.png">

**Comment by arnaudbroes** [comment]
This is now good. Needs code review.
