### ISSUE TITLE
Change link for schema.org to HTTPS

### ISSUE THREAD

**Issue by customtrim** [semperfiwebdesign/all-in-one-seo-pack#1366]
on line 4172 in the file aioseop_class.php

Here is the block of code:

		$search_box = <<<EOF
<script type="application/ld+json">
        {
          "@context": "http://schema.org",
          "@type": "WebSite",

It causes sssl validation errors.

Thank you!

**Comment by michaeltorbert** [comment]
Can you provide more information about the errors?
Screenshots, specific page you're one, exact text of the errors, etc.

**Comment by customtrim** [comment]
Hi Michael,
You really don't need a screenshot, what happens it the site will not call secure because of the http link. I have to change it to https on each update.
Schema.org is a secure site and there is no reason to leave that http link in your plugin.
Thanks,
Bill
   On Friday, November 17, 2017, 8:24:19 PM PST, Michael Torbert <notifications@github.com> wrote: 
 
 
Can you provide more information about the errors?
Screenshots, specific page you're one, exact text of the errors, etc.

**Comment by michaeltorbert** [comment]
@customtrim What browser is giving you ssl issues? What is the URL?

**Comment by customtrim** [comment]
Chrome, Firefox, and Edge.

Contourderm.com 

There is no error now because I changed the link upon each update from http://schema.org to https://schema.org

Did you receive this info in my github ticket?

I explained it in detail, with the file and line of code that’s the problem.

Thanks,

Bill

**Comment by michaeltorbert** [comment]
@customtrim Unfortunately I'm unable to replicate the issue. If you change it back, let me know and I'll take a look.

**Comment by customtrim** [comment]
I can let you have access to one of my dev sites on Monday, then you can test and see what I mean.

Contourderm.com is our main site and I try to keep it very secure as we are a medical office.

Thanks for all your support. It’s really refreshing to see!

Thanks,

Bill

**Comment by wpsmort** [comment]
We should do this as part of the Schema project in 3.0. All of the Schema examples that Google provides show https://schema.org

https://developers.google.com/search/docs/guides/search-gallery
