### ISSUE TITLE
Autogenerate Descriptions: Problem (2)

### ISSUE THREAD

**Issue by mobilapk** [semperfiwebdesign/all-in-one-seo-pack#1370]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1308

I opened the bug 2 months ago but no solution was made. I guess the crew does not have the ability to solve it. Please do not have the information we can not figure out this finding. I'm using yoast seo.

**Comment by arnaudbroes** [comment]
You posted this one month ago instead of two and this isn't one of our highest priorities.
Stop spamming us.
