### ISSUE TITLE
Correct tags order according to Sitemap protocol

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1371]
See conversation with Kevin K via email.

We should consider whether we want to correct the tag order for our XML sitemaps.
Currently, the priority tag is outputted before the changefreq tag while it should be the opposite.
https://www.sitemaps.org/protocol.html

**Comment by michaeltorbert** [comment]
Unless there's a reason not to I'd say we should. @wpsmort?

**Comment by michaeltorbert** [comment]
http://freetools.webmasterworld.com/tools/site-validator/#sthash.hCD7UuCC.vXNhS1Ia.dpbs

**Comment by michaeltorbert** [comment]
Ok generally it is the last one, we'll have to look into why it's not. Maybe only for indexed?

correct: view-source:https://semperplugins.com/sitemap.xml
incorrect: view-source:https://www.healthfulpursuit.com/sitemap_meal_type.xml

**Comment by arnaudbroes** [comment]
@michaeltorbert I'll look into it.

**Comment by contactashish13** [comment]
@michaeltorbert you were right. It was a problem only in the indexed pages. Additionally, the image tag was in the wrong location; have fixed that as well.

PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1378

**Comment by arnaudbroes** [comment]
@michaeltorbert I checked this and it works. Needs code review.

**Comment by wpsmort** [comment]
@contactashish13 I tested PR #1378 and found that the order is still wrong for all taxonomy sitemaps when indexes is disabled or enabled.  See screenshot:

<img width="996" alt="screen shot 2018-02-12 at 3 30 32 pm" src="https://user-images.githubusercontent.com/17548525/36118119-ef78c038-1009-11e8-9f97-a9c3cde85b6c.png">

**Comment by contactashish13** [comment]
@wpsmort fixed this.

@michaeltorbert another example here of things that will not work below WP 4.4.0: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1378/commits/0879891893bf73b20e75ca018194e14e7ba42621#diff-40a66dc34e8447efd254bdc5dc41f04cR2707

We may need to hasten support for 4.5.0

**Comment by michaeltorbert** [comment]
@contactashish13 We now don't support anything below 4.4. When you say hasten support for 4.5, do you mean not support below 4.5?
