### ISSUE TITLE
Update sitelinks searchbox code

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1375]
```
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebSite",
  "url": "https://www.example.com/",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "https://query.example.com/search?q={search_term_string}",
    "query-input": "required name=search_term_string"
  }
}
</script>
```

Updated with latest code from  here https://developers.google.com/search/docs/data-types/sitelinks-searchbox

**Comment by wpsmort** [comment]
I reviewed this with @EkoJR and we agreed that there is no action required here.  We're using the current code amended for use with WordPress, i.e. the search string is ?s={search_term_string}
