### ISSUE TITLE
Clean up current code for plugin UI

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#138]
This is in reference to issue #2 

This issue is for code cleanup as recommended by @iko-dev.

Once the code has been cleaned up and brought inline with the WordPress coding standards then we can improve the layout of the UI on mobile screen widths.

**Comment by iko-dev** [comment]
Ok, we will post regular updates here related to what comes on our way and we fix

**Comment by iko-dev** [comment]
On Friday, we have updated the names and id of css classes. Only dynamic names of classes are with _
