### ISSUE TITLE
After deploying to PROD, sitemap contains the correct domain but still uses http instead of https

### ISSUE THREAD

**Issue by heliodor** [semperfiwebdesign/all-in-one-seo-pack#1381]
Wordpress installation configured at http://localhost and deployed to https://somedomain.com

In my development environment, the sitemap and the robots file both show all urls as http://localhost/... Once copied over to my production server and accessed at https://somedomain.com, the sitemap and robots file both show **http**://somedomain.com instead of **https**://somedomain.com

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum.
Support is provided for Pro customers at https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by heliodor** [comment]
I don't need support. I'm simply reporting what looks like a bug to me, and explaining the context in case it helps you understand.

One expects that a dynamically generated sitemap should render with the same protocol, domain, and port from which it is being requested. If I request `http:localhost:5101/sitemap.xml`, the response should use `http:localhost:5101/` for all urls. And if I request `https://example.com/sitemap.xml`, the response should contain `https://example.com` and not `http://example.com`.

Would you say my experience indicates a bug or at least a missing "feature" or not?

**Comment by michaeltorbert** [comment]
These features use built-in WordPress functions to determine the scheme. 
Most likely, you haven't configured SSL correctly.
