### ISSUE TITLE
How to change changefreq

### ISSUE THREAD

**Issue by bimal008** [semperfiwebdesign/all-in-one-seo-pack#1383]
Hello 

how do i change change changefreq in a Sitemap ? 

Suppose i have a sitemap "sitemap_doctors.xml" and the sitemap has more the 100 url on it & each url's changefreq is set "monthly" at this time http://prntscr.com/hgrw3k . how do i change it to daly or weekly ?
Note: i only need to change or modify the "changefreq" for this particular sitemap other sitemaps need not any changes.

Any Help or guidance will be appreciated.

**Comment by arnaudbroes** [comment]
This is a development repository, not a support forum. 
You can purchase All in One SEO Pack Pro here and get acces to our support services - https://semperplugins.com/all-in-one-seo-pack-pro-version/
