### ISSUE TITLE
Ajax error on saving

### ISSUE THREAD

**Issue by taraschuiko** [semperfiwebdesign/all-in-one-seo-pack#1384]
When I'm trying to activate your xml sitemap module, i'm experiencing this issue. 
![screen shot 2017-11-29 at 16 02 38](https://user-images.githubusercontent.com/29632020/33378820-c29501c4-d51e-11e7-8141-040677dd89d8.png)

**Comment by arnaudbroes** [comment]
This is a development repository, not a support forum.
You can purchase All in One SEO Pack Pro here and get access to our support services - https://semperplugins.com/all-in-one-seo-pack-pro-version/
