### ISSUE TITLE
ALL IN ONE SEO PLUGIN

### ISSUE THREAD

**Issue by coreyconsulting** [semperfiwebdesign/all-in-one-seo-pack#1385]
Hello,

So why is it that the All in One SEO only allows me to choose the premium option for the plugin?

Thank you,

**Comment by arnaudbroes** [comment]
@coreyconsulting I'm not sure what you mean but please keep in mind that this a development repository, not a support forum or place to ask general questions about the plugin. You can contact us here - https://semperplugins.com/contact/
