### ISSUE TITLE
Get a wp.com business account for the purpose of AIOSEOP installation instructions

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1387]
Can we do a free trial or just one month so we can write instructions on installing .org or non-.org third party plugins?
We should also look at any other UI issues.

**Comment by arnaudbroes** [comment]
@michaeltorbert looks like there is no trial or a monthly plan but their FAQ does say this: Can I cancel my subscription? Yes. We want you to love WordPress.com, so we give you a 30-day refund on all your subscriptions. I will write to their support and confirm if we're able to purchase the annual plan, use it for testing purposes and then cancel it.

**Comment by michaeltorbert** [comment]
@arnaudbroes Maybe ask if we can have a short free or paid account of the business plan for purposes of writing instructions for our users since they have none.

**Comment by arnaudbroes** [comment]
@michaeltorbert their response:

> Hi there! You're right. You can receive a refund within 30 days of purchase, no questions asked. You can read more about it here: https://en.support.wordpress.com/refunds/

**Comment by tonyzeoli** [comment]
Hey guys...just following this. Is AIOSEOP going to be avail on
WordPress.com for WordPress Business Level customers?

**Comment by michaeltorbert** [comment]
@tonyzeoli It is available, which is why we have this issue to make instructions.

**Comment by tonyzeoli** [comment]
Cool - I'll start letting people know. Great news! Good luck!

**Comment by arnaudbroes** [comment]
I've written the documentation for this today and published it here - https://semperplugins.com/documentation/installation-instructions-for-wordpress-com-users/
