### ISSUE TITLE
Yandex and strange tag <image:image>

### ISSUE THREAD

**Issue by PaulStranger** [semperfiwebdesign/all-in-one-seo-pack#1388]
Hi.

The Yandex search engine (Yandex Webmaster) finds strange tags **<image:image>** in the sitemap.xml

I see by the code of the site map that for each link an post entry with a <image:image> tag for the picture is formed. How do I turn off or change the formation of these tags?

Screens:
https://image.prntscr.com/image/jMT3ILojTwm91demGzBjiA.jpg
https://image.prntscr.com/image/6gwAm0uWRFOfU2W4tMefug.jpg

Tnx!

**Comment by michaeltorbert** [comment]
@PaulStranger 
https://semperplugins.com/documentation/exclude-images-from-xml-sitemap-for-yandex/
