### ISSUE TITLE
Page Titles are not saving

### ISSUE THREAD

**Issue by JenniferFreeman** [semperfiwebdesign/all-in-one-seo-pack#1389]
The page titles are not saving - only half a title

**Comment by michaeltorbert** [comment]
@JenniferFreeman Can you provide more details and exact steps to reproduce?

**Comment by JenniferFreeman** [comment]
Hi Michael, yes. Thank you for replying. Literally as it sounds 
![image](https://user-images.githubusercontent.com/34233651/33556287-45a81ed6-d8fb-11e7-860a-cb9ecaf9a6a1.png)
I cannot add anything else to the home page title - it just deletes out. I have changed the force rewrite to prevent that from happening but still no fix..

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/why-doesnt-the-title-and-description-i-set-appear-in-search-results/
