### ISSUE TITLE
Social Meta Module - Validate entries in the Twitter Site and Twitter Domain fields

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#139]
This is related to issue #38 

We have two fields in the Social Meta Module under Twitter Settings where we should validate the entries.  These are:

Twitter Site:  This field should only contain a Twitter handle including the @ symbol
Twitter Domain:  This field should only contain a domain name (no http://)

See screenshot below:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14327441/5374b5f8-fc00-11e5-8d0c-dc6e2e2cbbe5.png)

**Comment by michaeltorbert** [comment]
@wpsmort The more I think about this, the more I think we need to validate on the way in...
At some point we have to say "if you were putting in nonsense all this time, it didn't work before, and it's not going to work now". We can't be concerned about preserving or trying to accommodate badly-formed data that's already stored.
I'm also still thinking we may want to consider copying the three fields over into one with a prefix

**Comment by wpsmort** [comment]
@michaeltorbert I agree with this.  I think it's the best approach out of the options.  Perhaps we can also include placeholder text that shows what the field expects as an input.

**Comment by michaeltorbert** [comment]
@wpsmort Ok this commit won't handle every case... it should handle username, @username, https://twitter.com/username, and http://twitter.com/username
This is why we need to validate on the way in :)
Make a separate issue for that, and reference these issues

**Comment by wpsmort** [comment]
This is tested and works fine.

**Comment by wpsmort** [comment]
This is tested and works in free and Pro.

A new issue #329 has been opened for Twitter Domain.
