### ISSUE TITLE
Problem with Protocol-Relative URL Format

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1390]
Reported here: https://wordpress.org/support/topic/problem-with-protocol-relative-url-format/

This may be if the URL for the image is a relative URL, and we don't turn it into a real URL in the sitemap, which Google likely needs.

**Comment by wpsmort** [comment]
@michaeltorbert I have tested this and confirmed that we do not output the protocol if it is missing from the image URL.  

For example, an image embedded using this URL:

//stevemortiboy.com/wp-content/uploads/2017/12/steve-headshot.jpg

results in the same URL in the XML Sitemap.  Google rejects that as an incomplete URL when you submit the sitemap to Google Webmaster Tools.

**Comment by contactashish13** [comment]
@wpsmort this has been fixed in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1286
