### ISSUE TITLE
Code Refactor - Add a AIOSEOP_Core / _Init class

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#1397]
Create a Core Class file as a Singleton in order to create only one instance to initiate AIOSEOP from.

Code from the initial file (`all-in-one-seo-pack.php`) can then be moved over, and there’s possibly some code in `All_in_One_SEO_Pack` class. Although, accessing variables or data objects should remain with the modules if they intend to be used multiple times, especially if outside of the core class instance.

Some key points regarding the issue. 

* [Singleton Design Pattern](https://sourcemaking.com/design_patterns/singleton).
* Add Hooks.
    * Hooks to modules, or classes, which may have more hooks, to be hooked on  `plugins_loaded`, `load_textdomain`, and/or `init`.
* Add required_once for files.
* Add Constants.
* Version Check (if any).
* Register_* (if any)
    * There is `register_activation_hook( __FILE__, 'aioseop_install' );`
* Keep file access warning in main file. 
    * "The All In One SEO Pack class is already defined".
    * Possibly add wp_die "Cannot access the files directly."
    * Possibly add requirement "Plugin requires WordPress X.X".

Things to avoid.

* Class variables/fields.
    * Singletons are treated as a single instance.
    * Can initiate & setup/install global variables. Accessing it outside is still possible, but slightly more complex ( ex. `class_name::get_instance()` ). Might be best to avoid.
* Static methods. Although, some code may have to be static.
    * For example, `aioseop_install()` would have to be a `public static` method.
* Don’t hook too late. Some classes, methods/functions require a hook that might be hooking too earlier.
    * [List of action hooks ordered by timing](https://codex.wordpress.org/Plugin_API/Action_Reference).

**Comment by michaeltorbert** [comment]
@contactashish13 Thoughts?

**Comment by contactashish13** [comment]
@EkoJr @michaeltorbert Based on my own struggles with the plugin, I would start with using a boilerplate that I've used/seen used with good results (https://github.com/DevinVinson/WordPress-Plugin-Boilerplate) as this will help separate the admin and public side of things and keep things more organized. The first thing the code needs IMHO is organization and separation so that it becomes patently obvious what will affect what part, which right is now is rather difficult.

I don't particularly like singletons because they don't make sense in PHP vs. the singletons in Java or C that actually are "singletons". I would prefer dependency injection in PHP to ensure a class is created once but can be used anywhere.

**Comment by EkoJr** [comment]
I definitely agree on code organization, and the boilerplate; which I also use, and was slowly introducing the concept. The Admin class was also something I was planning on bringing up as well, and I imagine it would clean things up the most, but wasn't sure if it would be too soon to introduce it with the way the `All_in_One_SEO_Pack` class is.

The `All_in_One_SEO_Pack` class seems to be what needs the most unraveling. It also contains many of the general settings, but thought it could be improved by introducing the following...

* Core / Init class.
* Post_Metadata class - As a data object.
* Post_Editor/Actions class - Contains actions and post transitions.
* Admin class - Admin content, scripts, etc.

Optimizing the Database options was another thought. Everything seems to be all in one wp_options, and the way modular classes use/add-to it was a lot to take in.

## Singleton & Dependency Injection ( DI )

I'm familiar DI with various situation, but I've never implemented it as an alternative to a singleton. My main worry is repeating or re-initializing code that has already been processed.

Singletons, I've applied mostly as the initial creation pattern, and the amount of use is usually small depending on how much initializing there is. 

This is what I was referring to for [Dependency Injection](http://php-di.org/doc/getting-started.html) in this situation.

I can't comment too much on it, but DI may work out very well for some situations by offering functions and variable some other modules share. It also makes me a bit curious about modular testing. However, as a single instance to start from...I'm not completely sure how it would look like to achieve the same concept.
