### ISSUE TITLE
Not able to update Google webmasters info. Upon pasting the code and clicking update the field is not getting updated.

### ISSUE THREAD

**Issue by ayushgangrade11** [semperfiwebdesign/all-in-one-seo-pack#1398]
I am using wordpress through heroku and have a free version of all in one seo pack.

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. You can find troubleshooting steps here https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/ or if you'd like Premium Support you can purchase a license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
