### ISSUE TITLE
Auto-generated Description not working if post starts with image

### ISSUE THREAD

**Issue by waqarts** [semperfiwebdesign/all-in-one-seo-pack#1402]
![setting 1](https://user-images.githubusercontent.com/30706949/33809122-62e073b4-de13-11e7-9074-8bcd0764db9a.png)
![setting 2](https://user-images.githubusercontent.com/30706949/33809123-6316c1e4-de13-11e7-9674-0fc9a427f1b0.png)
![source view](https://user-images.githubusercontent.com/30706949/33809124-634b824e-de13-11e7-9f36-276b5d0faab1.png)

Auto-generated Description not working on post which is starting with image example url https://apk4funfull.com/2017/04/solitaire-vr-v1-0-apk/

**Comment by wpsmort** [comment]
Reported again here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/autogenerate-descriptions-not-working-for-some-regular-posts/#p7275

**Comment by wpsmort** [comment]
@michaeltorbert I have verified this is a bug.  Here are the steps to reproduce:

1. On a new site, install AIOSEOP and enable Autogenerate Descriptions
2. Create a post with an image as the first object followed by text.  The code should look like this:

```
<img src="http://stevemortiboy.com/wp-content/uploads/2017/09/mega-yacht-20-300x139.jpg" />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget ex volutpat, vulputate nibh ut, tincidunt erat. Morbi nunc velit, lacinia sed nunc ac, vehicula dignissim nisl.
```

3. Verify that there's no auto generated description in the Description field or the source code.

The auto generated description does work if the image is wrapped in an anchor tag like this:

```
<a href="http://stevemortiboy.com/wp-content/uploads/2017/09/mega-yacht-20-300x139.jpg"><img class="alignnone" src="http://stevemortiboy.com/wp-content/uploads/2017/09/mega-yacht-20-300x139.jpg" alt="" width="300" height="139" /></a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget ex volutpat, vulputate nibh ut, tincidunt erat. Morbi nunc velit, lacinia sed nunc ac, vehicula dignissim nisl.
```

This first appeared in version 2.4.

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1420

**Comment by contactashish13** [comment]
@wpsmort just realized that https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1103 might be related to this

**Comment by wpsmort** [comment]
I have confirmed that this is the same issue reported in #1103.

**Comment by contactashish13** [comment]
@wpsmort synced with upstream
