### ISSUE TITLE
Double site title on posts page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1408]
Reported here: https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/posts-page-preview-snippet-shows-site-title-twice/

Preview snippet of posts page is showing page title | site title | site title

We need to determine whether this bug has always been there, or when it was introduced.

**Comment by arnaudbroes** [comment]
@michaeltorbert first appeared in 2.2.4. I found this in the changelog:

> Added placeholder text to show auto generated titles and descriptions on the edit post/page screen

**Comment by arnaudbroes** [comment]
Might be related (double vertical bar) - https://wordpress.org/support/topic/double-separator-in-wordpress-title/

**Comment by arnaudbroes** [comment]
I've cloned Marcos site to my personal development server and will look into this server.

**Comment by arnaudbroes** [comment]
Reported again here - https://wordpress.org/support/topic/title-shown-twice-in-preview-snippet-on-posts-page/

**Comment by michaeltorbert** [comment]
@arnaudbroes Can we reproduce this yet?

**Comment by wpsmort** [comment]
Reported again by Marcos by email today.

**Comment by wpsmort** [comment]
I have been able to reproduce this on a new site by following these steps:

1. Set up WordPress with Reading Settings > Your homepage displays set to A static page and a Homepage and Posts page selected
2. Install the current version of AIOSEOP (v2.12.1) and activate it
3. Edit the Posts page and you should see the double site titles in the Preview Snippet
