### ISSUE TITLE
Plugin broke my sitemap?

### ISSUE THREAD

**Issue by justinpward** [semperfiwebdesign/all-in-one-seo-pack#1409]
![image](https://user-images.githubusercontent.com/26862075/33902408-c2e4fca0-df29-11e7-9340-057eaf00916e.png)
Everything seemed to suddenly break for me. Reset to defaults, also broke. Updated to latest version. https://livemusicblog.com/sitemap.xml

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/this-page-contains-the-following-errors/
