### ISSUE TITLE
Error with Gutenburg

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1410]
Reported here: https://wordpress.org/support/topic/gutenberg-2/

The plugin throws the following console error when used together with the forthcoming Gutenberg editor plugin:

TypeError: Cannot read property 'aiosp_title' of undefined

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1412

**Comment by wpsmort** [comment]
This is tested and is good.  There were no console errors in the Gutenberg editor and everything worked with AIOSEOP and Gutenberg.
