### ISSUE TITLE
Don't know how to reactivate All in one SEO pro

### ISSUE THREAD

**Issue by wilfrantz** [semperfiwebdesign/all-in-one-seo-pack#1418]
Hi,

I had to uninstall the All in one plugins to troubleshoot a bug, now that everything is back to normal, I don't know how to reactivate the pro version. I still have the product key .

**Comment by arnaudbroes** [comment]
@wilfrantz this is our development repository so I'm afraid we're unable to help you here. Please fill out this form and we'll be happy to help you - https://semperplugins.com/contact/
