### ISSUE TITLE
Add a Free banner to all modules included in the free plugin

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#143]
Add a banner that indicates modules in Feature Manager are free.

Whilst doing this, we should improve the appearance of the Feature Manager.  A good example is how Jetpack used to look.  See screenshot of old Jetpack Feature Manager.

![jetpack-dashboard](https://cloud.githubusercontent.com/assets/17548525/14333733/2d0b8842-fc1e-11e5-8634-18bdddf03b17.png)

**Comment by wpsmort** [comment]
Code has been added and tested.

**Comment by michaeltorbert** [comment]
I disagree that it was tested. :)
Features couldn't be activated and deactivated? I'm committing a fix.
