### ISSUE TITLE
All in One SEO Plugin is rearranging title tag 

### ISSUE THREAD

**Issue by marhangelsky** [semperfiwebdesign/all-in-one-seo-pack#1431]
What we thought was a OPD indexing issue initially, however looks like the title tag is being re formatted. Looks like all settings are set correctly. Has anyone else experienced this issue before? The title tag format displays with a : and - ex: center for dental excellence : dentist - orlando fl 

We have the title tag set  Dentist - Orlando FL - Center For Dental Excellence

Any assistance is appreciated 

Thanks 

Mike

**Comment by marhangelsky** [comment]
What we thought was a OPD indexing issue initially, however looks like the title tag is being re formatted. Looks like all settings are set correctly. Has anyone else experienced this issue before? The title tag format displays with a : and - ex: center for dental excellence : dentist - orlando fl

We have the title tag set Dentist - Orlando FL - Center For Dental Excellence

Any assistance is appreciated

Thanks

Mike

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. Premium support is available for Pro customers which can be purchased here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
