### ISSUE TITLE
Improve all instances of get_permalink()

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1446]
related to #1445 

Search through the plugin and find all instances of it.
We can probably just use urldecode() for get_permalink for languages like Hebrew

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1460

I wonder why get_permalink does not do a urldecode by default and I couldn't find a reason for it.

**Comment by michaeltorbert** [comment]
@contactashish13 No idea. You'd think it would.
