### ISSUE TITLE
Change google urls to https

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1455]
I'm not sure if changing them to https will correct this.

Reported by Einar via email:

WordFence finds 2 issues related to All in One SEO Pack installed on this website:
---------------------
1: File contains suspected malware URL: /home/M/mestrestressno/www/wp-content/plugins/all-in-one-seo-pack-pro/public/google-analytics.php
Filename: wp-content/plugins/all-in-one-seo-pack-pro/public/google-analytics.php
Bad URL: http://www.google-analytics.com/analytics.js
File Type: Not a core, theme or plugin file.
Issue First Detected: 15 hours 58 mins ago.
Severity: Critical
Status New
This file contains a URL that is currently listed on Wordfence's domain blacklist. The URL is: http://www.google-analytics.com/analytics.js
-------------------------
2: File contains suspected malware URL: /home/M/mestrestressno/www/wp-content/plugins/google-sitemap-generator/sitemap-core.php
Filename: wp-content/plugins/google-sitemap-generator/sitemap-core.php
Bad URL: http://www.google-analytics.com/collect
File Type: Not a core, theme or plugin file.
Issue First Detected: 15 hours 58 mins ago.
Severity: Critical
Status New
This file contains a URL that is currently listed on Wordfence's domain blacklist. The URL is: http://www.google-analytics.com/collect

**Comment by michaeltorbert** [comment]
Update: this message was a false positive from WordFence, which they've now corrected. https://wordpress.org/support/topic/suspected-malware-url-2/#post-9830243

We may still want to consider the https version.

**Comment by wpsmort** [comment]
The code link in public/google-analytics.php is now HTTPS.  This change was made a while back, possibly as part of #921.
