### ISSUE TITLE
Social Meta Module - OG Image refers to the first image uploaded and attached to the post even if it is later deleted

### ISSUE THREAD

**Issue by contactashish13** [semperfiwebdesign/all-in-one-seo-pack#1462]
1. Create a new post, upload a new image and insert into post
2. View source of the post and og:image will contain a reference to this image.
3. Delete this image from the post and repeat steps 1 and 2. og:image will contain a reference to the first image instead of the new image uploaded and attached.

**Comment by contactashish13** [comment]
@michaeltorbert I'm not sure but is this a feature rather than a bug?

**Comment by contactashish13** [comment]
@wpsmort can you please comment on this?

**Comment by wpsmort** [comment]
@contactashish13 It depends what you have set under All in One SEO > Social Meta > Image Settings > Select OG:Image Source.  What do you have set there?  Which setting in that drop down causes a problem?

**Comment by contactashish13** [comment]
@wpsmort Here are the steps to reproduce this:

1. Enable Social Meta.
2. In "Select OG:Image Source" select "First Attached Image".
3. Click update options.
4. Create a new post and use the Add Media button to upload a new image, attach to the post and save post.
5. View the post and its source. og:type will refer to this image.
6. Delete the image from the post and save.
7. View the post and its source. og:type will still refer to this image.
8. Use the Add Media button to upload a new image, attach to the post and save post.
9. View the post and its source. og:type will still refer to the first image (**should refer to the second image**).
10. Go to the image library and delete the first image permanently.
11. View the post and its source. og:type will now refer to the second image.

It seems like when a new image is uploaded to a post, it becomes permanently attached to it till deleted from the library.

**Comment by wpsmort** [comment]
This is correct behavior.  When you delete the image from the content it does not detach it from the post.  You have to go to the Media Library and detach the image from the post.  Once you do that the image no longer shows as the og:image.
