### ISSUE TITLE
Not auto shortening the meta-description

### ISSUE THREAD

**Issue by nbagonoc** [semperfiwebdesign/all-in-one-seo-pack#1469]
After updating from Version 2.4.3 to Version 2.4.4 this morning, it wont auto shorten long descriptions taken from the post/page. Please fix :( I don't want to manually shorten all the descriptions.

Thank you.

**Comment by michaeltorbert** [comment]
@nbagonoc Can you please provide the exact steps to reproduce this issue.

**Comment by nbagonoc** [comment]
Welp, I've just auto updated from 2.4.3 to 2.4.4 using Easy Updates Manager on all my wordpress websites, and all dynamically generated meta-descriptions(before was 170 characters) now became  300+ characters.

**Comment by michaeltorbert** [comment]
@nbagonoc Google has increased the description from 170 to 280-320.

**Comment by nbagonoc** [comment]
Woah... Didn't know that. Thank you @michaeltorbert!
