### ISSUE TITLE
Change terminology from blog->website

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1471]
We've had people think All in One SEO Pack is blog-centric. To change this, we should use website-centric language as appropriate instead of blog-centric language.
Related to https://github.com/semperfiwebdesign/semperpluginstore/issues/468

**Comment by arnaudbroes** [comment]
Discuss with Steve and Michael.

**Comment by wpsmort** [comment]
See #1271 for changing %blog_title% macro
