### ISSUE TITLE
Refactor settings initialization function

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1475]
A user is reporting that he settings reset during times of high traffic. https://wordpress.org/support/topic/bug-all-settings-lost-every-few-days/#post-9853750

He claims it's because we're inserting the settings whenever the plugin doesn't see them, not just checking on activation and when a user manually resets.

This seems unlikely, but looking at the code, he has a point, and we should consider improving this.

_**line 45 in /inc/aisop_functions.php (aioseop_mrt_mkarry())**_

**Comment by contactashish13** [comment]
@michaeltorbert I encountered this poorly named function and changed its name to correctly reflect its functionality in https://github.com/semperfiwebdesign/aioseop-pro/pull/380/commits/8941acd4a2908a659412311559059bc27099e6f3#diff-6af21e50a76dede12b6ea57fd72afe8eR42. 

I wonder if there was a use case where this needed to be fired on every single request.

I've renamed the function and, as a temporary measure, I'm checking for this with an is_admin() check. PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1477

**Comment by michaeltorbert** [comment]
In testing, we need to make sure it still works for both manually reseting the settings as well as new installs.

**Comment by michaeltorbert** [comment]
@contactashish13 is_admin() is probably a good improvement in that it makes it run on every wp-admin load instead of every load, but I wonder if we could improve it even further (short of a complete overhaul of the functionality itself)

**Comment by contactashish13** [comment]
I didn't want to fiddle around with it too much. The ideal scenario would be to set it once when the plugin is activated. But I'm was not sure of the below points:

1) under what circumstances can the settings can go MIA/be deleted directly from the database. I don't see any way in the admin that they can be deleted.
2) if they are indeed MIA, the functionality that depends on them should continue working with the defaults or should throw an error?

**Comment by michaeltorbert** [comment]
1) I can't think of any where that would happen, yet WP and the plugin is running. This sounds like it's a very strange setup.
2) My guess is should be defaults for the most part?

**Comment by contactashish13** [comment]
I feel that if the options go missing, the plugin should report an error instead of continuing with defaults. This is because the user will not know the options went missing and will think the plugin is behaving incorrectly.

**Comment by michaeltorbert** [comment]
Currently it checks if the option exists, as a way of knowing whether the plugin has been installed before. I know of no way around that.

**Comment by contactashish13** [comment]
I think a more elegant way is by adding a timestamp when the plugin is first activated. This would also help in checking if the welcome screen needs to be launched or not because if the timestamp exists, this is the Nth time the plugin is being activated.

I've added this kind of a timestamp in one of my PRs, can't recall which one.

**Comment by michaeltorbert** [comment]
Presumably if the option entry isn't available, neither would the timestamp.
