### ISSUE TITLE
ob_start conflict

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1476]
Reported here: https://wordpress.org/support/topic/ob_start-and-html-minifying-error/ and https://wordpress.org/support/topic/minfy-html-error/

The plugin Fast Velocity Minify uses ob_start, and a user gets the following html validation errors due to our outputting of "ob_start_detected"

“Stray end tag ‘head’” and “‘body’ start tag seen, but element of the same type was already open”

**Comment by contactashish13** [comment]
I can't reproduce this issue.

The comment is correctly printed as below when the plugin detects a conflict
```
<!-- All in One SEO Pack 2.4.4 by Michael Torbert of Semper Fi Web Designob_start_detected [-1,-1] -->
```

 Also I'm not sure why the user specifically says Firefox (and where on Firefox? I can't find it on any tab in the dev tools)

> Firefox tells me “Stray end tag ‘head'” and “‘body’ start tag seen, but element of the same type was already open”.

**Comment by michaeltorbert** [comment]
@EkoJR Can you try one last time to reproduce this or figure out why it might be happening?

**Comment by arnaudbroes** [comment]
I couldn't reproduce this either. Looks fine.
