### ISSUE TITLE
Expanded snippets

### ISSUE THREAD

**Issue by jraechiu** [semperfiwebdesign/all-in-one-seo-pack#1482]
Does the plug-in support meta descriptions longer than 155 characters? Google has officially lengthened the SERP snippet to around 300 characters. I updated a client's meta descriptions so most are now longer than 200 characters; however, a crawl using Screaming Frog has me concerned that the full meta description cannot be crawled. 

I'd appreciate knowing if the full text that's entered into the meta description can be crawled by search engines.

Thank you!

**Comment by michaeltorbert** [comment]
We updated it to 320 after Google made their change.

**Comment by jraechiu** [comment]
Thanks for confirming. I should have updated the plugin first. Works fine now.
