### ISSUE TITLE
SEO Title field reverts upon save

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1492]
Reported by Morgane here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/issue-with-emojis/

The original report was that saving anything in the AIOSEOP meta box on a post, page or WooCommerce product resulted in the fields reverting to an empty state.  However, it appears this only happens when an Emoji is added into the SEO Title or Description or OG Title or Description fields.

I was unable to reproduce this on any of my sites, however, I can reproduce this on the client site and on a clone of the client site on our server.  I was able to reproduce the problem even when updating WordPress, deactivating all plugins and switching to the Twenty Seventeen theme.

I have set up a clone for testing where we can reproduce the problem.

**Comment by wpsmort** [comment]
@contactashish13 Can you take a look at this and see if you can find out what's causing this issue on the clone site please.  I will send you login info via Slack.

**Comment by bagit** [comment]
Hello @wpsmort and @contactashish13 

The issue concerns [emojis](http://getemoji.com/) and not smilies

Thank you for help 👍

**Comment by michaeltorbert** [comment]
@bagit Does it count if your comment made me smile? :D

**Comment by wpsmort** [comment]
@contactashish13 This may help:

https://codex.wordpress.org/Emoji
https://en.support.wordpress.com/emoji/#emoji

I'm on a Mac so I can press Command + Control + Space and it shows the Emoji popup.  You can also copy and paste emojis from sites such as https://getemoji.com/

**Comment by bagit** [comment]
@michaeltorbert :p  

@wpsmort Indeed, I copy & paste from getemoji.com and this empties the field

**Comment by bagit** [comment]
Hi,

any news ?

Best,

**Comment by wpsmort** [comment]
@contactashish13 Have you been able to reproduce this issue yet?

**Comment by contactashish13** [comment]
@wpsmort I had asked for some information on slack, can you please respond to that?

**Comment by wpsmort** [comment]
@contactashish13 Thanks, I just responded to you.  Let me know if you're still having problems editing files.

**Comment by contactashish13** [comment]
I have not been able to discover the reason for this. Apparently this happens for any post meta. I tested this by enabling custom fields from screen options and updating any custom field with an emoji. It doesn't get saved. Its not a problem with the database version. PHP has multibyte support on. I tested with chinese, Spanish and German characters and all of then work except emojis.

That said, https://github.com/backdrop/backdrop-issues/issues/884 could be the potential problem. I checked my local dev database and the columns are all of collation `utf8mb4_unicode_ci` whereas on the problematic site they are all `utf8_unicode_ci`. But then that does not explain how the post_title is able to store an emoji and post meta columns aren't.

**Comment by michaeltorbert** [comment]
Is this a problem specifically with AIOSEOP? ie if you deactivate AIOSEOP, and activate some other plugin with post meta entry fields, does it work?

**Comment by contactashish13** [comment]
Its not a problem with the plugin. Its a problem with the post meta fields only. I followed the steps below to test it outside of the plugin:

> Apparently this happens for any post meta. I tested this by enabling custom fields from screen options and updating any custom field with an emoji. It doesn't get saved

**Comment by michaeltorbert** [comment]
@wpsmort Should this be closed? Is it possibly related to Marcelo's problem?

**Comment by wpsmort** [comment]
There was a report from Marcelo by email on 2/1/2018 where he could not save SEO data to posts or pages.  I was able to verify this on his site, each time I tried to update the post with the SEO data the SEO data disappeared.  I tried adding a custom field and that also failed.  I tried backing up the database and that returned this error: 

Unable to get table creation SQL for table `wp_postmeta`. Result: `1`. Verify that it exists and mysql permissions allow this.

The issue with Marcelo's site is a problem with the database that affects saving any post meta.

**Comment by michaeltorbert** [comment]
Reported again here: https://wordpress.org/support/topic/emojis-in-meta-description-not-showing/

It's suggested that "our main competitor" doesn't have that problem.
We should look into seeing if we can come up with a resolution.

**Comment by michaeltorbert** [comment]
Reported again here: https://twitter.com/LanceH61920/status/1016766810081910784

**Comment by michaeltorbert** [comment]
Closing this until we can reproduce.

**Comment by randompixels** [comment]
This still happens under version 3.3.3.

@michaeltorbert to reproduce, just add a 🥇 character in the *Home Title* field of the General Settings page.

**Comment by arnaudbroes** [comment]
@randompixels works fine on my end - 
![image](https://user-images.githubusercontent.com/18156697/69273389-90e52800-0bd8-11ea-97fe-e13e81d0ea96.png)
