### ISSUE TITLE
Display settings do not work

### ISSUE THREAD

**Issue by FactorExtremo** [semperfiwebdesign/all-in-one-seo-pack#1495]
Hello, first, thanks for keeping the plugin updated.

There is a issue that I have detected for several months, when I want to change the display settings not work, simply the options do not deploy.

thanks

**Comment by michaeltorbert** [comment]
Please provide the exact steps to reproduce.

**Comment by FactorExtremo** [comment]
Hi Michael, 
I attached a screenshot
![screenshot_1](https://user-images.githubusercontent.com/35585666/35132621-16f1462c-fc9a-11e7-91d2-bca81dbd69b5.png)

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

**Comment by FactorExtremo** [comment]
Thanks, I'll try
