### ISSUE TITLE
I have a problem with sitemap

### ISSUE THREAD

**Issue by place4print** [semperfiwebdesign/all-in-one-seo-pack#1496]
Hello,
Can you help me with the error?

**This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.**

Thank you for your help.

Best,
Mike

**Comment by michaeltorbert** [comment]
This isn't a support forum. You can find our documentation here: https://semperplugins.com/documentation/ or pay for support here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
