### ISSUE TITLE
All in One SEO Categories Issue 

### ISSUE THREAD

**Issue by SobetonNYC** [semperfiwebdesign/all-in-one-seo-pack#1497]
We are unable to modify categories, in fact "Categories" does not even show as an
![general settings fantasy floral chantilly florist post types](https://user-images.githubusercontent.com/35630192/35184072-b1da66bc-fdbe-11e7-96e8-591447c8eba3.png)
![edit category fantasy floral chantilly florist wordpress -cats](https://user-images.githubusercontent.com/35630192/35184073-b1eafffe-fdbe-11e7-9043-a844f7607d80.png)
![edit product fantasy floral chantilly florist wordpress](https://user-images.githubusercontent.com/35630192/35184074-b1fbb146-fdbe-11e7-85d2-67478457ada6.png)

 option.

**Comment by michaeltorbert** [comment]
@SobetonNYC SEO for categories/product categories/taxonomies is a Pro feature, which you can purchase here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
