### ISSUE TITLE
Posts Page Title

### ISSUE THREAD

**Issue by YMBond** [semperfiwebdesign/all-in-one-seo-pack#1498]
Could you please advice? I recently found on my Posts Page
Title is: Heath Blog

Preview Snippet show me:
Heath Blog | SleepAdvice & more | SleepAdvice & more

	• WordPress Version4.9.2
	• WordPress DB Version38590
	• MultisiteNo
	• Active ThemeTwenty Seventeen 1.4
	• Site TitleSleepAdvice & more
	• All In One SEO Pack2.4.4.1

**Comment by michaeltorbert** [comment]
@YMBond We'd love to look into this for you. You can submit your login information to our secure form at https://semperplugins.com/contact/submit-login-information/
