### ISSUE TITLE
about meta name="description"

### ISSUE THREAD

**Issue by wp1113** [semperfiwebdesign/all-in-one-seo-pack#1531]
a long time ago, All in one seo pack will automatically cut out article main body first 200 words as meta name="description" if not fall in description manually. after some update, this feature disappeared.  i found at version 2.4.4.1 this feature back again. but right now not first 200 words to meta name="description" is all article will put on "description". 

could you please help check the issue? maybe this issue just for Chinese.

![capture](https://user-images.githubusercontent.com/32380576/35506456-476299d6-0524-11e8-8b80-4f825b594971.JPG)

**Comment by EkoJr** [comment]
That would probably be occurring because you have a manual description set with the plugin's meta data description.

I tested, and the Automatic Descriptions are still being trimmed; including the chinese language.
