### ISSUE TITLE
file_get_contents error in sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1538]
"Failed to seek to position -1" php error in aioseop_sitemap.php line 10:32

`$file = file_get_contents( $fn, false, null, - 1, 4096 );`

Reported here: https://wordpress.org/support/topic/sitemap-blocked-b-robots/ (It's not clear the other information in the post is related, so when working on this, we may need to ignore the extraneous stuff).

**Comment by EkoJr** [comment]
Duplicate of #1428
