### ISSUE TITLE
No pagination for canonical URLs results canonical URL pointing to 404 page

### ISSUE THREAD

**Issue by docjohn** [semperfiwebdesign/all-in-one-seo-pack#1550]
If you are on a paginated index result (blog index, author index, archives, etc.) and have No pagination for canonical URLs checked, it will output the canonical URL to be /page/ -- which does not exist in stock Wordpress install, resulting in a 404 error.

Example:

https://pro.psychcentral.com/exhausted-woman/page/2/

outputs the following meta tag:

`<link rel='canonical' href='http://pro.psychcentral.com/exhausted-woman/page/' />`

However, that page does not exist and therefore returns a 404 error:

http://pro.psychcentral.com/exhausted-woman/page/

**Expected behavior:**

Canonical URL meta tag should be outputting the root URL with the /page/ component of the URL removed:

`<link rel='canonical' href='http://pro.psychcentral.com/exhausted-woman/' />`

**Comment by wpsmort** [comment]
I am not able to reproduce this.  I tested different post types, taxonomies, archives, blog page, static homepage, dynamic homepage, search page, and WC shop page.  All canonical links were correct for paginated pages, meaning they redirected to the first page.
