### ISSUE TITLE
count(): Parameter must be an array or object that implements Countable in aioseop_class.php:2661

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1556]
Warning: count(): Parameter must be an array or an object that implements Countable in /public_html/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 2661

Reported here: https://wordpress.org/support/topic/warning-count-parameter-must-be-an-array-or-an-object-that-implements-counta/

**Comment by EkoJr** [comment]
Duplicate of #1491
