### ISSUE TITLE
wp_parse_url requires WP 4.4

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1559]
Whilst tested the dev branch of AIOSEOP v2.4.5 on a site running WP v4.3 I got this fatal error:

Fatal error:  Uncaught Error: Call to undefined function wp_parse_url() in /wp-content/plugins/all-in-one-seo-pack-development/modules/aioseop_sitemap.php:2845

The reason for this is that wp_parse_url was introduced in WP 4.4 - https://developer.wordpress.org/reference/functions/wp_parse_url/

**Comment by michaeltorbert** [comment]
Closing this since we no longer support <4.4
