### ISSUE TITLE
Remove support for get_the_post_thumbnail_url

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1561]
In Issue #1533 we added support for get_the_post_thumbnail_url so we could support WP v4.4.   During the release of AIOSEOP v2.4.5 we discussed whether we want to support WP v4.4.  We decided we did not so we should now remove the code added for get_the_post_thumbnail_url.

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1586
