### ISSUE TITLE
missing tinymce buttons in text editor 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1566]
This was introduced in 2.4.5

Reported:
https://wordpress.org/support/topic/admin-post-edit-area-issues-after-last-update/
https://wordpress.org/support/topic/tinymce-issues-since-updating-to-2-4-5/

Probably from https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/72bb77f4af9331c3183ca0499bd5438c6c3afbf2#diff-ef104315837de467ca8882f5a0a4b64b / https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/72bb77f4af9331c3183ca0499bd5438c6c3afbf2#diff-a49a1e48ac5a28e789ed856196af92c5R713

getting the error:
Cannot read property 'toLowerCase' of undefined

**Comment by contactashish13** [comment]
@EkoJr The problem appears to be that we are trying to determine property of something that does not exist. So, I think the fix can be improved by checking if the number of elements retrieved is > 0 instead of trying to determine the value of prop("type"). 

`
    if($('.aiseop-date').length > 0 && $('.aiseop-date').eq(0).prop('type').toLowerCase() === 'text'){
        $('.aiseop-date').datepicker({
            dateFormat: "yy-mm-dd"
        });
    }
`

**Comment by EkoJr** [comment]
@contactashish13 That doesn't seem to work for the XML Sitemap settings.

**Comment by contactashish13** [comment]
@EkoJr that part of the code adds backward compatibility to browsers that do not support HTML5 date field. So if you are using a modern browser, the part under `if` will not execute. Is that what you mean by its not working?
