### ISSUE TITLE
Create new square icon for wp.org

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1574]
Maybe replace the shield with the gear?

**Comment by EkoJr** [comment]
@michaeltorbert this sounds like it could be added to the "UI Changes" Project ( https://github.com/semperfiwebdesign/all-in-one-seo-pack/projects/8 ).

**Comment by arnaudbroes** [comment]
@michaeltorbert yes, I would use the shield. What are the required dimensions?

**Comment by michaeltorbert** [comment]
https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

**Comment by arnaudbroes** [comment]
Related to #1963.

**Comment by michaeltorbert** [comment]
This is done: https://wordpress.org/plugins/all-in-one-seo-pack/
