### ISSUE TITLE
Javascript conflict with Themify

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1577]
Reported via email:

> We found that the "All in one SEO Pack" plugin is causing Javascript errors and breaking the Themify Custom Panel: https://cl.ly/3i1W412B0s0w. It is recommended to report to the plugin's developer to fix it or deactivate it.
As per- info@themify.me

**Comment by EkoJr** [comment]
That should be fixed with 2.4.5.1. It appears he is still on 2.4.5; which also looks like the known issue at the time.

**Comment by michaeltorbert** [comment]
You're right. He is running 2.4.5.1, but javascript thinks it's 2.4.5, which points to caching.
