### ISSUE TITLE
256 memory php 68 mb

### ISSUE THREAD

**Issue by srmongo** [semperfiwebdesign/all-in-one-seo-pack#1578]
i can not get them to change one ny or my sites theall say i need more then 40 mb php and at least 256 mb  memory but can not figureout how to fix

Operating System Linux
Server Apache/2.2.22 (Debian)
**Memory usage 54.11 MByte**
MYSQL Version 5.5.35-0+wheezy1-log
SQL Mode Not set
PHP Version 5.6.33-1~dotdeb+7.1
PHP Allow URL fopen On
PHP Memory Limit 268435456
PHP Max Upload Size 32M
**PHP Max Post Size 32M**
PHP Max Script Execute Time 120
PHP Exif support Yes ( V1.4 )
PHP IPTC support Yes
PHP XML support Yes
Site URL http://the-ultimate-outlet-store.siterubix.com
Home URL http://the-ultimate-outlet-store.siterubix.com
WordPress Version 4.9.4
WordPress DB Version 38590
Multisite No
Active Theme New Shop 1.0.3
Site Title The Ultimate Outlet Store
Site Language en-US
Front Page Displays posts
Search Engine Visibility 1
Permalink Setting /%postname%

**Comment by michaeltorbert** [comment]
https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP
