### ISSUE TITLE
Auto description not working for pages, only work for articles.

### ISSUE THREAD

**Issue by OswaldoGonzalez** [semperfiwebdesign/all-in-one-seo-pack#1580]

**Comment by OswaldoGonzalez** [comment]
Auto description not working for pages, only work for articles. 
Any ideas?

Thanks

**Comment by michaeltorbert** [comment]
This isn't a support forum. You can purchase a premium support license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
