### ISSUE TITLE
Title counter color off

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1581]
Reported here: https://wordpress.org/support/topic/something-is-wrong-with-counting-the-signs-in-the-title/

Previously, the color of the title counter in edit post would change from gray to yellow at x characters, and then to red at y characters.
It now starts at yellow. 

This appears to have broken in 2.4.4.

**Comment by arnaudbroes** [comment]
@michaeltorbert this broke here https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/f17df674552dc4204130dee721fbdcfa1c2c3b7b#diff-4e533641bc4be27bca19bde1a2b60fe9R23 and I've already written and tested a tiny fix for it.

**Comment by arnaudbroes** [comment]
This should be fixed now with my latest commit and PR.
