### ISSUE TITLE
Does not work Managing modules

### ISSUE THREAD

**Issue by 999vda** [semperfiwebdesign/all-in-one-seo-pack#1599]
Plug-in modules are not activated. What is the reason?

**Comment by michaeltorbert** [comment]
You have to activate them.
This is a development repository, not a support forum.
You can follow thesentro troubleshooting steps https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/ or if you’d like support you can purchase a license here https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by 999vda** [comment]
Once again, I inform you. Your plugin does not work after the update. Modules are not activated.

**Comment by arnaudbroes** [comment]
Once again, as Michael stated earlier, this is not a support forum.
You can purchase a license on our website if you'd like to receive support or use the troubleshooting steps that he posted above.
