### ISSUE TITLE
The Edit link disappears in the Plugins screen

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#16]
When you enable Free or Pro the Edit link disappears from every plugin in the Plugins screen.  See before and after screenshots here:

Before - 
![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/13409731/475e5230-df02-11e5-8361-cd39a00b1e8b.png)

After - 
![screen-capture-2](https://cloud.githubusercontent.com/assets/17548525/13409735/4c2b7fd6-df02-11e5-87a0-b7ddeabff967.png)

**Comment by mrtorbert** [comment]
@wpsmort ready for testing... I think is actually is the same thing that broke updates in pro too

**Comment by wpsmort** [comment]
This is fixed
