### ISSUE TITLE
Unable to change any settings, 403 Forbidden request

### ISSUE THREAD

**Issue by marcela1637** [semperfiwebdesign/all-in-one-seo-pack#1606]
I am trying to add an additional script to my page headers and the plugin isn't allowing a save (update options).  It keeps sending me to a 403 Forbidden page.
I tried just unchecking one of the option boxes and saving, but even that sends me to the error page.
I'm not sure what to try, other than deactivating the entire plugin.

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
