### ISSUE TITLE
OG Image not working

### ISSUE THREAD

**Issue by majuki** [semperfiwebdesign/all-in-one-seo-pack#1608]
Hi!

I am using All in One SEO Pack and I setupa de Social Meta, but when I post a WP post in Facebook, the image doesn´t show up.

I passed debug, but the system is taking images from: https://www.marcaropa.com/blog/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png instead of "Featured Image", option selected.

Can you please let me know about this bug?

Regards

**Comment by michaeltorbert** [comment]
This isn't a bug.

You can read our documentation here:
https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/
https://semperplugins.com/documentation/social-meta-module/
https://semperplugins.com/documentation/social-meta-settings-individual-pagepost-settings/

or if you would like support, you can upgrade here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
