### ISSUE TITLE
Replace parse_url with wp_parse_url

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1614]
Just for the sake of being up to date, we should replace PHP's parse_url with WP's wp_parse_url, now that AIOSEOP's minimum requirement is WP 4.4.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/410ad40cc9c8a3640ad2be33fb16feab42b908e3/inc/aioseop_functions.php#L821

https://developer.wordpress.org/reference/functions/wp_parse_url/

"PHP 5.4.7 expanded parse_url()’s ability to handle non-absolute url’s, including schemeless and relative url’s with :// in the path. This function works around those limitations providing a standard output on PHP 5.2~5.4+.

Secondly, across various PHP versions, schemeless URLs starting containing a ":" in the query are being handled inconsistently. This function works around those differences as well."

**Comment by EkoJR** [comment]
This is part of the WPCS PR changes that occured from #2084

Sitemap where areas are marked as `// TODO Change to wp_parse_url().`

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L2380

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L2768

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L2772

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L3625

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L3640

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L3648

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/a7f01e2289ee6e16a276e529d91f156ab65c6fc3/modules/aioseop_sitemap.php#L3649

**Comment by michaeltorbert** [comment]
1) Look at the code for each place and make sure it makes sense to do wp_parse_url
2) Manually test to make sure the functionality is unchanged
3) Write unit tests for each instance

**Comment by arnaudbroes** [comment]
I don't think this is something that can be unit tested as it's part of a function and not a function on its own. These would fall under larger unit tests for the sitemap.
