### ISSUE TITLE
UI improvement suggestions

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1615]
Source: https://wordpress.org/support/topic/nonstandard-backend-ui-layout/

" It looks so ... wp-nonstandard. Bold fonts, misplaced question marks and a not very economic style of screen estate usage... currently the whole thing looks a little interim"

Also something like this looks good as well:

![divi-theme-options-adding-code-to-change-the-icons-in-your-divi-header](https://user-images.githubusercontent.com/17364998/41103012-23b0728e-6a36-11e8-9613-49fd9366ce42.png)

**Comment by phalancs** [comment]
Oh no please no more nonstandard stuff like divi. Divi is the worst :)

**Comment by michaeltorbert** [comment]
@phalancs We welcome any and all suggestions, screenshots, mockups, PRs, etc.

**Comment by michaeltorbert** [comment]
duplicate of #1735
