### ISSUE TITLE
PHP Notice: Trying to get property of non-object in aioseop_class.php on line 1616

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1616]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L1616

Reported here: https://wordpress.org/support/topic/php-notice-trying-to-get-property-of-non-object-13/

It's an easy fix, but I'm curious under what circumstances we'd get that warning. The function shouldn't be getting called when there's no global $post.

**Comment by Spreeuw** [comment]
Getting the same issue with 2.5 on my front page (none of the other pages throw this notice)

**Comment by davettt** [comment]
I see it in the debug logs on sites where WordPress settings are 'Settings > Reading ->Front page displays' is set to "Your latest posts". I think it happens around line 1629 of aioseop_class.php when $post->ID is called. 

This occurs in the get_aioseop_title function as the is_front_page() conditional returns true but $post is null, for themes that use the default WordPress reading settings to display their home pages.

**Comment by wpsmort** [comment]
This comment is copied from duplicate issue #678:

In aioseop_class.php on line 1624, we have

global $post;
$post_id = $post->ID;

Reported here, https://wordpress.org/support/topic/trying-to-get-property-of-non-object-35, there could be conditions in certain edge cases where there's no $post
We could consider checking if $post has anything, and if not, maybe bail out of the function gracefully?

For dev and testing, we'd need a theme that displays the posts without there being global $post.

**Comment by djboris88** [comment]
This is how I fixed it, since I believe it happens only if the static homepage is being loaded.

These are lines 1622-1626 in [`All_in_One_SEO_Pack::get_aioseop_title`](https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/1eb745292046d926fecf7ecf65663807cde4cce3/aioseop_class.php#L1622-L1626), latest version:
```php
global $post;
$frontpage_id = get_option( 'page_on_front' );

if ( $post === null ) {
	$post_id = $frontpage_id;
} else {
	$post_id = $post->ID;
}

if ( is_post_type_archive() && is_post_type_archive( 'product' ) && $post_id = wc_get_page_id( 'shop' ) && $post = get_post( $post_id ) ) {
	// $frontpage_id = get_option( 'page_on_front' ); - removed
```

So if the global `$post` is null, I suppose it is the static frontpage, since on every other page there will be something loaded as the global `$post`.

I am not aware of other consequences such an override could have.

**Comment by wpsmort** [comment]
I tested the fix provided above and it works for all test cases.  I've created a PR with this code change.
