### ISSUE TITLE
CAPTCHA code isn't working

### ISSUE THREAD

**Issue by florakaplan** [semperfiwebdesign/all-in-one-seo-pack#1617]
Hello, 

Our website uses a form for users to enter events on a community calendar and the CAPTCHA code isn't working, so no events can be added. It appears that this form is part of our "All in One SEO".

Thank you,
 Flora

Flora Kaplan
Sustainable San Mateo County

**Comment by michaeltorbert** [comment]
This is not part of All in One SEO Pack.
