### ISSUE TITLE
AIOSP New update - Problem with sitemap

### ISSUE THREAD

**Issue by goodworking** [semperfiwebdesign/all-in-one-seo-pack#1618]
Hi,
I have installed AIOSP on over 20 websites. It is a phenomenal plugin. But, after the last update, the sitemap is no longer visible and reachable. Opening it from Firefox the following error is reported:

This is my website

Errore nel caricamento del foglio di stile: Si è verificato un errore sconosciuto (805303f4)https://www.xxxx.it/sitemap.xsl (<< it's normal xsl?)

Translate: 
Error loading style sheet: An unknown error occurred
(805303f4)https://www.xxxx.it/sitemap.xsl

**Comment by michaeltorbert** [comment]
Since you didn't provide your actual URL, we don't have much to go on. However, it's always best to start with these troubleshooting steps.
https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

**Comment by goodworking** [comment]
Forgive me, I did not know it was possible to insert the url. I have updated the post. I also followed the steps suggested in the guide. The problem occurs on all websites that use AIOSP

**Comment by michaeltorbert** [comment]
Try clearing your cache.

**Comment by goodworking** [comment]
No, nothing changes :(

www.goodworking.it/sitemap.xml
https://www.rubinstein-taybi.it/sitemap.xml

These are only two, but problem occurs on over 20 websites on which AIOSP is installed.

Thanks

**Comment by michaeltorbert** [comment]
https://www.rubinstein-taybi.it/sitemap.xml is fine now and I can see that the cache on www.goodworking.it/sitemap.xml hasn't been cleared. 
This is almost certainly caching related, and isn't a bug in All in One SEO Pack.

As this is a development repository and not a support forum, I'm locking this conversation. If you need additional support, you can purchase a Pro license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
