### ISSUE TITLE
Headway + AIOSEOP disables bbpress admin menus

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#162]
reported here https://wordpress.org/support/topic/all-in-one-seo-and-bbpress?replies=12#post-8252584

I've verified this issue. The bbpress admin menus give a permissions error.

**Comment by michaeltorbert** [comment]
The issue is meta_import.php's line 39 delete_user_meta( get_current_user_id(), 'aioseop_yst_detected_notice_dismissed' ); being called too soon.

**Comment by michaeltorbert** [comment]
Now I wonder if this is why the woo notification we had before didn't always go ahead...

**Comment by michaeltorbert** [comment]
That specific function could possibly just add_action into init with a different function... or something

**Comment by nishant981** [comment]
We are working on this issue
