### ISSUE TITLE
Consider changing yellow limit for title character counter

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1622]
So @EkoJr  changed the max. amount of characters for the description to 320 and changed the limit for the counter to turn yellow to 230 characters (which is fine IMO because the line under it says "Most search engines use a max. of 230-320 characters").

However, the title is currently set to 60 characters max. and only turns yellow on character 56. Wouldn't it be better to drop it to 50?

**Comment by wpsmort** [comment]
I have no objections to changing it so we turn yellow at 50 characters.

The guidance from reputable SEO sites has always been that titles should be between 55 and 65 characters in length.  Google doesn't measure by number of characters but instead by number of pixels.  We have a separate issue open for this - #1396.  I believe Google maxes out around 600 pixels for the longer titles.  Also, I notice they've removed any reference to length here - https://support.google.com/webmasters/answer/35624?hl=en

We do need to fix the counter as per #1581.

**Comment by arnaudbroes** [comment]
@wpsmort I just fixed the counter. If that are Google's guidelines, then I'd suggest we leave it at the current 55 character limit and look at #1396. However, another thing that just came to mind is if it wouldn't be better to make the counter green instead of yellow when the recommended amount of characters has been reached? I see how the transition from yellow to red makes sense, but some people may think of yellow as a warning instead of acknowledgement of doing something right. What do you think?

**Comment by wpsmort** [comment]
@arnaudbroes I believe the yellow warning is still the best approach.  It's warning the user that they are getting close to the maximum number of characters and should be aware of this when writing.

**Comment by arnaudbroes** [comment]
@wpsmort alright cool, let's close this issue then.
