### ISSUE TITLE
Problem ins Scraping Website on Social media Platform

### ISSUE THREAD

**Issue by Ganga97** [semperfiwebdesign/all-in-one-seo-pack#1628]
The title which I am giving to the homepage from all in SEO option is not taking instead it is taking title and description from wordpress default option title and tagline.

I have tried debugging it no result tried a lot of time.

www.indoage.com

**Comment by arnaudbroes** [comment]
Hi @Ganga97 

I'm afraid that this is a development repository; not a support forum. You can purchase a license here if you'd like to have access to our support resources - https://semperplugins.com/all-in-one-seo-pack-pro-version/

Kind regards
