### ISSUE TITLE
Can All in One SEO Pack Plugin automatically to make canonical URLs only with HTTP?

### ISSUE THREAD

**Issue by intermedia1** [semperfiwebdesign/all-in-one-seo-pack#1644]
Hello,

I use All in One SEO Pack Plugin for WordPress and it is really great!

Recently I have an issue that I try to solve. I had SSL certificate on my website but due to some problems with it (for example embedding non-https sources don't work on my site), so I decided to remove SSL and prefer my site to load from HTTP.

Anyway Google is still indexing tons of my website pages with HTTPS. 
- I added only HTTP site url in Search Console;
- I set HTTP in Google Analytics.

Is there any way All in One SEO Pack Plugin automatically to make canonical URLs only with HTTP in order Google to index only HTTP?

Thank you in advance!

**Comment by arnaudbroes** [comment]
Hi intermedia1

I'm afraid that this is a development repository and not a support forum. If you'd like to gain access to our support resources, then I'd recommend you to purchase a license here - https://semperplugins.com/all-in-one-seo-pack-pro-version/

Kind regards

Arnaud
