### ISSUE TITLE
manage robot.txt doesn't seem to allow direct editing

### ISSUE THREAD

**Issue by BillPennock** [semperfiwebdesign/all-in-one-seo-pack#1645]
I hit add a rule and got an empty site map
i tried to add the html using the directory field, optimize and direct editing and nothing doing.  as far as I can tell this is an annoyingly simple operation that is being made incredibly difficult by the plug in.  there's no way this will encourage me to buy the pro version if the free features are so difficult.  all it would take is for me to be able to edit the robot.txt.  frustrating

**Comment by michaeltorbert** [comment]
We're in the process of an overhaul of the robots.txt UI.
