### ISSUE TITLE
Facebook not displaying correct image

### ISSUE THREAD

**Issue by chasteyn** [semperfiwebdesign/all-in-one-seo-pack#1646]
Good day. When sharing a classified ad from my site to Facebook, facebook does not use the featured image, as I have defined in my SEO settings. For all other adverts it uses the correct image, except for this one user. Please advise.

**Comment by michaeltorbert** [comment]
This isn't a support forum. You can purchase a Premium Support license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
