### ISSUE TITLE
FacebookFavIcon Issue After Latest Update

### ISSUE THREAD

**Issue by luxurypropertyagent** [semperfiwebdesign/all-in-one-seo-pack#1649]
Default OG:Image is no longer showing in facebook.
This worked fine prior to update no longer working after update.
![12](https://user-images.githubusercontent.com/36377758/38456502-3af768a2-3a53-11e8-8c9e-656ae854bc2c.jpeg)
![13](https://user-images.githubusercontent.com/36377758/38456506-465197e0-3a53-11e8-90fb-56090bae5298.jpeg)

https://developers.facebook.com/tools/debug/sharing/

**Comment by arnaudbroes** [comment]
@luxurypropertyagent this is a development repository and not a support forum. If you'd like to receive support from us, then please purchase a license on our website - https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by luxurypropertyagent** [comment]
Correct, I apologize this had to do with hosting security settings!

**Comment by arnaudbroes** [comment]
That's what I guessed. :-)
