### ISSUE TITLE
es-MX translation

### ISSUE THREAD

**Issue by josearce** [semperfiwebdesign/all-in-one-seo-pack#1652]
The es-MX translation it's mostly wrong. For example, in the menu, there's a page called "Redimiento", such word does not exist in the spanish language (http://dle.rae.es/?w=redimiento). Another example is in the Ajustes Generales -> Título original (General adjustments -> Original Title) the two options are "activado" (enabled?) and "discapacitado", the latter directly translates into "Handicapped", so there's no logic in that.

**Comment by wpsmort** [comment]
@josearce Thank you for letting us know.  You can submit suggestions for the correct translations on the WordPress Translate site here - https://translate.wordpress.org/locale/es-mx/default/wp-plugins/all-in-one-seo-pack.   Suggested translations are reviewed before inclusion in the plugin translation files served from WordPress.org.
