### ISSUE TITLE
Add opt in/out for Google Analytics

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1654]
Requested here - https://wordpress.org/support/topic/opt-out-cookie-2/
I don't think we need this but I just wanted to throw this here anyway to see what you think.

Currently, Google Analytics is fully compliant with GDPR as long as website owners do not store any personally identifiable information. This is not the case, unless someone modifies the standard implementation of Google Analytics.

However, German law seems to think otherwise and wants visitors to be able to opt in/out of Google Analytics when they visit a website. Documentation in their Privacy Policy on how to do so should suffice, although many German website owners clearly seem to prefer a pop-up on their website in order to be fully compliant.

**Comment by michaeltorbert** [comment]
Offhand I'd say that's something German website owners need to handle. 

However, we can at least look into why the Google Analytics Opt-Out plugin doesn't work with AIOSEOP. https://wordpress.org/plugins/google-analytics-opt-out/
