### ISSUE TITLE
Slow saving product after upgrading to 2.5

### ISSUE THREAD

**Issue by noindie** [semperfiwebdesign/all-in-one-seo-pack#1657]
Hello I used to have 2.3.5.1 and recently upgraded to 2.5
Using woocommerce 3.3.5 and wp 4.9.5 and PHP 7.0
Saving a simple woocommerce product (no variants) takes like 5 min, after disabling plugin just 4sec.
I tried also reverting back to 2.3.5.1 and just works fine, its much faster.

Any clue what might be the problem?

**Comment by michaeltorbert** [comment]
No clue. Try these troubleshooting steps. https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
