### ISSUE TITLE
Add templates for custom fields for title

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1662]

**Comment by wpsmort** [comment]
@michaeltorbert I tested this today and found that what we did for ACF custom fields (https://semperplugins.com/documentation/advanced-custom-fields-integration-with-title-format-fields/) actually works for standard WordPress custom fields as well.  I even works for custom fields added using the PODS and Toolkit plugins.  

If you use %cf_fieldname% and replace fieldname with the meta key for the custom field then we output the contents of the custom field in the doc title.  

In addition, I also found that this format template also works in the Description Format field.  

I will update the documentation accordingly.

**Comment by michaeltorbert** [comment]
Make sure to update both the documentation on the website as well as within the plugin.

**Comment by wpsmort** [comment]
I have updated the documentation here - https://semperplugins.com/documentation/custom-fields-in-titles-and-descriptions/

**Comment by wpsmort** [comment]
PR #2073
