### ISSUE TITLE
sitemap do not list translated articles with polylang

### ISSUE THREAD

**Issue by effidoc** [semperfiwebdesign/all-in-one-seo-pack#1667]
hello,
I use polylang to replace q-translate-x, and with those both engines, the sitemap do not list translated pages or articles, I add manually some of them, bu it is a problem with articles i produce twice a mont in frnech and english

**Comment by arnaudbroes** [comment]
@effidoc we have an open issue for this here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/102

**Comment by effidoc** [comment]
Hello 
My case is pretty directory  www.ancienne-ecole.com/en  with polylang
What is the medium priority since May 2o17.?

-------- Message d'origine --------
De :Arnaud Broes <notifications@github.com>
Envoyé :Mon, 23 Apr 2018 15:13:03 +0200
À :semperfiwebdesign/all-in-one-seo-pack <all-in-one-seo-pack@noreply.github.com>
Ci :effidoc <effidoc@gmail.com>,Mention <mention@noreply.github.com>
Sujet :Re: [semperfiwebdesign/all-in-one-seo-pack] sitemap do not list translated articles with polylang (#1667)

**Comment by arnaudbroes** [comment]
It means that issue has medium priority for it to be fixed.
