### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in 

### ISSUE THREAD

**Issue by njovanoski** [semperfiwebdesign/all-in-one-seo-pack#1673]
Warning: count(): Parameter must be an array or an object that implements Countable in /webroot/n/i/nikolajo001/stancepride.com/www/wp-content/plugins/css-javascript-toolbox/framework/events/subjects/hook.subject.php on line 81

Warning: count(): Parameter must be an array or an object that implements Countable in /webroot/n/i/nikolajo001/stancepride.com/www/wp-content/plugins/css-javascript-toolbox/framework/events/subjects/hook.subject.php on line 82

**Comment by michaeltorbert** [comment]
Looks like that's for a different plugin.
