### ISSUE TITLE
Compatibility issue breaks Envira Gallery lightbox functionality

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1677]
Reported by Jan Amtrup. This only occurs for standalone Envira Gallery pages and broke between 2.2.2 (last working version) and 2.2.3.

His website has been cloned to Cloudways (application name: galleri-sandberg) on my dev server. http://wordpress-157722-498997.cloudwaysapps.com/kunstnere/kjeld-ulrich/

**Comment by michaeltorbert** [comment]
https://plugins.trac.wordpress.org/changeset?old_path=%2Fall-in-one-seo-pack&old=956933&new_path=%2Fall-in-one-seo-pack&new=970845&sfp_email=&sfph_mail=

**Comment by arnaudbroes** [comment]
Unchecking the 'Run shortcodes in Autogenerated Descriptions' setting seems to solve the problem.

**Comment by arnaudbroes** [comment]
I closed this issue since it's not so much of an issue, rather a setting that shouldn't be enabled. 
At some point, we should improve the behaviour of that setting though.
