### ISSUE TITLE
How to get rid of adding name of my site to social media links?

### ISSUE THREAD

**Issue by Dagonhord** [semperfiwebdesign/all-in-one-seo-pack#1679]
Hello. I have an annoying problem that I can't solve. I run a journal with news and articles. When I copy the link of an article and paste it to social media your plugin adds a name of my journal to the end of the link. It looks like this:

"Name of the article" I "Name of my journal"

It is really annoying and looks very bad. I tried to edit setting of your plugin, but it didn't help. Can you tell me how to turn this off?

**Comment by arnaudbroes** [comment]
This is a development repository, not a support forum. You can purchase a license here if you'd like to gain access to our support resources - https://semperplugins.com/all-in-one-seo-pack-pro-version/
