### ISSUE TITLE
Functionality / errors report

### ISSUE THREAD

**Issue by psihohipnoza** [semperfiwebdesign/all-in-one-seo-pack#1680]
Please provide Functionality / errors report for www.psihohipnoza.ro.

Thank you.

Kind regards,
Adrian Moraru

**Comment by arnaudbroes** [comment]
This is a development repository, not a support forum. You can purchase a license here if you'd like to gain access to our support resources - https://semperplugins.com/all-in-one-seo-pack-pro-version/
