### ISSUE TITLE
title count off when using Japanese

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1681]
Reported by Chris C. via Facebook. 

When entering a title in Japanese (using the Avada theme, although that likely doesn't matter), the character count is off.

**Comment by arnaudbroes** [comment]
@michaeltorbert I'll look into it, but regardless of this issue, are we planning on changing our count from characters to pixels (what Google does now)? Because that would solve the underlying issue that Japanese characters are way bigger than Latin characters as well.

**Comment by arnaudbroes** [comment]
Haven't found anything yet. I requested Chris via FB to send me the theme file.

**Comment by arnaudbroes** [comment]
I've e-mailed Theme Fusion a second time today to request the latest build of their Avada theme as well since Chris never got back to us. We definitely want to take a look at this issue though since we have a pretty big Japanese userbase.

**Comment by arnaudbroes** [comment]
I tested this using the Avada theme, Fusion Builder and Fusion Core plugin and saw no issues.
