### ISSUE TITLE
Social settings don't save - Please help!

### ISSUE THREAD

**Issue by Traviata56** [semperfiwebdesign/all-in-one-seo-pack#1683]
For some weeks the social settings don't save any more. I have the previous pro-version of all-in-one-seo. I tried with the free version with absolutely the same results: no description or featured image gets transported into social media as it gets deleted whenever I try to save.

Help would be very appreciated.

![screen shot 2018-05-09 at 19 02 30](https://user-images.githubusercontent.com/26966292/39828789-9386c97c-53bc-11e8-8ab0-3137a1b72c6e.png) (after saving)
![screen shot 2018-05-09 at 19 01 48](https://user-images.githubusercontent.com/26966292/39828914-072d75ba-53bd-11e8-83f2-acdfe671f99b.png)
(before saving)

**Comment by michaeltorbert** [comment]
Hi @Traviata56 

This is a development repository, not a support version. This is likely a usage/settings issue, rather than a bug. 
Please contact us on the forum here for support: https://semperplugins.com/support/
