### ISSUE TITLE
og:image error

### ISSUE THREAD

**Issue by eastcoastjac** [semperfiwebdesign/all-in-one-seo-pack#1687]
The long story is this:
We are using a plugin to share blog posts to my client's Facebook page. The sharing plugin uses a default image (the company logo, very pixelated) instead of fetching the Featured Image from the post. So I got your all-in-one-SEO plugin which is supposed to fetch the Featured Image.
This is where the error occurs: it doesn't seem to like the content-encoding of the selected photo.
When I run the Facebook debug function, it says "your server using unsupported content-encoding." - see attached screenshots.
I have to re-scrape and then debug AGAIN for it to see the image correctly. Obviously, this is not a workable solution, as my client is posting time-sensitive articles and can't waste time on debugging every single post before sharing it.
Ultimately, we need a way to automatically share the posts, but that will be the subject of another project!

![incorrect-image](https://user-images.githubusercontent.com/16100694/39921416-1b7e3d9c-551b-11e8-9475-1f188612e2ca.jpg)
![debug-error](https://user-images.githubusercontent.com/16100694/39921425-2068a900-551b-11e8-9021-44b65863b3c9.jpg)

**Comment by michaeltorbert** [comment]
All in One SEO Pack doesn't do any content encoding. We simply tell Facebook where to look for the file. This sounds like either a server issue or a Facebook issue.
