### ISSUE TITLE
Notice: Undefined variable: tag in aioseop_opengraph.php

### ISSUE THREAD

**Issue by nikkiskene** [semperfiwebdesign/all-in-one-seo-pack#1688]
I am looking to resolve the following issue when I activate the all-in-one-seo-pack.  The following line is displayed on the header of my page:

Notice: Undefined variable: tag in /home/content/n3pnexwpnas04_data01/49/41464749/html/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_opengraph.php on line 1204

**Comment by michaeltorbert** [comment]
@nikkiskene Thanks for reporting this. We'll take care of it in a future release. 
In the meantime, as it's only a notice rather than an error, you can safely ignore it. Make sure to not have debug logging turned on for your live site.

**Comment by michaeltorbert** [comment]
Reported again here: https://wordpress.org/support/topic/undefined-variable-error-in-aioseop_opengraph-php/

**Comment by arnaudbroes** [comment]
I have been able to reproduce this with these settings:

![image](https://user-images.githubusercontent.com/18156697/57648178-cb6b6980-7592-11e9-9a1d-d45e2f2ea67f.png)

![image](https://user-images.githubusercontent.com/18156697/57648145-b4c51280-7592-11e9-9cae-1cc4087c875a.png)
