### ISSUE TITLE
NOINDEX / NOFOLLOW post types incorrectly affects taxonomies

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1690]
Reported by Dorian Golemi by email today.

When you set NOINDEX or NOFOLLOW for a post type under Noindex Settings then it sets the meta tag on all terms in taxonomies for that post type.

For example, if you go to Noindex Settings > Default to NOINDEX and check the Posts checkbox then this will incorrectly set the NOINDEX meta tag on all categories and tags.  

The Default to NOINDEX should only affect post types, not taxonomies.

**Comment by wpsmort** [comment]
@arnaud Can you test back through the versions to see if this is a new bug.

**Comment by contactashish13** [comment]
@wpsmort this seems to be related to #1798 but that is part of milestone 3.1. I think both are interdependent and should be done together. Let me know what you think.

**Comment by wpsmort** [comment]
@contactashish13 I can't say whether that Undefined variable notice has anything to do with this issue.  You will need to assess whether this can be completed independently of any other issue.

**Comment by wpsmort** [comment]
We discussed this in today's dev meeting and agreed that we should work to fix this specific bug without breaking anything else and keep it separate from all the other issues related to noindex/nofollow.

**Comment by contactashish13** [comment]
If you check https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-412670589, this is the change that caused the bug reported in #1798 and fixing that bug resulted in uncovering the bug that necessitated the need to rewrite behavior of NOINDEX/NOFOLLOW. Steve created a document (https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-430020572) to help in this. These issues are inextricably linked.

**Comment by contactashish13** [comment]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2264 needed to be assigned to @EkoJR not this issue. Even though both deal with NOINDEX issues, this issue is more about the need to rewrite the entire NOINDEX/NOFOLLOW behavior.

**Comment by arnaudbroes** [comment]
This should also be fixed in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2671.

**Comment by arnaudbroes** [comment]
This has been fixed by https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2671.
