### ISSUE TITLE
conflict with starfishwp - running their shortcode

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1691]
Reported by Tevya via email:

> https://starfishwp.com. We've found a conflict with AOI SEO. If you have "Run Shortcodes in Description" checked, under All in One SEO > Social Meta > Advanced Settings, AiO tries to process the shortcode somehow, causing it get blocked and our little "funnel" doesn't get rendered for the shortcode. You can see here: http://wordpress-125652-359449.cloudwaysapps.com/sample-page-1/ what it should look like because AiO SEO is disabled on this page. Then here: http://wordpress-125652-359449.cloudwaysapps.com/sample-page/ is what it looks like with AiO SEO enabled and the above mentioned option turned on.

**Comment by arnaudbroes** [comment]
Confirmed. Has been so since the release of the 'Run shortcodes in auto-generated descriptions' feature. AIOSEOP runs the shortcode in the meta description (and truncates it).

**Comment by michaeltorbert** [comment]
Reopening this, as moving the shortcode down far enough in the content that it's not in the description doesn't help.

**Comment by michaeltorbert** [comment]
That's correct. Arnaud didn't explain it completely. At first glance, it appeared as though when it was running in meta description, that interfered in some way (javascript conflict or whatever) with the one in the content, such that the content one never rendered in the browser. This would mean everything is working on our end as intended.
However, I moved the shortcode down far enough in the content that it wouldn't show up in the meta description, and it was still broken. This suggests there's a problem on our end.

**Comment by michaeltorbert** [comment]
Note for whoever works on this issue:
at first glance in the code, it appears we could probably just move our do_shortcode on the content down a bit to only run on the description at the end.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L2583

**Comment by tevyaw** [comment]
Okay, great! Thanks.

**Comment by tevyaw** [comment]
Any updates on this?

**Comment by michaeltorbert** [comment]
@tevyaw No, you'll see updates in the issue here. No need to ask.

**Comment by EkoJR** [comment]
@michaeltorbert That seems to be all that was needed. 

To summarize it: Currently it relies on the description to be empty in order to generate one, which is also nested with do_shortcodes. If the aioseop description was typed manually, then it just returns that without do_shortcodes.

**Comment by wpsmort** [comment]
@tevyaw I have emailed you to get a copy of your premium plugin or access to a test site where we can reproduce this conflict and verify that the new code resolves this.

**Comment by tevyaw** [comment]
Thanks @wpsmort ! I just sent it over.

**Comment by EkoJR** [comment]
@tevyaw I took a look at Starfish to see how the shortcode functions, and I noticed it only allows a single use of a file with `require_once`. The shortcode is being executed, but with `*_once` prevents adding the file multiple times.

`require_once 'inc/starfish-shortcode.php';` 
Located at starfish-reviews-premium/starfish-reviews.php Line 229

Could be changed to...
`require 'inc/starfish-shortcode.php';`

**Comment by tevyaw** [comment]
Thanks for this info @EkoJR. I'm not actually the developer. I'll pass this on to him. But for my info: is this something that's contributing to the issue with AiO SEO? Or is it just a tip for us to improve our plugin?

**Comment by EkoJR** [comment]
It's to provide a fix, but there are other methods that could be used. The shortcode function is being used, but that one line is preventing rendering.

The same issue could occur if the visitor happens to render 2 of the same shortcode.

**Comment by tevyaw** [comment]
Thanks all. I'm in the middle of switching developers for the plugin. So that's why the delay here. I'll see what the new dev says. He's much more experienced.

**Comment by EkoJR** [comment]
Hey @tevyaw. Just curious, do you have any updates regarding this issue?

**Comment by tevyaw** [comment]
Thanks for following up @EkoJR. We're just about to release an update that I believe has this fixed. I'll ping the new developer and make sure. But hopefully next week (at the latest) we'll have this release out with this fix in it.

**Comment by EkoJR** [comment]
Awesome to hear! Just let me know, so then I can close this issue.

**Comment by tevyaw** [comment]
It appears to all work fine now. Thanks so much.

**Comment by michaeltorbert** [comment]
@tevyaw Awesome!
