### ISSUE TITLE
Google reduced SERPs description length

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1694]
Reported here - https://wordpress.org/support/topic/google-changed-the-size-of-snippets-again-may-2018/. Seems to be valid. My search queries now show up with shorter snippets again. We should consider what to do and perhaps updating the documentation and in-line documentation based on Danny Sullivan's quote (Google Search liason):

> Our search snippets are now shorter on average than in recent weeks, though slightly longer than before a change we made last December. There is no fixed length for snippets. **Length varies based on what our systems deem to be most useful. The length of snippets is dynamic. We're not stating a maximum length because of this.**

**Comment by tonyzeoli** [comment]
They definitely did, because some of my clients entries have gone from 320
in desktop back down. They've eliminated all the good work I was doing for
my clients :( Going to make my job harder again.

**Comment by michaeltorbert** [comment]
https://twitter.com/dannysullivan/status/996068629140586497

**Comment by tonyzeoli** [comment]
Yes, I saw that, but they cut it back considerably and so the SEO is going
to be left to figure out what exactly is relevant in the snippet and hope
it gets adopted into the dynamic range of characters by relevance to the
snippet and what Google wants to display.
