### ISSUE TITLE
if seo is turned off for a CPT, hide other options for the CPT

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1698]
For instance, if SEO is turned off for x CPT, the user shouldn't see options for defaulting to noindex, etc.

**Comment by castmate** [comment]
Good idea! I might set it so that those options appear but are greyed out, and perhaps a tooltip appears when you hover over them, explaining why they're greyed out.

**Comment by michaeltorbert** [comment]
dupe of #67
