### ISSUE TITLE
Some notification messages are missing a CSS rule

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#17]
Notification messages that don't have a Dismiss link are appearing thinner than they should.  See screenshot below.  

![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/13438195/fb6c4e40-dfb5-11e5-9c84-01cc5f7cb5a2.png)

This is because the content in the notification div is usually wrapped in a paragraph tag so that the following CSS gets applied:

.form-table td .notice p, .notice p, .notice-title, div.error p, div.updated p {
    margin: .5em 0;
    padding: 2px;
}

Currently this CSS rule isn't getting applied because the content inside these messages is not contained in a paragraph.  Wrapping the text in a paragraph tag will resolve this issue.

**Comment by nishant981** [comment]
we are working on this issue

**Comment by michaeltorbert** [comment]
@wpsmort Is this only Pro notifications?

**Comment by michaeltorbert** [comment]
Moved to Pro https://github.com/semperfiwebdesign/aioseop-pro/issues/326
