### ISSUE TITLE
Add Show Column Labels for Taxonomies option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1702]
In https://github.com/semperfiwebdesign/aioseop-pro/issues/34 we added columns to the taxonomy screens.  However, we need the corresponding options to disable these for all users just like we have  Show Column Labels for Custom Post Types.

We know from when we tried to remove the Show Column Labels for Custom Post Types option that users complained and they gave us a use case where these checkboxes are necessary.

**Comment by wpsmort** [comment]
@michaeltorbert I hate the idea of adding another option here, especially when we wanted to trim options but this would be in Pro only.  Do we want to add an option or just have a filter that Pro customers can use to disable the columns on the taxonomy screens.

**Comment by michaeltorbert** [comment]
1) Rather than adding an option, I wonder if it's best to just have it on for all CPTs and taxonomies, and then there's a filter to disable

2) Isn't this redundant anyway? Don't we already do this (at least for post types) under "screen options"?

**Comment by wpsmort** [comment]
@michaeltorbert The use case that users provided for the checkboxes was that on sites with a large number of administrators they didn't want every user to have to go in and use the Screen Options to remove the columns, they liked being able to do that for all users with our option under Display Settings.

I think that a filter would work here provided you can filter for specific users, disabling columns for some and not for others.

**Comment by wpsmort** [comment]
We have a record of the conversation to put back the Remove SEO columns option here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/587

I agree that it should be up to the specific admin to decide what they want displayed or not but the user feedback we received went against that.  

Here's the current filter - https://semperplugins.com/documentation/filter-seo-columns-edit-post-screen/.  I don't think this can be applied for certain users.

My vote is that we start with a filter, if we get feature requests for an option then we can review at that time.

**Comment by michaeltorbert** [comment]
Bumping the priority to high since https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1447 depends on it.
