### ISSUE TITLE
Add api filter hook to change sitemap filename

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1703]
At a quick glance I'd say this can be probably just added to our get_filename() function at the end right before the return.

Related a bit to #520

**Comment by wpsmort** [comment]
Requested by Cameron Full via Facebook

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1903

The filter is called `aiosp_sitemap_filename` or `aiosp_video_sitemap_filename` depending on the module.
