### ISSUE TITLE
Fatal error:  Uncaught Error: [] operator in aioseop_class.php:4823

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1709]
Fatal error when testing v2.7 of Pro:

Fatal error:  Uncaught Error: [] operator not supported for strings in aioseop_class.php:4823

This is caused by the empty pair of brackets and is triggered when you disable Custom Post Type Settings.

**Comment by michaeltorbert** [comment]
Check if this commit broke it: https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/9135c839faca710ee9913f2a0429efb844e5c5d7

**Comment by wpsmort** [comment]
In testing, removing the [] from line 4823 clears the fatal error and still outputs the SEO meta box on custom post types and taxonomies.
