### ISSUE TITLE
Re: All In One SEO Not Showing in Edit Screen

### ISSUE THREAD

**Issue by ronusa** [semperfiwebdesign/all-in-one-seo-pack#1712]
Just now updated to the newest version; and now All In One section does not show when editing a post. It normally showed in the past. Also All In One does not show under the screen options as well. I also made sure that the plug in was activated

**Comment by arnaudbroes** [comment]
@ronusa you can find the answer to your question here:
https://wordpress.org/support/topic/tag-etc-options-gone-after-the-last-update/

**Comment by ronusa** [comment]
Thanks for solving the problem.
