### ISSUE TITLE
Preview snippet not showing in wordpress

### ISSUE THREAD

**Issue by leoemery** [semperfiwebdesign/all-in-one-seo-pack#1713]
When I open a post or want to create a new post in wordpress the all in one preview snippet along with everything else: title, meta description, no index and so on does not display below the wordpress post editor. It was functioning perfectly a few days ago, but since updating all in one it does not appear anymore. I am currnetly running the Thrive theme - Minus - it was also updated.

**Comment by wpsmort** [comment]
Make sure you have checked the boxes under SEO on only these post types (https://semperplugins.com/documentation/custom-post-type-settings/)

**Comment by michaeltorbert** [comment]
So this is where we actually fixed a bug. Previously, if you had all the post types unchecked, the metabox would still show up for posts. This gives the appearance of it suddenly disappearing if you had everything unchecked.

Changelog- https://semperfiwebdesign.com/all-in-one-seo-pack-release-history/
Github issue- https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1067

**Comment by leoemery** [comment]
Thank you - everything is sorted
