### ISSUE TITLE
Missing "General Settings" section from Post editor

### ISSUE THREAD

**Issue by jeremyfleischer** [semperfiwebdesign/all-in-one-seo-pack#1714]
After the update to version 2.6, I'm only seeing the "Social Settings" editor, and the "General Settings" editor is missing completely, even after I deactivate the "Social Settings" feature. I'm also seeing no options under the "Display" heading in the "General Options" settings screen.

**Comment by arnaudbroes** [comment]
@jeremyfleischer you can find the answer to your question here:
https://wordpress.org/support/topic/tag-etc-options-gone-after-the-last-update/
