### ISSUE TITLE
All in One SEO field no longer showing up on individual posts

### ISSUE THREAD

**Issue by lbrownie4** [semperfiwebdesign/all-in-one-seo-pack#1716]
I just updated to the new version and noticed the All in One SEO field that used to appear on individual posts within WordPress is no longer there. Was wondering what happened to it. Anyone know?

**Comment by michaeltorbert** [comment]
So this is where we actually fixed a bug. Previously, if you had all the post types unchecked, the metabox would still show up for posts. This gives the appearance of it suddenly disappearing if you had everything unchecked.

Changelog- https://semperfiwebdesign.com/all-in-one-seo-pack-release-history/
Github issue- https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1067

**Comment by lbrownie4** [comment]
Thank you! Just followed those steps to get it to appear again.
