### ISSUE TITLE
Individual Page/Post Settings

### ISSUE THREAD

**Issue by FactorExtremo** [semperfiwebdesign/all-in-one-seo-pack#1719]
Hello, in the new version (2.6) I can not see the main settings. In version 2.5 I can see the two options (main settings and social settings)
![all in one seo pack version 2 5](https://user-images.githubusercontent.com/35585666/40729850-ef4f0116-63f2-11e8-8895-fb47cb559926.png)
![all in one seo pack version 2 6](https://user-images.githubusercontent.com/35585666/40729854-f222e0c4-63f2-11e8-9d76-6540de262b9a.png)

**Comment by wpsmort** [comment]
Please read this - https://semperplugins.com/missing-all-in-one-seo-pack-2-6-post-and-page-meta/

**Comment by FactorExtremo** [comment]
Thanks @wpsmort
