### ISSUE TITLE
Robots.txt - Bug with HTML code output

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1720]
**Describe the bug**
Whilst testing PR #1669 on the customer dev site, I found that the Robots.txt module screen loaded HTML source code after importing a static robots.txt file.  I was able to reproduce this locally with just WooCommerce installed.

**To Reproduce**
1. On a brand new site with WooCommerce installed, upload a static robots.txt file to the root directory
2. Click on the Robots.txt module in AIOSEOP
3. Click on the Import and Delete link
4. The page should load as HTML source code

**Expected behavior**
The page should load the normal UI after importing the static robots.txt file but instead it loads HTML code.

**Comment by wpsmort** [comment]
This was traced back to the line below in the aioseop_robots.php file:

`do_action( 'do_robots' );`

Adding `header( 'Content-Type:text/html' );` immediately after that line fixed the problem but we still need to determine what caused it.

**Comment by michaeltorbert** [comment]
I'm pretty sure this was fixed in PR #1743 
@wpsmort Can you check after me and confirm before we close this?

**Comment by wpsmort** [comment]
@michaeltorbert Yes, this was fixed in PR #1743 so I am closing this issue.
