### ISSUE TITLE
Google search console reporting missing XML tag on index.xml

### ISSUE THREAD

**Issue by djordan2000** [semperfiwebdesign/all-in-one-seo-pack#1725]
Google search console reports an error that the All in one XML sitemap is missing an XML tag.

**Comment by arnaudbroes** [comment]
This is a support issue and should therefore not be reported in our development repository. If you do not have an active license for All in One SEO Pack Pro, then please purchase one and create a new thread on the Premium Forums or e-mail us if you'd like to receive support - https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by michaeltorbert** [comment]
@djordan2000 Please provide both a link to your sitemap and the exact error reported.

**Comment by michaeltorbert** [comment]
Closing this as it's been two days without a reply from @djordan2000
