### ISSUE TITLE
images that aren't assigned to a post

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1733]
We should figure out what to do about redirecting attachment pages for images not assigned to a post, or that are assigned to multiple posts.
One option is to just redirect them to the image itself.

**Comment by colocoquillo** [comment]
I have just recently opened a post about it (4 minutes ago) and think this could be the "issue" im facing, I think the approach of redirecting to the image itself is the way to go or at least one way to go. A decission should be taken in regards to this, it is affecting my SEO and my google results.

**Comment by michaeltorbert** [comment]
Closing as a duplicate of #1834
