### ISSUE TITLE
Custom title format for individual categories

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1738]
https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/category-title-format/#p7898

I think it'd be awesome if we were able to set a custom title format for each category (possibly on the category page) instead of one single format for all categories.

**Comment by michaeltorbert** [comment]
Agreed. We can probably just apply a filter somewhere in apply_page_title_format().

**Comment by ehsan680** [comment]
Any update on this?

**Comment by arnaudbroes** [comment]
@ehsan680 it's on the roadmap and we're working on it, but we have no definite release date at this time.

**Comment by michaeltorbert** [comment]
This is a very niche functionality that is covered by our API.
