### ISSUE TITLE
all-in-one-seo-pack disappeared

### ISSUE THREAD

**Issue by silencesilence** [semperfiwebdesign/all-in-one-seo-pack#1748]
all-in-one-seo-pack disappeared from edit a post or post new, at the bottom
where it should be, but it is gone 

All In One SEO Pack 2.6.1
WordPress 4.9.6
WP theme - https://www.solostream.com/wp_theme/wp-clear/

**Comment by michaeltorbert** [comment]
You can read about this here: https://semperplugins.com/missing-all-in-one-seo-pack-2-6-post-and-page-meta/
