### ISSUE TITLE
Description is not working

### ISSUE THREAD

**Issue by aleksmytiuk** [semperfiwebdesign/all-in-one-seo-pack#1750]
Title is ok, but there is no description. In cms everything is ok.
When I'm switch to default theme it's working, but with mine no. Is there any solution to this issue?
If it's help - mototpress and cherry theme.

**Comment by michaeltorbert** [comment]
This is a development repository and is not for support. We offer support for users who upgrade to a Pro license, which can be purchased here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
