### ISSUE TITLE
add %currentyear% title format

### ISSUE THREAD

**Issue by jayyap24** [semperfiwebdesign/all-in-one-seo-pack#1754]
I'm trying to figure out how to pull up the "current year" using a string so I don't have to update the SEO title anymore. For example, Yoast has "%%CURRENTYEAR%%" and it will get whatever is the current year.

Do you guys have that in All in One?

**Comment by michaeltorbert** [comment]
We have current_date, but not current year. 
However now that there's an issue open for it, we'll be happy to add current year as well. :)

**Comment by michaeltorbert** [comment]
We should even go so far as to have an article written on "How to add the current year to your title".

**Comment by arnaudbroes** [comment]
This will need a unit test as well.
