### ISSUE TITLE
Issues with descriptions length & Sitemaps

### ISSUE THREAD

**Issue by freelancekid** [semperfiwebdesign/all-in-one-seo-pack#1755]
Hello, 

We are seeing issues with snippet length restricting to 155 characters: http://nimb.ws/R0VtTQ
The above image has been confirmed by Moz and Google that the snippet length has increased. 

In addition, the plugin is not working with Simple Press - creating a sitemap for the forum. 

Any updates?

**Comment by michaeltorbert** [comment]
Separate issues should be created for unrelated things.

For the first, we increased it in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1395 and decreased it in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1694

For the second, this is an issue with simplepress, not AIOSEOP. You need to purchase their XML Sitemap integration plugin. 
https://simple-press.com/store/plugins/ 
https://simple-press.com/documentation/codex/plugins/our-plugins/available-plugins/google-sitemap/
