### ISSUE TITLE
change "media" to "attachment" 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1757]
This can be confusing for some, so we should discuss whether to change it.

**Comment by arnaudbroes** [comment]
We're only using one instance of Media (see below) on line 844 of /modules/aioseop_sitemap.php. Apart from that, all other occurences of Media aren't (hard)coded in the plugin but fetched from the list of Custom Post Types that the plugin detects. 

`$post_type_titles['attachment'] = __( 'Media / Attachments', 'all-in-one-seo-pack' );`

@michaeltorbert I think we'd be better off closing this issue as we would only be able to change it to "Attachment" in the XML Sitemap module, which may lead to even more confusion. If you disagree, feel free to reopen this issue.

**Comment by arnaudbroes** [comment]
I realize we might be able to change this everywhere using the above code snippet but that seems like a lot of work for something so minor.

**Comment by michaeltorbert** [comment]
In general settings "media" is listed, which some users take to mean the photos themselves, rather than the attachment post type.
