### ISSUE TITLE
XML sitemap does not contains the pictures

### ISSUE THREAD

**Issue by jguerine** [semperfiwebdesign/all-in-one-seo-pack#1758]
Hello,

I use the version 2.6.1 of AIOSEO.
I didnt tick the box 'exclude pictures', but those are not integrated in the sitemap?

thanks !

**Comment by michaeltorbert** [comment]
The sitemap does contain images. This isn't a support forum. 
We offer support via Pro license which can be purchased here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
