### ISSUE TITLE
noindex for search pages fails when no search results are found

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1759]
I've been able to verify this behavior.
Does this fail is_search?  https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/7550dd8f46ce436216288c3dada2e71ad9929f12/aioseop_class.php#L4228

Reported here: https://wordpress.org/support/topic/search-page-noindex-setting-not-working/

**Comment by michaeltorbert** [comment]
I'm no longer able to reproduce this.

**Comment by arnaudbroes** [comment]
I'm not able to reproduce this either. Seems to be working fine.
