### ISSUE TITLE
Bad Bot Blocker module blocks SEMRush's site audit

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1769]
Reported here: https://twitter.com/Paul47Insights/status/1016816541264826368

To fix this, we'll probably need to run a site audit and log exactly what bot name/string is getting blocked.

We may want to see if we can get a test account for semrush.

**Comment by arnaudbroes** [comment]
I was able to reproduce this. Their bot is part of our blocklist.
![image](https://user-images.githubusercontent.com/18156697/46638491-73ced080-cb61-11e8-8d26-26556d6c3ae3.png)
