### ISSUE TITLE
FTP credentials required on every pageload bug

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1774]
This happens with some sites that have whatever filesystem issues (no suexec, incorrect permissions, not having FS_METHOD as direct, or whatever). (Reported by Eric in email)

For testing, we can force the issue by changing FS_Method to ftpsockets in wp-config.php

<img width="1408" alt="screen shot 2018-07-12 at 12 02 04 am" src="https://user-images.githubusercontent.com/17364998/42612011-e516c14e-8566-11e8-83bf-6b3dd6f6a556.png">

The problem is has_physical_file() may be getting called on every pageload, ultimately meaning request_filesystem_credentials() is getting called on every pageload.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/6b15775b799d5f90ea78d0b9139f7af69c74df04#diff-afdd82b6421840c82e93c85bac49b713R82

Offhand I'd recommend something like this to move it out of the construct:

$dirname = AIOSEOP_PLUGIN_DIRNAME;
			$robots_admin_page = "all-in-one-seo_page_$dirname/modules/aioseop_robots";
		    add_action('load-'.$my_admin_page, array( $this, function_to_wrap_has_physical_file_call_in ) );
		}
		
			function function_to_wrap_has_physical_file_call_in

			if ( $this->has_physical_file() ) {
				if ( ( is_multisite() && is_network_admin() ) || ( ! is_multisite() && current_user_can( 'manage_options') ) ) {
		

-----------

This will at least restrict it to the robots.txt options page... then we need to figure out where to go from there to not have it request filesystem credentials every time we want to access the filesystem. If we can't access it, we should fail gracefully.

In the sitemap module, it uses add_action( $this->prefix . 'settings_header'...  
in add_page_hooks()

**Comment by michaeltorbert** [comment]
While this code still needs to be improved (doesn't need to happen on every pageload, and at a minimum on just the robots.txt module options page), we may want to start with just 1777 as a quick fix in the meantime.

**Comment by wpsmort** [comment]
Reported again by Krystian Hamerlik-Konopka via email

**Comment by wpsmort** [comment]
Testing identified a bug and issue #1785 was opened to fix this in v2.7.2.  Leaving this open until everything has been resolved and users have been notified.

**Comment by wpsmort** [comment]
@michaeltorbert I tested this and it's much improved but the code looks to still be loaded on the Plugins page.

**Comment by michaeltorbert** [comment]
@wpsmort Some of the code I wrote was wiped out in another PR.  I've added it back I think entirely here https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1843

**Comment by michaeltorbert** [comment]
@wpsmort  That's from WP core.
