### ISSUE TITLE
aioseop_load_modules not found

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1775]
Reported here: https://wordpress.org/support/topic/oops-plugin-vanished-with-upgrade/

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function ‘aioseop_load_modules’ not found or invalid function name in /srv/users/serverpilot/apps/wordpress/public/wp-includes/class-wp-hook.php on line 286

Warning: Cannot modify header information – headers already sent by (output started at /srv/users/serverpilot/apps/wordpress/public/wp-includes/class-wp-hook.php:286) in /srv/users/serverpilot/apps/wordpress/public/wp-admin/includes/misc.php on line 1124

**Comment by arnaudbroes** [comment]
![image](https://user-images.githubusercontent.com/18156697/42659792-a5a411ba-8629-11e8-8625-e4198453477e.png)

This only happens when the plugin is **not network-wide activated**, but rather activated separately on each individual subsite.

**Comment by wpsmort** [comment]
Reported again by email from Paul Speck today.

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/error-after-updating-17/

**Comment by 21stcn** [comment]
Same warning after update. I am running multisite with AIOSEO only active on some of the subsites.

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'aioseop_load_modules' not found or invalid function name in /usr/www/u.../wp-includes/class-wp-hook.php on line 286

**Comment by wpsmort** [comment]
This is tested and is good.  We have notified all users who reported this bug that v2.7.1 has been released.

**Comment by mqudsi** [comment]
I was just about to report this having ascertained it wasn't from anything on my end.

I can verify it's fixed with 2.7.1.
