### ISSUE TITLE
version 2.7 update on multisite issues

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1776]
Reported here: https://wordpress.org/support/topic/version-2-7-update-on-multisite-issues

"updated all in one to version 2.7.0 in one multisite installation.
Plugin are activated per site, not network wide.
Latest version of wp 4.9.7

All all in one seo options are dissapear from single post, page, and also main page options dissapear. Try access to options page from link in plugin view but get error “i unable to access this page” permissions error, i have a super admin account.
Also in post list page don’t view a fast edit title and description fields."

**Comment by arnaudbroes** [comment]
I'll report my findings below:

- This error is only triggered when All in One SEO Pack is not network-activated, but activated on each subsite individually.

**Comment by arnaudbroes** [comment]
This only occurs on multisites where the plugin is **not network-wide activated**, but rather activated separately on each individual subsite. Therefore, it is definitely related to #1775. It also started in the same commit - https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/67f1339fa8ef8a64a5ff701b7a5abf836a0960e3#diff-a49a1e48ac5a28e789ed856196af92c5

![image](https://user-images.githubusercontent.com/18156697/42661372-4a377fba-862e-11e8-87d6-746eaac7db95.png)

This error is what you get when you to try to access the settings of the plugin. In addition, the meta box does not appear on the Edit Post/Page screen. The Quick Edit SEO title and SEO description fields also do not appear in the list overview of Posts/Pages.

**Comment by wpsmort** [comment]
This is tested and is good.  We have notified all users who reported this bug that v2.7.1 has been released.
