### ISSUE TITLE
Consider removing support for FTP credentials for filesystem

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1777]
When we call request_filesystem_credentials we support FTP credentials, which is outdated, not needed on 99% of websites, and causes problems like https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1774

We should consider ditching this, or at least only supporting it when explicitly requested, such as with an aioseop-specific constant in wp-config.php or a filter hook.

**Comment by michaeltorbert** [comment]
From https://codex.wordpress.org/Filesystem_API

> Another problem with calling request_filesystem_credentials() directly is you cannot determine if you will have direct access to the file system or if the user will be prompted for credentials. From a UX standpoint this becomes problematic if you want to make changes to files when a plugin is activated. Just imagine, a user goes to install your plugin via their admin area, enters their FTP details, completes the installation and activates your plugin. But as soon as they do, they are prompted to enter their FTP details again and are left scratching their head as to why.

**Comment by wpsmort** [comment]
Testing identified a bug and issue #1785 was opened to fix this in v2.7.2.
