### ISSUE TITLE
Cannot import or delete a static robots file with 2.7.1 branch

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1785]
I tested the code in the 2.7.2 branch on three sites and got the following problem when a static robots.txt file is present:

**On a Local dev site with nothing in the wp-config file for filesystem access method:**
- When I go to the Robots module it recognizes there is a static robots.txt file and provides the links to import and delete or delete but clicking either link does nothing
- If I add define('FS_METHOD','direct'); in the wp-config file nothing changes, same result as above

**On an NGINX site on Digital Ocean with define('FS_METHOD','direct'); in the wp-config file:**
- When I go to the Robots module it recognizes there is a static robots.txt file and provides the links to import and delete or delete but clicking either link does nothing
- If I remove the define('FS_METHOD','direct'); from my wp-config file nothing changes, same result as above

**On a Cloudways site with nothing in the wp-config file for filesystem access method:**
- When I go to the Robots module it doesn't recognize that there is a static robots.txt file and therefore doesn't prompt me to import and/or delete
- If I add define('FS_METHOD','direct'); in the wp-config file it does recognize the static robots.txt file and does display the links but they do not work

**Comment by wpsmort** [comment]
This is related to #1780 and #1781

**Comment by arnaudbroes** [comment]
On a local dev site on my machine, the static robots.txt file is not recognized when it's placed in the root folder and when "define('FS_METHOD', 'direct'); isn't added to wp-config.php. Once it is, the plugin recognizes it, displays the import/delete anchors but they don't work.
