### ISSUE TITLE
Import SEO Settings - Issue with error message wording

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#179]
The error message that appears when you try to convert before selecting a platform reads:

Sorry, you can't do that. Please choose a platform platforms.

This needs to be corrected to read:

Sorry, you can't do that. Please choose a platform and then click Analyze or Convert.

**Comment by michaeltorbert** [comment]
@wpsmort Should this be closed or does it still need testing? (It's in the live version)
