### ISSUE TITLE
I would like to change old url "xyz.com/abdc" to "xyz.com/abcd", redirection option is lacking here

### ISSUE THREAD

**Issue by santoshjmb** [semperfiwebdesign/all-in-one-seo-pack#1791]
I would like to change the old URL "xyz.com/abdc" to "xyz.com/abcd"

Would be happy if the plugin allows for a quick redirection change for the old URL just after changing the URL. Similar to Yoast SEO. This would remove the need of having a redirection plugin overall.

**Comment by michaeltorbert** [comment]
Thank you for your feedback. We've got an issue open for this https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/157

In the meantime, we use and recommend: https://wordpress.org/plugins/redirection/
