### ISSUE TITLE
all in one seo sitemap generation

### ISSUE THREAD

**Issue by Dougmc100** [semperfiwebdesign/all-in-one-seo-pack#1794]
Hi I've been on chat with go daddy and they say the reason for a blank sitemap page is down the plugin. It has been working in the past but now its just a blank page.

**Comment by michaeltorbert** [comment]
Godaddy wouldn't know anything about this. 
You can read about it here: https://semperplugins.com/documentation/this-page-contains-the-following-errors/

As this isn't a support forum, I'm closing this issue. If you'd like additional support, you can purchase a Pro license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
