### ISSUE TITLE
noindex doesn't work when no SEO for a post type

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1797]
While working on https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/when-to-noindex-media/, I realized that if a post type has "no seo for this post type" selected, we  can't noindex it... it completely takes away the AIOSEOP section

related to #1796

**Comment by EkoJR** [comment]
@michaeltorbert It appears that nofollow is also affected in the same way. Should I include it here, or make a separate issue?

**Comment by michaeltorbert** [comment]
@EkoJR You can make a separate issue, however, depending on what we do to fix it, the fix for this issue may apply to both.
