### ISSUE TITLE
social tab conflict with YOP Poll plugin

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1799]
Reported here: https://wordpress.org/support/topic/clicking-on-social-tab-does-nothing

> Since the last update, clicking on the social tab inside pages/posts does nothing. It does not display the social settings and therefore I cannot edit any of the og: settings.
SEO on custom post types is enabled for Pages/Posts/Media

> There is a conflict with YOP Poll plugin

**Comment by arnaudbroes** [comment]
@michaeltorbert I'm not able to reproduce this. This works just fine. I can access the social meta tab and all its fields. I noticed that the YOP Poll plugin changes all our meta box headers to full uppercase but I reckon that's not something we need to deal with. 

I'll inform the user and let him know he can reopen the issue if needed.

![image](https://user-images.githubusercontent.com/18156697/45258036-e4db6680-b3b0-11e8-8652-3131b5e8ca05.png)
