### ISSUE TITLE
Not possible to override OG data when page contains global Fusion Builder container

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1804]
Issue reported by Nicolas D. via e-mail.

It's not possible to override OG data (title, description) in AIOSEOP when someone is using the Fusion Builder plugin to create his pages and added a global container to his page. 

To reproduce this, install both All in One SEO Pack and Fusion Builder, create a new page, add a container and save that container as a global element. Then, change the OG data and confirm that it hasn't changed after updating the page.

@wpsmort, could you please verify this again on your end?

We also have this issue with WooCommerce and Fusion Builder - #1682. We should get a fix or two out since this is a pretty popular plugin (comes with the Avada theme).

I have access to the repositories of Theme Fusion's plugins and their Avada theme. Contact me in case you need them.

**Comment by wpsmort** [comment]
@arnaudbroes I have confirmed this by following the steps you outlined to reproduce the bug.  This only happens with elements saved as Global such as Global Containers or Global Columns and it only affects the OG Title and Description.

**Comment by arnaudbroes** [comment]
Nicolas D. requested to be updated when this issue has been fixed. Just making a note to self here.

**Comment by contactashish13** [comment]
@arnaudbroes have messaged you yesterday on slack for the cloudways information and the plugins. Could you please provide those?

**Comment by arnaudbroes** [comment]
@contactashish13 sent all steps to reproduce and the plugin file on Slack. You won't need the clone since we were able to reproduce it on a new, fresh test site.

**Comment by wpsmort** [comment]
Also reported here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/https-www-servextra-com-csr-start/

**Comment by michaeltorbert** [comment]
This was introduced in 2.0.4, though I'm not sure why. The changelog just says "Bugfixes for issues reported by users in WordPress.org support forums"
https://semperfiwebdesign.com/all-in-one-seo-pack-release-history/6/

**Comment by contactashish13** [comment]
@michaeltorbert If the intent was to keep the function from running multiple times on the same save etc. then the approach is incorrect. The correct way is to remove the hook and then add it back again. 

Do you want to (1) leave this bug as it is, (2) correct the behavior by removing/adding hooks or (3) by checking if there is a specific way this functionality can be overridden only for posts that are built with fusion builder?

**Comment by michaeltorbert** [comment]
@contactashish13 I'm just making an educated guess as to why it's there.

Personally, I'd think we should try for (2), but do (3) only if needed.
What are your thoughts?

**Comment by contactashish13** [comment]
Approach (2) works but I don't know what it breaks :)

PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1904
