### ISSUE TITLE
error on line 2 at column 6: XML declaration allowed only at the start of the document

### ISSUE THREAD

**Issue by harunresitc** [semperfiwebdesign/all-in-one-seo-pack#1805]
Error:
http://hrc.karaliyor.com/sitemap.xml
```
This page contains the following errors:
error on line 2 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.
```

Source code of sitemap.xml:

```

  |  
-- | --
  | <?xml version="1.0" encoding="UTF-8"?>
  |  
  | <!-- Sitemap dynamically generated by All in One SEO Pack 2.7.2 by Michael Torbert of Semper Fi Web Design on Wed, 01 Aug 2018 18:19:21 UTC -->
  | <?xml-stylesheet type="text/xsl" href="http://hrc.karaliyor.com/sitemap.xsl"?>
  | <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  | <sitemap>
  | <loc>http://hrc.karaliyor.com/sitemap_addl.xml</loc>
  | </sitemap>
  | <sitemap>
  | <loc>http://hrc.karaliyor.com/sitemap_post.xml</loc>
  | </sitemap>
  | <sitemap>
  | <loc>http://hrc.karaliyor.com/sitemap_page.xml</loc>
  | </sitemap>
  | <sitemap>
  | <loc>http://hrc.karaliyor.com/sitemap_category.xml</loc>
  | </sitemap>
  | <sitemap>
  | <loc>http://hrc.karaliyor.com/sitemap_post_tag.xml</loc>
  | </sitemap>
  | <sitemap>
  | <loc>http://hrc.karaliyor.com/sitemap_ngg_tag.xml</loc>
  | </sitemap>
  | </sitemapindex>


```

The first line is actually empty.

**Comment by wpsmort** [comment]
This is not a support forum.  Support is available in the forums here https://semperplugins.com/support/ for customers who have purchased All in One SEO Pack Pro.

**Comment by harunresitc** [comment]
This is not a support question! This is a error feedback. ;)

**Comment by wpsmort** [comment]
This is typically caused by whitespace in a theme or plugin file.  We have documentation addressing this here - https://semperplugins.com/documentation/this-page-contains-the-following-errors/

**Comment by GuzmanAriel** [comment]
I have had the same issue and removed all other plugins and deleted all code from templates in case of any whitespace and still see this issue

**Comment by michaeltorbert** [comment]
@GuzmanAriel It is not caused by All in One SEO Pack. Unfortunately it's a frustrating issue which can be difficult to locate the cause.

**Comment by michaeltorbert** [comment]
@GuzmanAriel It is not caused by All in One SEO Pack. Unfortunately it's a frustrating issue which can be difficult to locate the cause.
If you've purchased an All in One SEO Pack Pro license, you can contact our support team for help locating the cause. If you would like to purchase a license, you can do so here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
