### ISSUE TITLE
Preview Snippet does not match autogenerated title or description

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1809]
Whilst testing #1421 I found that the Preview Snippet on the Edit Post screen does not always match the autogenerated title and description.

Like #1808, I believe this is a problem we've known about for some time but I couldn't find an issue open for this.

The code that controls how the Preview Snippet is created needs to be reviewed. The Preview Snippet should match what's displayed as the title tag and meta description in the source.

To test this, change the Title Format fields and Description Format field under Title Settings to any of the supported macros and see if the Preview Snippet matches the format used and matches what's displayed in the source code.

For example, these macros don't work when used in the Post Title Format field (the output does not appear in the Preview Snippet:

%blog_description%
%post_author_login%
%post_author_nicename%
%post_author_firstname%
%post_author_lastname%

None of the macros for the Description Format field seem to work. The output does not appear in the Preview Snippet.

This affects all post types and taxonomies.

**Comment by michaeltorbert** [comment]
We need to completely extract all the code that deals with generating the title, and then do the same for the description. Currently, different (overlapping) code handles it differently depending on whether it's the snippet or the live site.

**Comment by arnaudbroes** [comment]
The missing macros will be added as part of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2718, the other part of this issue has already been fixed.
