### ISSUE TITLE
Sitemap file size error in Google

### ISSUE THREAD

**Issue by abdramahi** [semperfiwebdesign/all-in-one-seo-pack#1821]
After I increased no of products on my website store http://phonetuningshop.com,
When my website submitted to Google I got errors on sitemap file size error, please help me

**Comment by abdramahi** [comment]
I am using All on one SEO plugin

**Comment by arnaudbroes** [comment]
@abdramahi this is a support issue, not a bug. If you'd like to gain access to our support resources, please purchase a license here - https://semperplugins.com/all-in-one-seo-pack-pro-version/
