### ISSUE TITLE
Meta dscription PREFIX

### ISSUE THREAD

**Issue by wattaman** [semperfiwebdesign/all-in-one-seo-pack#1827]
Hi,

Is it possible to add a prefix to the meta descriptions/titles, especially the Facebook's (ie og:). 
My site sells products and I want to insert a "Where to buy " before the description or the title.

So when sharing on FB, instead of the title of the page/product such as "iFruit X phone", it would appear as "Where to buy iFruit X phone".

Thank you.

**Comment by wpsmort** [comment]
This is a development repository, not a support forum. Customers who have purchased All in One SEO Pack Pro can get support here - https://semperplugins.com/support
