### ISSUE TITLE
Blank category page

### ISSUE THREAD

**Issue by NesooseN** [semperfiwebdesign/all-in-one-seo-pack#1831]
Hi, we get now blank category page when All In One SEO is enabled, free version, there is no error when wp-debug is enabled also. 

Version 2.7.2

Where we can download old version ?

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. You can find troubleshooting steps here: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
