### ISSUE TITLE
Used no Index for Attachments, Tags & Categories etc., But They're Still Indexed on Google

### ISSUE THREAD

**Issue by anasknp** [semperfiwebdesign/all-in-one-seo-pack#1833]
Hi there,
2 days ago I installed All In One SEO pack and removed Yoast plugin from my WP blog which have 32 Posts and 7 Pages.
There is around more than 200 tags and 20 categories in my website along with hundreds of image files. After installing the All In One SEO pack I tick marked on NOINDEX for Categories, Date Archive, Author Archives, Tag Archives, Searched Pages & 404 Pages but what I see on Google is all these Archive and Pages which produce canonical content is been indexed in Google while I've tick marked on NoIndex from the noindex setting tab.
Also I've already excluded all these pages from the sitemap.

Kindly tell me what's wrong

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. Premium support is available for All in One SEO Pack Pro customers: https://semperplugins.com/all-in-one-seo-pack-pro-version/
