### ISSUE TITLE
Site Map Error - XML Parsing Error: syntax error

### ISSUE THREAD

**Issue by CybersmithNZ** [semperfiwebdesign/all-in-one-seo-pack#1841]
Hi, no matter what I have tried I can't get my site map working in All In One SEO. It's coming up with: XML Parsing Error: syntax error (https://www.movingtoaustralia.co.nz/sitemap.xml). Hope you can help. Thanks Johanna

**Comment by wpsmort** [comment]
This is a development repository, not a support forum. Premium support is available for All in One SEO Pack Pro customers: https://semperplugins.com/all-in-one-seo-pack-pro-version/
