### ISSUE TITLE
Output buffering conflict

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1849]
This message sometimes shows up for people using both AIOSEOP and Yoast. While we typically recommend people not use both due to potential conflicts, it would at least be nice to avoid fatal errors.

`PHP Fatal error: ob_start(): Cannot use output buffering in output buffering display handlers in /home/mrrogersvps/public_html/mrrwebdev01.org/wp-content/plugins/wordpress-seo/frontend/class-frontend.php on line 1820`

Probably related: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1422

**Comment by contactashish13** [comment]
@michaeltorbert @arnaudbroes I tried to reproduce this but wasn't able to reproduce this error. If this is a specific scenario, can you mention the steps?

**Comment by michaeltorbert** [comment]
I can't seem to reproduce it either. The code that is likely breaking it is custom_category_descriptions_add_shortcode_support which fires on the core category_description filter hook... even when making sure that function runs, it doesn't seem to conflict for me.

I'll close it since we can't reproduce it. If we get more reports and are able to reproduce the issue, we can reopen it.
