### ISSUE TITLE
Menu Icon reverts to default cogwheel w/ alt. plugin folder name

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#1861]
**Describe the bug**
The icon used within the wp-admin menu uses the default cogwheel image/dashicon when the plugin directory is changed to a name different from what is registered with WP (possibly as well as coded in AIOSEOP); which is `all-in-one-seo-pack`.

**To Reproduce**
1. Change the plugin folder name to something other than `all-in-one-seo-pack`.
2. Activate the plugin (if deactivated)
3. Should see AIOSEOP's menu icon is WP's default; instead of the shield icon.

**Expected behavior**
The menu icon should resemble a shield.

**Screenshots**
Broken
![menu_icon](https://user-images.githubusercontent.com/2794445/44441307-c7b93200-a580-11e8-8209-3b29ae7ae97b.png)
Expected
![menu_icon_fix](https://user-images.githubusercontent.com/2794445/44441310-cab42280-a580-11e8-8aee-1407245dda58.png)

**Additional context**
The Icon is applied using CSS, and uses the toplevel id that is supplied by WP by default. It's possible there may be an alternative with CSS classes that is also supplied by WP.

**Comment by michaeltorbert** [comment]
BTW this should be the newest gear icon

**Comment by arnaudbroes** [comment]
@EkoJR I came to the same conclusion in #2349, however, the toplevel ID is generated by our plugin based off the plugin directory name. I'm guessing JavaScript is the only thing that will solve the trick here? Unless I'm mistaken, we can't dynamically change the target ID inside our CSS code.
