### ISSUE TITLE
Polylang's String Translations for "Title" and "Description" not loaded on homepage

### ISSUE THREAD

**Issue by the-udjat-team** [semperfiwebdesign/all-in-one-seo-pack#1862]
Reported here: [https://wordpress.org/support/topic/the-problem-with-title-and-description-of-the-home-page/](https://wordpress.org/support/topic/the-problem-with-title-and-description-of-the-home-page/)

**Describe the bug**
"**Title**" and "**Description**" of the homepage don't get translated although you have added their translations in the "**String Translations**" section of **Polylang**.
Instead, the default text that you specified in the **AIOSEOP** settings section is loaded.
Translations are loaded correctly on all other pages.

If you comment out the “**is_admin()**” check that is performed in “**aioseop_class.php**“ then everything returns back to normal and the title and description of the homepage gets translated according to the “**String Translations**” you specified in **Polylang**.

“**aioseop_class.php**“
`if ( is_admin() ) {`
`     // this checks if the settiongs options exist and if they dont, it sets the defaults.`
`     // let's do this only in backend.`
`     aioseop_update_settings_check();`
`}`

**To Reproduce**
1. Have both **AIOSEOP** and **Polylang** activated.
2. Set "**Home Title**" and "**Home Description**" in **AIOSEOP Home Page Settings**.
3. Set translations of "**Home Title**" and "**Home Description**" in **Polylang's String Translations** section.
4. When you change site's language, "**Home Title**" and "**Home Description**" don't get translated. Instead, the default settings that you specified in **AIOSEOP Home Page Settings** are loaded for all languages. This happens only when viewing the home page. On all other pages, the translations that are specified in **Polylang's String Translations** section work as expected.

**Comment by michaeltorbert** [comment]
@the-udjat-team Please add the exact steps to reproduce.

**Comment by the-udjat-team** [comment]
Steps added.

**Comment by cryptosam** [comment]
Any update? i have a same problem.

**Comment by arnaudbroes** [comment]
@michaeltorbert I've tested this. It's the same as #1761 and I've confirmed the PR for that issue fixes it.

@cryptosam @the-udjat-team the fix for this will be released with the next version of AIOSEOP (2.8.0).
