### ISSUE TITLE
XML sitemap error - This page contains the following errors:

### ISSUE THREAD

**Issue by rubinshah28** [semperfiwebdesign/all-in-one-seo-pack#1864]
I' ve installed the all in one SEO plugin for our site on wordpress. When we try accessing the sitemap (http://shreyautomotives.com/sitemap.xml) we get the following error

This page contains the following errors:
error on line 4 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

I tried to disable each plugin but for all in one seo but still get this error. Any help?

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/this-page-contains-the-following-errors/
