### ISSUE TITLE
improve admin pointers code

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#187]
We're using admin pointers... let's improve the code and make it into a generic class.

https://premium.wpmudev.org/blog/using-wordpress-pointers-in-your-own-plugins/
http://wordpress.stackexchange.com/questions/162745/create-wp-tutorial-for-users-with-admin-pointer-using-next-button-for-navigation
http://bavotasan.com/2013/working-with-custom-admin-pointers-in-wordpress/

**Comment by arnaudbroes** [comment]
This can be closed since we'll be removing them.
