### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by Luunka** [semperfiwebdesign/all-in-one-seo-pack#1871]
Lorsque je met à jour l'extension "All in One Seo" le site plante complètement. Je dois carrément désinstaller et re installer le site pour qu'il soit fonctionnel... Le problème : je ne peut plus mettre l'extension "All in One Seo" à jour (sinon le site re plante) et il a apparemment créé un bug sur le site : je ne peux plus faire de sauvegardes, même quand je supprime l'extension !

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum.

You can find troubleshooting steps here https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
or access premium support here https://semperplugins.com/all-in-one-seo-pack-pro-version/
