### ISSUE TITLE
XML Sitemap - Include linked external images, even from a subdomain

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1872]
Reported here: https://wordpress.org/support/topic/site-map-images-not-listing-subdomain-images/#post-10640711

We need to verify this behavior, then discuss whether we should support external images if we don't already and whether that should just include from subdomains or from any domain, and whether it should be default behavior or an option/API hook. If default behavior we need to consider any increased performance burden with lots of posts and images.

**Comment by wpsmort** [comment]
@michaeltorbert We do support external images through our API - https://semperplugins.com/documentation/support-external-images-in-the-xml-sitemap/

I tested and verified that in the example provided by the user, they could use our filter to include images from their subdomains.  

One of the reasons we added this API filter was so we could support images from CDN such as Photon in Jetpack as these images have an external URL such as i0.wp.com.

**Comment by michaeltorbert** [comment]
Should this be an option or leave it as just an API hook?

**Comment by wpsmort** [comment]
I think this should remain a filter unless we get a lot of requests for this and then we can consider adding an option.
