### ISSUE TITLE
Sitemap files too large

### ISSUE THREAD

**Issue by djordan2000** [semperfiwebdesign/all-in-one-seo-pack#1877]
Google search console reports an error that the sitemap files generated are too large. They are 1KB, rather that the limit of 50MB.

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum.

You can find troubleshooting steps here https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
or access premium support here https://semperplugins.com/all-in-one-seo-pack-pro-version/
