### ISSUE TITLE
PHP 7.2 Function create_function() is deprecated

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1882]
Reported here: https://wordpress.org/support/topic/php-7-2-function-create_function-is-deprecated-2/

> add_filter( “option_{$field_id}”, create_function( ‘$field_value’, ‘return EC_Settings::ec_render_option(“‘.$field_id.'”, $field_value ); ‘ ) );

in all_in_one_seo_pack.php line 879

**Comment by EkoJR** [comment]
Seems like an older version of the plugin. The only create_function there is is already commented out. It also isn't the same as what is described.

**Comment by michaeltorbert** [comment]
It's definitely 2.7.3 which you can see in the source code of https://camilowp.com/sitemap.xml
However you're right, that code isn't anywhere in the plugin, and there aren't 879 lines in that file.
