### ISSUE TITLE
Cannot deactivate plugin

### ISSUE THREAD

**Issue by jvbrawley** [semperfiwebdesign/all-in-one-seo-pack#1883]
I decided to deactivate your plugin and when I did site went into the 500 internal error.  I reactivate and site comes back normally.   deleted and reinstalled plugin and the same problem.   completely deleting plugin also causes the error.   cannot get rid of your plugin.   If you come up with a solution please email me at jvbrawley@gmail.com
Thanks
Jack Brawley www.liveaboardcruising.com

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum.

You can find troubleshooting steps here https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
or access premium support here https://semperplugins.com/all-in-one-seo-pack-pro-version/
