### ISSUE TITLE
Description in Post Title Format is messed up

### ISSUE THREAD

**Issue by contactashish13** [semperfiwebdesign/all-in-one-seo-pack#1888]
![image](https://user-images.githubusercontent.com/12953439/45252405-8df07580-b34d-11e8-9397-e68861c7906f.png)

**Comment by contactashish13** [comment]
@wpsmort you can disregard and close https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1674. I have corrected the bug in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1898

PS - @michaeltorbert I think testing ought to come before code review as the latter will not make sense if things do not work as expected.

**Comment by michaeltorbert** [comment]
@contactashish13 So that @shoheitanaka gets some of the credit, I edited his PR with your changes.
