### ISSUE TITLE
Menu Problem

### ISSUE THREAD

**Issue by chrisTUP** [semperfiwebdesign/all-in-one-seo-pack#1889]
Hello, 
Whenever i activate the plugin my menu category pages do not work anymore and link to an empty white page, with nothing displayed.

This is very frustrating as i really love the plugin and would like to use it.

Thank you,

**Comment by michaeltorbert** [comment]
You can find troubleshooting steps here https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
