### ISSUE TITLE
license key field autocompletes with admin password

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1908]
We should rethink our license key field... in some cases, when someone is filling out the general settings, it autocompletes with their password, but since it's obfuscated, they don't know until they click save and they get a notice that their license key is no good (they usually don't know why).

There are probably a few things we could do... we probably want to stop obfuscating the license key, which may fix it anyway since it's no longer the "password" type. Also, I think we should be able to ask browsers not to autocomplete the field... 
These should take care of it, but as a last resort we could make it so the field can't be edited right there... either it moves to its own page/tab, or a popup dialog, or something else like that.

**Comment by arnaudbroes** [comment]
Imo, no longer obfuscating the field would solve a lot of problems.

I also agree that we need to make sure the field cannot be autocompleted. We can do this using the "autocomplete=off" attribute or through some JavaScript code so that field is only writable when it's been focused (click or tab).

**Comment by michaeltorbert** [comment]
Dupe of https://github.com/semperfiwebdesign/aioseop-pro/issues/213
