### ISSUE TITLE
Change Admin Menu icons to an Icon-Font

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#1917]
![title menu icon](https://user-images.githubusercontent.com/2794445/45653306-5a6bc480-ba8c-11e8-8018-0aaadc82d59a.png)

Related to #289

**Comment by michaeltorbert** [comment]
This should be the newest gear icon

**Comment by michaeltorbert** [comment]
I don't remember now why we did it this way, but here's the shield: https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/css/aiosp_admin.css#L5
