### ISSUE TITLE
Change Help Icon to Icon-Font

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#1918]
![help icons](https://user-images.githubusercontent.com/2794445/45653356-8edf8080-ba8c-11e8-93af-77d6912524bb.png)

Related to #289

**Comment by EkoJR** [comment]
Should use WP's Dashicon

https://developer.wordpress.org/resource/dashicons/#editor-help

**Comment by wpsmort** [comment]
Related to #289

**Comment by EkoJR** [comment]
Closing this since, as mentioned, we'll be using the built in dashicon.

**Comment by michaeltorbert** [comment]
Removing the 3.0 milestone.
