### ISSUE TITLE
Default should be sitemap indexes

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1929]
We have a notice "Notice: To avoid problems with your XML Sitemap, we strongly recommend you enable Sitemap Indexes and set the Maximum Posts per Sitemap Page to 1000.
Click here to make these recommended changes"

We should check when this is displaying. On a brand new site it showed up for me. Shouldn't we just default to indexes? Should this even be an option?

**Comment by wpsmort** [comment]
Ashish and I have discussed auto-enabling sitemap indexes and pagination on sites with over x number of URLs.  This was discussed because of the problems reported in #2008 and #2014 where users with large sites reported 500 and 503 errors with their large sites when updating to v2.9.

**Comment by arnaudbroes** [comment]
I'm all for default sitemap indexing. I don't see a reason not to.

**Comment by michaeltorbert** [comment]
Why would we only auto-enable for >x URLs? That seems tricky and buggy, shouldn't we just auto enable it for all new sites and set it to 1000?

**Comment by michaeltorbert** [comment]
We simply need to change the default option from off to on in the settings code.
