### ISSUE TITLE
Not generating sitemap

### ISSUE THREAD

**Issue by Xervenine** [semperfiwebdesign/all-in-one-seo-pack#1931]
I seem to be having an issue with a sitemap not being generated...  The file is there but it is blank.

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. 

You can check out our documentation:

https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
https://semperplugins.com/documentation/this-page-contains-the-following-errors/

or if you'd like premium support, you can purchase a Pro license:

https://semperplugins.com/all-in-one-seo-pack-pro-version/
