### ISSUE TITLE
Add API documentation for upcoming (video) sitemap filename filter hook

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1951]
@wpsmort please review both draft API documentation pages that I created for #1703

**Comment by arnaudbroes** [comment]
@wpsmort can you quickly review both pages and then publish them, considering that 2.9 is already out.

**Comment by wpsmort** [comment]
@arnaudbroes Done.  I had to make a minor but important change to both.  The name of the parameter you were returning was wrong. 

Both have been published.
