### ISSUE TITLE
"Custom post type" language should just be "post type" when appropriate

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1952]
"Content type" might be even better.

Requested here: https://wordpress.org/support/topic/no-index-missing-from-pages/#post-10751090

**Comment by arnaudbroes** [comment]
That's exactly what I was thinking too when I responded on the WordPress.org forums. I'm not sure why I didn't open an issue. In any case, I definitely support renaming that setting to "content type".

**Comment by arnaudbroes** [comment]
@wpsmort can you let me know what your thoughts are? If you agree on "content type", then I'll go ahead and make the changes.
