### ISSUE TITLE
sitemap name not show

### ISSUE THREAD

**Issue by ariyanusman** [semperfiwebdesign/all-in-one-seo-pack#1953]
Hi! my plugin not showing the name of the sitemap,  I mean I want to change it's patch. .xml to idex.xml

**Comment by arnaudbroes** [comment]
We've removed the "Sitemap Filename" feature in a recent update, but we're going to add a new filter hook soon which will allow you to manually change the sitemap file name - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1703
