### ISSUE TITLE
Meta box help icon is out of place

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1956]
<img width="735" alt="screen shot 2018-10-08 at 2 55 38 pm" src="https://user-images.githubusercontent.com/17364998/46628141-a3062300-cb0a-11e8-9154-e42da18bf825.png">

This only seems to occur when the social module isn't active.

<img width="702" alt="screen shot 2018-10-08 at 2 55 27 pm" src="https://user-images.githubusercontent.com/17364998/46628100-7fdb7380-cb0a-11e8-8704-810db2f73ebb.png">

**Comment by wpsmort** [comment]
This has been fixed for when the Social Settings tab is not present but needs improving when the Social Settings tab is present.  See screenshots:

<img width="824" alt="Screen Shot 2019-05-23 at 4 23 57 PM" src="https://user-images.githubusercontent.com/17548525/58284108-eea6cd80-7d77-11e9-90c2-90f1276997a1.png">

<img width="815" alt="Screen Shot 2019-05-23 at 4 25 09 PM" src="https://user-images.githubusercontent.com/17548525/58284109-eea6cd80-7d77-11e9-9542-d99815adf7bc.png">

**Comment by wpsmort** [comment]
@arnaudbroes This is a simple fix, just remove margin-right: 45px; from here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/1eb745292046d926fecf7ecf65663807cde4cce3/css/modules/aioseop_module.css#L136

That shouldn't affect anything else so I'm not sure why that margin was added.

**Comment by arnaudbroes** [comment]
@wpsmort that fixes it. Is it normal though that the help icon jumps from the collapsable menu bar to its position next to the upgrade link when the Social Meta module is enabled?

Social Meta menu disabled:
![image](https://user-images.githubusercontent.com/18156697/58291728-c3939c80-7dbe-11e9-85fe-94d15652ab38.png)

Social Meta menu enabled:
![image](https://user-images.githubusercontent.com/18156697/58291750-d1e1b880-7dbe-11e9-85e6-19c0f70ed4e7.png)

**Comment by wpsmort** [comment]
@arnaudbroes Yes, that's normal.  The location of the help link moves when the tabs are present because there are two help links, one on the Main tab and one on the Social tab.
