### ISSUE TITLE
noindex/nofollow for no SEO on post type only works together

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1957]
For #1797 and #1943 we made it so noindex/nofollow works when SEO for that post type is disabled, however this only works if you're using both noindex and nofollow. If you're trying to use just one it doesn't work.

To make the logic easier, it may be best to pull this out into its own function(s). Eventually it should be in its own file, rather than junking up that big class file.

**Comment by EkoJR** [comment]
It seems the git merge didn't go as smooth as would of hoped; looks like it duplicated code instead of line changes.
