### ISSUE TITLE
SEO data is in body and not head (w/ categories page)

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#1965]
**Describe the bug**
When inspecting the data with categories, I found that the SEO was being excluded from the head element/section. This also causes all other head data to be outside of it.

**To Reproduce**
1. Activate plugin (unsure if there may a trigger)
2. Go to Categories
3. Inspect Source

**Expected behavior**
SEO data should be printed in the head element

**Screenshots**
![category head bug](https://user-images.githubusercontent.com/2794445/46757789-02397400-cc80-11e8-8fb4-63ebd9085511.PNG)

**Version Info (please complete the following information):**
 - WordPress version: 4.9.8
 - All in One SEO Pack version: 2.8
 - PHP version: 7.2

**Comment by michaeltorbert** [comment]
Is this new or has it always been this way?

**Comment by EkoJR** [comment]
I tested this as far back as 2.7.3. So, I want to say it's probably been like that for quite some time now.

I haven't tried tracking it down other than comparing with recent versions.

**Comment by michaeltorbert** [comment]
It shows up for me.

<img width="878" alt="screen shot 2018-10-10 at 9 38 58 pm" src="https://user-images.githubusercontent.com/17364998/46775369-ead8a600-ccd4-11e8-929b-ebc8d85f222e.png">

**Comment by EkoJR** [comment]
Interesting...I wonder what caused mine to change.

I noticed it was right at a `<br />` element, and it looked like it might of been part of WP's Auto-P.

**Comment by michaeltorbert** [comment]
I'll go ahead and close this for now unless it can be reproduced.
