### ISSUE TITLE
No OG: meta data output for WooCommerce shop page

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1970]
There's an issue with WooCommerce where the dedicated "Shop" page does not output OG: meta data.
www.mydomainname.com/shop/

In addition, the plugin will only output the doc title and meta description when SEO is enabled for "Products", while the shop page is considered a Page.

**Comment by arnaudbroes** [comment]
@wpsmort can you verify my findings and see if you find anything else? The other pages that WooCommerce generates seemed to work for me.

**Comment by wpsmort** [comment]
@arnaudbroes This is a known issue, see #96
