### ISSUE TITLE
all in one seo not creating sitemap properly

### ISSUE THREAD

**Issue by Grogadog** [semperfiwebdesign/all-in-one-seo-pack#1973]
XML Parsing Error: XML or text declaration not at start of entity
Location: https://www.roadangelsdriving.co.uk/sitemap.xsl
Line Number 3, Column 1:<?xml version="1.0" encoding="UTF-8"?><xsl:stylesheet version="2.0"
goolge webmaster tools reports
Invalid UTF-8
3 instances
Sitemap contains either C0 or C1 control codes (other than CR LF HT FF) or non-characters.
Line: 3
Line: 4
Line: 5
Please help me get this right

**Comment by wpsmort** [comment]
This is a development repository, not a support forum.

You can check out our documentation:

https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
https://semperplugins.com/documentation/this-page-contains-the-following-errors/

or if you'd like premium support, you can purchase a Pro license:

https://semperplugins.com/all-in-one-seo-pack-pro-version/
