### ISSUE TITLE
SEO On Page Shop Page

### ISSUE THREAD

**Issue by majuki** [semperfiwebdesign/all-in-one-seo-pack#1975]
Hi! 
I am writing you because I need to know where I can update SEO Title / Metadescription at a Woocommerce Shop Page using your Plugin.

On the other hand, using formulas I was able to edit SEO Title at categories, BUT these formulas will appear at SERPS or just at browser tab? 

Thanks!

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. You can upgrade to a Pro license here for access to Premium Support: https://semperplugins.com/all-in-one-seo-pack-pro-version/
