### ISSUE TITLE
Undefined variable: post_type in aioseop_class.php on line 4251

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1985]
Reported here: https://wordpress.org/support/topic/updated-to-2-8-still-see-undefined-variable-error-line-4181/#post-10794921

Looks like $post_type didn't get a value yet. Looking at the code, $post_type = get_post_type() comes later in an elseif

**Comment by wpsmort** [comment]
Possibly a duplicate of #1798
