### ISSUE TITLE
XML Sitemap "Last Modified" column for archive pages should reflect latest post

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1986]
As requested on the Premium Forums on 10/19/2018.

**Comment by arnaudbroes** [comment]
Yst does this, so should we.

**Comment by michaeltorbert** [comment]
This should be the last modified date from the last modified post. Is this going to cause performance issues if there are a lot of archives?

**Comment by EkoJR** [comment]
I'm not able to find the issue. Was this fixed at some point? If not, could someone add the steps to reproduce?

**Comment by arnaudbroes** [comment]
> I'm not able to find the issue. Was this fixed at some point? If not, could someone add the steps to reproduce?

@EkoJR this is the same as https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/262, which now has a PR, so I'll close this issue in favour of the other (as it is a duplicate).
