### ISSUE TITLE
Cannot create sitemap

### ISSUE THREAD

**Issue by JovoVranjes** [semperfiwebdesign/all-in-one-seo-pack#1994]
Hi, I have been experiencing issues with XML Sitemap feature in AIO. So far it worked but not any more. I contacted my hosting service and they could not solve the issue and suggested to contact the plugin support.

Is there anybody who could look at it? I have tried the usual way, by creating a single sitemap and it did not work. Then tried creating multiple files, so some are created and can see them, but sitemaps for posts and pages and few more cannot open. Nothing appears in Webmaster when I add it there. Can send screenshots. Thank you. Jovo

**Comment by wpsmort** [comment]
This is a development repository, not a support forum.

You can check out our documentation:

https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
https://semperplugins.com/documentation/this-page-contains-the-following-errors/

or if you'd like premium support, you can purchase a Pro license:

https://semperplugins.com/all-in-one-seo-pack-pro-version/
