### ISSUE TITLE
Autogenerated descriptions with shortcodes affected by 2.9 release

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1995]
Reported by Iskan by email.

Iskan uses the Enfold theme which as a visual page builder called Avia.  After updating from Pro v2.9 to v2.10 his autogenerated SEO and OG descriptions changed to include the shortcodes from Avia.  

Here's the SEO description autogenerated by Pro v2.9:

`Removed at customer request`

Here's the SEO description autogenerated by Pro 2.10:

`<meta name="description"  content="[av_one_full first min_height=&#039;&#039; vertical_alignment=&#039;&#039; space=&#039;&#039; custom_margin=&#039;&#039; margin=&#039;0px&#039; padding=&#039;0px&#039; border=&#039;&#039; border_color=&#039;&#039; radius=&#039;0px&#039; background" />`

If I enable the Run Shortcodes in Autogenerated Descriptions option then two things break:

1. It breaks the output on the page.  One of the content blocks containing a JavaScript embed doesn't show on the front end.  
2. It outputs a different autogenerated SEO and OG description which still includes shortcodes.

Related to #1990 and #1677.

# Updated

### To Reproduce
1. Go to AIOSEOP General Settings, and enable...
    1. Autogenerate Descriptions.
    2. Use Content For Autogenerated Descriptions.
    3. Run Shortcodes In Autogenerated Descriptions.
2. Go to AIOSEOP Social Meta, and enable...
    1. Run Shortcodes In Description.
    2. Use Content For Autogenerated OG Descriptions.
3. Activate Fusion Plugins & Enfold Theme.
4. Go to "Add New" Post/Page.
5. When using the page builder, DO NOT click "Use Fusion Builder" (plugin). This step will use the Theme's code; which is where the code in question exists.
6. Be sure to add "Layout Elements" to put the Content & Media Elements into; Layout Elements is what creates `avia_codeblock_placeholder` shortcode.
7. Save/Update post/page.

**Comment by wpsmort** [comment]
I've confirmed it's the code change in PR #1964 that broke this.

**Comment by wpsmort** [comment]
@EkoJR @contactashish13 Here is a synopsis of this problem:

SEO / Open Graph descriptions can be created in three ways:

1).  We auto generate the description from the excerpt.  This is the behavior if Autogenerate Descriptions is enabled.

2).  We auto generate the description from the content.  This is the behavior if Autogenerate Descriptions is enabled and Use Content for Autogenerated Descriptions is enabled or there is no excerpt present.  

3).  A description is manually entered in the Description field by the user.

For options 1 and 2, we have an option to Run Shortcodes in Autogenerated Descriptions.  This option is designed so that we run shortcodes before we get the text content for the description.  It was added when page builders that use shortcodes became popular because the shortcodes have to be run in order to create the page layout so that you can extract the text content for the auto generated description.

For option 3, we output exactly what is typed into the Description field.  If someone types [] in the description field we output it as is, we do not try to run it as a shortcode, nor should we.

With this customer's site, he has Autogenerate Descriptions enabled but he **does not** have Run Shortcodes in Autogenerated Descriptions enabled.  

With Pro v2.9 running the plugin **was** running shortcodes before creating the meta descriptions.  This is not expected behavior because he did not have the Run Shortcodes option enabled.  

If we enable the Run Shortcodes option then the description contains a shortcode that is not getting run.  The shortcode in question is a Code Block widget.  I have confirmed that adding a Code Block to a new page on a new site results in the shortcode not getting run.  **This is a compatibility issue with that element in the Enfold theme.**

In addition, the customer reported 502 errors when editing and updating posts or pages.  I have not been able to reproduce this on the customer's live site or on our clone site.

**Comment by wpsmort** [comment]
@EkoJR I have tested PR #1998 with the customer site running the Enfold theme and it did not work.  Here's the behavior I'm getting on the customer site and my test site with a page built using the Enfold Avia Layout Builder:

**Running v2.8:**  The meta and OG description are output with no problems when Run Shortcodes is not enabled.  When Run Shortcodes is enabled then code in any Code Block element doesn't output to the screen.  The meta and OG description are still output fine.

**Running v2.9:**  We have the problem where shortcodes are output in the meta and OG descriptions when Run Shortcodes is not enabled.  When Run Shortcodes is enabled then code in any Code Block element doesn't output to the screen and the shortcode [avia_codeblock_placeholder] is output in the meta and OG descriptions.

**Running code from this PR:**  No meta and OG descriptions are output when Run Shortcodes is not enabled.  When Run Shortcodes is enabled then code in any Code Block element doesn't output to the screen and the shortcode [avia_codeblock_placeholder] is output in the meta and OG descriptions.

I have no idea if this is an issue with the Enfold Code Block element or if it's AIOSEOP.  However, we need to know why content is blocked from being output on the front end of the site when Run Shortcodes is enabled.  We also need to know why the [avia_codeblock_placeholder] shortcode gets output in our meta and OG description.

To reproduce, place a Code Block element on the page with some YouTube embed code for a video.  When Run Shortcodes is enabled either in General Settings or Social Meta then the video does not display.

**Comment by EkoJR** [comment]
As mentioned in Slack.

Unfortunately, that is the expected behavior I was worried about, and I've been thinking about adding a hook that we can use as well as any other plugin devs and/or users in order to remove specific shortcodes remaining (since we can't remove by brackets []).

The reason it is happening, is because it was not registered as a shortcode. That shortcode one  `avia_codeblock_placeholder`, is actually parsed instead...and it's not too surprising, I do the same with my plugin.

**Comment by EkoJR** [comment]
I took a look at the other problem with shortcodes not executing as intended on the frontend, but I'm not sure if there can be anything done on our part; minus the fact that AIOSEOP triggers the issue.

I believe it is more of a 'flawed concept'. Conceptually, the class responsible for shortcodes is based on how the instance itself is carried out, and in a situation with AIOSEOP, the instance is called prior to what is expected and did not result in what was intended; in other words, it is called twice.

As an example, If you have code with an array that expects certain indexes to be the set of keys for the instance, but the instance is called more than once, then the key indexes will not match up with the expected instance.

**Comment by wpsmort** [comment]
@EkoJR This doesn't address the bigger problem which is that when Run Shortcodes is enabled, the code in the Enfold Code Block element doesn't run so whatever it's supposed to output doesn't get output to the screen.  

For example, if you put the iFrame embed code for a video into a Enfold Code Block element in a post and then view the post, the video is not displayed if Run Shortcodes is enabled.  If you disable Run Shortcodes then the video is output on the post.

Please let me know if you can't reproduce this and need me to demonstrate this behavior.

**Comment by EkoJR** [comment]
@wpsmort My second comment addressed that issue. https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1995#issuecomment-437766061

**Comment by wpsmort** [comment]
I've contacted the theme developer to notify him of this compatibility issue to see if it's something he can fix in the Avia Code block.

**Comment by wpsmort** [comment]
The theme developer responded and asked me to test this with the latest version of their theme, v4.5.2.  I tested but the same problem still exists.  I notified the theme developer of this.

**Comment by wpsmort** [comment]
@InoPlugs I tested that patch and it works great.  We were able to output the meta description with the Run Shortcodes option checked and the page content was not broken.

I will close this issue as you are patching this in your code.  

Have you had a chance to look at Issue #2120 which is also a compatibility issue with Enfold?

**Comment by InoPlugs** [comment]
@wpsmort 

Sorry - no.

I added an issue to our dev repo - I will try to have a look at it next week :)
