### ISSUE TITLE
Video XML Sitemap - Is returning an error for Missing Thumbnail in Google Webmaster Tools

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#200]
When I test my video sitemap in Google Webmaster Tools it returns an error for Missing Thumbnail for this post - http://stevemortiboy.com/videos/wordpress-tv-video/

**Comment by arnaudbroes** [comment]
Moved to Pro:
https://github.com/semperfiwebdesign/aioseop-pro/issues/202

**Comment by amostajo** [comment]
@wpsmort this link http://stevemortiboy.com/videos/wordpress-tv-video/ doesn't appear to exists.

**Comment by wpsmort** [comment]
@amostajo I've set up the post again here - http://stevemortiboy.com/wordpress-tv-video/
I've created the Video XML Sitemap (http://stevemortiboy.com/video-sitemap.xml) and submitted it to Google Webmaster Tools and got this error:

We've detected that one of the URLS in your Sitemap contains a missing or invalid reference to a thumbnail image file. Please ensure that each URL contains <video:thumbnail_loc> element specifying a valid image URL.

I've also added a YouTube and Vimeo video to the sitemap so you can see how they compare.
