### ISSUE TITLE
image tag issues

### ISSUE THREAD

**Issue by Jayip** [semperfiwebdesign/all-in-one-seo-pack#2000]
I'm having an issue with my log post images not going to my Facebook page via Jetpack. This is what they sent me when I asked them about it:
I ran your post through Facebook's debugging tool (https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.bluewaterprism.com%2Falways-full-of-surprises%2F), and it looks like the image it's trying to pull in for your most recent post is a default one from your All In One SEO plugin: https://www.bluewaterprism.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png

That tells me that your site's image tags are not configured correctly, so Facebook doesn't know how to find the right image and is using that image instead. I found some resources here that may help you change those settings in All In One SEO:

https://www.inmotionhosting.com/support/edu/wordpress/recommended-wordpress-plugins/all-in-one-seo-pack/set-social-meta

and https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/

If that doesn't work, you may need to disable any social settings in the plugin since they may be overriding Jetpack's default sharing settings, or reach out to the plugin creator here for assistance: https://semperplugins.com/support/

Can you offer any suggestions?? Thanks

Jay

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum.

You can read our documentation here:
https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/
and here: https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/
and here: https://semperplugins.com/documentation/social-meta-settings-individual-pagepost-settings/

If you'd like to access Premium Support, you can purchase a Pro license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
