### ISSUE TITLE
RSS sitemap

### ISSUE THREAD

**Issue by nmurciano** [semperfiwebdesign/all-in-one-seo-pack#2010]
Hi!

I want to edit my Rss Sitemap, But i have this error:

> This page contains the following errors:
> error on line 276 at column 41: Entity 'rsquo' not defined
> Below is a rendering of the page up to the first error.
> 

How can i fix this?

Thanks you!

**Comment by wpsmort** [comment]
@nmurciano Please provide the URL for your RSS sitemap.  If you'd prefer to send that privately please use the form here - https://semperplugins.com/contact/

**Comment by arnaudbroes** [comment]
I'm closing this until we receive more information from @nmurciano.
