### ISSUE TITLE
XML Sitemap doesn't load after updating to v2.9

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2014]
Reported by Miguel Emmara by contact form on 10/23.

Miguel reported that after updating to v2.9 and v2.9.1 that individual sitemaps in his indexed sitemap wouldn't load.  I as able to verify this on his site and that it works fine with v2.8.

I noticed that he has over 61GB of images in his uploads directory and when I exclude images from the XML Sitemap it works fine.

**Comment by wpsmort** [comment]
Possibly related to #2008 and #2011

**Comment by HOTDOG2705** [comment]
Hello, I have the same problem, with image selected no sitemap! With 2.8 worked well.. I'll might close the other thread. 
Thanks!

**Comment by wpsmort** [comment]
@HOTDOG2705 Can you send us an Administrator login for your site and FTP login for your server using the secure form below so we can troubleshoot this:

https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment]
Reported again here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/sitemap-xml/

I got a login for this site and confirmed that it has 2200 posts with 8800 images.  Dynamic Sitemaps was enabled but Sitemap Indexes was not.  Even after enabling Sitemap Indexes and Pagination, trying to view a sitemap resulted in a 504 error.  However, excluding images resolved the problem.  Rolling back to the last version resolved the problem.

**Comment by wpsmort** [comment]
@EkoJR @contactashish13 I've set up separate clones of a site where this issue can be reproduced and sent you login information via Slack.

**Comment by EkoJR** [comment]
@wpsmort I found this is the same as #2008 and PR #2012 does fix it for this issue.

**Comment by wpsmort** [comment]
@contactashish13 I have tested PR #2022 on both cloned sites where we could reproduce this problem.  It works fine on both sites, resolving the problem with the XML Sitemap timing out and with the 503 errors reported in #2008.  However, I do see that it still takes a long time to generate the sitemap. 

Here are the timings and memory usage from both sites:

**Site 1 - Dynamic sitemap with indexes and pagination (21205 URLs and 32,204 images)**
**AIO v2.8**  -  25.56 MB memory used generating the dynamic sitemap in 1.059 seconds, 37.00 MB total memory used.
**AIO PR2022**  -  68.51 MB memory used generating the dynamic sitemap in 0.392 seconds, 80.04 MB total memory used.
NOTE:  Without Sitemap Indexes enabled, the sitemap failed to load with this PR but loaded with v2.8.

**Site 2 - Static sitemap, no indexes (1714 URLs and 2646 images)**
**AIO v2.8**  -  99.28 MB memory used generating the static sitemap in 2.688 seconds, 107.35 MB total memory used.
**AIO PR2022**  -  107.84 MB memory used generating the static sitemap in 6.092 seconds, 115.92 MB total memory used.

Is there anything that can be done to optimize this further?  The biggest issue I found when testing was that if Sitemap Indexes was not enabled then the sitemap failed to load but loaded fine if I use v2.8.

**Comment by EkoJR** [comment]
That was one idea I had tried, but still didn't seem optimal enough. I would say, we would want to avoid 'N posts', and ideally avoid using the query on every instance it would be called.

Also, #2022 doesn't use any of WP's Cache, it's just a static variable; which might explain the high memory.

**Comment by wpsmort** [comment]
Reported again here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/updating-large-sitemap-locks-out-wp-api/#p8333#spEditFormAnchor

**Comment by wpsmort** [comment]
Reported again by Phillip Berry by email.  Phillip's site has 1.8M images.

**Comment by davettt** [comment]
Reporting that I am also seeing sitemap.xml not loading on sites following update from 2.8.

**Comment by michaeltorbert** [comment]
@davettt What's the url to your sitemap?

**Comment by davettt** [comment]
@michaeltorbert here's one that you can take a look at if you like http://aioseo.davidtiong.net/sitemap.xml as the site is setup temporarily for testing of an issue with the meta description on the home page (details are in an email going through support at moment)

**Comment by michaeltorbert** [comment]
@davettt  The sitemap looks fine to me.

**Comment by davettt** [comment]
@michaeltorbert thanks for checking. It seems a little odd, as I use Firefox and the sitemap stopped loading (checked on 2 computers using Firefox), but I can see it loads without issue in Chrome.

**Comment by michaeltorbert** [comment]
@davettt It loads in Firefox for me. I'd say the problem is specific to your computer(s) and not on our end

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/sitemap-broken-after-update-2/.  This site has 2,386 images.  I enabled sitemap indexes and set pagination at 1000 but the post sitemap still loads blank, although the source code is fine.

**Comment by davettt** [comment]
> @davettt It loads in Firefox for me. I'd say the problem is specific to your computer(s) and not on our end

@michaeltorbert you are correct it was at my end, thanks for the help with checking on Firefox. 
Seems that the Ghostery extension (https://www.ghostery.com/) is preventing the sitemap from loading in the browser, as soon as I disable the extension the sitemaps load immediately again. Interestingly the sitemaps on sites running 2.8 load with Ghostery active.
