### ISSUE TITLE
Review sitemap ping URLs

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2027]
Are the URLs we currently use still working?
```
'google' => 'https://www.google.com/webmasters/sitemaps/ping?sitemap=',
'bing'   => 'https://www.bing.com/webmaster/ping.aspx?siteMap=',
```
Google's documentation now says this:

> There are a few different ways to make your sitemap available to Google:
> - Submit it to Google using the Search Console Sitemaps tool
> Insert the following line anywhere in your robots.txt file, specifying the path to your sitemap:
> `Sitemap: http://example.com/sitemap_location.xml`
> - Use the "ping" functionality to ask us to crawl your sitemap. Send an HTTP GET request like this:
>  **`http://www.google.com/ping?sitemap=<complete_url_of_sitemap>`**
> for example:
>   `http://www.google.com/ping?sitemap=https://example.com/sitemap.xml`

Same goes for Bing:

> If you have an automated system that generates your sitemap, you may find it easier to inform Bing about your sitemap by sending a HTTP request. Using your favorite method to send the request, use the following URL, replacing the example with your sitemap location and URL encoding everything behind the sitemap parameter:
> 
> **`http://www.bing.com/ping?sitemap=http%3A%2F%2Fwww.example.com/sitemap.xml`**

**Comment by arnaudbroes** [comment]
@wpsmort can you check this and see if we need to change them?

**Comment by wpsmort** [comment]
I have confirmed that both Google and Bing have changed the URLs where you can ping and XML sitemap:

**From Google:**
https://support.google.com/webmasters/answer/183668?hl=en

**From Bing:**
https://www.bing.com/webmaster/help/how-to-submit-sitemaps-82a15bd4
