### ISSUE TITLE
Remove option "SEO for Content Types"

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2028]
I'm not sure why we need this.  @wpsmort?

![seo for content types](https://user-images.githubusercontent.com/2794445/47691531-b4919680-dbaf-11e8-8098-f1bffbd4d274.png)

**Comment by arnaudbroes** [comment]
I'd like to see it removed as well to be honest.

**Comment by EkoJR** [comment]
What about plugins that use Custom Post Types to store their data, and forcing SEO on those is needless processing and irrelevant data? Allowing others to disable/enable Post Types would prevent that.

For each Custom Post Type adds additional processing, and for some big sites it would have to deal with all the post types.

**Comment by michaeltorbert** [comment]
@EkoJR It's not that we'd take away the check boxes to enable/disable SEO meta per post type, only the radio for all of them. It's an unneeded extra layer.

**Comment by EkoJR** [comment]
In that case, I would agree then. That setting has always felt redundant.

**Comment by wpsmort** [comment]
I'd really like to get rid of this option.  I'd also like to get rid of the Enable Advanced Options radio and the Custom Titles checkbox.  I see no reason for any of them to be there.  

We have a trim options issue open for this here - #68

**Comment by arnaudbroes** [comment]
@wpsmort yes, yes and yes!!
