### ISSUE TITLE
NEED YOUR HELP FOR A BUG ISSUE

### ISSUE THREAD

**Issue by designertale** [semperfiwebdesign/all-in-one-seo-pack#2031]
We have working with the free version of the all in one seo pack as a trial version and whenever any 404 page like this is hit one our website a new error shwoing at the top of the page

Please check and guide me to resolve this issue

https://www.designertale.com/female-polo-t-shirt-mockup-230/

Thanks

**Comment by designertale** [comment]
Hello why my ticket has been closed.

*ANUSREE NANDI*
*ADMIN: WWW.DESIGNERTALE.COM <https://www.designertale.com/>*
*admin@designertale.com <admin@designertale.com> *
*designertalemail@gmail.com <designertalemail@gmail.com>*

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. You didn't open a support ticket, you opened a development issue.

If you'd like to access Premium Support, you can purchase a Pro license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
