### ISSUE TITLE
page sitemap white :( 

### ISSUE THREAD

**Issue by Valentin-che** [semperfiwebdesign/all-in-one-seo-pack#2035]
hi 

my sitemap's page xml is white :( , i can see xml shema when i look source code.
i have this error in my erro log controle : Notice: Undefined variable: post_type in /wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 4253

thank you  for your feedback ;)

**Comment by michaeltorbert** [comment]
Turn off debug mode.
