### ISSUE TITLE
google unable to read my Sitemap.xml

### ISSUE THREAD

**Issue by udafadil** [semperfiwebdesign/all-in-one-seo-pack#2040]
Hi There,

currently i'm using free version of "All in one SEO" plugin - version 2.9.1 on my website.
Since about last week, google unable to read my sitemap. It says: "It may contain an entry we are unable to recognize. Please validate your Sitemap before resubmitting."

I've already validate my sitemap.xml but problem still persist.
my sitemap location was at https://www.propertyinside.id/sitemap.xml

Please advise for any error/missed on my sitemap.

Thank you.

**Comment by michaeltorbert** [comment]
You're using a different plugin for your sitemap.

**Comment by udafadil** [comment]
Yes, for now i've disabling All in one SEO plugin, since i have no clue why
all in one sitemap couldnt read by google webmaster tools

**Comment by arnaudbroes** [comment]
@udafadil we can't troubleshoot the issue if you're not actively using the plugin on your website.
