### ISSUE TITLE
PHP Notice from AIOSEOP_Translations::set_native_language

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2046]
Reported here: https://wordpress.org/support/topic/php-notice-from-aioseop_translationsset_native_language/

----------------------

When the plugin settings pages are visited, PHP notices such as the following can be issued:

“Undefined index: en-UK”

This applies to “All In One SEO Pack” version 2.9.1 running under WordPress 4.9.8.

#### Steps to Reproduce

1. Have locale language set to en-UK.
2. Visit the “All In One SEO” > “XML Sitemap” admin page.

#### Expected Behaviour

Display of page with no PHP errors.

#### Actual Behaviour

PHP notices are logged, though not displayed.

#### Impact

Unwanted messages adding unecessary noise to the server’s PHP error log files.

#### Analysis

Calling wp_get_available_translations can result in an empty array being returned. However, this condition is not checked for in AIOSEOP_Translations->set_native_language, which results in the notice message being generated.

#### Recommendation

Check for empty array using empty() or missing key with isset().

**Comment by arnaudbroes** [comment]
I tried reproducing this with a bunch of locales but I'm not seeing any errors in my PHP error log.

**Comment by michaeltorbert** [comment]
change $translations      = wp_get_available_translations(); to instead set $translations as an empty array. This should reproduce it.

**Comment by arnaudbroes** [comment]
I've been able to reproduce this using Michael's instructions.
