### ISSUE TITLE
My Site is messed up and it is seo related.

### ISSUE THREAD

**Issue by celmore1230** [semperfiwebdesign/all-in-one-seo-pack#2048]
`
				### WordPress ###

Version: 4.9.8
Language: en_US
Permalink structure: /%postname%/
Is this site using HTTPS?: Yes
Can anyone register on this site?: Yes
Default comment status: open
Is this a multisite?: No
User Count: 1
Communication with WordPress.org: WordPress.org is reachable
Create loopback requests: The loopback request to your site completed successfully.

### Installation size ###

Uploads Directory: 1.11 GB
Themes Directory: 23.25 MB
Plugins Directory: 82.89 MB
Database size: 22.38 MB
Whole WordPress Directory: 27.23 MB
Total installation size: 49.62 MB

### Drop-ins ###

advanced-cache.php: Advanced caching plugin.
object-cache.php: External object cache.

### Active Theme ###

Name: Envo Magazine
Version: 1.3.5
Author: EnvoThemes
Author website: https://envothemes.com/
Parent theme: Not a child theme
Supported theme features: title-tag, menus, post-thumbnails, custom-background, custom-logo, automatic-feed-links, custom-header, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, editor-style, widgets

### Other themes (10) ###

DailyMag (dailymag): Version 0.9.0 by UpThemes
Discovery (discovery): Version 2.6.1 by Template Express
Espied (espied): Version 1.2.2-wpcom by Automattic
Indie (indie): Version 1.3.6 by Templateexpress.com
Magazine O Pro (magazine-o-pro): Version 1.2 by teamocean
Magazine O (magazine-o): Version 1.1.0 by teamocean
Melos News (melos-news): Version 1.0.3 by Think Up Themes
Melos (melos): Version 1.2.6 by ThinkUpThemes
Storefront (storefront): Version 2.3.5 by Automattic
Twenty Seventeen (twentyseventeen): Version 1.7 by the WordPress team

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: Version 1.5.0
WP.com Site Helper: No version or author information available

### Active Plugins (28) ###

Accelerated Mobile Pages: Version 0.9.97.19 by Ahmed Kaludi, Mohammed Kaludi
AddToAny Share Buttons: Version 1.7.32 by AddToAny
Akismet Anti-Spam: Version 4.0.8 by Automattic
All-in-One WP Migration: Version 6.79 by ServMask
All In One SEO Pack: Version 2.9.1 by Michael Torbert
Categories to Tags Converter Importer: Version 0.5 by wordpressdotorg
Classic Editor: Version 0.5 by WordPress Contributors
Duplicate Post: Version 3.2.2 by Enrico Battocchi
Google Analytics Dashboard for WP (GADWP): Version 5.3.5 by ExactMetrics
Google XML Sitemaps: Version 4.0.9 by Arne Brachhold
Gutenberg: Version 4.2.0 by Gutenberg Team
Health Check & Troubleshooting: Version 1.2.1 by The WordPress.org community
Image Widget: Version 4.4.7 by Modern Tribe, Inc.
Instagram Gallery: Version 1.6.3 by Karan Singh
Instagram Slider Widget: Version 1.4.3 by jetonr
Jetpack by WordPress.com: Version 6.7 by Automattic
NextGEN Gallery: Version 3.0.16 by Imagely
Ninja Forms: Version 3.3.17 by The WP Ninjas
One Click Demo Import: Version 2.5.1 by ProteusThemes
Page Builder by SiteOrigin: Version 2.9.1 by SiteOrigin
Pages with category and tag: Version 0.9.0 by YAHMAN
Photo Gallery: Version 1.5.7 by Photo Gallery Team
Press This: Version 1.1.1 by WordPress Contributors
RSS Importer: Version 0.2 by wordpressdotorg
SiteOrigin Widgets Bundle: Version 1.13.2 by SiteOrigin
Smush: Version 2.9.1 by WPMU DEV
TablePress: Version 1.9.1 by Tobias Bäthge
WP-Optimize: Version 2.2.6 by David Anderson, Ruhani Rabin, Team Updraft

### Media handling ###

Active editor: WP_Image_Editor_GD
Imagick Module Version: Imagick not available
ImageMagick Version: Imagick not available
GD Version: bundled (2.1.0 compatible)
Ghostscript Version: Not available

### Server ###

Server architecture: Linux 4.9.0-8-amd64 x86_64
PHP Version: 7.0.32 (Supports 64bit values)
PHP SAPI: fpm-fcgi
PHP max input variables: 6144
PHP time limit: 1200
PHP memory limit: 256M
Max input time: 1200
Upload max filesize: 2047M
PHP post max size: 2047M
cURL Version: 7.61.1 OpenSSL/1.1.0f
SUHOSIN installed: No
Is the Imagick library available: No

### Database ###

Extension: mysqli
Server version: 5.5.5-10.2.12-MariaDB-log
Client version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
Database prefix: wp_68268414_

### WordPress Constants ###

ABSPATH: /wordpress/core/4.9.8/
WP_HOME: https://celmoreblog.com
WP_SITEURL: https://celmoreblog.com
WP_DEBUG: Disabled
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG_DISPLAY: Disabled
WP_DEBUG_LOG: Disabled
SCRIPT_DEBUG: Disabled
WP_CACHE: Enabled
CONCATENATE_SCRIPTS: Undefined
COMPRESS_SCRIPTS: Undefined
COMPRESS_CSS: Undefined
WP_LOCAL_DEV: Undefined

### Filesystem Permissions ###

The main WordPress directory: Not writable
The wp-content directory: Writable
The uploads directory: Writable
The plugins directory: Writable
The themes directory: Writable
The Must Use Plugins directory: Writable

`

**Comment by arnaudbroes** [comment]
@celmore1230 if you don't tell us what the problem is, then we can't help you.
