### ISSUE TITLE
performance problems with all in one seo pack

### ISSUE THREAD

**Issue by alex2005** [semperfiwebdesign/all-in-one-seo-pack#2053]
the plugin cause a performance problems with big sites

**Comment by wpsmort** [comment]
@alex2005 This is a development repository and not a support forum.  Please contact us at https://semperplugins.com/contact/ with more specific information.  Please note that is you have a site with a lot of images then we are aware of a performance problem and have an issue open for this here https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2008
