### ISSUE TITLE
No SEO output on homepage when there are no posts

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2055]
Reported by David Tiong (by email) and Shaul Hader (https://wordpress.org/support/topic/after-the-update-the-plug-in-does-not-work/)

The bug occurs in the v2.9 release and happens when Settings > Reading > Your homepage displays is set to Your latest posts.  If there are no posts on the site then AIOSEOP doesn't output anything in teh source code of the homepage.  This bug was introduce in v2.9.

To reproduce this follow these steps:

1. Create a new site with no posts
2. Go to Settings > Reading and set Your homepage displays to Your latest posts
3. Go to All in One SEO Pack > Home Page Settings and add a title and description
4. View the source code of the homepage and you'll see that nothing is being output by AIOSEOP
5. Add a post and then view the source code of the homepage and you'll see that now AIOSEOP is outputting the title and description

**Comment by wpsmort** [comment]
@contactashish13 This bug was introduced in v2.9.  Please let me know ASAP if you need me to demonstrate how to reproduce this.

**Comment by contactashish13** [comment]
@wpsmort I have fixed this. PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2058
