### ISSUE TITLE
Open Graph

### ISSUE THREAD

**Issue by SwordAndrew** [semperfiwebdesign/all-in-one-seo-pack#2056]
Hi! We have problem with OpenGraph – photos aren’t displayed during cross-posting… on all pages. [The site](https://slovo-dnr.info/poetry/nebo/) is installed All In One SEO Pack. Two or three weeks ago everything worked fine. Any idea?

Thanks))
![default](https://user-images.githubusercontent.com/45046910/48504867-d26d2580-e856-11e8-8a59-be9a34865912.png)

**Comment by michaeltorbert** [comment]
@SwordAndrew This is an issue specific to your website. You have another plugin or your theme is outputting conflicting OG data.

**Comment by SwordAndrew** [comment]
Hello!

1. We always used All In One SEO Pack with the theme OceanWP and there were no problems. Opengraph from the OceanWP we enable too. There was no conflict until about November 1. This is clearly seen in the cache pages in social networks (where the images remained in their places).

2. When the problem occurred, we disabled the plugin and enable only Opengraph from the OceanWP. This did not solve the problem.

3. Then disabled Opengraph from the OceanWP and enable All In One SEO Pack.And this did not solve the problem.

Support threads redirected to you. And how do we solve the problem?
