### ISSUE TITLE
RSS Sitemap should be optional and disabled by default

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2057]
Whilst troubleshooting issues with the XML sitemap (issues #2008 and #2014), we looked into whether the addition of the RSS sitemap in v2.9 contributed to the issues being reported by users.

As the RSS sitemap is not a requirement of any search engines, we should make this feature an option in the XML Sitemap settings and it should be disabled by default.

**Comment by michaeltorbert** [comment]
Are the performance problems caused by the RSS sitemap functionality only on large sites? 
If so, I'd recommend that the documentation (on semperplugins.com and in AIOSEOP) warn that this option can cause performance issues on large sites.

**Comment by wpsmort** [comment]
@EkoJR is going to look into this and see if the RSS sitemap is causing or contributing to the performance problems.

**Comment by contactashish13** [comment]
@wpsmort I had also suggested on call that we can actually count how many elements are going to be included in the sitemap and on the basis of that we can recommend whether the user should enable indexes or not. Let me know if you think that needs to be done as well.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2074

**Comment by contactashish13** [comment]
@wpsmort shouldn't the module be renamed to Sitemaps rather than XML Sitemaps as this can generate RSS as well?

**Comment by arnaudbroes** [comment]
@contactashish13 feel free to open an issue to discuss it.
