### ISSUE TITLE
Edit robots.txt

### ISSUE THREAD

**Issue by fabiobfava** [semperfiwebdesign/all-in-one-seo-pack#2064]
Your actual robots.txt module just allows to create new rules, we need back (it was present in earlier versions) the capability to fully edit the robots.txt file. I just can't remove the lines:

User-agent: *
Disallow: /

So no matter what I add later, the robots.txt just blocks all Google Crawlers.

**Comment by arnaudbroes** [comment]
@fabiobfava it's possible to delete rules, as you can see in the image below. If you're using the latest version of All in One SEO Pack pro and do not have this option, then please reopen this issue and we'll investigate.

![image](https://user-images.githubusercontent.com/18156697/48705801-80cbee80-ebfa-11e8-8e4a-67b3b2d93cd5.png)

**Comment by fabiobfava** [comment]
I use the basic version (not Pro) and there's no way to delete a pre-existing rule. One year ago with the free version was possible to fully edit the robots.txt I don't understand why it's not possible now...

**Comment by arnaudbroes** [comment]
If you're using a multilingual plugin, then there's going to be multiple sitemaps where the slug starts with the language code.

We recently overhauled the Robots.txt module and since we added a Edit Rule feature in v2.9, this is a non-issue.
