### ISSUE TITLE
Lost aiosp social thumbnails settings after regenerated thumbnails

### ISSUE THREAD

**Issue by evanre** [semperfiwebdesign/all-in-one-seo-pack#2066]
**Describe the bug**
Hi, I've regenerated my media thumbnails (with 'regenerate thumbnails' plugin) and now all posts lost social image setting! There is few thousand of posts, please, help get this settings back!

**Version Info (please complete the following information):**
 - WordPress version: 4.9.8
 - All in One SEO Pack version: 2.9.1
 - PHP version: 5.6.33

**Comment by wpsmort** [comment]
This is a development repository, not a support forum.

You can find troubleshooting steps here https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
or access premium support here https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by evanre** [comment]
I don't need a "Troubleshooting for housewives" or premium support. I just wanted to ask, do you guys think it was a good idea to hardcode absolute link to the cropped image right into post_meta table???
![image](https://user-images.githubusercontent.com/12615906/48729148-90215b00-ec3f-11e8-9a44-aace901a2797.png)

**Comment by michaeltorbert** [comment]
I've updated the title to be more relevant
