### ISSUE TITLE
setting not saved

### ISSUE THREAD

**Issue by msongz** [semperfiwebdesign/all-in-one-seo-pack#2069]
![](https://ws4.sinaimg.cn/large/006tNbRwgy1fxedf55kqjg30f30b0405.gif)

**Comment by arnaudbroes** [comment]
@msongz this is development repository; not a support forum. You can use [these steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/) to narrow down a conflict or else you can purchase a premium license to gain access to our support resources - https://semperplugins.com/all-in-one-seo-pack-pro-version/
