### ISSUE TITLE
No caption and title attributes for images with sitemap indexes

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2071]
When Sitemap Indexes are enabled, caption and title attributes for images seem to be lacking.

**Comment by wpsmort** [comment]
@arnaudbroes I cannot reproduce this. Both tags shows for me when I use Sitemap Indexes.

<img width="2539" alt="screen shot 2018-11-20 at 1 54 43 pm" src="https://user-images.githubusercontent.com/17548525/48795869-13888e00-eccc-11e8-8487-2aec69f30981.png">

**Comment by arnaudbroes** [comment]
We found out this isn't caused by sitemap indexes but rather the fact that the plugin recognizes caption/title attributes for featured images, but not for images that are embedded into the content. Closing this in favour if #2077.
