### ISSUE TITLE
Social Meta Module - Consider adding support for multiple og:image tags

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#208]
Consider adding support for multiple og:image tags

**Comment by michaeltorbert** [comment]
Another request for this here https://wordpress.org/support/topic/how-to-put-my-custom-twitterimage-og-meta-tag?replies=1

**Comment by wpsmort** [comment]
Until we add new tabs for social media (see issue #400) then I recommend the easiest solution here is to add a Custom Twitter Image field below the Custom Image field.  We should rename Custom Image to Custom OG Images to differentiate it (og:image) from the Twitter image (twitter:image).  See mockup below:

<img width="918" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/17492196/be27b24a-5d78-11e6-9fbe-4833673b4e96.png">

**Comment by wpsmort** [comment]
This is tested and works fine.
