### ISSUE TITLE
GA Code Does not appear

### ISSUE THREAD

**Issue by FactorExtremo** [semperfiwebdesign/all-in-one-seo-pack#2083]
Hello there, My Google Analytics Code does not appear in any page

regards

**Comment by wpsmort** [comment]
@FactorExtremo Can you please provide the URL for your site.

**Comment by FactorExtremo** [comment]
Yes ,https://elsegurosocial.net/

**Comment by wpsmort** [comment]
@FactorExtremo Please follow the steps below:

- Go to All in One SEO > General Settings > Content Type Settings
- Make sure that SEO for Custom Post Types is set to Enabled
- Make sure you've ticked the checkboxes for Posts and Pages in SEO on only these post types
- Check the source code of your posts and pages to verify that the All in One SEO Pack Pro section is back and that your Google Analytics tracking code is there.

If it's not, please send us an Administrator login using the secure form here - https://semperplugins.com/contact/support-login-information/

**Comment by FactorExtremo** [comment]
@wpsmort Thanks a lot, it's working now.
