### ISSUE TITLE
NOINDEX / NOFOLLOW this page/post doesn't work on the WooCommerce Shop page

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2085]
NOINDEX / NOFOLLOW this page/post doesn't work on the WooCommerce Shop page.

Reported here - https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/woocommerce-removing-shop-page-from-sitemap/

**Comment by wpsmort** [comment]
This is also the case for the Exclude from Sitemap setting as well.  In fact, I can't see any way to exclude the Shop page from the XML Sitemap.

**Comment by arnaudbroes** [comment]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2317 fixed noindex but didn't affect nofollow so that still has to be fixed.

**Comment by arnaudbroes** [comment]
I've got a fix for this that can be implemented after #1798 is merged.

**Comment by arnaudbroes** [comment]
This has been fixed in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2671.
