### ISSUE TITLE
Litespeed Sitemap issue

### ISSUE THREAD

**Issue by evallee** [semperfiwebdesign/all-in-one-seo-pack#2087]
Hi,
Receiving an error
XML Parsing Error: not well-formed
Location: https://novelfinancial.ca/sitemap.xml
Line Number 20, Column 91:

I am using the Litespeed cache tool.  I tried using the same text provided for W3/WP-Rocket in the Exclude URI field, but no luck.

https://novelfinancial.ca/sitemap.xml is the file in question

**Comment by michaeltorbert** [comment]
That sitemap wasn't created with All in One SEO Pack.
