### ISSUE TITLE
Use double quotes for pagination links

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2088]
Requested here - https://wordpress.org/support/topic/single-quotes-on-prev-next-links-in-archives/

We currently output the link rel=prev and link rel=next with single quotes.  We should consider changing this to double quotes like so:

```
<link rel="prev" href="https://www.example.com/category/recipes/page/2/" />
<link rel="next" href="https://www.example.com/category/recipes/page/4/" />
```

**Comment by michaeltorbert** [comment]
I don't see any compelling reason for either, but sure, we can do double.

**Comment by EkoJR** [comment]
They way it currently is, is incorrect. WP Coding standards say we should be using single quotes to wrap strings, and this is the other way around and should be fixed.

The only time I've seen double quotes being useful is with SQL strings. Otherwise WP standards tend to be better.

**Comment by michaeltorbert** [comment]
@EkoJR You're thinking about PHP coding standards. HTML coding standards are either: https://make.wordpress.org/core/handbook/best-practices/coding-standards/html/#quotes
