### ISSUE TITLE
Undefined index: aiosp_cpostactive aioseop_class.php:953

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2096]
Reported here - https://wordpress.org/support/topic/error-messages-since-version-2-10/

Reported right after release of v2.10
Undefined index: aiosp_cpostactive /wp-content/plugins/all-in-one-seo-pack/aioseop_class.php:953

**Comment by EkoJR** [comment]
I wasn't able to reproduce this, but I created a PR that may fix it.

**Comment by martijnrusschen** [comment]
Still seeing this issue. Example: https://studio-hoogeveen.nl/.

**Comment by wpsmort** [comment]
@martijnrusschen Can you confirm you are running version 2.10.1 of All in One SEO Pack which has the patch for this.  If you are, then please can you let us know the exact steps to reproduce this and can you send us an Administrator login for your site using the secure form here - https://semperplugins.com/contact/support-login-information/

**Comment by martijnrusschen** [comment]
Yep see below:
![screenshot 2018-12-17 at 5 38 02 pm](https://user-images.githubusercontent.com/1412392/50101216-85e48380-0222-11e9-85c9-677b3b6dc0e2.png)

I'd like to avoid sharing Admin credentials, it seems this started to happen after the Wordpress 5 upgrade. There was an upgrade for the plugin available at that time, which I executed as well, but it didn't resolve the errors I'm seeing.

**Comment by arnaudbroes** [comment]
@martijnrusschen om de waarschuwing te verbergen (aangezien het vermoedelijk om een website van een klant gaat) kan je trouwens in de tussentijd in het wp-config.php-bestand van de website debugging uitschakelen.
