### ISSUE TITLE
Character count JS 404 error

### ISSUE THREAD

**Issue by rdrewniak** [semperfiwebdesign/all-in-one-seo-pack#2100]
I just updated to WordPress v5 as well as the latest version of All In One SEO, when I got a 404 error for the **count-chars.js** file.

**Comment by michaeltorbert** [comment]
Thanks for reporting this. Can you delete and reinstall the plugin and see if it's fixed for you?

**Comment by rdrewniak** [comment]
...You know what they say, the simplest solution is usually the correct one...

Sorry, I should have done that before reporting this.

**Comment by michaeltorbert** [comment]
Don't be sorry. You really did find a bug. I just fixed it quickly and reinstalling applies it to your site. :)
Thank you for reporting it.
