### ISSUE TITLE
sitemap error

### ISSUE THREAD

**Issue by plykite** [semperfiwebdesign/all-in-one-seo-pack#2105]
Hello, 
i tried to creat my sitemap but i get this error https://airdeslyonnais.fr/sitemap.xml

Thnk you for your help,

PAscal (Wordpress 4.9.8)

**Comment by plykite** [comment]
In chrome error message : 'This page contains the following errors:
error on line 3 at column 14: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.'

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/this-page-contains-the-following-errors/
