### ISSUE TITLE
SEO box now displayed in the middle of my post

### ISSUE THREAD

**Issue by elefly2297** [semperfiwebdesign/all-in-one-seo-pack#2108]
The SEO box at the bottom of the section where you create posts is now right in the middle of some posts and it covers my content and I can't edit. Some posts have it stuck more towards the bottom and it won't allow me to scroll through my post. Please advise.

Thank you,
Jamie

**Comment by michaeltorbert** [comment]
Please try these troubleshoot steps to narrow down a plugin or theme conflict. Make sure to clear your browser’s cache, server cache, and any other caching you have.
https://www.google.com/amp/s/semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/amp/

**Comment by arnaudbroes** [comment]
FYI, I've seen this happening a few times, each time caused by a plugin conflict.

**Comment by michaeltorbert** [comment]
@arnaudbroes Feel free to reopen it if you can reproduce with repeatable steps.
