### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HelenD123** [semperfiwebdesign/all-in-one-seo-pack#2115]
1) When I post to Facebook it is showing the title of my blog not the title of the post and no meta description. However when sending through Hootsuite it shows correctly but still does not post properly.

2) When I tweet, sometimes it shows the picture and meta description and sometimes not

Please can you advise?
Thanks

**Comment by wpsmort** [comment]
@HelenD123 This is a development repository, not a support forum.

You can find troubleshooting steps here https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/
or access premium support here https://semperplugins.com/all-in-one-seo-pack-pro-version/
