### ISSUE TITLE
XML Sitemap - Chinese sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#212]
https://wordpress.org/support/topic/encoding-error-for-opening-sitemap

We need to test whether this is a newly introduced bug.

Start with verifying it on the current release, then test a while back (6 months?), then in the middle of that, etc until it's narrowed down when it was introduced.

**Comment by wpsmort** [comment]
@michaeltorbert This is fixed in the latest version 2.3.5.  The XML sitemap works fine in Chinese language.

**Comment by wpsmort** [comment]
We should test again with v2.3.6 given all the changes we're making to the XML Sitemap module.

**Comment by michaeltorbert** [comment]
Agreed. For testing, make sure to start with an old version where it's broken, verify it's broken on the site, then upgrade to dev and test that it's still fixed.

**Comment by wpsmort** [comment]
@michaeltorbert: I tested with this development code and the XML sitemap is broken when you switch to Chinese language.

**Comment by michaeltorbert** [comment]
@wpsmort Ok we should be good with this now in the dynamic-xsl branch

**Comment by wpsmort** [comment]
This works fine now.

We should test again when ready to release v2.3.6

**Comment by wpsmort** [comment]
This is still working fine.
