### ISSUE TITLE
Extra | in Title

### ISSUE THREAD

**Issue by silentmedia** [semperfiwebdesign/all-in-one-seo-pack#2122]
Hello,

I have set Product Title Format: (product)
%post_title% | %blog_title%

But it keeps adding and extra | in title to all meta tags (as below):
Near Wall TV Floor Stand, VESA Ready, 23″-55″ TVs | | Forest-AV.com

WooCommerce + Flatsome Theme.  There is no setting in Theme adding this.

Regards,
Jasbir

**Comment by arnaudbroes** [comment]
@silentmedia this is a development repository; not a support forum. If you'd like access to our support resources, then you can purchase a license on our website and create a forum thread in our premium support forums - https://semperplugins.com/all-in-one-seo-pack-pro-version/
