### ISSUE TITLE
القنطري يهنئ عكاشة برئاسة الاتحادات العربية

### ISSUE THREAD

**Issue by suwaih** [semperfiwebdesign/all-in-one-seo-pack#2125]
القنطري يهنئ عكاشة برئاسة الاتحادات العربية
تقدم رئيس الهيئة العامة للشباب والرياضة الدكتور بشير القنطري بالتهنئة للأستاذ مصطفى عكاشة رئيس الاتحاد العربي للكرة الحديدية بمناسبة حصوله على عضوية المكتب التنفيذي لاتحاد الاتحادات العربية والذي عُقد مؤخراً في دولة الإمارات العربية المتحدة.
حيث أعرب القنطري خلال لقائه بعكاشة وأمينه العام محمود الطويل عن استعداد ليبيا لتقديم الدعم اللازم لإنجاح عمل الكوادر الليبية في المناصب القيادية.
ومن جانبه أكد مصطفى عكاشة بأن سيسعي على ترشيح عدداً من الكوادر الليبية المتميزة لتولي مناصب باللجان العاملة بالدورات العربية.

**Comment by michaeltorbert** [comment]
According to Google Translate this is spam.
