### ISSUE TITLE
Static pages included twice in sitemap

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2126]
Reported here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/sitemap-lists-same-url-twice-with-two-different-dates-of-updates/

The WooCommerce Shop page is included twice in the XML Sitemap and can the two entries may have different Priority, Frequency and Last Change date.

1. Install WooCommerce and AIOSEOP on a new site
2. Ensure the default pages have been created by WooCommerce so there is a Page called Shop
3. Activate the XML Sitemap module and view the sitemap
4. You should see the Shop page listed twice, see screenshot below.

I verified that the Shop page is included once as a page (one entry goes away if you uncheck Pages next to Post Types) and is included once as the post type archive for Products (one entry goes away if you uncheck Products next to Post Types).

Tested with:
- WordPress version: 5.0.2
- AIOSEOP version: 2.10.1
- PHP version: 7.2.0

<img width="1083" alt="screen shot 2018-12-28 at 6 29 58 pm" src="https://user-images.githubusercontent.com/17548525/50530798-2c584080-0acf-11e9-9b18-4842751c59e8.png">

**Comment by wpsmort** [comment]
@arnaudbroes Can you test back through the old versions of AIO and see if this has always been the case or is new.

**Comment by arnaudbroes** [comment]
@wpsmort traced this back to https://github.com/semperfiwebdesign/all-in-one-seo-pack/tree/6a40943844702930faa44cb4cc757f3b5a44c124.

**Comment by arnaudbroes** [comment]
@wpsmort I'm no longer able to reproduce this anymore with the newest versions of All in One SEO Pack and WooCommerce nor with older versions (nor with the commit I traced it back to). 

Can you confirm this?

**Comment by wpsmort** [comment]
@arnaudbroes I've set up a new site on your Cloudways server where the problem is present - https://wordpress-281813-887299.cloudwaysapps.com

**Comment by arnaudbroes** [comment]
Whilst testing the PR for this issue Steve found that, if configured, the static homepage and blog page are also included twice.

**Comment by arnaudbroes** [comment]
So we are also including the homepage twice; once in the Additional Pages index and another time in the Pages index. I'd suggest that we do the same as for #2126 which is to leave it under Additional Pages if it is a post archive page and leave it under Pages if it is a static page.
