### ISSUE TITLE
All in One SEO Pack overlays text in Gutenberg

### ISSUE THREAD

**Issue by iKarel** [semperfiwebdesign/all-in-one-seo-pack#2128]
The SEO fields overlay the text. This makes it impossible to write longer pages, posts ...
I use Chrome on a Macbook Pro.

![schermafbeelding 2019-01-04 om 22 05 21](https://user-images.githubusercontent.com/29686660/50711008-f7b72c80-106c-11e9-9cd7-a61f880f9117.png)

**Comment by michaeltorbert** [comment]
Hi @iKarel 
Thanks for reporting this. We're unable to reproduce it. 
Try these steps to narrow down a possible plugin/theme conflict.

**Comment by iKarel** [comment]
It was a conflict with another plugin: Form Maker. It’s okay now.

Met vriendelijke groet
Kind Regards

Karel Overlaet
Medianaut - nautical news and photos
VAT.: BE 0861.429.581
M.: + 32 487 41 42 58

**Comment by arnaudbroes** [comment]
I was able to reproduce this.

In able to reproduce this issue, use the following steps:
1. Create a fresh test site and install All in One SEO Pack
2. Create a new Post or Page and use something like to Bacon Ipsum (https://baconipsum.com/) to generate some dummy text and add the generated paragraphs (at least 10) to the body
3. Publish. You'll now see that the meta box is hovering in the middle of the body.

**Comment by wpsmort** [comment]
@arnaudbroes Was this reproduced with the default theme and no other plugins installed or does this only happen when Form Maker is active on the site?

**Comment by wpsmort** [comment]
@arnaudbroes Does the problem happen when AIOSEOP is deactivated and another plugin that adds a meta box on the Edit Post screen is activated?  If it does then this is a problem with Form Maker.

**Comment by arnaudbroes** [comment]
@wpsmort @michaeltorbert I've confirmed this isn't an issue on our end since the Form Maker plugin also breaks this for the meta box of Toast.

**Comment by michaeltorbert** [comment]
@arnaudbroes Does it break all plugins that have meta boxes?

**Comment by arnaudbroes** [comment]
@michaeltorbert yes, breaks all plugins with meta boxes.

**Comment by arnaudbroes** [comment]
Just as a follow up and FYI: 

I just had this issue with All in One SEO Pack and no other plugins and the default theme. After looking around, I was able to confirm again that this isn't coming from our end and found out it happens whenever a plugin (or something else) is outputting something in the source code of the Edit page before the HTML document declaration. In my case, this was WP_DEBUG displaying an error.

I'm creating an issue here to add a doc to explain this as I have no doubt people will keep creating bug reports and opening support threads for this - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2416
