### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by gena8208** [semperfiwebdesign/all-in-one-seo-pack#2135]
Fatal error: ob_start() [<a href='ref.outcontrol'>ref.outcontrol</a>]: Cannot use output buffering in output buffering display handlers in .../wp-content/plugins/wordpress-seo/frontend/class-frontend.php on line 1813

**Comment by michaeltorbert** [comment]
That's a different plugin causing that error. Disable Yoast and the error should go away.
