### ISSUE TITLE
Add recommended and/or max. amount of chars for og:title and og:description

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2139]
We might want to consider this:

> As with metadata, the lengths of your OG tag are defined by the platform that they will be viewed on. For example, a link shared to Facebook will create a card that looks different on mobile and desktop Facebook and will look different again on LinkedIn.
> 
> As such, the optimum length is more defined by what is most likely to be seen by all users across any platform and, even then, you should keep your key messages upfront in the copy to reduce the risk of them being truncated.
> 
>* Optimum OG Title length: 55 characters or under. This ensures that your title will be visible on desktop and mobile devices and also allows for your description to be visible.
> * Maximum recommended OG Title length: 95 characters or under.
>
> * Optimum OG Description length: 55 characters or under. Combined with a 55 character title, your copy will be visible on all devices.
> * Maximum recommended OG Description length: 200 characters or under.

**Comment by wpsmort** [comment]
@arnaudbroes Are you recommending we change the text and the character counter (yellow and red levels) under the Title and Description fields on the Social Settings tab?  If not, what are you recommending?

**Comment by arnaudbroes** [comment]
@wpsmort I recommend the following:

1. OG:title
< 55 => green
>= 55 and <= 95 => yellow
> 95 => red

2. OG:description
< 55 => green
>= 55 and <= 200 => yellow
> 200 => red

Also, we need to add the counter to the Home Title and Home Description fields in the Social Meta menu. Let me know what you think. We might want to separate this into two specific issues.

**Comment by wpsmort** [comment]
@arnaudbroes I agree with your recommendations.  

We have #1337 open for adding the counter to the Home Title and Home Description fields under the Social Meta settings.

**Comment by wpsmort** [comment]
This is related to #808

**Comment by wpsmort** [comment]
We agreed in the dev meeting today that, in the absence of any official documentation from Facebook, we'll go with the information in the thoughtshift.co.uk article that Arnaud found and we'll make it clear in our documentation and help that this is just a guide.
