### ISSUE TITLE
Robots.txt should filter WP virtual robots.txt instead of a physical file

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#214]
Look into whether we want to do this.

"When using the AIO SEO to create the robots.txt file, it creates an actual file, instead of maintaining the virtual robots.txt file that wordpress generates. It would be nice if it kept it as a virtual file."

https://wordpress.org/support/topic/great-seo-plugin-22?replies=1#post-8283912

**Comment by michaeltorbert** [comment]
1. Considering they may have a static robots.txt already in place, on upgrade and on activating the module, we'll need to check that a) the module is checked and b) the static file exists, and if so, rename it (check to see if there's even a conflict in the first place... if not, maybe we just leave it?)
2. Also make sure we're used instead of the built-in WP one. Does Jetpack do anything with robots.txt?
3. Would it make sense to try and just hook into the built-in WP one instead of making our own?

**Comment by wpsmort** [comment]
See also #1124

**Comment by michaeltorbert** [comment]
-do we add sitemap to robots.txt if module is off
-can we determine if we made the robots.txt physical file before deleting (check if the robots.txt module is active, and any other DB clues) 
-we should remove the robots.txt module completely… it’s redundant with the file editor
-by default, we should leave the robots.txt alone and simply add in the link to the sitemap
