### ISSUE TITLE
SEO Missing Data

### ISSUE THREAD

**Issue by vit1260** [semperfiwebdesign/all-in-one-seo-pack#2144]
Hello - We use the free version of All in One SEO on our WordPress site. We've recently discovered that a great majority of our posts seem to have lost their SEO data (title, description, keywords, and image). In looking at the long list of all of our posts, it seems that the posts between 12/21/2018 and 5/30/2018 are missing data. That said when we click into the posts, some of them actually do show data in the SEO section and some do not. I reviewed the note about checking the content type settings and confirmed that our settings are checked for posts and pages. Any insights or guidance you can provide on why this may have happened or how to fix it are greatly appreciated. Thank you, Lauren

**Comment by arnaudbroes** [comment]
@vit1260 this a development repository; not a support forum. If you'd like to gain access to our support resources, then you'll need to puchase a license for All in One SEO Pack Pro - https://semperplugins.com/all-in-one-seo-pack-pro-version/
