### ISSUE TITLE
Robots.txt optimizer should look for bad things to remove

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#215]
ex:
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /xmlrpc.php
blocking js,css, etc

http://semperplugins.com/blog/important-google-search-console-announcement-googlebot-cannot-access-css-and-js-files-on-your-site/

**Comment by michaeltorbert** [comment]
@wpsmort Anything else we want to add to this?

**Comment by wpsmort** [comment]
@michaeltorbert we should check for:
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/

We should also check for blocking JS, CSS, etc.
We should also check that the link to the XML sitemap matches the site URL and our XML Sitemap URL.
We don't need to check for Disallow: /xmlrpc.php as that's is valid.

See also #86 and #46 which are releated feature requests.

**Comment by wpsmort** [comment]
This is no longer needed as the optimizer was removed as part of #1647
