### ISSUE TITLE
Website Name being added to product titles

### ISSUE THREAD

**Issue by EquineChallengeSupplements** [semperfiwebdesign/all-in-one-seo-pack#2153]
I recently updated to All in One SEO 2.10.1 from All In One 2.8. I had updated from the 2.8 and had problems, my sitemap disappeared, so I went back to 2.8. When 2.10.1 became available I updated and then noticed that my website name was automatically being added to all of my product page titles (not adding to post titles or page titles.)

Example:
Amino Acid Horse Supplement | Muscle Mass | Topline | Equine Challenge Horse Supplements

Should read, and what I have on this page is

Amino Acid Horse Supplement | Muscle Mass | Topline

Any suggestions on how to fix this? 

Thank you

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum.
You can find documentation here https://semperplugins.com/documentation/
or access premium support here https://semperplugins.com/all-in-one-seo-pack-pro-version/

**Comment by EquineChallengeSupplements** [comment]
Thank you!
