### ISSUE TITLE
E-mail debug information form missing

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2157]
The E-mail debug information form is missing from the System Status box in the Performance module.  This happened in v2.10.

<img width="629" alt="screen shot 2019-01-18 at 11 21 58 am" src="https://user-images.githubusercontent.com/17548525/51399163-4952c300-1b13-11e9-837e-641812118e3c.png">

**Comment by wpsmort** [comment]
@arnaudbroes Can you find out which commit resulted in the form not being displayed anymore.

**Comment by arnaudbroes** [comment]
Traced it back to https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/77bbe410dc75765aee0e53947dc964046c05b6e6.
