### ISSUE TITLE
Undefined index: aiosp_opengraph_options in aioseop_opengraph.php line 1101

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2158]
I got this PHP Notice whilst testing the 2.11 branch on a new site:

PHP Notice:  Undefined index: all-in-one-seo-pack/modules/aioseop_opengraph.php on line 1101

It is related to this commit for PR #1873 - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1873/commits/527c4cf730d4047103b2cfccc9eec3d1478592cf

**Comment by EkoJR** [comment]
It looks like the options array in the backend had some restructuring done on it, but doesn't seem to be getting set/initialized.

@contactashish13 might have a better idea. I'm unsure where to apply changes.

**Comment by contactashish13** [comment]
@wpsmort I can see the potential problem but I cannot reproduce this. Can you outline the exact steps?

**Comment by wpsmort** [comment]
@contactashish13 Here are the steps to reproduce this:

1. Download the v2.11 branch of free and the v2.12 branch of Pro and create the Pro plugin from these branches.
2. Install the plugin on a brand new site.
3. Enable wp_debug in the wp-config.php file
4. Activate the Social Meta module.
5. View the Uncategorized category and you should see the PHP notice.

**Comment by contactashish13** [comment]
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2159
