### ISSUE TITLE
top level menu icon flickers from gear to shield on pageload

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#216]
As reported https://wordpress.org/support/topic/great-seo-plugin-22?replies=1#post-8283912

**Comment by arnaudbroes** [comment]
I'm not able to reproduce this. @wpsmort can you confirm this, label the issue as "can't reproduce" and close it if you can't either?

**Comment by EkoJR** [comment]
@arnaudbroes I believe I may have already fixed this from another issue https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/292

**Comment by arnaudbroes** [comment]
@EkoJR correct, thanks!
