### ISSUE TITLE
Updating large (static) sitemap locks out WP-API

### ISSUE THREAD

**Issue by contactashish13** [semperfiwebdesign/all-in-one-seo-pack#2160]
https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/updating-large-sitemap-locks-out-wp-api/

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2161

We have to explore whether https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L436 is even required. This causes a redraw of the entire sitemap whenever a post (any post_type enabled for the sitemap) is updated. This seems to irrelevant for dynamic sitemaps. I have a feeling this was done for static sitemaps and can be removed. If so, then my PR is not required.

**Comment by contactashish13** [comment]
@michaeltorbert @wpsmort please refer to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2160#issuecomment-456706271. Maybe this issue can be linked to the issue for removing static sitemap support?

**Comment by wpsmort** [comment]
Related to #541

**Comment by michaeltorbert** [comment]
Does this only happen for static sitemaps?

**Comment by wpsmort** [comment]
I will contact the customer to confirm if this only happens when he has static sitemap enabled.

**Comment by arnaudbroes** [comment]
I can confirm this only happens for static sitemaps.

**Comment by michaeltorbert** [comment]
@arnaudbroes Great that this is a bug only in static sitemaps. Hopefully the user can try simply using dynamic.
It's still work testing to see if this resolves the problem as well. Were you able to get a testing site up for it?
