### ISSUE TITLE
admin-ajax.php 403 Forbidden on (un)collapsing menu sections

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2162]
Check the JavaScript console. This was reported here - https://wordpress.org/support/topic/403-admin-ajax/#post-11122409. I wasn't able to track it down to a specific version. Looks like it's been there since we made them collapsable in 2.2.

**Comment by michaeltorbert** [comment]
@arnaudbroes Can you provide the steps to reproduce?

**Comment by arnaudbroes** [comment]
This was a bug in Chrome's dev version. Not on our end.
