### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by annayogi** [semperfiwebdesign/all-in-one-seo-pack#2163]
When the plug-in is activated, I keep getting an error when going to categories pages.
Fatal error: ob_start(): Cannot use output buffering in output buffering display handlers in /home3/fashior4/public_html/livingyogilife/wp-content/plugins/wordpress-seo/frontend/class-frontend.php on line 1813

My website: livingyogilife.com

**Comment by michaeltorbert** [comment]
That message is from the Yoast SEO plugin, not All in One SEO Pack. Deactivate that plugin and the error message should go away.

**Comment by arnaudbroes** [comment]
@annayogi this is the development repository for All in One SEO Pack; not Yoast SEO. If you're using Yoast SEO, then you need to post this issue in their development repository.
