### ISSUE TITLE
Parent elements overlap input fields in menus in latest Chromium dev build

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2164]
Reported here - https://wordpress.org/support/topic/403-admin-ajax/page/2/#post-11122737.

This is a CSS issue. The latest Chromium development build causes parent elements to overlap with their child input fields. When this happens, the user can't adjust any settings.

We need to find out whether this is just a bug in the Chromium dev build, or if we need to change our HTML and CSS.

In order to reproduce the problem, download and install the latest Chromium dev build here - https://www.chromium.org/chrome-release-channels. Go to the General Settings menu in the plugin on any given website and try to click on any of the checkboxes or type in any of the input fields. This won't work.

**Comment by arnaudbroes** [comment]
@wpsmort can you try the development build for Mac and see if this issue is also present there.

**Comment by arnaudbroes** [comment]
The latest stable version for Windows currently is 71.0.3578.98; the latest dev build for Windows is 73.0.3679.0.   

The next stable release (v72) is going to release on January 29th and v73 is scheduled for March 12th.

**Comment by wpsmort** [comment]
I tested this in Chrome v73 on Mac but everything worked fine.  The problem appears to only affect Windows.

**Comment by arnaudbroes** [comment]
The beta and dev builds are now at v73 and v74 respectively and the issue is no longer present, which means this was a bug in the v73 dev version of Chrome.
