### ISSUE TITLE
XML Sitemap - Line break in caption breaks sitemap

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2169]
Reported here - https://wordpress.org/support/topic/sitemap_post_1-is-blank-with-no-errors-in-the-console/

**Comment by wpsmort** [comment]
I tested this and was not able to reproduce the bug.  I tested back to version 2.9.1.1 and that version does have this bug but all versions after 2.9.1.1 do not.  I tested on my love site and did not get any errors from Google Search Console.

**Comment by arnaudbroes** [comment]
@wpsmort your love site? 😃
