### ISSUE TITLE
How to add several categories to the title?

### ISSUE THREAD

**Issue by Pivovody** [semperfiwebdesign/all-in-one-seo-pack#2172]
Hello. There is a question. How to put some rubrics in the title? One post can be in several categories.

**Comment by wpsmort** [comment]
@Pivovody This is a development repository and not a support forum.  There's no way to do this in the plugin settings but it may be possible with the API.  You can find documentation on our API filter for the title here - https://semperplugins.com/documentation/aioseop_title/
