### ISSUE TITLE
My Meta Description is disappear WHY?

### ISSUE THREAD

**Issue by ddv1976** [semperfiwebdesign/all-in-one-seo-pack#2173]
Show META but empty WHY?

See:
https://gyazo.com/f018a9a4b516fe7fc1bc1d9f944ecf12

I have tried everything ... and nothing works!

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. As this functionality does work, this is most likely a configuration issue or else something specific to your environment. 
You can visit our documentation here https://semperplugins.com/documentation/ or upgrade to All in One SEO Pack Pro for a Premium support license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
