### ISSUE TITLE
Create realistic large site for testing

### ISSUE THREAD

**Issue by contactashish13** [semperfiwebdesign/all-in-one-seo-pack#2176]
We may want to consider creating a test site on a droplet (maybe the same one that we use for grunt?) that has a large number of links and images so that we can use this for automated testing and continuous integration. Typically this instance should also contain posts and pages with all conceivable test scenarios (similar to what Steve has on his test instance(s)).

Here is how I foresee it would behave:

## one time activity (manual)
- create a WP instance, similar to the most heavily used sites that we are aware of
- create posts/pages with test scenarios
- install both current version of free and pro plugins
- install a REST service that will trigger the tests

## activity whenever a PR is created into development branch (or if this too heavy, whenever a PR is created into master)
- travis fires a remote trigger that causes the script to
- clone the WP instance 
- deploy development branch 
- run test cases
- collect the data and send it back to travis with a status indicating if it failed or succeeded

## activity whenever a new bug is reported (manual)
- create a post/page mimicking the conditions of that bug

I can start working on this once we discuss this as this does not require a PR. Suggestions/thoughts?

**Comment by michaeltorbert** [comment]
I love it. On a somewhat related note, we do a lot of manual testing before each release. It would be great to have some/most/all of that automated. @wpsmort should be able to provide a comprehensive pre-release testing list.

**Comment by arnaudbroes** [comment]
@michaeltorbert during the development meeting today we discussed and thought it might be a good idea to move one of the cloned client sites we have now over to Digital Ocean (of course with noindex enabled on the full site) as we have an excellent site available with tens of thousands of images and posts.

**Comment by michaeltorbert** [comment]
@arnaudbroes Sounds like a great idea. Do you want to take charge of that?

**Comment by arnaudbroes** [comment]
@michaeltorbert of course.

**Comment by arnaudbroes** [comment]
Steve and I decided to relocate our large test site (cosmopolitan-estate) to the sfwd-dev server and that should be fine for now.
