### ISSUE TITLE
Problem in XML sitemap caused by rsquo; character

### ISSUE THREAD

**Issue by media377** [semperfiwebdesign/all-in-one-seo-pack#2177]
Hi,

I have a problem in the All in One SEO plugin generated Sitemap :

Erreur d’analyse XML : entité non définie
Emplacement : http://www.jeremy-taburchi.com/sitemap.xml
Numéro de ligne 37, Colonne 40 :	image:captionDessin de presse de l`&rsquo;`eau sur mars</image:caption>

I tried to update everything, I changed the theme, deactivate (major) plugins, but nothing seems to fix that...

Thanks,

Jerry

**Comment by media377** [comment]
Some characters have disapeared from my previous post sorry (I add blankspace to & r s q u o ; ) : 

Hi,

I have a problem in the All in One SEO plugin generated Sitemap :

Erreur d’analyse XML : entité non définie
Emplacement : http://www.jeremy-taburchi.com/sitemap.xml
Numéro de ligne 37, Colonne 40 :	image:captionDessin de presse de l & r s q u o ; eau sur mars</image:caption>

The "& r s q u o ;’" seems to bug parsing.

I tried to update everything, I changed the theme, deactivate (major) plugins, but nothing seems to fix that...

Thanks,

Jerry

**Comment by wpsmort** [comment]
@media377 You are correct, this is caused by the use of the `&rsquo;` character.  However, I cannot reproduce this if I use the shortcut for that character.  I can reproduce this if I type the `&rsquo;` character out.  

@arnaudbroes Can you see if you can reproduce this on Windows using the Windows shortcut listed here - http://www.rsquo.net/

**Comment by media377** [comment]
Hi, thanks I will test this in the next hours, and come back there as soon after.

**Comment by arnaudbroes** [comment]
@wpsmort I'm not able to reproduce this when I copied the ’ character. The shortcut at rsquo.net doesn't make sense to me.

**Comment by media377** [comment]
Tried to change the character with its escape code but nothing changes.

**Comment by arnaudbroes** [comment]
@media377 do you have a keyboard with a French layout by any chance?

**Comment by media377** [comment]
Yes I have !

Le 2019-02-01 12:44, Arnaud Broes a écrit :

> @media377 [1] do you have a keyboard with a French layout by any chance? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/media377
[2]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2177#issuecomment-459696908
[3]

**Comment by arnaudbroes** [comment]
> Yes I have !

Are you able to tell me which keyboard key(s) you need to press for that character? I have an AZERTY keyboard as well, but a Belgian one. If ours doesn't support it, then I'll go ahead and order a cheap French version on Amazon.fr.

**Comment by media377** [comment]
the ' is under the "4" number and with the "{" sign

**Comment by arnaudbroes** [comment]
@media377 so I have that key as well on my AZERTY (BE), but it produces an apostrophe (&#8216;) instead of a right quotation character (&rsquo;). Can you confirm that the French layout produces an &rsquo; by default? If so, then I'll go ahead and order one.

**Comment by media377** [comment]
My keyboard produce correctly an apostrophe, and the sitemap should too ! There is a bug.

**Comment by arnaudbroes** [comment]
@contactashish13 user has responded.

**Comment by contactashish13** [comment]
@media377 unfortunately, `Dessin de presse de l'eau sur mars` contains the normal apostrophe and I can't see where on the page the special character is used. @arnaudbroes can you verify?

**Comment by wpsmort** [comment]
@contactashish13 I can only reproduce this if I actually use `&rsquo;` typed out exactly like that.  I cannot reproduce this any other way.

**Comment by contactashish13** [comment]
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2183

I have tested with all the characters on http://www.rsquo.net/

**Comment by wpsmort** [comment]
Reported again by Josh Broughton by email today.  This report was for the character `&trade;`.  I confirmed this is fixed in the PR.
