### ISSUE TITLE
Remove Yandex from bad bots default list

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#218]
I'm not sure that a large Russian search engine should be included in the list of bots to block by default, especially considering that we have a lot of Russian users.

**Comment by michaeltorbert** [comment]
@wpsmort What are your thoughts?

**Comment by michaeltorbert** [comment]
@wpsmort I've committed this change to the dev branch. We should do the full testing like we did for "DOC" to make sure it's removed from .htaccess and the custom list, no matter the settings they have and what's enabled. (It's basically the same code so it should work the same.)

**Comment by wpsmort** [comment]
This has been tested and is good to go.
