### ISSUE TITLE
Sitemap not displaying - no style information.

### ISSUE THREAD

**Issue by McG77** [semperfiwebdesign/all-in-one-seo-pack#2180]
- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Describe the bug**
What happened?
What did you expect to happen?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version:
 - All in One SEO Pack version:
 - PHP version:

**Additional context**

**Comment by McG77** [comment]
Hi,
I am using your software (Version 2.11) on 3 of my WP sites.  On missionarynightmare.com it is not working correctly. After creating the sitemap, I click on "view your XML sitemap."  I get a blank page with this line at the top:
**"This XML file does not appear to have any style information associated with it. The document tree is shown below."**

Can you please help?
Kind regards.

**Comment by wpsmort** [comment]
@McG77 Can you please provide us with an Administrator login for your site and FTP login for your server using the secure form below and we can take a look:

https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment]
@McG77 Thanks for the login information.  This appears to be a server issue.  When I take a backup of your site and restore it to a local server here the XML Sitemap works fine.  Can you tell me who is your hosting provider?

**Comment by McG77** [comment]
I'm hosted through Wealthyaffiliate.com on ns1.mywahosting.com

Thanks

**Comment by McG77** [comment]
I eventually contacted my host and they fixed it instantly. Thanks for pointing me in the right direction!

Kind regards
McG77

**Comment by arnaudbroes** [comment]
@McG77 good, thanks for letting us know.

**Comment by michaeltorbert** [comment]
@McG77 For the benefit of others reading this issue can you share the problem and solution?
