### ISSUE TITLE
Test compatibility with WordPress 5.1

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2188]
WordPress 5.1 RC1 has been released (https://wordpress.org/news/2019/02/wordpress-5-1-release-candidate/).  We need to test compatibility and update the readme to 5.1.

**Comment by michaeltorbert** [comment]
WP 5.1 RC2 is out https://wordpress.org/news/2019/02/wordpress-5-1-rc2/

**Comment by wpsmort** [comment]
I have tested compatibility with RC2 and found no problems.
