### ISSUE TITLE
Non-existing /sitemap_XXX URLs navigate to empty sitemap instead of 404

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2190]
Some examples:

https://semperplugins.com/sitemap__arnaudiscool.xml
https://semperplugins.com/sitemap_weneedmorearnaud.xml
https://semperplugins.com/sitemap_arnaudforpresident2020.xml

The underscore seems to matter as this works fine and redirects to a 404:
https://semperplugins.com/sitemapredirectto404.xml

**Comment by michaeltorbert** [comment]
Is this new?

**Comment by arnaudbroes** [comment]
I checked. Been since sitemap indexes were introduced.

**Comment by contactashish13** [comment]
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2272
