### ISSUE TITLE
Drop support for < WP 4.6

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2196]
We need to update the readme to reflect this.

**Comment by contactashish13** [comment]
I'm reopening this as there are many instances in the code where version checks are being done to support version lower than 4.6.

- https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L901
- https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L3300
- https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L3333
- https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php#L3748-L3752
-
