### ISSUE TITLE
possible jquery compatibility issue with WordPress 4.5

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#221]
In 4.5, AIOSEOP tabs on the edit post screen don't work quite right...

![screen shot 2016-04-18 at 2 15 27 pm](https://cloud.githubusercontent.com/assets/17364998/14614831/e224f852-0570-11e6-9283-a48ad06ae0e6.png)

**Comment by wpsmort** [comment]
This is tested and the fix is good.
