### ISSUE TITLE
Exclude list not reflecting RSS feeds

### ISSUE THREAD

**Issue by weirdnose** [semperfiwebdesign/all-in-one-seo-pack#2215]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Describe the bug**
Within my WordPress installation I want to be able to host a podcast. I want to publish this podcast to Google Podcasts. As is happens Google Podcast expects a RSS feed (see https://developers.google.com/search/docs/data-types/podcast).

When creating the podcast RSS with the plugin Seriously Simple Podcasting it will show fine within the browser. 

Unfortunately for this case, RSS feeds are set automatically to "noindex, follow" by the AIO SEO plugin. Since "noindex" is set, Google will not read the podcast RSS feed and show an error in Google Search Console (translated from german: "Not indexed. Found value noindex in HTTP header x-robots-tag".

I verified the response with Postman. If the AIO SEO plugin is disabled, no x-robots-tag is being provided.

Now to exclude the RSS feed from being processed within the plugin I added the podcast url to the exclude list within the settings of the SEO plugin.

This setting is ignored and the RSS feed will still have the x-robots-tag "noindex, follow" set. For Google Podcasts to process correctly it must be "index, follow" _or_ not set at all.

**To Reproduce**
1. Go to All In One SEO settings
2. Add podcast RSS to "Advanced settings" / "exclude pages" (translated from German)
3. Save settings
4. Pull RSS feed, still holds x-robots-tag "noindex, follow"

**Expected behavior**
I expected the exclude list in the advanced settings to also include RSS feeds.

**Screenshots**
-

**Version Info (please complete the following information):**
 - WordPress version: 5.0.3
 - All in One SEO Pack version: 2.11
 - PHP version: 7.2.14

**Additional context**
-

**Comment by arnaudbroes** [comment]
I was able to reproduce. This is still happening even when all noindex options have been disabled in the plugin.

**Comment by wpsmort** [comment]
We added noindex for RSS feeds in #356.  We should adda filter to remove this.  Requested again here - https://semperplugins.com/upgrading-to-2-9-seo-meta-disappear/#comment-24206
