### ISSUE TITLE
Convert - XML Sitemap - Remove "Only show 1000 posts per sitemap file" message

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2218]
Reported here: https://wordpress.org/support/topic/bugs-with-the-sitemap-please-fix-them/

> Even though you give the option to choose the split number, if I choose 2000 per split instead of default 1000, I am haunted by a pop-up message showing up everywhere annoying me to set it to 1000 because this is how its recommended! There is a little X but if I close the popup and simply navigate to a another page, it will show up again and again and again. There is no way to permanently disable this annoying notification to force me to have 1000 posts per split.

**Comment by arnaudbroes** [comment]
Shouldn't we also just make that notification appear once?

**Comment by wpsmort** [comment]
I cannot reproduce this behavior.  If I click the X to dismiss the message and then navigate away and then back again, the message does not come back.  I've tried but cannot make that message reappear.

@arnaudbroes Can you try to reproduce this.

**Comment by arnaudbroes** [comment]
I'll take a look. I believe it's been reported a number of times now.

**Comment by arnaudbroes** [comment]
@wpsmort I'm not able to reproduce this either.

**Comment by michaeltorbert** [comment]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/7550dd8f46ce436216288c3dada2e71ad9929f12/modules/aioseop_sitemap.php#L458 is where the magic happens. It is indeed written so that the message doesn't show again. While this will be obsoleted once we have the new notification system in place, perhaps @EkoJR or @contactashish13 could have a look at it and see if anything jumps out in our current notice code that could cause the notices to keep coming back.
Recall we used to have this problem with the WooCommerce notice a few years ago where it wouldn't go away for some people and we could never manage to reliably reproduce it.

**Comment by contactashish13** [comment]
@michaeltorbert the only reason that I see for this is the ajax method not being fired that updates the user meta. This may happen because of a JS error because of some other component. That is why the user is being redirected to another page when clicking on the 'X' instead of it firing the ajax method. Can we get a screenshot of the JS console?

**Comment by michaeltorbert** [comment]
@contactashish13 Unfortunately we're not able to reliably reproduce it on our site or a user's site.

**Comment by contactashish13** [comment]
I don't think we can reproduce it on another instance as it will be specific to the components installed on that site. The user says it happens all the time so it seems like it's consistent behavior for him. We can't get a screenshot of his console?

**Comment by vikingrunes** [comment]
Perhaps this notification should be removed altogether.... after all the user is being told that 1000 is recommended in the sitemap settings. Doesn't need to be alerted by yet another notification when he navigates away to other pages.

**Comment by michaeltorbert** [comment]
I'm actually not opposed to the idea of removing the notification. Anyone in favor of keeping it?

**Comment by vikingrunes** [comment]
silence is acceptance, so we should remove the notification :+1:

**Comment by EkoJR** [comment]
There is a WP Community constant, `DISABLE_NAG_NOTICES`, to handle this kind of stuff, and is also implemented in another branch. Plus, I thought current notice could be dismissed.

As a minor notification that does tend to get in the way, I do see others potentially finding it useful to know their site isn't being crawled; especially those who are new to WordPress. ...but I would agree being able to disable the admin notice would be ideal.

**Comment by michaeltorbert** [comment]
@EkoJR The ability to dismiss it is there, but periodically someone reports they can't dismiss it. We haven't been able to reproduce that behavior, and don't know why that would be the case.

**Comment by michaeltorbert** [comment]
We decided to simply remove the notification.

**Comment by michaeltorbert** [comment]
Now that we've created a new notifications class, we've just converted it.
