### ISSUE TITLE
Sitemap with "No Index"

### ISSUE THREAD

**Issue by Soldier4Life** [semperfiwebdesign/all-in-one-seo-pack#2224]
I just noticed a Google "coverage" issue in my webmaster console that I have never seen before. In doing a URL inspection for the /sitemap.html page, it says the page is not being indexed because it has 'noindex' detected in 'robots' meta tag. Not sure if this is deliberate, but I have never seen it come up before and I see no way to control it. I have not enabled a noindex anywhere on the site.

**Comment by wpsmort** [comment]
@Soldier4Life Can you provide the URL for this page and can you confirm that you mean sitemap.html and not sitemap.xml.

**Comment by Soldier4Life** [comment]
Hi there... It is just the HTML version causing the error. I disabled the "create HTML version" in the SEO settings and resubmitted the site map to Google. Looks like it is still on my server. I may need to manually remove it.

aaclassicexteriors.com/sitemap.html

-------- Original Message --------

**Comment by wpsmort** [comment]
All in One SEO Pack doesn't create an HTML sitemap or have an option for "create HTML version".  I checked your site and your XML Sitemap is being generated by Google XML Sitemaps plugin so you may have contacted the wrong company.

**Comment by Soldier4Life** [comment]
So sorry for the confusion I must have hit the wrong support link. I'll contact the other guys thank you for setting me straight.

-------- Original Message --------
