### ISSUE TITLE
Make upgrade to pro action link more visible

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#223]
different color (red?), bold, etc

![screen shot 2016-04-19 at 6 44 56 pm](https://cloud.githubusercontent.com/assets/17364998/14658021/1251def2-065f-11e6-8608-23a127d9437b.png)

**Comment by nishant981** [comment]
We have also  worked on pro action link. pls see the below attached screenshot.
![2](https://cloud.githubusercontent.com/assets/13958896/14843159/631dc1fe-0c6b-11e6-87ba-13b261dfa721.png)
