### ISSUE TITLE
Rename, Remove /cateogory/ prefix from URL

### ISSUE THREAD

**Issue by vikingrunes** [semperfiwebdesign/all-in-one-seo-pack#2230]
Please add an option to remove or rename the word "CATEGORY" from URLs in AIOSEOP general settings. This option is provided by YOAST and I think its a very good idea. This can even be added to tags.

Here is an example for a typical WordPress category URL:
www.example.com/category/movies/
add an option to hide category form URL and transform it like this:
www.example.com/movies/
Or maybe others would like to rename them into let's say...  topics:
www.example.com/topics/movies/

Here's how the option looks like in YOAST:
Category URLs
Remove the categories prefix

Category URLs in WordPress contain a prefix, usually /category/, this feature removes that prefix, for categories only.

**Comment by michaeltorbert** [comment]
Dupe https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/665
