### ISSUE TITLE
Add "Use Static Homepage" to Social Meta menu

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2238]
As seen on Vivian C.'s website on 03-02-2019.

When the "Use Static Homepage" setting is enabled in the General Settings menu, then the plugin is outputting the SEO data that can be found in the meta box of the relevant page. 

However, the Open Graph data for the homepage still has to be set in the Social Meta menu. That doesn't make sense. We should either (1) add the same setting in the Social Meta menu; or (2) make sure that, when it's enabled in the General Settings menu, it's outputting the Open Graph data that can be found in the meta box of the relevant page.

**Comment by michaeltorbert** [comment]
@wpsmort Make the necessary notes here about why this will be closed and create the new issue.

**Comment by wpsmort** [comment]
We don't want to add a new option for this as we're removing the related option (Use Static Front Page Instead) from the General Settings - see issue #495.

Instead we want to do what we're doing with the home page SEO settings and hide the fields based on what's set under Reading Settings in WordPress.  We have issue #515 open for this. I am therefore closing this issue.
