### ISSUE TITLE
Undefined index: aiosp_opengraph_options in aioseop_opengraph.php on line 1302

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2239]
As seen on Olivier S.'s website who reported this on 03-02-2019 in the Premium Forums.

> Notice: Undefined index: aiosp_opengraph_options in .../wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_opengraph.php on line 1302

https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/php-error-message/

**Comment by wpsmort** [comment]
I believe this is a dupe of #2158 which was fixed in PR #2158

**Comment by arnaudbroes** [comment]
I asked Olivier in the Premium Forums which version he is using.

**Comment by michaeltorbert** [comment]
He says in there it's Pro 2.13.

**Comment by michaeltorbert** [comment]
Can you reproduce this?

**Comment by arnaudbroes** [comment]
I can't reproduce it and I don't see any reason why this error would appear since $type doesn't seem to be empty in any scenario.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/3d46a348779d90594ce02f4ed6537b851c07ec2c/modules/aioseop_opengraph.php#L1307-L1321

I'll go ahead and close this issue for now since no one else has reported this.

**Comment by arnaudbroes** [comment]
I've asked Olivier in the Premium Forums for access to his website so we can troubleshoot the issue there since we're not able to reproduce it on a test server.

**Comment by michaeltorbert** [comment]
Closing as we've not received a response from the one person who reported it.
