### ISSUE TITLE
Add &nbsp; to point out space to translators

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2242]
![image](https://user-images.githubusercontent.com/18156697/53683423-eacb5800-3d00-11e9-9b60-802d534bc255.png)

**Comment by onetarek** [comment]
How about print a space in new line instead of adding &nbsp; ?
Below is the proposed code : 
`echo aiosp_common::get_upgrade_hyperlink( 'side', __( 'Pro Version', 'all-in-one-seo-pack' ), __( 'CLICK HERE', 'all-in-one-seo-pack' ), '_blank' );
								echo ' ';//extra line to print a space here
								echo __( 'to upgrade to Pro Version and get:', 'all-in-one-seo-pack' );`

**Comment by arnaudbroes** [comment]
Duplicate of #825.
