### ISSUE TITLE
"Title Settings" section should be called "Rewrite Settings" section

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2244]
Imo this should be called "Rewrite Settings" section because that section also controls the format for the meta description.

Related to #2245.

**Comment by michaeltorbert** [comment]
I could see this. I'd like to hear what anyone else has to say though.

**Comment by wpsmort** [comment]
I'm not sure Rewrite Settings is a good title as I think it may be confusing to many users.  How about Search Appearance instead?

**Comment by arnaudbroes** [comment]
Or "Rewrite Format Settings"? Now that the rewrite titles option has been removed.

**Comment by wpsmort** [comment]
I still don't like that title, it's not intuitive for novices.  How about either of these titles:

- Title / Description Settings
- Search Appearance

**Comment by michaeltorbert** [comment]
I like Search Appearance but that maybe too broad, and probably includes other stuff from other sections.
Title / Description Settings is pretty straightforward.

**Comment by arnaudbroes** [comment]
I agree with the latter. Let's use that.
