### ISSUE TITLE
Remove meta itemprop="image" from social meta markup

### ISSUE THREAD

**Issue by Brain8torm** [semperfiwebdesign/all-in-one-seo-pack#2246]
![2019-03-05_1-12-30](https://user-images.githubusercontent.com/571307/53767759-cf6e7180-3ee7-11e9-96df-2573c45f30ae.png)
Hi!
The new version of All in One SEO Pack has an error as a result of checking the validity of the code in W3C in The social meta functionality. Before updating the `itemscope itemtype="plugin http://schema.org/WebSite"` was added to the html tag, so the code `<meta itemprop= "image" content=" https://site.com/wp-content/uploads/2019/02/social.png" / >` displayed in the head section was valid.

After plugin update code `itemtype="http://schema.org/WebSite"` moved to the tag body and accordingly `itemprop= "image"` does not apply to anything and ceased to be valid.

**Comment by wpsmort** [comment]
I've edited the title of this issue to better reflect the action required here.

The meta itemprop="image" was added for Google+ but as that is going away soon (see #2121) we should be able to remove this meta tag.  This was the article we referred to when we added the meta tag - https://moz.com/blog/meta-data-templates-123

**Comment by wpsmort** [comment]
This was removed in PR #2390

**Comment by EkoJR** [comment]
Confirming it was removed, and closing this issue.
