### ISSUE TITLE
PHP Parse error in aioseop_class.php on line 1107

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#225]
PHP Parse error:  syntax error, unexpected '$taxes' (T_VARIABLE), expecting function (T_FUNCTION) in /Users/stevemortiboy/Sites/aioseop/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 1107

**Comment by michaeltorbert** [comment]
@wpsmort Any idea what version this was? That line number doesn't mean anything anymore, and I've looked at every use of $taxes and haven't found a problem. This almost certainly means that the PHP parser found a variable being used outside of the constructor or some other function in the class, but that wouldn't be an intermittent error, it would be persistent, which makes me wonder if this just popped up when changing around some code.

**Comment by wpsmort** [comment]
@michaeltorbert This was either in v2.3.4 or v2.3.4.1.

**Comment by michaeltorbert** [comment]
@wpsmort Do you know how to reproduce this?

**Comment by wpsmort** [comment]
We're unable to reproduce this error at this time so we agreed to close this.
