### ISSUE TITLE
Create comprehensive release testing doc

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2252]
This should probably go in the github wiki, it should be step by step, etc so that testing doesn't depend on one person. Anyone off the street should be able to go step by step and test. 

Once completed, also add the list to #1980 so we can write tests.

**Comment by arnaudbroes** [comment]
Here's what we have now - https://docs.google.com/spreadsheets/d/1zaO5b4XabWiL_kbTa59SnvUadArtyZ5A153cWirPvhU/edit#gid=0

**Comment by wpsmort** [comment]
The doc is complete and can be viewed here - https://docs.google.com/spreadsheets/d/1RMeC_LDZd9jzbcuKmCadRYOR4xvVJy097FP01hyloO8/edit?usp=sharing
