### ISSUE TITLE
theme astra

### ISSUE THREAD

**Issue by urvesh18** [semperfiwebdesign/all-in-one-seo-pack#2267]
Please fill out this form as completely as possible so that we can help you more quickly.

- [ ] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [ ] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**

**Describe the bug**
What happened?
What did you expect to happen?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version:
 - All in One SEO Pack version:
 - PHP version:

**Additional context**

**Comment by wpsmort** [comment]
Closing as there's no information
