### ISSUE TITLE
"PHP Compatibility Checker" Reports Errors When Checking PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by Nupee** [semperfiwebdesign/all-in-one-seo-pack#2273]
FILE: /home/NAME/public_html/NAME/blog/wp-content/plugins/all-in-one-wp-migration/functions.php
-----------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------
 1402 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
-----------------------------------------------------------------------------------------------------------------------

FILE: /home/NAME/public_html/NAME/blog/wp-content/plugins/all-in-one-wp-migration/lib/vendor/servmask/database/class-ai1wm-database-mysql.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 9 ERRORS AFFECTING 9 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  39 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
  49 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
  58 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
  67 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
  76 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
  86 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
  96 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
 106 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
 116 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by michaeltorbert** [comment]
That's a different plugin, all-in-one-wp-migration, not All in One SEO Pack.
