### ISSUE TITLE
Use jQuery Tabs on Edit Post screen

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2274]
From #1715:

I see that we are using a bespoke implementation of tabs where as now we can use https://jqueryui.com/tabs/ as jqueryui is being used extensively in other parts of the plugin as well.

**Comment by contactashish13** [comment]
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2290

**Comment by wpsmort** [comment]
@contactashish13 I don't like the design of the new tabs.

I'd like to see us improve on how the tabs currently look.  Here is an example of a design I like that's simple, clean and looks good - https://tympanus.net/Blueprints/FullWidthTabs/

**Comment by contactashish13** [comment]
I'm reopening this in view of https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2290#issuecomment-475834342
