### ISSUE TITLE
Write release post

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2278]
-make sure to mention https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/495
-For removing the compression option, make sure in the post we point out that we're only removing the option, that compression still works ie you can go to either url

We should probably also have a mailing about it.

**Comment by arnaudbroes** [comment]
@wpsmort please review the release post and let me know if something is missing - https://semperplugins.com/wp-admin/post.php?post=4834&action=edit

**Comment by wpsmort** [comment]
@arnaudbroes Here are some additional items for the release post:

- We now default to Sitemap Indexes.  We should state why we did this and that we strongly recommend existing users enable this with pagination set to 1000.  Add a nice visual that shows users how to do this.
- The sitemap indexes now display content in reverse chronological order and why (see #2217).
- We've removed Sitemap Compression but the old URLs should redirect.  We do strongly recommend users submit the uncompressed sitemap URL to Google, Bing etc.
- We've removed all the settings to do with Google+ and why.
- Lots of translation improvements.
- Support for Rank Math in the SEO Data Importer
- We've dropped support for WordPress 4.6 and lower.

**Comment by arnaudbroes** [comment]
@wpsmort I've added the first four items to the release post but I'd personally wouldn't include the others and only add them to the changelog since the release post is already quite bulky as it is and I find them to be of less importance. I'll put them in if you'd still like me to.

**Comment by wpsmort** [comment]
I made some changes to the post and published it - https://semperplugins.com/all-in-one-seo-pack-3-0/
