### ISSUE TITLE
Improve design of tooltips

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2283]
Our new tooltips are awesome! However I think they could be improved so that they're even more attractive.
<img width="733" alt="Screen Shot 2019-03-11 at 8 55 22 PM" src="https://user-images.githubusercontent.com/17364998/54167513-671c1480-4440-11e9-890f-ebcaefc384e4.png">

**Comment by arnaudbroes** [comment]
After we've improved the look, we should also go through all tooltips and add line breaks or other formatting where needed.

**Comment by arnaudbroes** [comment]
Here's what I would do as far as the styling of the tooltip and its content goes:
![image](https://user-images.githubusercontent.com/18156697/57719931-c10ea580-764e-11e9-95b0-31b6ea39fc36.png)

What I would also like to do is add the setting name/title to all tooltips so they look like this:
![image](https://user-images.githubusercontent.com/18156697/57719986-e7ccdc00-764e-11e9-8fe9-6c3e67aa5b69.png)

@wpsmort @michaeltorbert let me know what your thoughts are.

**Comment by wpsmort** [comment]
I like the proposed design and changes. The only additional change I'd suggest is adding a triangle to the top left of the bubble that points to the help icon.  See the example below of the WooCommerce tooltips:

<img width="237" alt="Screen Shot 2019-05-14 at 2 50 01 PM" src="https://user-images.githubusercontent.com/17548525/57723973-ccb29a00-7657-11e9-946b-6144339df5bf.png">

**Comment by arnaudbroes** [comment]
I tried implementing Steve's suggestion and although it looks great, we can't implement it. If a tooltip doesn't fit on the screen (for example when someone wants to view a tooltip for an option at the bottom of the screen), then it is displayed above, and we can't dynamically adjust the pointer in that scenario.
