### ISSUE TITLE
XML Sitemap - Excluding category also excludes posts in the category

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2285]
We discovered this bug when responding to https://wordpress.org/support/topic/exclude-parent-category-from-sitemap/

If you exclude a category using the checkboxes under XML Sitemap > Excluded Items, then all posts in that category are excluded from the sitemap.

If you exclude a parent category, then all posts in that category and all posts in the child categories are also excluded.

This has been present since we introduced the XML Sitemap feature in v2.0.3.  We need to discuss what we want the functionality to be here:

- Do we want to exclude posts in the category or just the category?
- Do we consider the exclusion of posts in child categories a bug or intended behavior?

**Steps to reproduce:**

1. Create a parent category and a child category
2. Populate both categories with at least one post
3. Go to the XML Sitemap module and view the sitemap to verify all your categories and posts are present
4. Exclude the parent category by checking the box under Excluded Items
5. View the sitemap, the parent category should not be present which is correct, but you'll also see that the posts in the parent and child categories are not present which is incorrect.

**Comment by michaeltorbert** [comment]
The documentation reflects this functionality.

**Comment by arnaudbroes** [comment]
> The documentation reflects this functionality.

Yes, I think we already discussed this and decided that posts assigned to taxonomy terms should also be excluded.
