### ISSUE TITLE
twitter:title should be truncated

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2296]
Whilst discussing #808 with @contactashish13, we agreed that we should open a separate issue for truncating the twitter:title.

Twitter states that the title should be a maximum of 70 characters - https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.html

This does not, and should not, affect the og:title meta tag as Facebook does not truncate the title. I confirmed this with a title that was over 100 characters long and Facebook displayed the entire title.

@contactashish13 As discussed, we should have a filter that enables users to disable truncation of the twitter:title meta tag.

Related to #2139

**Comment by contactashish13** [comment]
@wpsmort as discussed PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2297 addresses this

**Comment by arnaudbroes** [comment]
This also affects the Twitter:description which is truncated to 200 character (maximum). Just adding a note here because this was confusing me.
