### ISSUE TITLE
Store the version in the database

### ISSUE THREAD

**Issue by mrtorbert** [semperfiwebdesign/all-in-one-seo-pack#23]
https://make.wordpress.org/core/2010/10/27/plugin-activation-hooks-no-longer-fire-for-updates/

**Comment by dougalcampbell** [comment]
Added methods `version_update()` and `do_version_updates()`. A new option called `update_version` will be tracked, and compared against the currently running plugin version. If the plugin is newer than the last stored `update_version`, then it will call `do_version_updates($old_version)`, which can then perform any maintenance tasks needed between the old version and the current version.

**Comment by mrtorbert** [comment]
@dougalcampbell Make sure this can distinguish between pro and free. Keep in mind that many people upgrade to pro by activating pro while free is still active, and free only deactivates on admin_init (even then, only in the dev version, 2.3.2.3 and lower doesn't even do this)... so we'll need to test upgrading from various versions, including from various version of free to new free and various versions of free to pro (and maybe various versions of pro to newest pro?)
