### ISSUE TITLE
Add current_month and current_year to title formats

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2301]
Requested by Ron by email today.

Add new macros for current_month and current_year to title format fields for Page Title, Post Title and Description Format.

**Comment by michaeltorbert** [comment]
We already do current year in #1754

**Comment by michaeltorbert** [comment]
On second thought. Since we're localizing this, I can see a need for someone who has a site's backend in their native language for ease of use, but wants the front-end in English for wider reach.
Maybe we should have something like %current_month% and %current_month_i18n%?

**Comment by arnaudbroes** [comment]
It's an interesting thought, although I don't have a strong opinion on it. @wpsmort?

**Comment by wpsmort** [comment]
Good point.  I think this would be a good idea.
