### ISSUE TITLE
Make it easy to test PRO features in the free plugin with minimal changes

### ISSUE THREAD

**Issue by contactashish13** [semperfiwebdesign/all-in-one-seo-pack#2305]
I thought about this change while working on https://github.com/semperfiwebdesign/aioseop-pro/issues/34. 

The traditional way of testing PRO features are:

**Method 1**
- make changes in the PRO plugin code
- once everything works, migrate the code to the equivalent FREE files
- be careful **not to forget** anything

**Method 2**
- copy the PRO headers to the FREE plugin
- change value of `AIOSEOPPRO` to true
- copy `pro` folder to the free plugin
- test

**Method 3**
- change value of `AIOSEOPPRO` to true
- copy `pro` folder to the free plugin
- test

The problems with method 1 are the below:
- forgetting the files one worked on (because they are in the pro plugin folder during development)

The problems with method 2 are the below:
- the headers might be checked in accidentally

The problems with method 3 are the below:
- does not work because the free plugin is automatically deactivated 

I discovered that instead of the above, we can instead make subtle quantifiable changes to the FREE plugin so that it behaves like the PRO plugin.

This issue and its PR deal with those small changes that will help in development till both plugins are merged.

**Comment by contactashish13** [comment]
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2306

comments welcome @semperfiwebdesign/aioseop-core-committers 

The steps to test PRO features using the FREE plugin are:
- change value of `AIOSEOPPRO` to true
- change value of `AIOSEOPPRO_MIMIC` to true
- copy `pro` folder to the free plugin
- test

The advantages I see are:
- 2 switches that need to be switched on
- no copying the header
- no forgetting files in some other folder
- no inadvertent commits or forgetting of commits

**Comment by michaeltorbert** [comment]
Even better is to use action/filter hooks so that Pro functionality doesn't require changes in free.
