### ISSUE TITLE
Add doc for new disable_meta_tag_truncation filter

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2308]
In issues #808 and #2296 we added a new filter as follows:

```
add_filter( 'aiosp_opengraph_disable_meta_tag_truncation', 'aiosp_opengraph_disable_meta_tag_truncation', 10, 4 );
function aiosp_opengraph_disable_meta_tag_truncation( $disable, $network, $meta_tag, $network_meta_tag ) {
	switch ( $network_meta_tag ) {
		case 'og:description':
			$disable = true;
			break;
	}
	return $disable;
}
```

We need to add this to our API documentation.

**Comment by michaeltorbert** [comment]
create issue for phpdoc

**Comment by arnaudbroes** [comment]
@wpsmort please review and then publish the doc - https://semperplugins.com/?p=4819&post_type=documentation&preview_id=4819

**Comment by wpsmort** [comment]
I've reviewed the doc and published it - https://semperplugins.com/documentation/aiosp_opengraph_disable_meta_tag_truncation/
