### ISSUE TITLE
Update doc for aiosp_opengraph_meta filter

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2309]
In PR #2297 we added two new parameters to the aiosp_opengraph_meta filter:

string $v The meta tag with the network name prefixed. This is not always $network:$meta_tag.

array $extra_params Extra parameters that might be required to process the meta tag.

We should update the API doc here - https://semperplugins.com/documentation/aiosp_opengraph_meta/

**Comment by michaeltorbert** [comment]
create issue for phpdoc

**Comment by wpsmort** [comment]
The documentation has been updated.

@arnaudbroes to do the phpdoc

**Comment by arnaudbroes** [comment]
phpdoc has already been updated by the developer.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/07c77b9c68930c13567f49e93dcdbb65109fa03f/modules/aioseop_opengraph.php#L1569-L1580
