### ISSUE TITLE
Plugins -All In One SEO Pack

### ISSUE THREAD

**Issue by yonnsmit** [semperfiwebdesign/all-in-one-seo-pack#2316]
| Documentation \| Support Forum \| SEO Settings \| Deactivate | Out-of-the-box SEO for your WordPress blog. Features like XML Sitemaps, SEO for custom post types, SEO for blogs or business sites, SEO for ecommerce sites, and much more. More than 50 million downloads since 2007.Version 2.12 \| By Michael Torbert \| View details \| Feature Request/Bug Report
-- | --
How to make my plugin settings on this plugin :1 Free , 2-  SEO Settings ? 3- Feature Request/Bug Report ?

**Comment by arnaudbroes** [comment]
This isn't something we can help you with.
