### ISSUE TITLE
General - Update HTTP hyperlinks to HTTPS equivalents

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2328]
Requested here on 4/7/2019 - https://wordpress.org/support/topic/plugin-update-needed-to-correct-url-requests/

> To ensure the URL requests don’t delay page load speed, any old HTTP URL requests need to be removed and replaced with their correct HTTPS URL protocols.
> 
> These two at least,
> 
> http://schema.org
> http://www.w3.org/2000/svg
> 
> The above two domains are no longer HTTP, they are HTTPS. They upgraded, so this plugin needs to correct their coding to coincide with those changes.
> 
> Unfortunately, some domains, like http://ogp.me/ns# , are sorely outdated. Their website is still HTTP and have not upgraded to HTTPS. – yea sure, so many themes and plugins developers have to update their files when Open Graph (ogp) does update to HTTPS, but hey, that is progress.

**Comment by wpsmort** [comment]
The only one we need to change is http://ogp.me/ns# here:
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/be9b965d1179b443b8485c97e384cd8b306283b9/modules/aioseop_opengraph.php#L1053
