### ISSUE TITLE
NO Robot.txt EDITOR

### ISSUE THREAD

**Issue by maramofilms** [semperfiwebdesign/all-in-one-seo-pack#2331]
Hello,
I've got a little problem. That would be that I do not see the Robots.txt editor! I can not edit that, so my page will not be indexed on google. Although I have turned off, I get the message that is in the robots txt still Disallow. WHERE DO I FIND THE ROBOTS.TXT FILE? HOW CAN I EDIT THEM ???

 Thank you!

**Comment by wpsmort** [comment]
This is not a support forum, this is a development repository.  
You can find documentation here https://semperplugins.com/documentation/
or access premium support here https://semperplugins.com/all-in-one-seo-pack-pro-version/
