### ISSUE TITLE
Add field for Amazon OneLink id

### ISSUE THREAD

**Issue by MikeLeddy** [semperfiwebdesign/all-in-one-seo-pack#2333]
It would be very cool if you added a feature to include Amazon OneLink functionality within All in One SEO in much the same way as site ownership verification & google analytics code can be added.  Thanks in advance.

**Comment by michaeltorbert** [comment]
I'm closing this as Amazon OneLink is for affiliate revenue, and is unrelated to an SEO plugin.

**Comment by MikeLeddy** [comment]
Thanks Michael.  I hadn't thought of that but of course you are right.  I
guess I've got so used to using All in One SEO as the one app to rule them
all - google, bing, social media accounts etc that it seemed a logical
place to put another identifying / tracking code.  Thanks again.

**Comment by michaeltorbert** [comment]
@MikeLeddy What's more likely is that we could add an option for additional headers to your site, similar to the existing ones for specific pages. https://semperplugins.com/documentation/all-in-one-seo-pack-advanced-settings/#additional-post-headers
