### ISSUE TITLE
PHPCS checks for strict comparsion

### ISSUE THREAD

**Issue by contactashish13** [semperfiwebdesign/all-in-one-seo-pack#2335]
All PRs will fail grunt because of the new release of WPCS until these rules are excluded or addressed.

e.g.

![image](https://user-images.githubusercontent.com/12953439/56078350-9d183400-5e04-11e9-83d4-30c03595586a.png)

**Comment by michaeltorbert** [comment]
@contactashish13  So my understanding is that this PR (now merged) will keep subsequent PRs from failing, but we still need to apply the fixes for the new standards?

**Comment by contactashish13** [comment]
@michaeltorbert yes thats correct. We still need to decide if we need to apply the fixes for the new rules or let them be excluded.

**Comment by michaeltorbert** [comment]
Is there any reason we wouldn't want to apply all the fixes?

**Comment by contactashish13** [comment]
Yes thats the only reason to not apply the fixes right now.

**Comment by michaeltorbert** [comment]
As soon as all the existing PRs are cleared (our first priority) we should do this.

**Comment by michaeltorbert** [comment]
This is already fixed.
