### ISSUE TITLE
404 error when viewing Video XML Sitemap 

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2339]
Whilst testing PRs #2334 and https://github.com/semperfiwebdesign/aioseop-pro/pull/474, I found that I got a 404 error when clicking on the link to view the Video XML Sitemap.

I tested back and found that this bug originates in this commit in he 3.0 branch of free - https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/5a2d96a76cd8b4bd21526e239b367a5513e49c2c

**Comment by EkoJR** [comment]
This is a Pro issue

**Comment by arnaudbroes** [comment]
@EkoJR good catch. I'll do it, but feel free to close the issue after duplicating it to the correct repo.
