### ISSUE TITLE
XML sitemap is not compatible to Google requirements

### ISSUE THREAD

**Issue by gvburg** [semperfiwebdesign/all-in-one-seo-pack#2343]
Dear support and dear Michael

There have been similiar issues, which have been discarded because of informalities. I try to learn from your demands, and want to open up the issue again.
Our company's website is [https://www.one-pm.com/](url) and your XML of course is under /sitemap.xml . The plugin will be active whenever you check it.
So Google does not recognise your XML configuration, because let me cite Google on their Search Console https://search.google.com/u/1/search-console/sitemaps: 

"Sitemap can be read, but has errors
Invalid URL **(155 instances)**: This is not a valid URL. Please correct it and resubmit.
Examples
[...]
URL: /en/one-wealth-en/ (Line 17)
Parent tag: url, Tag: loc
[...]"

It simply would be an option you could add, to add the complete URL instead of the redirect link, in this example it would be "https://www.one-pm.com/en/one-wealth-en/" instead of your choice of putting "/en/one-wealth-en/" as the URL. I would still recommend to put it as a opt-out option to have the full URL, because I cannot tell with other search engines.

Please write back if you have more questions or other things are unclear. Thanks

**Comment by michaeltorbert** [comment]
@gvburg You can add this to your secret list of "similar issues" that are closed. Feel free to try again if you want to fill out the bug report form with the information we'd need about your specific issue.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by gvburg** [comment]
@michaeltorbert Maybe you should tell in advance about the bug report template, even though your suggestion is completely unnecessairy in my case. Every necessairy information is given by me here already, and if I was not clear: The XML feature is broken, and even though 5 people reported on that issue, you closed all of their issues including mine.

Following your recommendation, I filled out a bug report for the broken feature. See you over there:
[https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2344](url)

**Comment by michaeltorbert** [comment]
> Maybe you should tell in advance about the bug report template

It's there automatically when you create an issue. This is functionality built into Github.

> even though your suggestion is completely unnecessairy in my case

No, it's absolutely unnecessary. Even now, you've still failed to provide steps to reproduce your issue.

> The XML feature is broken

No it's not. Your website has an issue. I've don't recall ever having seen this behavior. Hence the need for you to provide steps to reproduce.

> even though 5 people reported on that issue, you closed all of their issues including mine.

Please provide the 5 URLs.

**Comment by gvburg** [comment]
> It's there automatically when you create an issue. This is functionality built into Github.
You are actually wrong. The link you provide on your own plugin overview on wordpress is the following: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new ... as there is no additional argument like "&template=bug_report.md" as you stated in your previous answer, this is again smth you did not provide properly.
> No, it's absolutely unnecessary. Even now, you've still failed to provide steps to reproduce your issue.
I assume you meant "necessary", and you still fail to understand, that the steps to reproduce ARE just to install the plugin. There is no setting in "XML sitemap" feature for this issue, but I'll go on an complete the report. Making multiple reports is asinine and closing them right away too.
> No it's not. Your website has an issue. I've don't recall ever having seen this behavior. Hence the need for you to provide steps to reproduce.
You show me a website where it does not create indirect URLs but instead full URLs in those .xml files, and I will gladly accept that you are right. Until then, don't tell me you know the behaviour of your software, if you go harsh on your customers for helping out.
> Please provide the 5 URLs.
I'll gladly do so, if you cannot see yourself:
- https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2040#issue-377189846
- https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2041#issue-377324039
- https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2042#issue-377347396
- https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1725#issue-329136260
- and like I said including myself: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2344#issue-436484534

**Comment by michaeltorbert** [comment]
> You are actually wrong.

Clicking the "new issue" link takes you to a page where you choose which type of issue template to use. You're correct that the link in our plugin predates this Github functionality. I'll open an issue to change that.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new/choose

> You show me a website

Literally every other website AIOSEOP is installed on I've ever seen.

> I'll gladly do so

Not a single one of those is reporting the same issue, and the one still using AIOSEOP definitely doesn't have the same behavior as yours. https://www.propertyinside.id/sitemap.xml
