### ISSUE TITLE
"Title Tag for a Page" problem

### ISSUE THREAD

**Issue by alexavd1** [semperfiwebdesign/all-in-one-seo-pack#2348]
Hello, after update a plugin, i have a problem: 
Although the option "Display site name" is disabled - it still shows.

In Title Settings - Title Format Fields  section i entered next text: %page_title%
so it have to be show without "My Site Title" but it shows anyway
![AIOS_01](https://user-images.githubusercontent.com/49962591/56695033-d0a26a80-66f0-11e9-81ad-c6a381c0e801.jpg)
![AIOS_02](https://user-images.githubusercontent.com/49962591/56695034-d0a26a80-66f0-11e9-95cd-612fa0bba2da.jpg)

**Comment by arnaudbroes** [comment]
@alexavd1 Properties aren't pages but custom post types.
