### ISSUE TITLE
Conflict with Tabs - Responsive Tabs with Accordions plugin

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2359]
**Provide the relevant URL(s) here**
Reported: https://wordpress.org/support/topic/content-not-showing-19
https://wordpress.org/plugins/vc-tabs/

**Describe the bug**
Content isn't showing on any of the tabs created by the "Tabs - Responsive Tabs with Accordions" plugin.

**To Reproduce**

...

**Comment by arnaudbroes** [comment]
Not a bug. "Run Shortcodes In Autogenerated Descriptions" needs to be disabled.
