### ISSUE TITLE
DB migration to remove deprecated %blog_xxxx% macros

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2361]
%blog_title% and %blog_description% are deprecated since we've added the %site_title% and %site_description% macros, but at some point we'll probably want to do a migration.

**Comment by michaeltorbert** [comment]
No, we should continue to support %blog*% as a deprecated macro. 

Database changes to post and metadata can cause significant and irreversible problems if done incorrectly, and should only be done in rare cases as a last resort. A deprecated macro isn't one of them.
