### ISSUE TITLE
Add Yandex and Baidu Webmaster Tools verification documentation

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2363]
Now that #875 has been addressed, we need to add two documentation pages:

https://semperplugins.com/documentation/yandex-webmaster-verification/
https://semperplugins.com/documentation/baidu-webmaster-verification/

**Comment by arnaudbroes** [comment]
@wpsmort both have been written. Can you review them?

**Comment by wpsmort** [comment]
@arnaudbroes I have reviewed both documents and they are good to go.

**Comment by arnaudbroes** [comment]
Documentation has been published.
