### ISSUE TITLE
Allowed length of site title and description

### ISSUE THREAD

**Issue by sbiese** [semperfiwebdesign/all-in-one-seo-pack#2370]
I'm very disappointed that as long as Google has increased the limits for site titles and descriptions, I have to push your program into the red constantly since I know the limits have been increased. It's still an uneasy feeling seeing all that red. When will All In One SEO update these values?

https://user-images.githubusercontent.com/10327059/57000657-af270000-6b82-11e9-9e12-312382e97434.png

**Comment by arnaudbroes** [comment]
@sbiese I'm not sure why you'd think the character limit is any higher than that. 

Google briefly changed the maximum length of meta descriptions last year, which we adjusted in our plugin accordingly, but after a few months they decided to revert the change, which we then also did.
The current title limit is still set at 600 pixels (which roughly corresponds with 60 characters) and the meta description hasn't changed either.
