### ISSUE TITLE
Use WP 5.2 Gutenberg field styling for our meta box/menus

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2376]
The latest release of Gutenberg affects our meta box styling (currently only for Posts and Pages as Steve correctly pointed out) and it seems like a big improvement. We should consider whether we want to replicate Gutenberg's styling across all our menus and meta boxes.

![image](https://user-images.githubusercontent.com/18156697/57101740-d6e7a680-6cef-11e9-9ed2-1c4516ae9028.png)

This only happens when the Gutenberg plugin is installed so I've asked in #core-editor on Slack what the difference between the plugin and built-in version is at this point.

**Comment by wpsmort** [comment]
It's actually version 5.4 of the Gutenberg plugin released on April 3rd where they started overriding the styles of meta boxes added to the Edit Post / Edit Page screen by plugins.  I verified that this happens with meta boxes from other plugins (i.e. ACF).

I really like the styles and would be interested to know if the plan is to roll these styles out to all WP admin screens.  If the new styling is not going to be part of WordPress core then we should definitely copy them.

**Comment by arnaudbroes** [comment]
@wpsmort #core-editor considers it to be a bug in the Gutenberg editor so they will probably fix it. However, we should definitely copy the styling.

**Comment by arnaudbroes** [comment]
I did this earlier.
