### ISSUE TITLE
Add HTML <time> tag option

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2386]
We should consider adding an option for this - 
![image](https://user-images.githubusercontent.com/18156697/57313066-cb63f900-70bc-11e9-863c-817f4488553d.png)

Related to #2385.

**Comment by wpsmort** [comment]
Actually, were adding this as part of the Schema project as per Google's recommendations here - https://webmasters.googleblog.com/2019/03/help-google-search-know-best-date-for.html

Specifically, datePublished and dateModified will be added as part of #73.

**Comment by arnaudbroes** [comment]
@wpsmort does that result in the same snippet? I've seen sites where meta descriptions look like that without Schema.org markup but with the HTML `<time>` tag in the source code.

**Comment by wpsmort** [comment]
@arnaudbroes This is certainly what Google says you must do in order for them to display the date in SERPS.  

To help Google to pick the right date, site owners and publishers should:

- Show a clear date: Show a visible date prominently on the page.
- Use structured data: Use the datePublished and dateModified schema with the correct time zone designator for AMP or non-AMP pages.

**Comment by arnaudbroes** [comment]
@wpsmort let's go with that then since I just found that `<time>` is a visible tag, which we do not want.
