### ISSUE TITLE
is_admin

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#239]
In admin/aioseop_module_class.php we have function is_admin(). Other than the fact that this is confusing because of the built-in is_admin function (which checks to see if you're on wp-admin), there may be a better way than current_user_can( 'level_8' )... generally it's recommended to current_user_can( some_admin_capability ). 
We should look at this and see if there's something better.

**Comment by nishant981** [comment]
We are working on this issue.
