### ISSUE TITLE
Remove Google Connect

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2395]
We have a bunch of code for Google Connect that isn't doing anything (mostly commented out). Should it be removed?

**Comment by wpsmort** [comment]
Yes, this code should be removed.  This connection method has now been replaced by the newer OAuth 2.0 from Google - https://developers.google.com/identity/protocols/OAuth2

See issue #140

**Comment by michaeltorbert** [comment]
Instead of removing Google Connect, will the button work again if we replace the old oauth with the new oauth as a drop-in replacement?

**Comment by wpsmort** [comment]
It does not look like this is an easy drop-in replacement for the old OAuth connection method.  I have therefore created a PR to remove the legacy Google Connect and OAuth code.
