### ISSUE TITLE
XML sitemap menu shows "changes are automatically submitted" when pings are disabled

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2398]
"Changes are automatically submitted to search engines." is displayed even when there's no ping schedule. Does that make sense?

![image](https://user-images.githubusercontent.com/18156697/57394682-169d0b00-7194-11e9-813f-381827a9cd6a.png)

**Comment by michaeltorbert** [comment]
Yes.
