### ISSUE TITLE
Add noopener noreferrer to sitemaps.org link

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2399]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/inc/sitemap-xsl.php#L93

**Comment by Zodiac1978** [comment]
`<?php echo __( 'You can find more information about XML sitemaps at <a href="http://sitemaps.org">sitemaps.org</a>', 'all-in-one-seo-pack' ); ?>.</p>`

could be written shorter:
`<?php _e( 'You can find more information about XML sitemaps at <a href="http://sitemaps.org">sitemaps.org</a>', 'all-in-one-seo-pack' ); ?>.</p>`

"noopener noreferrer" is just needed if the link is opened in a new window/tab (with target="_blank"). I don't see this in the mentioned link, so I don't think this addition is needed.

Or this attribute have to be added too.

See: https://www.wpbeginner.com/beginners-guide/what-is-relnoopener-in-wordpress-explained/

I'm happy to provide a PR - I just to know if the link should open i a new window/tab.

**Comment by arnaudbroes** [comment]
@Zodiac1978 we probably want these to open as new tabs. Thank you for your input though!

**Comment by Zodiac1978** [comment]
@arnaudbroes I have made a PR. I wasn't sure about the usage of `echo __` - is this intentional? I haven't touched this ... because this is used more than once, so it could be wanted.

**Comment by arnaudbroes** [comment]
@Zodiac1978 thank you, I'll definitely have a look at it. 

__() is a function that's built into WordPress Core and it allows you to make strings translatable so that, when a user is using a language different than English, it shows up in that language instead (assuming that the string has been translated on translate.wordpress.org) - https://developer.wordpress.org/reference/functions/__/

Alternatively, you could also use e_() which makes the echo statement redundant.

**Comment by Zodiac1978** [comment]
> Alternatively, you could also use e_() which makes the echo statement redundant.

Yes, I know (German GTE for years) ;)
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2399#issuecomment-499397616

I just wasn't sure if this is your code style to use it this way ...

**Comment by arnaudbroes** [comment]
@Zodiac1978 my bad. :-)

**Comment by michaeltorbert** [comment]
@Zodiac1978 Thanks for your comments and PR! 
After all the new and changed strings in the latest major release, we could use your help with some of the German strings if you like. :)
https://translate.wordpress.org/locale/de/default/wp-plugins/all-in-one-seo-pack/
