### ISSUE TITLE
Sitemap Priorities and Frequencies options don't work for main page

### ISSUE THREAD

**Issue by JakubPie** [semperfiwebdesign/all-in-one-seo-pack#2423]
Sitemap: value change in Priorities and/or Frequencies for a main page does not reflect in sitemap.xml file - still shows "old" values.

**Comment by arnaudbroes** [comment]
I'm not able to reproduce so I'll go ahead in close this without further investigation considering that we'll revisit priorities/frequencies at some point in the future.
