### ISSUE TITLE
Add a warning for when file import fails due to detected scripts/injection attempt

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#243]
@wpsmort @amostajo We can discuss what exactly the wording should be so we can go ahead and get it translated.

**Comment by amostajo** [comment]
I propose the following warning notice:

> Security warning: Your file looks compromised. Please check the file for any script-injection.

**Comment by michaeltorbert** [comment]
@amostajo Looks good to me. 
@wpsmort Thoughts?

**Comment by amostajo** [comment]
`Security warning:` on bold by the way.
