### ISSUE TITLE
Incorrect output with Article Tags options in Social Meta module

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2430]
Whilst testing PR #2427 I found that the output in the article:tag meta tag don't correspond to the checkboxes that are checked under Social Meta > Facebook Settings > "Use xxxx in Article Tags".

This happens with the current version of AIOSEOP.

**Describe the bug**
Under Facebook Settings, there are three checkboxes related to Article Tags, these are:
- Use Keywords in Article Tags
- Use Categories in Article Tags
- Use Post Tags in Article Tags
 
If Use Keywords is checked that it doesn't matter if the other two are checked or unchecked, categories and tags are still output in the article:tag meta tag.

**To Reproduce**
1. Go to Social Meta > Facebook Settings and enabled Automatically Generate Article Tags
2. Next, enable Use Keywords in Article Tags
3. View the source code of a post that have categories, tags and SEO keywords
4. Check the article:tag meta tags and you'll see that the categories, tags and SEO keywords are all output
5. Test with different combinations of the three checkboxes and you'll see that this only happens when the Use Keywords in Article Tags checkbox is checked

**Expected behavior**
Categories should only be output in the article:tag meta tag when the appropriate checkbox is checked.
Tags should only be output in the article:tag meta tag when the appropriate checkbox is checked.

**Version Info (please complete the following information):**
 - WordPress version: 5.2
 - All in One SEO Pack version: 2.12.1
 - PHP version: 7.2

**Comment by arnaudbroes** [comment]
@wpsmort have you checked whether this isn't happening because the "Use Categories for META keywords" and "Use Tags for META keywords" settings in the General Settings menu are enabled and its using those keywords?

**Comment by wpsmort** [comment]
@arnaudbroes Great catch!  Yes, that's exactly what this was.  Closing this as it's irrelevant.
