### ISSUE TITLE
Condense title format functions

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2442]
We have multiple functions to replace placeholders in the title:

get_title_format()
title_placeholder_helper()
apply_tax_title_format()
apply_description_format()

Is there any reason why we shouldn't combine these into a single function?

**Comment by arnaudbroes** [comment]
This is basically why I opened https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2394. All of that code needs to be moved to its own class/file and needs to be refactored.
