### ISSUE TITLE
Translation requests don't always match correct language

### ISSUE THREAD

**Issue by aquorange** [semperfiwebdesign/all-in-one-seo-pack#2444]
There is only one german translation waiting: Your product name which could hardly be translated - would be funny ;-) So you could simply close all requests for help on the german translation by approving this one.
Best, C

**Comment by michaeltorbert** [comment]
@aquorange Unfortunately we're not able to approve strings. Only a Project Translation Editor, which is a translator submitted by us and approved by the wordpress.org translation staff, can approve them.

We have an issue open to remove the plugin name from being translated: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2432

If you'd like to be a Project Translation Editor for the All in One SEO Pack project, reach out to @arnaudbroes at abroes AT semperplugins.com with your wordpress.org profile username and we can request it.

**Comment by michaeltorbert** [comment]
Reopening this issue as I just realized the issue (bug?) that it's reporting 80% complete (which is the completeness for German (formal) instead of 99%.
