### ISSUE TITLE
Add index files to each directory

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2462]
We had a user report that Google was indexing his directory index page created by mod_autoindex.
We should include an index.php in every directory that doesn't have one to avoid this.

**Comment by wpsmort** [comment]
Will a PR need to be created in the Pro repo to add an index.php file to the pro/ directory and it's subdirectories?

**Comment by michaeltorbert** [comment]
Good catch. I've opened an issue.

> Will a PR need to be created in the Pro repo to add an index.php file to the pro/ directory and it's subdirectories?
