### ISSUE TITLE
Rename clean_url() to avoid false deprecation positives 

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2469]
When running the plugin files through https://wpseek.com/pluginfilecheck/ this deprecated function was identified:

clean_url is deprecated since WordPress 3.0.0
esc_url() all-in-one-seo-pack-3.0/modules/aioseop_sitemap.php

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/53b0a5f9c74941979d645caa4866145287f7e944/modules/aioseop_sitemap.php#L3387

(edited by Michael to add link to code)

**Comment by michaeltorbert** [comment]
This is actually our own internal function, not WP's. We can just rename it to avoid false positives.
