### ISSUE TITLE
improve grunt/coding standards/sniffs

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2472]
Maybe take some guidance from some other projects.
https://github.com/Automattic/jetpack/blob/master/.phpcs.xml.dist looks pretty good.

Also look at ones we should be customizing, such as minimum WP version

* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties
* https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage

**Comment by EkoJR** [comment]
When applying coding standard updates, try to isolate your changes to each module for testing purposes. So that each module has their own PR. This will make testing easier and less widespread.

**Comment by arnaudbroes** [comment]
I'd like for us to add these rulesets:

- PHPCompatibilityWP (Check PHP cross-version compatibility issues).
- WordPress-Extra (extended ruleset for recommended best practices).

WordPress-Extra includes WordPress-Core so we could use it to replace it.

==

Here's what properties I'd like to add:

```
<rule ref="WordPress.WP.I18n">
	<properties>
		<property name="text_domain" type="array" value="all-in-one-seo-pack" />
                <property name="check_translator_comments" value="true"/>
	</properties>
</rule>
```

Checks whether all i18n functions contain our text domain. Useful to make sure that all translatable string are localized. Also should check whether all strings with placeholders have translator comments.

```
<rule ref="WordPress.NamingConventions.PrefixAllGlobals">
	<properties>
		<property name="prefixes" type="array" value="aioseop_" />
	</properties>
</rule>
```
Checks whether all functions are prefixed. This isn't the case now, but we should do this at some point.

`<config name="minimum_supported_wp_version" value="4.6"/>
`

Speaks for itself.

**Comment by EkoJR** [comment]
That was/is the plan.

After grinding through about 20 different rules in 2-3 days as fast as I could, I was exhausted, and that was a lot of additions and deletions.

I would like to get the rest of these added when we start 3.3, or at some point when PR submission is slow.

**Comment by arnaudbroes** [comment]
> I would like to get the rest of these added when we start 3.3, or at some point when PR submission is slow.

I'm good with that.
