### ISSUE TITLE
File Editor does not appear on WordPress Admin Bar

### ISSUE THREAD

**Issue by iamchana** [semperfiwebdesign/all-in-one-seo-pack#2476]
![seo](https://user-images.githubusercontent.com/50954361/58255139-83b8bf00-7d96-11e9-9a56-44b922c60ce7.png)

I have activated the File Editor under Feature Manager. But the menu does not appear on the admin sidebar. Please see screenshot attached.

Thanks in advance.
Chana

**Comment by wpsmort** [comment]
Please refer to our documentation - https://semperplugins.com/documentation/the-file-editor-or-robots-txt-modules-are-missing/

This is not a support forum.
