### ISSUE TITLE
custom Github og image

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2478]
Github now supports custom OG images for repositories. 

1) Is this only for the repo page itself? What about issues?
2) Design a nice image
3) Github mentions they have a template of some kind to get started. https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/

**Comment by arnaudbroes** [comment]
@michaeltorbert I was just setting up 2FA and by coincidence saw that your personal Gravatar account was linked to our Organization so I've removed it, updated the old AIOSEOP icon to the gear logo and now that's the fallback image for OG.
