### ISSUE TITLE
Add docs for generate_descriptions_from_content filters

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2481]
Add docs for the two new filters added here - https://github.com/semperfiwebdesign/aioseop-pro/issues/185

**Comment by wpsmort** [comment]
@arnaudbroes Please review the new docs here:

https://semperplugins.com/?post_type=documentation&p=4811
https://semperplugins.com/?post_type=documentation&p=4814

**Comment by arnaudbroes** [comment]
These have been published.
