### ISSUE TITLE
Missing character from notice

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2506]
I noticed that the following text is missing a t in the word doesn't:

User doesn' have `aiosp_manage_seo` capabilities.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/b6c7803cbf5f3a1624098e6653379178f6c5dde9/admin/class-aioseop-notices.php#L646

**Comment by michaeltorbert** [comment]
It's also easier, more readable (less confusing for translators) if we use double quotes on the string so we can have an apostrophe without escaping it.
