### ISSUE TITLE
Create documentation for new sitemap URL in robots.txt filter hook

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2519]
aioseop_robotstxt_sitemap_url

**Comment by arnaudbroes** [comment]
@wpsmort please review the doc here and then publish it - https://semperplugins.com/wp-admin/post.php?post=4854&action=edit&lang=en

**Comment by wpsmort** [comment]
This has been reviewed and published - https://semperplugins.com/documentation/aioseop_robotstxt_sitemap_url/
