### ISSUE TITLE
Update documentation for (removed) Rewrite Titles option.

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2521]
Offhand I'd say we should 
a) update the images on the page
b) replace the text under the "Rewrite Titles" heading with a message that this option has been removed as of 3.0.

**Comment by arnaudbroes** [comment]
@wpsmort take screenshots with the #1168 PR so the new visual changes are in as well.

**Comment by wpsmort** [comment]
The documentation and screenshot here have been updated - https://semperplugins.com/documentation/title-settings/
