### ISSUE TITLE
% sign in title breaks Preview Snippet

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2526]
**Describe the bug**
Placing multiple % signs in the title of a post or page breaks the Preview Snippet.  

NOTE: It does not break the placeholder text in the Title field or the doc title tag  in the source code.

**To Reproduce**
In order to reproduce this issue, follow these steps:

1. Install All in One SEO Pack on a new test site
2. Create a new Post and set a title without a %. You'll see that the Preview Snippet is fine
3. Now add two % signs to the title with some text in between each % sign, for example:

Testing 100% and another 100%

You'll see the Preview Snippet doesn't show any of the text between the two % signs.  See the screenshot below.

**Expected behavior**
Text between percent signs should be displayed correctly in the Preview Snippet.

**Screenshots**
<img width="801" alt="Screen Shot 2019-05-29 at 12 31 27 PM" src="https://user-images.githubusercontent.com/17548525/58574348-c6065400-820d-11e9-87f9-a2749e37da37.png">

**Version Info:**
 - WordPress version: 5.2.1
 - All in One SEO Pack version: 2.12.1
 - PHP version: 7.2.0

Arnaud believes that this is related to #1408.

**Comment by wpsmort** [comment]
@arnaudbroes Please test back to see what version this bug first occurred in.

**Comment by arnaudbroes** [comment]
I believe this is related to #1408.
