### ISSUE TITLE
new issue labels to improve development process

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2527]
needs-origin
has-PR

**Comment by arnaudbroes** [comment]
Labels have been added. I've also broken up the Documentation labels into Inline, Tooltip and Website.

**Comment by michaeltorbert** [comment]
@arnaudbroes Personally I think in-app is better than tooltip, since we may not always only have tooltips in-app.

**Comment by arnaudbroes** [comment]
@michaeltorbert sure I've changed them.
