### ISSUE TITLE
Move email field in performance module outside the scroll area

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#254]
It's not obvious how you'd email debug info

<img width="682" alt="screen shot 2016-04-28 at 6 29 11 pm" src="https://cloud.githubusercontent.com/assets/17364998/14903456/260d44ec-0d6f-11e6-9a9d-3fff2d66e0af.png">

**Comment by wpsmort** [comment]
This is tested and is good.  Needs a code review.
