### ISSUE TITLE
Content not being correctly excluded from sitemap

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2546]
**Describe the bug**
In PR #2317 we added support for excluding content from the sitemap when NOINDEX is enabled.  The bug here is that individual posts set to NOINDEX or Exclude from Sitemap are not being excluded from the sitemap when Indexes is enabled and the sitemap is being paginated.  

**To Reproduce**
1. On a new site, install the master branch and enable the sitemap module
2. Now create a hundred posts in the Uncategorized category
3. Next, edit three posts  as follows:

- One post should be set to Noindex
- One post should be set to Exclude from Sitemap
- One post should be removed from Uncategorized and added to a new category that is excluded from the sitemap using the new Excluded Terms option in the sitemap module

4. View the sitemap, the three posts that have been excluded above should not appear in the sitemap_post.xml
5. Now go to the sitemap settings and set pagination to 50 and view the sitemap
6. You should see two post sitemaps (sitemap_post_1 snd sitemap_post_2). View each one and check to see if the posts set as Noindex and Exclude from Sitemap are excluded.  You should see that the only post that is excluded is the one assigned to the category that has been excluded using Excluded Terms

Additionally, if you create three new posts and make one Noindex and another Exclude from Sitemap, all three show up in sitemap_post_3. 

**Expected behavior**
Posts set to Noindex or Exclude from Sitemap should be excluded from the sitemap regardless of the pagination setting.  However, posts are not excluded when pagination is set to a number lower than the number of published posts.

**Screenshots**
<img width="749" alt="Screen Shot 2019-06-01 at 1 28 13 PM" src="https://user-images.githubusercontent.com/17548525/58751799-ba1acc00-8471-11e9-8184-9d1c568a56df.png">

<img width="976" alt="Screen Shot 2019-06-01 at 1 28 35 PM" src="https://user-images.githubusercontent.com/17548525/58751802-c0a94380-8471-11e9-9d35-844434c5aa36.png">

**Version Info:**
 - WordPress version: 5.2.1

 - All in One SEO Pack version:
 - PHP version: 7.x

This is a new bug as it affects a new feature added in v3.0.

**Comment by michaeltorbert** [comment]
When I install the original PR where this should have been fixed, I'm still getting the URLs included in the sitemap. https://github.com/semperfiwebdesign/all-in-one-seo-pack/tree/04899b3f30e65956b35aac93b16a5c58893ff51d

**Comment by wpsmort** [comment]
@EkoJR I tracked this bug down to this commit - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2317/commits/1b5cf30650f5972bed7011dc3b1c4fb18e91bc0b

**Comment by EkoJR** [comment]
Oh yea, I remember that one. That was actually a change that was requested on that PR, and the only reason I added it was to get the PR to move forward.

**Comment by EkoJR** [comment]
Looking at the code, that set of args is made to exclude, and setting a limit to it restricts the exclude concept; I added a note for future reference.

**Comment by michaeltorbert** [comment]
@ekojr What was the intended purpose of it changing it previous?

**Comment by EkoJR** [comment]
@michaeltorbert Can't limit an exclude method. You need the list of all the posts that are going to be excluded, and trying to add pagination within another pagination query will have unstable results.
