### ISSUE TITLE
Error when generating sitemap.xml

### ISSUE THREAD

**Issue by sbiese** [semperfiwebdesign/all-in-one-seo-pack#2547]
XML Parsing Error: XML or text declaration not at start of entity
Location: http://thebibleuniversity.org/sitemap.xml
Line Number 2, Column 1:<?xml version="1.0" encoding="UTF-8"?>
^

Only, there is NOTHING on line 2 when I view the file:
<?xml version="1.0" encoding="UTF-8"?>
(This would be line 2. It's empty!)

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/this-page-contains-the-following-errors/
