### ISSUE TITLE
site health problem

### ISSUE THREAD

**Issue by tawanya** [semperfiwebdesign/all-in-one-seo-pack#2548]
Site Health Status
The site health check shows critical information about your WordPress configuration and items that require your attention.

2 Critical issues

Your PHP version requires an update
Security

The REST API encountered an error
Performance
3 Recommended improvements

Have a default theme available
Security

Outdated SQL server
Performance

A scheduled event has failed
Performance
Passed tests
Thank you for creating with WordPress. Version 5.2.1

how do i fix theses issues

**Comment by michaeltorbert** [comment]
This is the All in One SEO Pack development repository.
Unless I'm missing something, none of those issues have anything to do with Al in One SEO Pack.
