### ISSUE TITLE
ПРОБЛЕМА ПОСЛЕ ОБНОВЛЕНИЕ ALL-IN-ONE-SEO

### ISSUE THREAD

**Issue by aLEX19911111** [semperfiwebdesign/all-in-one-seo-pack#2552]
дОБРЫЙ ДЕНЬ, ПОСЛЕ вАШЕГО ОБНОВЛЕНИЯ произошла вот такая ерунда!! скриншоты прикладываю. отключаю плагин и все работает нормально , включаю и вижу вот такую ерунду. Решите проблему в крадшайшие сроки. и выпустите новое обновление которое устранит все это заранее спасибо!!

![цукцукцук](https://user-images.githubusercontent.com/51360348/58863693-ff323e80-86bb-11e9-81e5-59ce62a9eb4a.png)
![уцауацуа](https://user-images.githubusercontent.com/51360348/58863694-ff323e80-86bb-11e9-8dbd-c84a6ddaf906.png)

**Comment by aLEX19911111** [comment]
Все ребят отключил WPGLOBUS и все заработала . Спасибо Вам все равно

**Comment by michaeltorbert** [comment]
I can't tell what problem you're reporting. The translator just says "nonsense" which isn't helpful.

**Comment by michaeltorbert** [comment]
@aLEX19911111 I can't tell what problem you're reporting. The translator just says "nonsense" which isn't helpful.

**Comment by aLEX19911111** [comment]
Просто у меня пошла какая то не совместимость с плагином wpglobus

**Comment by michaeltorbert** [comment]
Can you provide more details than that?

**Comment by alexgff** [comment]
@aLEX19911111 
выпущен WPGlobus 2.2.9 с исправлением для ALL-IN-ONE-SEO v.3

**Comment by arnaudbroes** [comment]
I've tested and also confirmed through the changelog that WPGlobus has fixed this on their end.
![image](https://user-images.githubusercontent.com/18156697/58944516-48e55c80-8782-11e9-9e43-96eb7e2917cf.png)
