### ISSUE TITLE
Divi icon set broken

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2555]
Reported here: https://wordpress.org/support/topic/divi-icons-set-broken/

**Comment by michaeltorbert** [comment]
@wpsmort @arnaudbroes Can one of you try and reproduce this?

**Comment by wpsmort** [comment]
I'll test ad see if I can reproduce this.

**Comment by arnaudbroes** [comment]
Both Steve and I weren't able to reproduce this is. Now waiting on more info from the user.
