### ISSUE TITLE
sitemap.xml problems after update to 3.0

### ISSUE THREAD

**Issue by mkulgin** [semperfiwebdesign/all-in-one-seo-pack#2558]
Hi! 

After upgrade the plugin to v.3.0 I get some errors in sitemap.xml (link https://companylist.ru/sitemap.xml) when open it in Chrome: https://prnt.sc/nxi9tx and Google doesn't accept the file :(

Before upgrading everything was OK! 
WordPress v4.9

Opening the sitemap.xml will get the following output inside:

<br />
--
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <br />
  | <b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/home/host1725276/companylist.ru/htdocs/www/wp-includes/post-template.php</b> on line <b>284</b><br />
  | <?xml version="1.0" encoding="UTF-8"?>
  |  
  | 
  | <?xml-stylesheet type="text/xsl" href="https://companylist.ru/sitemap.xsl"?>
  | <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  | xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  | <url>
  | <loc>https://companylist.ru/</loc>
  | <lastmod>2019-05-31T11:36:49Z</lastmod>
  | <changefreq>daily</changefreq>
  | <priority>1.0</priority>
  | </url>
  | <url>

**Comment by michaeltorbert** [comment]
This is a known issue and will be fixed in 3.0.1. 
In the meantime, you can fix it by upgrading to the latest version of WordPress. If you're holding off on updating because of Gutenberg, you can keep the classic editor with this plugin. https://wordpress.org/plugins/classic-editor/

**Comment by mkulgin** [comment]
> This is a known issue and will be fixed in 3.0.1.
> In the meantime, you can fix it by upgrading to the latest version of WordPress. If you're holding off on updating because of Gutenberg, you can keep the classic editor with this plugin. https://wordpress.org/plugins/classic-editor/

Thanks! I will wait 3.01 and pray you will do it fast :) because it has affect to SEO... :(

**Comment by michaeltorbert** [comment]
You can resolve it now by updating WordPress.

**Comment by mkulgin** [comment]
> You can resolve it now by updating WordPress.

Well... Im afraid that it may affect others plugin (I have alot of). And it might be problems. But thanks, if it take months to release 3.01 I will surely to update WP.

**Comment by michaeltorbert** [comment]
We're trying to get 3.0.1 released today.

**Comment by mkulgin** [comment]
> We're trying to get 3.0.1 released today.

THANKS. I go to and leave 5 stars and perfect review on your plugin. Right now.

**Comment by michaeltorbert** [comment]
@mkulgin We've released 3.0.1 which should fix this issue for you.
