### ISSUE TITLE
Undefined index: aiosp_sitemap_taxonomies in aioseop_sitemap.php on line 712

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2561]
The following PHP Notice occurs when going to the Video Sitemap module screen:

PHP Notice:  Undefined index: aiosp_sitemap_taxonomies in modules/aioseop_sitemap.php on line 712

**Comment by wpsmort** [comment]
@EkoJR We need to know why we're getting an undefined index on aiosp_sitemap_taxonomies in the Video Sitemap because the Taxonomies option was supposed to be removed in PRs #474 and https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2334

I tried the following code change on line 712 which fixed the notice:

`if ( isset( $this->options['aiosp_sitemap_taxonomies'] ) && is_array( $this->options['aiosp_sitemap_taxonomies'] ) ) {`

However, the Taxonomies option should be removed from the Video Sitemap but still be present in the XML Sitemap.

**Comment by EkoJR** [comment]
@wpsmort it was missing the module prefix variable, rather than the static string. It was checking for `aiosp_video_sitemap_taxonomies`. At the time, I expected only the sitemap module to use the function. Changing it to `$this->prefix . 'taxonomies'` fixes the problem.

**Comment by michaeltorbert** [comment]
@EkoJR Can you make a PR for this?
