### ISSUE TITLE
Restrict review notice to our own screens

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2565]
Is that here? https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/ce0acebb6efd9d30c6547049bddff1c6a6e31b51/admin/display/notices/review-plugin-notice.php#L21

**Comment by EkoJR** [comment]
Yes, it would be `array( 'aioseop' )` to target all AIOSEOP screens; or individual screen IDs could be used.
