### ISSUE TITLE
Missing social tab in 3.0.1

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2572]
The Main Settings and Social Settings tabs are missing:

<img width="979" alt="Screen Shot 2019-06-05 at 2 02 53 PM" src="https://user-images.githubusercontent.com/17548525/58978908-db91f580-879a-11e9-92dd-d5511617df14.png">

**Comment by wpsmort** [comment]
I tracked this down to a conflict with this plugin - https://wordpress.org/plugins/accelerated-mobile-pages/

I was able to reproduce this on a new site with only AIO and that plugin installed.  The Accelerated Mobile Pages plugin has a CSS style of display: none; applied to the class .hide on line 1038 of accelerated-mobile-pages/pagebuilder/inc/admin-amp-page-builder.css

We use the class .hide on our tabs here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/ce0acebb6efd9d30c6547049bddff1c6a6e31b51/aioseop_class.php#L4334

The commit that caused this is here https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2290/commits/0dade54d6cdea0283f19321fad3dfbbe200b9c28 where we removed the style .aioseop_header_tabs.hide
