### ISSUE TITLE
Restrict WooCommerce notice to our own screens

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2583]
Since there are still some users with the problem of it not staying away (and I'd still like us to figure out why) we need to discuss whether to at least restrict it to our own admin screens. This may be the more considerate option anyway.

Thoughts?

**Comment by arnaudbroes** [comment]
Is what I would have done. I'd either limit it to only AIOSEOP or AIOSEOP and the Edit Product & Edit Product Category screens.

**Comment by wpsmort** [comment]
I agree with restricting the notice to just our admin screens. As you say, it's the considerate option.
