### ISSUE TITLE
Taxonomy term meta

### ISSUE THREAD

**Issue by mrtorbert** [semperfiwebdesign/all-in-one-seo-pack#26]
-Add ability (autodetect? button?) to migrate pre-4.4 custom taxonomy term meta over to built-in 4.4 taxonomy term meta... 
-maybe make requirement for tax term meta functionality 4.4? or should we use the old method for pre-4.4?
because we're currently checking for the existence of the tax term meta functions first, any tax term meta entered pre-4.4 will probably no longer be showing up post upgrade to 4.4

**Comment by dougalcampbell** [comment]
This feature is only in the Pro version of the plugin, and it's being worked on there. Closing this.
