### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Vanellih** [semperfiwebdesign/all-in-one-seo-pack#2601]
I can't update the plugin on my wordpress site. What could be the problem?

**Comment by michaeltorbert** [comment]
@Vanellih Since you don't provide any details, such as what exactly happens when you try and fail to update, we couldn't possibly know.
You can try these troubleshooting steps. https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
