### ISSUE TITLE
Tag font has changed

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2603]
![D8dAi7EWsAAaQeG](https://user-images.githubusercontent.com/17364998/59102699-da77da00-88fa-11e9-8113-9139374f4f9a.jpg)

**Comment by wpsmort** [comment]
I have been able to reproduce this.  This was added in PR #2236 in this commit https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2236/commits/1ab9b68e89aea2187d5e84f4efe1b3903f30463d

**Comment by EkoJR** [comment]
I'm not sure this can be fixed; unless the styling isn't enqueued. The element structure & element classes are set up in WP in such a way, that enqueueing a style will apply those styles. It seems to be more of a problem with WP's element structure.
