### ISSUE TITLE
Google APIs are blocked in China

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2607]
Reported https://wordpress.org/support/topic/problems-with-new-version-6/

> Google APIs are not reachable in china. in admin/aioseop_module_class.php, a googleapis jqueryui CDN was enqueued, as google was blocked in china for several years, this cdn makes every Chinese user take too long to open the admin page, even time out.
> Consider pack the js file in the plugin files if you would?
> 

We need to see when we started using Google APIs in order to determine if this needs to go out in 3.0.4. 
Is there a reason why we aren't just shipping it?

**Comment by wpsmort** [comment]
This was added in PR #2290 in this commit https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2290/commits/23309f192f8f9ff1783cd538966b85b35e146892

**Comment by michaeltorbert** [comment]
Ok so we can either load it from a different location, ship it, or use a built-in library
These are one that ship with WP https://developer.wordpress.org/reference/functions/wp_enqueue_script/#default-scripts-included-and-registered-by-wordpress

If we use ones built into WP, we need to check what version of WP they were first included with.

This tabs library is included https://jqueryui.com/tabs/

**Comment by EkoJR** [comment]
Those aren't scripts, those are styles. Most of which do not ship with WP.

**Comment by EkoJR** [comment]
After 8 years....it's still an open issue. https://core.trac.wordpress.org/ticket/18909

**Comment by michaeltorbert** [comment]
Test Microsoft's for China @EkoJR
