### ISSUE TITLE
Sitemap and admin section not loading...

### ISSUE THREAD

**Issue by ediong** [semperfiwebdesign/all-in-one-seo-pack#2608]
Sitemap and admin section not loading...

**Comment by michaeltorbert** [comment]
@ediong Can you please provide screenshots?

**Comment by ediong** [comment]
wp-admin/admin.php?page=all-in-one-seo-pack-pro/modules/aioseop_sitemap.php and sitemap.xml are all loading blank.

**Comment by michaeltorbert** [comment]
@ediong What is the URL to your sitemap?

**Comment by ediong** [comment]
<img width="1440" alt="Screenshot 2019-06-07 at 3 54 59 PM" src="https://user-images.githubusercontent.com/28027710/59113367-c6ed6300-893c-11e9-9801-a8afa06a41c2.png">
<img width="1440" alt="Screenshot 2019-06-07 at 3 55 18 PM" src="https://user-images.githubusercontent.com/28027710/59113368-c6ed6300-893c-11e9-8791-61b663400a40.png">
<img width="1440" alt="Screenshot 2019-06-07 at 3 55 23 PM" src="https://user-images.githubusercontent.com/28027710/59113371-c6ed6300-893c-11e9-9621-8ebce9d2988c.png">

https://www.today.ng/sitemap.xml It was working before this update.

**Comment by michaeltorbert** [comment]
@ediong Try these troubleshooting steps to narrow down a plugin or theme conflict: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

**Comment by ediong** [comment]
Taking those actions are far bigger risk. The website is an active news site with large audience. Everything was okay until I updated the plugin. The only problem is with sitemaps alone...every other thing is OK.

**Comment by ediong** [comment]
The website is large. It has nearly 500k tag and posts.

**Comment by michaeltorbert** [comment]
@ediong 

> Taking those actions are far bigger risk. 

Those troubleshooting steps are required in order to diagnose whether there's a plugin/theme conflict.

> The website is an active news site with large audience

We recommend testing on a development copy of the site if possible. If you are not able to do that, you can also try using the healthcheck plugin, which will allow you to deactivate plugins just for your session, while others will see the regular live site. https://wordpress.org/plugins/health-check/

> Everything was okay until I updated the plugin

Unfortunately we're unable to reproduce the problem you're having, and nobody else has reported it, which means it's something specific to your site, which is why those troubleshooting steps are the necessary first step.

**Comment by ediong** [comment]
<img width="1440" alt="Screenshot 2019-06-07 at 4 08 22 PM" src="https://user-images.githubusercontent.com/28027710/59114171-88f13e80-893e-11e9-92a9-57f307f91b2d.png">
<img width="1440" alt="Screenshot 2019-06-07 at 4 09 09 PM" src="https://user-images.githubusercontent.com/28027710/59114209-9c9ca500-893e-11e9-8858-00b8ea5c7ae5.png">

This is at Troubleshooting Mode. Everything disabled. Same result.

**Comment by michaeltorbert** [comment]
You can submit your login info to our secure form here and we'll have a look: https://semperplugins.com/contact/support-login-information/

**Comment by michaeltorbert** [comment]
This can be reopened if we get more info such as steps to reproduce.
