### ISSUE TITLE
Make plugin name constant dynamic

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2609]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/01bf171799b6b45443d0b7f4b3de2c61256b7bdf/all_in_one_seo_pack.php#L41-L42

We should just check for the AIOSEOPPRO constant and then conditionally call it whichever to make switching easier.

If Pro - name = pro
else - name = free/core

**Comment by arnaudbroes** [comment]
That would be a welcome change.
