### ISSUE TITLE
XML Sitemap pagination not working for SimplePress forums

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2613]
This can be seen on https://semperplugins.com/sitemap_forum.xml where we have sitemap indexes enabled and pagination set to 1000 but the sitemap for forums is not being paginated.  This could be caused by the SimplePress XML Sitemap add-on (https://simple-press.com/downloads/xml-sitemap-plugin/).

**Comment by wpsmort** [comment]
I'll do more testing to determine where this problem

**Comment by wpsmort** [comment]
This is not new, and it doesn't just affect AIO, it affects other well known plugins too.  Looking at the code of the SimplePress Google XML Sitemap add-on, it doesn't have any way of paginating their sitemap.  I've emailed the developers to ask if they intend on adding pagination.

**Comment by wpsmort** [comment]
I received this response from the developers of SimplePress:

> As far as the pagination goes, none of our large forum users has asked us for it yet so its not something on our todo list.

**Comment by michaeltorbert** [comment]
> none of our large forum users has asked us for it yet so its not something on our todo list

Aren't *we* one of their large forum users? Besides, that absurd. Surely they don't expect their users to be experts on sitemaps? How would they even know to ask?

Considering pagination is standard practice among sitemap plugins, should we take this as a signal that they don't intend keeping the plugin modern and expedite our finding a replacement for our own forum?
