### ISSUE TITLE
Old icon in new version

### ISSUE THREAD

**Issue by kovalets** [semperfiwebdesign/all-in-one-seo-pack#2614]
**In the new installation of the plugin, the new icon, in the old version updated to the new version, is still the old icon.**
New install ![new install](https://user-images.githubusercontent.com/22265102/59134309-59185a00-8983-11e9-9bdb-96b0a5f0a710.png)

Old Install ![Old install](https://user-images.githubusercontent.com/22265102/59134311-5c134a80-8983-11e9-854c-6b5f9a7e8f74.png)
_(Do not pay attention to localization)_
**_The latest version of the plugin is used._**

**Comment by michaeltorbert** [comment]
The top one is the new version of the icon.
The bottom one is the old icon.

**Comment by kovalets** [comment]
Missing the button to disable the SEO button in the panel.
![seo](https://user-images.githubusercontent.com/22265102/59134793-2ec79c00-8985-11e9-8639-e815da967570.png)

**Comment by kovalets** [comment]
I translate your plugin into Ukrainian Leanguage.
Can you add me to the list of translators of your plugin?
https://profiles.wordpress.org/sergeykovalets/

**Comment by michaeltorbert** [comment]
@kovalets 
This is a development repository, not a discussion forum. Many people get notifications for these issues, so let's please use the site appropriately. 
If you have a bug report, feature request, etc, create a new issue. Do not post on another unrelated existing issue.
If you would like to be a translator, please contact us here and our Translator Wrangler will get in touch with you. https://semperplugins.com/contact/
