### ISSUE TITLE
Empty <lastmod> for SimplePress forum sitemap

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2616]
This can be seen on https://semperplugins.com/sitemap.xml where we have sitemap indexes enabled.  The sitemap for the forums contains an empty <lastmod> tag which results in an error in Google Search Console shown in the screenshot below:

<img width="957" alt="Screen Shot 2019-06-07 at 6 10 39 PM" src="https://user-images.githubusercontent.com/17548525/59136100-a24eb680-894f-11e9-9730-8e3a3f15708e.png">

This could be caused by the SimplePress XML Sitemap add-on (https://simple-press.com/downloads/xml-sitemap-plugin/).

the <lastmod> tag is optional for the sitemap index file according to Google (https://support.google.com/webmasters/answer/75712?hl=en) but we have an issue open to consider adding it - See #262

**Comment by michaeltorbert** [comment]
@EkoJR Can you look and see whether this is something that needs fixing by us or by their add-on?

**Comment by wpsmort** [comment]
This is caused by the Google XML Sitemap add-on for SimplePress.  Specifically line 125 of sp-google-sitemap-components.php contains `'lastmod' => ‘’` which, when removed, fixes the problem.

I have emailed the developers of SimplePress to ask them to update their add-on and provided the code to fix this.

**Comment by wpsmort** [comment]
I have also emailed the SimplePress developers to request that they change the name of their sitemap to comply with the new naming convention we introduced in v3.1.

Currently, their Google XML Sitemap add-on for SimplePress creates a sitemap called sitemap_forum.xml (see screenshot from semperplugins.com below), which results in a 404 Page not found when you go to it.  

I have requested that they change line 125 of sp-google-sitemap-components.php to reflect the correct sitemap name as follows:

`site_url('forum-sitemap.xml')`

**Comment by wpsmort** [comment]
These problems have been fixed in version 3.1.1 of the Google XML Sitemap add-om from SimplePress.
