### ISSUE TITLE
XML Sitemap - Last changed date for sitemaps improvements

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#262]
1) Add last changed for sitemap entries for when indexes is turned on. Only posts have last changed. We should look into whether categories, tags, etc should have it as well.

2) Even without indexes turned on, categories, tags, etc may not have a date.

3) Homepage doesn't always have a date... maybe only if it's a static page? If the homepage is the latest posts, we should have it use the date of the latest post. 

reported:
https://wordpress.org/support/topic/sitemap-tag-and-categories-does-not-show-date-lastchange?replies=5

**Comment by michaeltorbert** [comment]
@wpsmort Thoughts?

**Comment by michaeltorbert** [comment]
Also, on semperplugins.com for instance, the homepage and blog archive page don't update the date in the sitemap when a new blog post is published...

**Comment by wpsmort** [comment]
@michaeltorbert I think we should add/update the lastchange date based on the date of the last post in that archive.  We should also do this for the blog page.

**Comment by wpsmort** [comment]
Here's a recent post with some clarification from John Mueller at Google about the Last Change date - https://www.seroundtable.com/google-on-sitemap-dates-web-page-dates-27469.html

My thoughts are as follows:

- For the homepage (when homepage is set to latest posts), we should take the date the latest post was modified.  The action needed here is to add the Last Change date for the homepage which is currently missing.

- For the Blog page (selected in Posts page under Reading Settings), we should do the same as above.  The action needed here is to add the Last Change date for the Blog page which is missing from the addl-sitemap when indexes is enabled.

- For the static Home page (selected in Homepage under Reading Settings), we should use the date the page was modified.  The action needed here is to add the Last Change date for the Home page which is missing from the addl-sitemap when indexes is enabled.

- For custom post type archives, we should take the date the latest post in the post type was modified.  The action needed here is to modify the Last Change date for CPT archives.

- For taxonomies (categories, tags and custom), we should take the date the latest post in the taxonomy was modified.  The action needed here is to add the Last Change date for taxonomies.

- For date and author archives, we're currently using date the latest post was modified so no action is needed here.

- Finally, for the WooCommerce Shop page, we should use the date the latest product was modified.  Arnaud is handling this under #2126.

**Comment by arnaudbroes** [comment]
I'll take care of development for this if needed since it will be similar to what I do in #2126.

**Comment by arnaudbroes** [comment]
So we are also including the homepage twice; once in the Additional Pages index and another time in the Pages index. I'd suggest that we do the same as for #2126 which is leave it under Additional Pages if it is a post archive page and leave it under Pages if it is a static page.
