### ISSUE TITLE
Fix placeholder

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2622]
should be 1 then 2

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/2e61d1552f37d3f41904a6f18e69a7f44573e00c/admin/display/notices/review-plugin-notice.php#L24

**Comment by michaeltorbert** [comment]
1) Test and make sure it works with 1,1 instead of 1,2.
2) Add a translator comment, because translators may get confused thinking it's wrong.

**Comment by arnaudbroes** [comment]
Duplicate of #2638. 

I've created a PR to improve readability; will add a translator description as part of #803.
