### ISSUE TITLE
Add new post broken

### ISSUE THREAD

**Issue by BartGysens** [semperfiwebdesign/all-in-one-seo-pack#2630]
After updating to version 3.1

Uncaught TypeError: jQuery(...).tabs is not a function
    at HTMLDocument.<anonymous> (aioseop_module.js:543)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.J (jquery.js:2)

Additional info:

Uncaught Error: Undefined class constant
'DISPLAY_HELP_START' in
/home/ek2sz83820yt/public_html/wp-content/plugins/wpglobus/includes/vendor/class-wpglobus-aioseop.php:236
Stack trace:
#0 /home/ek2sz83820yt/public_html/wp-content/plugins/wpglobus/includes/vendor/class-wpglobus-aioseop.php(212):
WPGlobus_All_in_One_SEO->get_option_row('aiosp_keywords', Array,
Array)
#1 /home/ek2sz83820yt/public_html/wp-content/plugins/wpglobus/includes/vendor/class-wpglobus-aioseop.php(775):
WPGlobus_All_in_One_SEO->wpg_get_option_row('aiosp_keywords', Array,
Array, 'nl')
#2 /home/ek2sz83820yt/public_html/wp-includes/class-wp-hook.php(286):
WPGlobus_aioseop->on_admin_footer('')
#3 /home/ek2sz83820yt/public_html/wp-includes/class-wp-hook.php(310):
WP_Hook->apply_filters(NULL, Array)
#4 /home/ek2sz83820yt/public_html/wp-includes/plugin.php(465):
WP_Hook->do_action(Array)
#5 /home/ek2sz83820yt/public_html/wp-admin/admin-footer.php(73):
do_action('admin_footer', '')
#6 /home/ek2sz83820yt/public_html/wp-admin/post-new.php(83): inclu

**Comment by arnaudbroes** [comment]
@BartGysens dag Bart, bedankt om dit te rapporteren. Het gaat hier echter om een bug in WPGlobus die  in versie 2.2.9 werd verholpen. Ik raad je aan WPGlobus te updaten als je een oudere versie gebruikt.  Mocht dat niet het geval zijn, geef ons dan gerust een seintje.

**Comment by BartGysens** [comment]
Ok, bedankt voor je reply!

_______________________________

Bart Gysens
bart.gysens@gmail.com
0032 475 84 69 56
