### ISSUE TITLE
i18n - Fix placeholder in admin/class-aioseop-helper.php:451

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2632]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/3da681fc9e66a522414b5c17398af93aca10ca3c/admin/class-aioseop-helper.php#L451

**Comment by arnaudbroes** [comment]
This is actually good and shows up fine (see below), but I understand the confusion.

![image](https://user-images.githubusercontent.com/18156697/67722270-fdee0f00-f9d8-11e9-9280-9a7420be0af2.png)
