### ISSUE TITLE
i18n - Add translator comment

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2639]
It needs a placeholder comment anyway, also it may be confusing that it starts with 2.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/3da681fc9e66a522414b5c17398af93aca10ca3c/admin/class-aioseop-helper.php#L451

**Comment by arnaudbroes** [comment]
Duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2632. I'll go ahead and add the translator comment though.
