### ISSUE TITLE
Add FAQ about noindex and robots.txt

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2650]
As suggested here https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2637 we could add an FAQ that explains the difference between Noindex and Robots.txt and why you'd use them.

**Comment by tonyzeoli** [comment]
Cool, this would be helpful to those who get Google Search Console errors but don't see the rule written into the robots.txt file. Thanks!

**Comment by arnaudbroes** [comment]
Maybe also mention this - https://searchengineland.com/google-to-stop-supporting-noindex-directive-in-robots-txt-319003

**Comment by wpsmort** [comment]
@arnaudbroes Please review the doc here and publish - https://semperplugins.com/?post_type=documentation&p=5005

**Comment by arnaudbroes** [comment]
This has been published.
