### ISSUE TITLE
Google Analytics - Tracking code doesn't show up on CPT without AIOSEOP section

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2651]
Reported here: https://wordpress.org/support/topic/google-analytics-feature-is-not-working-with-custom-post-type/

Is there any reason we shouldn't have it show up everywhere? Maybe we should unhook it from the AIOSEOP section and just display it on every page?

**Comment by wpsmort** [comment]
I agree that Google Analytics should show up everywhere regardless of whether the user has AIOSEOP active on that page.  We should have a filter hook to enable users to remove it if they wish.

**Comment by arnaudbroes** [comment]
Agreed, this should show up on each page.

**Comment by michaeltorbert** [comment]
We either need to->

- Always show the AIOSEOP section, but only show this if the rest of the SEO functionality is disabled
- unhook and put GA code outside of and independent from the AIOSEOP section
- something else?
