### ISSUE TITLE
Better controls over welcome page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2662]
Probably in the updates file, we should make it explicit for when the welcome page appears... ie after major releases.

**Comment by arnaudbroes** [comment]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2631.

**Comment by arnaudbroes** [comment]
Requested again here - https://wordpress.org/support/topic/annoying-splash-screen-when-updating/
