### ISSUE TITLE
Make webmaster tool verification fields untranslatable

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2669]
With the exception of "Pinterest Site verification", is there a reason why we want these to be translatable? I don't think there's a different term for these in other languages.

* Google Search Console
* Bing Webmaster Tools
* Yandex Webmaster Tools
* Baidu Webmaster Tools

**Comment by michaeltorbert** [comment]
Is there any way to research it?

**Comment by arnaudbroes** [comment]
> Is there any way to research it?
Only thing I can think is going through our locales and see what our translators are doing with those strings.

**Comment by michaeltorbert** [comment]
That only works if that particular translator knows, which we may not be able to assume is the case.

**Comment by michaeltorbert** [comment]
Although looks like we can test it:
https://www.google.com/webmasters/tools/home?hl=es
https://www.google.com/webmasters/tools/home?hl=zh-cn

Looks like it is indeed not translated.
