### ISSUE TITLE
Correct URL casing

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2673]
Option label for Track Url Changes needs correct casing:

https://github.com/semperfiwebdesign/aioseop-pro/blob/dd73239a666035d2cdc8c34b0ee118ff7fcd4bc7/inc/commonstrings.php#L91

**Comment by arnaudbroes** [comment]
This was fixed in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2666.
