### ISSUE TITLE
  The function of this plug-in conflicts with many plug-ins, which will cause text overflow in the front end of the website. How to solve this problem?

### ISSUE THREAD

**Issue by cyberxsboy** [semperfiwebdesign/all-in-one-seo-pack#2683]
It conflicts with webp-express and Autoptimize plug-ins. Webp-express needs to cancel the cache, while the Autoptimize plug-in feels unable to set it. The text overflow prompt caused by the front-end conflict of the website is: 
http://images.gaofumei.net/Bug__ob_start_detected.png

In Ubuntu, you can search the home directory of the website by command. See the screenshot:
http://images.gaofumei.net/jiancetishi.png

**Comment by michaeltorbert** [comment]
This is expected behavior, not a bug. Not everyone can do output buffering. 
Try disabling force rewrites.

**Comment by cyberxsboy** [comment]
> This is expected behavior, not a bug. Not everyone can do output buffering.
> Try disabling force rewrites.

Is it because different plug-ins use the function of "caching enabled", that this conflict is caused?

Let me give it a try.

**Comment by cyberxsboy** [comment]
> 这是预期的行为，而不是错误。不是每个人都可以做输出缓冲。
> 尝试禁用强制重写。



> This is expected behavior, not a bug. Not everyone can do output buffering.
> Try disabling force rewrites.

Disable mandatory rewriting???

How do you disable this plug-in without this option?

**Comment by cyberxsboy** [comment]
> This is expected behavior, not a bug. Not everyone can do output buffering.
> Try disabling force rewrites.

Disable mandatory rewriting???

How do you disable this plug-in without this option?

**Comment by wpsmort** [comment]
Force Rewrites is the option on the Performance screen - https://semperplugins.com/documentation/performance-settings/

**Comment by cyberxsboy** [comment]
> Force Rewrites is the option on the Performance screen - https://semperplugins.com/documentation/performance-settings/

The point is, I'm not talking about this rewrite function. I'm talking about turning off the plug-in's caching function, because its internal'ob_start_detected'property always conflicts with other plug-ins' caching function, causing the front page to overflow with this prompt text.
