### ISSUE TITLE
Add setting for users to add extra code to GA snippet

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2687]
We might want to consider adding a setting where users can add extra code to their GA snippet for features we do not support yet.

**Comment by wpsmort** [comment]
@arnaudbroes We already have a couple of filters for this:

https://semperplugins.com/documentation/filter-all-in-one-seo-pack-google-analytics/
https://semperplugins.com/documentation/add-code-after-google-analytics-in-all-in-one-seo-pack/

Plus we're adding support for Google Tag Manager (https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1386) in v3.2 which enables users to do much more complex customizations with Google Analytics.

I don't think we need to add another option for this.

**Comment by arnaudbroes** [comment]
Wasn't aware we had a filter. I agree that we do not need a setting for this then.
