### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by alomotorlukurye** [semperfiwebdesign/all-in-one-seo-pack#2691]
ALL İN SEO İÇİNDE ÖZELLİKLER YÖNETİCİSİNDE ROBOT TXT VE DOSYA DÜZENLEYİCİ KISMI BİR TÜRLÜ AÇILMIYOR. GÖSTERMİYOR. SORUN NEDİR ACABA?
AHMET BAL alomotorlukurye.com

**Comment by wpsmort** [comment]
This is a development repository, not a support forum.  You can find an FAQ on this here - https://semperplugins.com/documentation/the-file-editor-or-robots-txt-modules-are-missing/ and customers with a valid license for All in One SEO Pack Pro can access support here - https://semperplugins.com/support/

**Comment by alomotorlukurye** [comment]
YANİ YARDIMCI OLMAYACAK MISINIZ.
