### ISSUE TITLE
All In One SEO Not Working!

### ISSUE THREAD

**Issue by sceniccycletours** [semperfiwebdesign/all-in-one-seo-pack#2695]
Suddenly Google is using my words on my home page sliders for a Description when people search for my site instead of the ALL in One SEO description it used to. WHY and how can I fix it?
![search 6 26 19](https://user-images.githubusercontent.com/52426887/60463387-b5783d80-9c00-11e9-962d-9b55a930be60.png)

**Comment by michaeltorbert** [comment]
First of all, there's no need to use exclamation points. We're humans. Don't yell at us.

Second, All in One SEO Pack does indeed work. What you're experiencing is covered in our documentation. https://semperplugins.com/documentation/why-doesnt-the-title-and-description-i-set-appear-in-search-results/

**Comment by tonyzeoli** [comment]
And all that keyword stuffing! Yikes!

>

**Comment by sceniccycletours** [comment]
Those are just the titles on my Home page Layer SliderS that search  
engines are using suddenly as my Description.

This is what it says in my All In One SEO Description area and what I  
want it to say again:

"Our Guided Bike Tours Are Fun, Safe & Fascinating! San Diego &  
Coronado are ideal for riders of all levels with separate bike paths &  
mild year-round weather."

I've removed all the actual text in the slider now and uploaded new  
images with the text embedded on them so hopefully that corrects it  
soon. Just wondering why this happeded - I love the Layer Slider text  
options...

----- Message from Tony Zeoli <notifications@github.com> ---------
    Date: Mon, 01 Jul 2019 17:41:17 -0700
