### ISSUE TITLE
All in one SEO Not working suddenly!

### ISSUE THREAD

**Issue by sceniccycletours** [semperfiwebdesign/all-in-one-seo-pack#2697]
Suddenly in searches my Description is all my text on my Home page Layer Slider NOT my All in One SEO Description like it used to be! Do you know why and how to fix it? Thanks
![search 6 26 19](https://user-images.githubusercontent.com/52426887/60474589-a5278900-9c27-11e9-9ac0-91a70842f78b.png)

**Comment by michaeltorbert** [comment]
Stop spamming us please. This has already been addressed.

**Comment by sceniccycletours** [comment]
My initial message said it couldn't send it from Safari. I went out  
for a bit and then tried again in Chrome. I wasn't spamming you - just  
didn't realize it had acturally been sent from Safari.

Sorry.
----- Message from Michael Torbert <notifications@github.com> ---------
    Date: Mon, 01 Jul 2019 17:53:21 -0700
