### ISSUE TITLE
Divi reporting an undefined variable issue

### ISSUE THREAD

**Issue by tonyzeoli** [semperfiwebdesign/all-in-one-seo-pack#2700]
Please fill out this form as completely as possible so that we can help you more quickly.

- [ ] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [ ] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**

**Describe the bug**
What happened?

Divi is reporting this in the log file: 

[03-Jul-2019 06:46:48 UTC] PHP Notice:  Undefined variable: post_type in /home/clearasheville/public_html/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 3983

What did you expect to happen?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version: 5.2.2
 - All in One SEO Pack version: latest
 - PHP version: 7.3

**Additional context**

Not sure, it was noticed in the log for this theme and I can't switch over on a live site.

**Comment by michaeltorbert** [comment]
Hi Tony, thanks for reporting this. 
We've got an issue open for it here, so I'll go ahead and close this one. https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798

Fortunately this is only a warning, so you can safely ignore it. Make sure to disable error logging on live sites.

**Comment by tonyzeoli** [comment]
Sounds good. Thanks!

>
