### ISSUE TITLE
XML Sitemap - Remove Change Frequency and Priority

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2704]
We should discuss whether to remove or keep these. Not all sitemap plugins even have them anymore, and Google may ignore them. https://twitter.com/methode/status/846796737750712320

We should investigate whether other search engines like Bing, Yandex, Baidu, etc use them.

**Comment by wpsmort** [comment]
John Mueller at Google confirmed later in 2017 that they ignore Priority and Change Frequency (https://twitter.com/johnmu/status/898150027054514176) and that they care about URL and Last Change date AKA <lastmod> - https://www.seroundtable.com/google-url-last-modification-date-24319.html.  

In addition, I found this more recent post with some clarification from John Mueller about the Last Change date - https://www.seroundtable.com/google-on-sitemap-dates-web-page-dates-27469.html

I've therefore changed the title of this issue to reflect that it's Priority and Frequency that we need to discuss whether to remove or keep.

**Comment by michaeltorbert** [comment]
Someone may want to verify whether any other search engines use them.

**Comment by wpsmort** [comment]
I couldn't find anything from Bing or Baidu on this but I did find that Yandex says they support Change Frequency and Priority - https://yandex.com/support/webmaster/controlling-robot/sitemap.html

**Comment by arnaudbroes** [comment]
Just throwing this out here but I'm good with removing this.

**Comment by michaeltorbert** [comment]
We do have a lot of Russian users, so I hate to alienate them. 
So we could 1) drop it completely, even though Yandex uses it, 2) move it to a free add-on plugin, 3) move it to a paid add-on plugin, or 4) move it to Pro

**Comment by michaeltorbert** [comment]
We also have a lot of issues about frequency and priority open. I recommend we find them all, remove their milestones, put them on hold as well, and link them to this issue.
