### ISSUE TITLE
Fix Scrutinizer code issues

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2711]
Scrutinizer is detecting more than 800 issues where we could improve the code. I'll go through and fix some with each version.

![image](https://user-images.githubusercontent.com/18156697/60767264-bce28f80-a0b5-11e9-9755-82ad1641410a.png)

**Comment by michaeltorbert** [comment]
Going through and fixing minor code issues isn't a good use of resources when we have a neverending list of github issues that are more important.
Unless there's something major, things like this should be fixed when working in that code.
