### ISSUE TITLE
Update Failed: Download failed. A valid URL was not provided.

### ISSUE THREAD

**Issue by leitah** [semperfiwebdesign/all-in-one-seo-pack#2712]
I encounter the following error:
Update Failed: Download failed. A valid URL was not provided.

All In One SEO PackUpgrade to Pro \| Documentation \| Support Forum \| SEO Settings \| Deactivate | Out-of-the-box SEO for your  WordPress blog. Features like XML Sitemaps, SEO for custom post types,  SEO for blogs or business sites, SEO for ecommerce sites, and much more.  More than 50 million downloads since 2007. 						Version 2.12.1 \| By Michael Torbert \| View details \| Feature Request/Bug Report
-- | --
Update Failed: Download failed. A valid URL was not provided.

**Comment by michaeltorbert** [comment]
Updates are 100% handled by WordPress, so this isn't related to AIOSEOP itself.
Try the update again. If that doesn't work, delete and reinstall the plugin.
