### ISSUE TITLE
Some Custom Permalinks missing paths in XML Sitemap When Dynamically Generated

### ISSUE THREAD

**Issue by mattypants** [semperfiwebdesign/all-in-one-seo-pack#2713]
Last week (July 2) my XML the dynamically generated XML sitemap began spitting 404s for 34 of my custom permalinks, most of which display properly in the sitemap. For now in order to remedy the problem, I've had to disable 'Dynamically generate XML sitemap', and the paths show. I've cleaned out old slugs from the database and that didn't help.

**Comment by michaeltorbert** [comment]
Please provide the steps to reproduce this issue.

**Comment by wpsmort** [comment]
I'm closing this as we've had no feedback from the user.
