### ISSUE TITLE
Create Schema release post

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2717]
Create a release post announcing the new Schema features.

**Comment by arnaudbroes** [comment]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2716

**Comment by wpsmort** [comment]
@arnaudbroes This is drafted and ready for review here - https://semperplugins.com/wp-admin/post.php?post=5023&action=edit&lang=en
