### ISSUE TITLE
Having trouble change the rich snippet Tittle when sending my link via iMessage

### ISSUE THREAD

**Issue by carlostiscareno** [semperfiwebdesign/all-in-one-seo-pack#2722]
![Screenshot 2019-07-10 12 20 15](https://user-images.githubusercontent.com/50848237/61239568-09504f80-a6f4-11e9-86f4-f48860a258f2.png)

Hi I've updated the plugin to see the change would happen but it's not. I currently have on web search 'Heater Furnace Air Conditioning AC Repair Service Southern California' and when I send the link via text message- appears as 'Heater Furnace Air Conditioning AC Repair Service Torrance' 

Not sure what else I need to do so this change happens. Please let me know what I should do. Thank you

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. If you'd like support, you can purchase an All in One SEO Pack Pro license here: https://semperplugins.com/all-in-one-seo-pack-pro-version/
