### ISSUE TITLE
Add documentation for aioseop_robots_meta filter hook

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2723]
> $robots_meta = apply_filters( 'aioseop_robots_meta', $this->get_robots_meta() );

@wpsmort am I correct that this filter is undocumented on our site?

**Comment by wpsmort** [comment]
@arnaudbroes I cannot find any documentation for that filter hook.

**Comment by arnaudbroes** [comment]
@wpsmort please review the documentation here and then publish it - https://semperplugins.com/wp-admin/post.php?post=4989&action=edit&lang=en

**Comment by wpsmort** [comment]
@arnaudbroes I couldn't get your example to work so I changed the if statement to use is_single() instead.  The doc has been published.
