### ISSUE TITLE
social settings

### ISSUE THREAD

**Issue by HelenD123** [semperfiwebdesign/all-in-one-seo-pack#2726]
Selected image from post. Not being picked up in Twitter or Linkedin correctly. Twitter shows wrong random image, LI shows none and FB shows correctly. FB doesn't show blog post title

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. You can read our documentation here: https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/
