### ISSUE TITLE
Page Title show the SEO TITLE

### ISSUE THREAD

**Issue by shaulhadarn** [semperfiwebdesign/all-in-one-seo-pack#2753]
Hello, I have a strange bug in a number of my sites.
The page title shows the meta data that is in ALL IN ONE SEO.

Please check this site to see what i mean.
Check the inner pages...

https://www.toronto-garage-repairs.ca/about-us/

**Comment by arnaudbroes** [comment]
That's what our plugin is meant to do.

**Comment by shaulhadarn** [comment]
i don't think you read my post...
