### ISSUE TITLE
Page's name gets the Page's title bug

### ISSUE THREAD

**Issue by shaulhadarn** [semperfiwebdesign/all-in-one-seo-pack#2765]
Hello, I tried posting before, but maybe i wasn't clear enough..

anyways, I have a page here :
https://www.toronto-garage-repairs.ca/about-us/

The page's original name is :"About Us"

The page's name currently shows:"About us - Garage Doors Toronto | 647-660-4792"
this is the page's title, and shouldn't show in the page's name area.
This is a really big bug, please help me fix this...

Thanks...

**Comment by shaulhadarn** [comment]
it as if the title and the page's name got mixed and switched places...

**Comment by arnaudbroes** [comment]
Please stop spamming us. As I mentioned before (https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2753), our plugin is meant to use the SEO title as the page/doc title.

**Comment by shaulhadarn** [comment]
Hi Arnaud, I am really sorry but i am not spamming you, i raised a
legitimate bug with your system, you could at least try to understand
what's going on.
I use your plugin for 5 years now and know exactly what it does,
I have an issue and i please need to at least check it out, is it too much
to ask?

**Comment by arnaudbroes** [comment]
@shaulhadarn with "spamming" I meant that you opened 2 issues on GitHub and one support thread on wordpress.org for the same issue.

I'm not entirely sure what you mean. Do you mean that the front-end of your page is using our SEO title as the H1?

**Comment by shaulhadarn** [comment]
Hi, i wrote in the wordpress support area, here is what i wrote, i hope you
can understand better...

If you go to this url:

https://www.toronto-garage-repairs.ca/about-us/

You will see a page named :
“About us – Garage Doors Toronto | 647-660-4792”
this is actually the information inside the SEO title and shouldn’t be
shown in that place. the correct page name is only “about us” without
anything after it.

A strange thing, is, when i am logged in wordpress, and than check the live
site, the page name shows ok, so maybe it is connected in some way, i don’t
know..

I am not sure but i think for some reason the plugin shows the information
there, and i hope this can be fixed…

If you need anymore information from me please let me know, i really want
to help you understand and fix this bug…


there's definitely something going on there, if you need my login please
let me know and i will send, maybe it will help you undersatnd better
what's going there...

**Comment by wpsmort** [comment]
By default, All in One SEO Pack outputs the <title> tag as Page Title followed by Site Title.  You can control this in the Title Settings (https://semperplugins.com/documentation/title-settings/) by removing %blog_title% or %site_title% from the Page Title Format field.

If you're saying that Garage Doors Toronto | 647-660-4792 is not your Site Title then we can look into this further but if that's your Site Title then the plugin is doing exactly what it should do.

**Comment by shaulhadarn** [comment]
Hi, my page title is set to:
%page_title%

this only need to show the page's name! I have hundreds of sites and i know
how the plugin works, I know what is the site title and everything. I am
trying to say that i configured everything as i usualy do but it is not
working well..

in my settings, the page's title should be only the name of the page, not
the additional information that is in the SEO title.

Can I send you the details for my site somewhere so you can check it??

Thanks...

**Comment by arnaudbroes** [comment]
@shaulhadarn try switching to the default theme and see what happens.

**Comment by shaulhadarn** [comment]
Hi Thanks, i tried the wordpress default theme and it worked as expected...
This is still a problem since there is some kind of conflict there than...

I sent you a contact form from the wordpress support url, and i put for you
the admin details for the site, please check it out, and maybe you could
find something there.....
Thanks,
Shaul.

**Comment by wpsmort** [comment]
@shaulhadarn By switching to the default theme you have proven that  the problem is with the theme and not All in One SEO Pack. You should contact the theme developer for support.

**Comment by shaulhadarn** [comment]
I understand, thanks for the help!
