### ISSUE TITLE
Full-width slider images disappear in Divi builder

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2767]
Reported here - https://wordpress.org/support/topic/problem-after-updating-plugin-2/

**Comment by wpsmort** [comment]
We've been unable to reproduce this and have requested a login from the user.

**Comment by arnaudbroes** [comment]
This happens when the plugin is updated to 3.2(<). There seem to be some styles lacking. However, when the plugin is deactivated and then reactivated, it's no longer broken.

**Comment by arnaudbroes** [comment]
Specifically et-core-unified-cached-inline-styles and et-core-unified-cached-inline-styles-2.

**Comment by arnaudbroes** [comment]
I've reached out to Divi for this issue as I have no idea what's causing this. They might be able to provide us with more insight.

**Comment by arnaudbroes** [comment]
This is the same as https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2772 so I'm closing this in favour of that one.
