### ISSUE TITLE
Don't output robots meta tag if values are index,follow

### ISSUE THREAD

**Issue by esolix** [semperfiwebdesign/all-in-one-seo-pack#2768]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x ] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [ x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

https://androidcommunity.com (on all pages)

**Describe the bug**
After upgrading to 3.2, it seems like all pages are now displaying `"<meta name="robots" content="index,follow" />"` which is the default behavior of all search engines. I think this is redundant.

Taken from Google Webmaster Guide
https://webmasters.googleblog.com/2007/03/using-robots-meta-tag.html

"Unnecessary content values
By default, Googlebot will index a page and follow links to it. So there's no need to tag pages with content values of INDEX or FOLLOW."

**To Reproduce**
1. Upgrade to 3.2

**Expected behavior**
Not showing <meta name="robots" content="index,follow" /> and only show those with nofollow and noindex

**Version Info (please complete the following information):**
 - WordPress version:5.2.2
 - All in One SEO Pack version:3.2
 - PHP version:7.3

**Comment by esolix** [comment]
Another fellow publisher experience the same thing (we dont have similar theme or framework) - https://geardiary.com/

**Comment by michaeltorbert** [comment]
I've been able to reproduce this. I'm marking it as low priority until after we've fixed the more urgent bugs.

**Comment by esolix** [comment]
> I've been able to reproduce this. I'm marking it as low priority until after we've fixed the more urgent bugs.

Thanks!
