### ISSUE TITLE
Version 3.2 and higher: Themedesign destroyed

### ISSUE THREAD

**Issue by nikko739** [semperfiwebdesign/all-in-one-seo-pack#2773]
Dear team,
with the version 3.2 and higher the design of the homepage is destroyed. When I do a  downgrade to 3.1.1 everything is ok. All other plugins are disabled and actual.

**Comment by wpsmort** [comment]
Please provide more information.  First deactivate all other plugins and switch to the default theme.  Then provide the exact steps to reproduce the problem and provide the WordPress version and PHP version.

**Comment by nikko739** [comment]
Done. There was also a themeupdate. After installing the themeupdate, all is fine.
