### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, boolean given in aioseop_class.php on line 4735

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2781]
Reported here https://wordpress.org/support/topic/error-message-767/

Also reported by Jim Douglas by email today.

**Comment by wpsmort** [comment]
Awaiting access to the sites so we can troubleshoot and reproduce.

**Comment by wpsmort** [comment]
Reported by Carole Asselin by email today.

**Comment by arnaudbroes** [comment]
This was happening because BuddyPress user profiles are considered as some kind of post type but there's actual post meta data tied to them which is why get_post_meta() is returning false instead of an array.
