### ISSUE TITLE
Test plugin with Chrome 76 LayoutNG

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2782]
From Ahmad Awais in the Advanced WordPress Facebook group:

I wanted to share an important development that impacts Gutenberg editor and/or #Gutenberg plugin/theme integrations. The Chromium (Chrome, Edge, etc) will have a new layout engine called LayoutNG (read about it here: https://www.chromium.org/blink/layoutng).

LayoutNG is a new layout engine for Chromium that has been designed for the needs of modern scalable web applications. It is scheduled to be released in Chrome 76 (next major version to be released relatively soon).

Several developers on Google/Microsoft teams have reported that there are issues with Gutenberg (esp. with Yoast Premium not sure about other plugins at this point). Chrome, Edge, Opera, Brave and all the browsers that will have LayoutNG "ON" by default pretty soon. I urge developers here to check out Gutenberg, their plugins/themes/products integration in the Chrome/Edge Canary versions to see if there's anything to be fixed.

**Comment by arnaudbroes** [comment]
For now, I don't see any changes/bugs on Windows.

**Comment by wpsmort** [comment]
I don't see any problems when testing with LayoutNG enabled.  Not, you have to go to chrome://flags/ in Chrome to enable this.

FYI...  The on-by-default for LayoutNG has been delayed until Chrome v77 due out soon (https://www.chromium.org/blink/layoutng).

**Comment by arnaudbroes** [comment]
Closing this as Chrome v77 is out and there are no issues.
