### ISSUE TITLE
All in one SEO latest update broke my theme?

### ISSUE THREAD

**Issue by LADGRES** [semperfiwebdesign/all-in-one-seo-pack#2784]
For some reason, the new code in the plugin (v3.2.1) has broken my theme.  Theme works great when I deactivate this plugin, looks like crap when it is active.  Just started with the last update and I have been trying to figure out what the issue is, but can't seem to find it.  Maybe something with js files  .... ?

**Comment by LADGRES** [comment]
I have narrowed it down to the 3.2 release.  I reverted back to 3.1 and everything working again ...

**Comment by arnaudbroes** [comment]
@LADGRES thank you for reporting this. Please provide us with your domain name and tell us which theme you are using.

**Comment by LADGRES** [comment]
G5 Theme - Beyot is the theme I am using
https://mtkchomes.com is the web site

**Comment by arnaudbroes** [comment]
@LADGRES we'll need to access your website to troubleshoot the issue. Please send us an admin login by filling in our secure support form here - https://semperplugins.com/contact/support-login-information/

**Comment by LADGRES** [comment]
I have already fixed the issue on my site - I reverted back to 3.1
Both versions 3.2 and 3.2.1 adversely affects the js/css on my site - I don't know the specifics, but don't want to use my live site to test your plugin.

**Comment by arnaudbroes** [comment]
@LADGRES there's not much we can do if we can't access your website or aren't able to reproduce the issue on our end. However, it's likely you're experiencing the same issue as https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2778 and that it will be resolved once we resolve that issue. 

I'm going to close your issue for that reason but please feel free to reopen it if you change your mind and would like to give us access to your website. We typically create a clone of your website on our test servers so we do not have to mess around on your live website.

**Comment by LADGRES** [comment]
Looks like update 3.2.2 took care of the issue - everything good :-)

**Comment by michaeltorbert** [comment]
That's great! Thanks for letting us know.
