### ISSUE TITLE
"Illegal string offset" errors related to /schema/graphs showing up at top of website

### ISSUE THREAD

**Issue by rhythmspice** [semperfiwebdesign/all-in-one-seo-pack#2789]
Please fill out this form as completely as possible so that we can help you more quickly.

- [ x ] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [ x ] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**
https://designingforanalytics.com

**Describe the bug**
PHP Errors displaying at top of page, even after disabling all other plugins except this one.

Warning: Illegal string offset 'width' in /home/betterd5/public_html/wp-content/plugins/all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 114

Warning: Illegal string offset 'height' in /home/betterd5/public_html/wp-content/plugins/all-in-one-seo-pack/inc/schema/graphs/graph-organization.php on line 115

**To Reproduce**

See screenshots; I have temporarily disabled the plugin to remove the error codes from my site so users do not see this. One screen shot shows all plugins active; the other (black/white) shows my URL with all plugins except SEO pack disabled. I also purged the cache multiple times via the Siteground plugin that offers this functionality.

**Expected behavior**

Do not expect to see error warnings at all.

**Screenshots**

Yes, attached - see above for comments.

![Screen Shot 2019-08-05 at 10 16 09 PM](https://user-images.githubusercontent.com/610006/62506515-f1d62500-b7ce-11e9-8612-5e4daaf625ae.png)

![Screen Shot 2019-08-05 at 10 12 46 PM](https://user-images.githubusercontent.com/610006/62506516-f1d62500-b7ce-11e9-846a-9146d57d4929.png)

**Version Info (please complete the following information):**
 - WordPress version: 5.2.2
 - All in One SEO Pack version: 3.2.1
 - PHP version: 7.1.30

**Additional context**
 
I installed "Debug Bar – Enable WP_DEBUG from admin dashboard" plugin trying to check the debug logs. It installed, but I couldn't figure out where the debug info was supposed to show up. HOWEVER, simply installing this tool, and turning on the debug feature made the SEO errors above disappear. Disabling this plugin or turning off the debug setting using the plugin causes the error to reappear.

**Comment by arnaudbroes** [comment]
@rhythmspice thank you for reporting this. We are aware of this issue and have already developed a fix for it (https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2775). It will be included in our next release which will hopefully be rolled out today.
