### ISSUE TITLE
Schema.org - Manually enter schema person info

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2792]
Currently, you can only select Author, Editor or Administrator. We should consider being able to manually add this info.

_Requested by Bula via email:_

> Person "Username" - There should be an option to manually enter in the person's information without them being a user as many clients have not presence in the back end.

**Comment by not-enough-yet** [comment]
+1 Definitely need this.

**Comment by wpsmort** [comment]
Ben and I discussed the following:

- We could turn the drop down into a text field with auto-suggest where you start typing a name and if a WP user matches the name then we auto complete.  If the name doesn't match a WP user then the typed name would be used.  
- We then need a solution for the person logo (avatar) so do we then display an add image field where you can upload the avatar for the manually entered person.

**Comment by EkoJR** [comment]
I was unable to use selectizer as a 'drop down into a text field with auto-suggest'. It requires valid data to be entered, and could not find a way to allow manually entered data.

I had to keep the same drop down, but added "Manually Enter" as an option that will bring up the additional options for the name and image.
