### ISSUE TITLE
XML Sitemap - addl file still generated when there is no static posts page

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2794]
Reported here - https://wordpress.org/support/topic/issue-with-addl-sitemap-xml/

If the homepage is set to a static page but the posts page is left blank (--select--), then the addl-sitemap is still generated. 

I'll take care of this one.

**Comment by Garconis** [comment]
FWIW, we also have this issue with `addl-sitemap.xml`: https://freshysites.com/sitemap.xml

- Screenshot of AIOSEO settings: https://d.pr/free/i/U6IZji
- Screenshot of WP "Reading" Settings: https://d.pr/free/i/4HlkfF

**Comment by arnaudbroes** [comment]
Reported again by Brian O. via e-mail.

**Comment by arnaudbroes** [comment]
@Garconis thank you for reporting this. The issue should be fixed in our next release.
