### ISSUE TITLE
General - Noindex for paginated content does not apply to paginated homepage

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2797]
Reported here: https://wordpress.org/support/topic/the-robots-meta-tag-does-not-work/

> in the plugin version 3.2.2, the noindex meta tag on the pagination page stopped working. When switching from the main page of the site to the page pagination meta tag noindex no.
> 
> https://vellisa.ru/page/2
> 
> In the plugin settings, this option is enabled.
> 
> http://i.piccy.info/i9/12c2443fab24df6ce75d804a9778904b/1565170889/14923/1329154/2019_08_07_123818.png

and here: https://wordpress.org/support/topic/noindex-for-pagination-pages/

> In version 3.2.2. robots (noindex) meta tag parameters for pagination pages in HTML code are not displayed, although they are specified in the settings.

**Comment by wpsmort** [comment]
I've reproduced the first issue here where noindex is no longer added to the paginated homepage.  

I have not been able to reproduce the second issue regarding paginated pages so I've requested more info from the person who reported this.

I need to some research into noindex for paginated homepages to see what the best practice is.

**Comment by wpsmort** [comment]
@arnaudbroes As discussed today, we need to fix the problems with noindex / nofollow on paginated content that we introduced in v3.2.
