### ISSUE TITLE
Fatal error:  Call to undefined function array_column() in modules/aioseop_sitemap.php on line 4651

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2799]
This happens in the video sitemap only when running PHP 5.4:

Fatal error:  Call to undefined function array_column() in modules/aioseop_sitemap.php on line 4651

**Comment by michaeltorbert** [comment]
array_column() was only introduced in PHP 5.5. We are using it in two places in that file.

**Comment by michaeltorbert** [comment]
@wpsmort The line number doesn't match up. Compare your aioseop_sitemap.php with the one in https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/modules/aioseop_sitemap.php
array_collumn is used on 4612 and 4644.

**Comment by wpsmort** [comment]
It's line 4644 from the current master.  I was seeing it on line 4651 because I was testing PR #2798.
