### ISSUE TITLE
Bug - Cannot add sitemap URL to Google Search Console

### ISSUE THREAD

**Issue by JovoVranjes** [semperfiwebdesign/all-in-one-seo-pack#2802]
Hi
As of today, August 8th, I noticed in several sites already that new posts cannot be added to Search Console. This seems to be after the latest AIO update.

Note that all previously generated posts' urls can be added to the webmaster. I tested it after modifying the existing posts.
Can you help with this? Thank you in advance.
Jovo

**Comment by wpsmort** [comment]
@JovoVranjes Can you provide more details such as the exact steps you're following, any error messages you're seeing and screenshots that show what's happening.  If we don't get steps to reproduce the problem then we cannot help you.  You should note that All in One SEO Pack does not interfere in any way with adding URLs to Google Search Console.

**Comment by michaeltorbert** [comment]
Closing as it's been a month with no followup. 
@JovoVranjes If you can provide steps to reproduce this, the issue can be reopened.
