### ISSUE TITLE
Code Refactor - Move PHP compatibility functions to compatibility/php-functions.php

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#2806]
**Is your feature request related to a problem? Please describe.**
PR #2800 introduced a file to containing PHP functions for compatibility with older PHP versions. Some other PHP compatibility functions still exists elsewhere, primarily with `inc/functions.php`.

Moving rest of the php compatibility functions into one file will make it easier to locate, and when older PHP versions aren't supported then it can be deprecated/removed.

**Describe the solution you'd like**
Move functions to new file ( `compatability/php-functions.php` ) .

**Additional context**

**Comment by arnaudbroes** [comment]
I already did this in 3.3.
