### ISSUE TITLE
Please help issues with all in one seo breaking the website

### ISSUE THREAD

**Issue by erichz123** [semperfiwebdesign/all-in-one-seo-pack#2810]
all in one seo is breaking forms on the website
go here : https://www.baronchestney.com/homes-for-sale-details/370-BRANDON-WAY-MENLO-PARK-CA-94025/ML81764212/190
and you get (attached)
![allinoneseobreaks_forms](https://user-images.githubusercontent.com/8279756/62888403-6a237580-bcfc-11e9-8f72-ae8dcc9cf40a.jpg)

**Comment by michaeltorbert** [comment]
@erichz123 Please fill out the bug report form as completely as possible. https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new/choose

**Comment by michaeltorbert** [comment]
Closing as a duplicate.
