### ISSUE TITLE
All in one  seo issue

### ISSUE THREAD

**Issue by erichz123** [semperfiwebdesign/all-in-one-seo-pack#2811]
Please fill out this form as completely as possible so that we can help you more quickly.

- [ ] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [ ] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**
https://www.baronchestney.com

**Describe the bug**
What happened?
the forms are broken when all is one is active

What did you expect to happen?
that it wouldn't break the forms 

**To Reproduce**
1. Go to 'https://www.baronchestney.com/homes-for-sale-details/370-BRANDON-WAY-MENLO-PARK-CA-94025/ML81764212/190'
2. just scroll
3. Scroll down to
see attached for how it should look

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version:
 - All in One SEO Pack version:
 - PHP version:

**Additional context**

![how_it-should_look](https://user-images.githubusercontent.com/8279756/62890426-b83a7800-bd00-11e9-8e7c-801f5ac7ca0b.jpg)

**Comment by michaeltorbert** [comment]
@erichz123  Steps to reproduce don't mean on your site, it means steps for us to reproduce on our own site so we can determine if there is a bug to fix, and then fix it.
