### ISSUE TITLE
XML Sitemap - &rsquo; in image title returns error in Search Console

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2823]
Reported here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/sitemap-syntax-error/

User reported getting this error in Google Search Console:

XML parsing error: undefined entity

The line in question is an image title as follows:

`<image:title>In Situ &#8211; Banque d&rsquo;accueil</image:title>`

It's the use of `&rsquo;` as an apostrophe that Google didn't like.

**Comment by wpsmort** [comment]
I'm unable to reproduce this either by using the keyboard shortcut on Mac for a single quote or by pasting the HTML code into the Image Title field. However, in each test it gets encoded correctly in the sitemap. 

@arnaudbroes Can you see if you can reproduce this on Windows please.

**Comment by arnaudbroes** [comment]
This is the same as https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2177 which was fixed in v2.12. User was using an older version (v2.10.1).
