### ISSUE TITLE
Release docs and checklist

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2829]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/wiki/Release-documentation-and-checklist

Check anything you've completed, and put your name next to it.

- [x] Make release checklist issue for your new version.
- [ ] Copy/paste from old checklist.

**Comment by arnaudbroes** [comment]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/wiki/Releasing-All-in-One-SEO-Pack-to-wordpress.org
