### ISSUE TITLE
Robots.txt - Add support for crawl-delay directive

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2836]
Requested here - https://wordpress.org/support/topic/adding-crawl-delay-to-robots-txt-file/. 

I'm open to adding this to the plugin. Google ignores it but other search engines don't (Bing, Yahoo) and their crawling might take up resources that are best used elsewhere.

Thoughts @michaeltorbert @wpsmort?

**Comment by arnaudbroes** [comment]
> I don't believe we should add this because it's not part of the proposed IETF standards for robots.txt. See my comment here - [#46 (comment)](https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/46#issuecomment-508209212)

Agreed.

**Comment by meek2100** [comment]
@arnaudbroes & @wpsmort,
If you won't provide direct support in the plugin you should provide steps to disable All in One SEO's Robot.txt file and to use a custom one.  Or just add support that a user can use a File editor to customize it how they need it like Yoast SEO does. 
 https://yoast.com/help/how-to-edit-robots-txt-through-yoast-seo/
 
 Getting DDOS by a crawler is a real issue and crawl-delay is a way to address it.   So maybe it doesn't need to be the preferred path, but an alternative path should be supported.

**Comment by arnaudbroes** [comment]
@meek2100 we use the official WP Core hook for the robots.txt (https://developer.wordpress.org/reference/hooks/robots_txt/), so if you'd like you can simply hook into it as well after AIOSEO does and add the crawl-delay directive. You can also remove AIOSEO's callback for that hook if you'd like to disable what AIOSEO does. Alternatively, you can add a physical file yourself in your site's root directory, which will automatically override any dynamically generated files.
