### ISSUE TITLE
How to create custom tags

### ISSUE THREAD

**Issue by CreativForm** [semperfiwebdesign/all-in-one-seo-pack#2838]
Hi guys.

Im author of CF Geo Plugin and want to add custom tags in the SEO title & description like `%%city%%`, `%%state%%`, etc.

This support I add to Yoast as well and want add it also to your plugin.

Can you give me some hook or filter where I can connect my plugin with your?

Thanks!

**Comment by arnaudbroes** [comment]
@CreativForm https://semperplugins.com/documentation/aioseop_title_format/ can be used for this. I'll go ahead and close the issue, but if you have any other questions, then please contact us here - https://semperplugins.com/contact/
