### ISSUE TITLE
WordPress v5.3 changes behaviour when site is private

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2857]
WordPress 5.3 will change how WordPress discourages indexing on private sites:

- The "Disallow: /" directive in the robots.txt file will be removed.
- The default meta tag changes to `<meta name='robots' content='noindex,nofollow' />`.

@wpsmort can you take a look and see if this affects our robots.txt file? It will not affect our robots meta tag code but I'll have to make some adjustments in the new unit tests that I'm working on.

FYI, WP 5.3 is expected to be released around November 12, 2019.

**Comment by michaeltorbert** [comment]
Good find Arnaud!

For reference:
https://make.wordpress.org/core/2019/09/02/changes-to-prevent-search-engines-indexing-sites/
https://core.trac.wordpress.org/ticket/43590

**Comment by michaeltorbert** [comment]
Moving this to 3.3 until we've determined whether it affects us.

**Comment by wpsmort** [comment]
I've checked this and can confirm that it does not affect our Robots.txt file.  

All that will happen is that the default robots.txt rules will be displayed instead, i.e. the robots.txt will look like this:

User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php

I'm going to leave this open and assigned to me to test when the first Beta for WP 5.3 is released.

**Comment by wpsmort** [comment]
Now that WP v5.3 is out, I've tested this again and confirmed that we have no compatibility issues with the way WP handles the Search Engine Visibility setting now.
