### ISSUE TITLE
Social Meta Module - http loading over https for og:image

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#286]
It shows up as http in the source code as well for the og:image (Facebook may or may not care), but causes an error in Chrome dev tools in the edit post screen for mixed content.

**Comment by michaeltorbert** [comment]
This seems to be fixed in a previous version. @wpsmort Can you confirm?

**Comment by wpsmort** [comment]
@michaeltorbert I have confirmed this on my Pressmatic site running the latest dev branch.  This is only an issue if you select the radial next to an image in the Social tab of the post.  This also affects the Twitter image and the meta image.

See screenshot:

![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/19748926/fab40d26-9bb2-11e6-8196-7f1aa0df6361.png)
![screen-capture](https://cloud.githubusercontent.com/assets/17548525/19748925/faac690e-9bb2-11e6-8b8b-5691f193717c.png)

**Comment by wpsmort** [comment]
@michaeltorbert The Twitter image is still being output as HTTP but the other image URLs are now correctly showing as HTTPS:

<link rel="canonical" href="https://aioseop.dev/post-with-seo-meta-and-og-meta/" />
<meta property="og:url" content="https://aioseop.dev/post-with-seo-meta-and-og-meta/" />
<meta property="og:image" content="https://aioseop.dev/wp-content/uploads/2014/01/dsc20050315_145007_132.jpg" />
<meta name="twitter:image" content="http://aioseop.dev/wp-content/uploads/2014/01/dsc20050315_145007_132.jpg" />
<meta itemprop="image" content="https://aioseop.dev/wp-content/uploads/2014/01/dsc20050315_145007_132.jpg" />

**Comment by wpsmort** [comment]
This is tested and is good.
