### ISSUE TITLE
Invalid Robots.txt file

### ISSUE THREAD

**Issue by RomanRuss** [semperfiwebdesign/all-in-one-seo-pack#2860]
In the constructor of the plugin All in one seo pack creates invalid file robots and nothing can be done
When you add a rule, the agent repeats
 cannot delete predefined rules
Empty lines in the file
https://mumpups.ru/robots.txt
Help me, please fix it
![QIP Shot - Screen 039](https://user-images.githubusercontent.com/54832940/64148468-09cfb180-ce2c-11e9-89a2-e561be626021.png)

Thank you!

**Comment by wpsmort** [comment]
@RomanRuss Please can you provide more detail.  What is the invalid file?  

The default rules are added by WordPress and are added to every WordPress site.  WordPress has a filter hook for filtering their default robots.txt - https://developer.wordpress.org/reference/hooks/robots_txt/

**Comment by RomanRuss** [comment]
File has a two same operator as you see on screenif I add the right for all statements.  Yandex considers this a mistakeFor example:User-agent: *Disallow: /wp-admin/Allow: /wp-admin/admin-ajax.phpUser-agent:*Disallow: /cart03.09.2019, 16:54, "wpsmort" <notifications@github.com>:@RomanRuss Please can you provide more detail.  What is the invalid file?
The default rules are added by WordPress and are added to every WordPress site.  WordPress has a filter hook for filtering their default robots.txt - https://developer.wordpress.org/reference/hooks/robots_txt/

**Comment by arnaudbroes** [comment]
@RomanRuss thank you for getting back to us. We are aware of this issue with Yandex and have an open issue for it here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2487.

**Comment by RomanRuss** [comment]
How I can make robots from myself and do not use your file?03.09.2019, 23:59, "Arnaud Broes" <notifications@github.com>:@RomanRuss thank you for getting back to us. We are aware of this issue with Yandex and have an open issue for it here - #2487.

**Comment by michaeltorbert** [comment]
@RomanRuss You can disable the Robots.txt module.

**Comment by RomanRuss** [comment]
Could you tell me, please, as? 04.09.2019, 14:46, "Michael Torbert" <notifications@github.com>:@RomanRuss You can disable the Robots.txt module.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.  -- Sincerely, Roman J.
