### ISSUE TITLE
make bool ready for php upgrade

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2863]
In a recent version, we had to change boolval() to (bool) to accomodate older versions of PHP.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/e780901af2ef8b690c53fbe7e87ab960e76852bf/aioseop_class.php#L4408

We should do something to support older versions of PHP, but then make it obvious when it's time for us to drop support.

Possible choices:

`if (!function_exists('boolval')) {
        function boolval($val) {
                return (bool) $val;
        }
}`

`if ( version_compare( PHP_VERSION, '5.5', '>=' ) ) {`

**Comment by michaeltorbert** [comment]
@EkoJR @arnaudbroes Any input?

**Comment by arnaudbroes** [comment]
The latter is more clear to me.

**Comment by michaeltorbert** [comment]
It also probably makes it more obvious when dropping PHP support, since we just have to search for version_compare.

> The latter is more clear to me.
