### ISSUE TITLE
Changes to prevent search engines from indexing sites in WordPress 5.3

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2865]
https://make.wordpress.org/core/2019/09/02/changes-to-prevent-search-engines-indexing-sites/

Creating this issue as a reminder to determine how this affects us.

**Comment by arnaudbroes** [comment]
Isn't this the same as https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2857?

**Comment by michaeltorbert** [comment]
@arnaudbroes  Of course. I'm just making sure you're paying attention. ;)
