### ISSUE TITLE
jquery issue on edit post screen seems to be back

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#287]
in the latest live pro, the recent jquery tabs issue seems to be back (from #221)

in my 3.5alpha free version it's completely broken... social tab doesn't appear at all

**Comment by wpsmort** [comment]
@michaeltorbert: 

I installed AIOSEOP Pro v2.4.4.2 and found that when you switch tabs there was a browser console error:

Uncaught Error: Syntax error, unrecognized expression: .aioseop_header_tab[href!=#aioseop_opengraph_settings]

I tested with Pro v2.4.5 and the error was no longer present.  I also tested with the current live version of Pro and couldn't replicate the issue.  

Interestingly, I could not replicate this at all in free and I can find no issues or commit where we fixed this.

**Comment by arnaudbroes** [comment]
We've redid the tabs a while ago so this can be closed.
