### ISSUE TITLE
AMP Head unexpectedly returns when there is no AIOSEOP Description 

### ISSUE THREAD

**Issue by EkoJR** [semperfiwebdesign/all-in-one-seo-pack#2875]
When working on Add JSON-LD Schema for AMP #506, I found posts not displaying any form of meta data on amp posts/pages when attempting to add additional data (Schema) to `All_in_One_SEO_Pack::amp_head()`.

The problem occurs when mistaking an empty string for a false value; which is intended for `aioseop_amp_description` hook ( https://semperplugins.com/documentation/disable-meta-description-on-amp-pages/ ). 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/8b5b6a6960af511fdd786d5a42b8d768044b05dd/aioseop_class.php#L4146

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Describe the bug**

Meta data that is currently available with AMP wasn't displaying any data, even though it was an empty value.

Data should still display, or be changed to only omit the meta description so that other AMP operations can continue.

**To Reproduce**
1. Install and Activate AMP plugin.
2. Go-to/Create a post with no AIOSEOP Description.
3. Go to view post on frontend.
4. Click AMP on the top Admin menu to render page as AMP.
5. Inspect code, and there is no meta description.

**Expected behavior**
Unless the disable filter is used. Meta data should still be added, and/or other operations with AMP should be allowed to continue.

**Version Info (please complete the following information):**
 - WordPress version: 5.2.3
 - All in One SEO Pack version: 3.2

**Additional context**

**Comment by EkoJR** [comment]
This would also be more of a refactor since there wouldn't be any way to test the changes with the output. Essentially, it is a concept flaw to the function's operations itself, and prevents other operations; which **Add JSON-LD Schema for AMP** #506 is dependant on.

**Comment by michaeltorbert** [comment]
@EkoJR What is your recommendation? Should we bump this to a later version?

**Comment by EkoJR** [comment]
@michaeltorbert This will have to be included in this version. PR #2979 is dependant on the change and has the change included as well.

It's included because there would be no difference in the output, and is more of a refactor to improve already existing code. Even if the change was applied separately, an empty string would still prevent any output (no changes). At first sight, I thought this was a bug (sorta is), but later found out it was just preventing other operations within the function which made it appear to be more of a refactor.

This is also related to WPCS with strict comparators; using `===` rather than `==`.
