### ISSUE TITLE
Double robots noindex tags output

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2881]
**Describe the bug**
In certain specific circumstances, two robots noindex meta tags are output in the source code of a post/page.

**To Reproduce**
1. Go to Settings > Reading and enable the option for Search Engine Visibility
2. Create a post, enable the Noindex this post option and publish the post
3. View the source code and you'll see one robots noindex tag output by WordPress (i.e. not inside the output from All in One SEO Pack)
4. Go to All in One SEO > General Settings > Content Type Settings and uncheck Posts and save
5. View the source code of the post again and you'll see two robots noindex tags, one from WordPress and one from us.

**Expected behavior**
We should not output a noindex tag when Search Engine Visibility is enabled in WordPress. 

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version: 5.x
 - All in One SEO Pack version: 3.2.x

**Comment by arnaudbroes** [comment]
This is a pre-existing bug because get_robots_meta() occurs twice in aioseop-class.php - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2877.

**Comment by michaeltorbert** [comment]
Moving this to 3.4 since it's not new.

**Comment by arnaudbroes** [comment]
I've already fixed this.
