### ISSUE TITLE
XML Sitemap can't be generated

### ISSUE THREAD

**Issue by kseniyaoskerko** [semperfiwebdesign/all-in-one-seo-pack#2885]
I added a plugin "All in one SEO". But XML Sitemap can't be generated for no reason. I follow all recommendations but without a success. RSS file was generated, but not XML.

What can I do?

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. 
The XML Sitemap functionality works, which indicates this is likely an issue specific to your website.

You can use the troubleshooting steps here to narrow down a possible plugin or theme conflict: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
If you'd like us to troubleshoot it for you, you can purchase a support license here and our Support Team will be happy to take a look: https://semperplugins.com/all-in-one-seo-pack-pro-version/
