### ISSUE TITLE
Nonexistent pages included in sitemap

### ISSUE THREAD

**Issue by sbiese** [semperfiwebdesign/all-in-one-seo-pack#2891]
Google is telling me that my sitemap includes pages that aren't there. I checked and sure enough, they are not there. However, when I create a sitemap, it keeps including these pages. Why is it doing that and how do I get rid of them?

**Comment by michaeltorbert** [comment]
I’d love to tell you. In order for me to do that you’ll need to provide some more details about the pages.

**Comment by sbiese** [comment]
http://restoremotion.com/miriam-graham-pt-dpt-mba/
http://restoremotion.com/oyinda-awe-pt-dpt/

**Comment by michaeltorbert** [comment]
@sbiese That's really not helpful. I have no way of knowing what those pages are.
Where they old posts you deleted? Content created by another plugin or your theme?

All in One SEO Pack doesn't just make up pages to include in the sitemap. If those pages are showing up, it's because they exist in the database. In order for us to do anything about it, you need to give us more information, such as how they got there, why they now 404 on the front-end, etc.

**Comment by sbiese** [comment]
I can't be sure. But, I'm guessing they are pages that the owner of the site deleted. There's nothing in thee Trash folder. What I don't understand is why would AIO put them in the sitemap file if they clearly don't exist anymore?

**Comment by michaeltorbert** [comment]
> What I don't understand is why would AIO put them in the sitemap file if they clearly don't exist anymore?
Again, they clearly do exist in the database. 

If you'd like us to take a look at why they're showing up, you can submit your login info to our secure form here: https://semperplugins.com/contact/support-login-information/

**Comment by michaeltorbert** [comment]
@sbiese There's no entry from you.

**Comment by sbiese** [comment]
I did a search on the database and it didn't find these pages.

**Comment by sbiese** [comment]
I'll try sending it again.

**Comment by wpsmort** [comment]
@sbiese I checked the XML Sitemap and don't see either of those two URLs.  All I see in the XML Sitemap are the 44 published posts and 30 published pages which is correct.

I notice that there's some caching happening on your site and your XML sitemap is being cached.  I could make changes to the XML Sitemap configuration but those changes wouldn't take effect until I clicked on Clear Sucuri Cache and did a hard refresh.  This could explain why URLs were appearing in the XML Sitemap after the pages/posts had been deleted from the site.  You should find out how to exclude the XML Sitemap URL from caching so this doesn't happen in future.

**Comment by sbiese** [comment]
Awesome! Can't believe I missed that.

**Comment by michaeltorbert** [comment]
@sbiese 

Thanks for the followup. We're glad to see it's working for you.
Would you mind taking a moment to help us out and let others know with a 5 star review? https://wordpress.org/support/plugin/all-in-one-seo-pack/reviews/?rate=5#new-post
