### ISSUE TITLE
Error "A value for the logo field is required"

### ISSUE THREAD

**Issue by JovoVranjes** [semperfiwebdesign/all-in-one-seo-pack#2900]
Hi
I am using option Schema within AIO and after checking in Google's Structured Data testing tool, get the error "A value for the logo field is required" which appears 3 times **when I check a post**. 
So how to solve this issue? Thanks.

**Comment by wpsmort** [comment]
@JovoVranjes This is not a support forum, this is a development repository.  You can find documentation on the Schema Settings in All in One SEO Pack (including the Organization Logo option) here - https://semperplugins.com/documentation/schema-settings/
