### ISSUE TITLE
About editor bugs

### ISSUE THREAD

**Issue by ryo2mattock** [semperfiwebdesign/all-in-one-seo-pack#2903]
Hi,The ALL in one SEO form that was fixed at the bottom of the editor is displayed on the editor. This issue has occurred since the last plug-in update.

Pls check it,thanks!

**Comment by michaeltorbert** [comment]
@ryo2mattock You can use these troubleshooting steps to narrow down a plugin or theme conflict. Make sure to clear your cache between each step.
https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

**Comment by wpsmort** [comment]
I'm closing this as we've had no feedback from the user.
