### ISSUE TITLE
SEO info is in the middle of the wordpress editor

### ISSUE THREAD

**Issue by richardurban444** [semperfiwebdesign/all-in-one-seo-pack#2918]
Hi.  Suddenly, the SEO info that should be at the bottom of the editor is in the middle of the page.  When I try to drag it down, it pops back up to the previous position in the middle of the page.
WordPress version 5.2,3
all in one seo version 3.2.7

**Comment by michaeltorbert** [comment]
This is a known bug in Gutenberg, which conflicts with the latest version of the Chrome browser, and affects every plugin with metaboxes, not just AIOSEOP.
They’re fixing it in WordPress 5.3 due out in a few weeks, although I think if you install the actual Gutenberg plugin it’s already fixed there.
We’ll also be releasing 3.2.8 (hopefully today) to “fix” it on our end.
