### ISSUE TITLE
XML Sitemap not generated

### ISSUE THREAD

**Issue by UnknownGuy123** [semperfiwebdesign/all-in-one-seo-pack#2919]
Hi there on my website:
https://smartwheels.io/
Im using the sitemap feature:
![image](https://user-images.githubusercontent.com/20700707/65177426-a7c69d00-da24-11e9-8b43-ea56d256e4e5.png)

but when I go onto the sitemap, error 404 not found.
https://smartwheels.io/sitemap.xml

Thank you!

**Comment by michaeltorbert** [comment]
There's a redirect from another plugin conflicting.
Use these troubleshooting steps: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/
