### ISSUE TITLE
Code Refactor - Define AIOSEOP_VERSION using get_file_data function

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2926]
https://developer.wordpress.org/reference/functions/get_file_data/

**Comment by michaeltorbert** [comment]
Please don't put the code for this, other than a function call at the most, in the main plugin file. ;)

**Comment by EkoJR** [comment]
Example https://github.com/Advanced-Post-List/advanced-post-list/blob/02af4254d0a21cf2327483d4756ce21e42f6a607/class-apl-core.php#L122
