### ISSUE TITLE
option to host ga.js locally

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#293]
Hosting google analytics locally can improve page load times.

As this changes often, we probably want some method of updating the code periodically.

https://wordpress.org/plugins/local-gajs/
https://bjornjohansen.no/host-ga-js-locally-wordpress-plugin

We should look into any downsides to doing this, and if we want it to be the default behavior. 
One option is to have a filter hook.

**Comment by contactashish13** [comment]
@michaeltorbert @wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1439

I've added a filter hook to switch this feature off as well: 
```
apply_filters( 'aioseop_ga_host_locally', true )
```

**Comment by wpsmort** [comment]
@contactashish13 I tested the PR but found two problems:

1). It adds a second block of Google Analytics tracking code at the top of the source code
2). It defaults to the GA script being loaded from the local source when this should only be changed if the filter is used.  By default the GA script should be loaded from https://www.google-analytics.com/analytics.js

See screenshot:

<img width="1073" alt="screen shot 2018-05-23 at 1 30 21 pm" src="https://user-images.githubusercontent.com/17548525/40441117-1072ee6c-5e8e-11e8-8c8c-b034ea740288.png">

**Comment by michaeltorbert** [comment]
I'm going to close this issue and corresponding PR, as we only provide relatively basic GA functionality.  Generally, if someone wants more GA functionality, they should use a plugin specific for GA (as we do internally).
If someone can make a case for including this, it can be reopened.
