### ISSUE TITLE
All the categories were inexplicably added with noindex

### ISSUE THREAD

**Issue by overbegin** [semperfiwebdesign/all-in-one-seo-pack#2935]
my site All categories were inexplicably added with noindex。
in all in one seo settings  "Use noindex for Categories" has been cancled.
![image](https://user-images.githubusercontent.com/43157854/65586183-4ec3af80-dfb6-11e9-9811-fd48a4d28f46.png)
![image](https://user-images.githubusercontent.com/43157854/65586248-6ef36e80-dfb6-11e9-9e70-81ebcc523240.png)

**Comment by michaeltorbert** [comment]
That's most likely not coming from this plugin.
