### ISSUE TITLE
Social Meta - Description pulled from post instead of AIO description

### ISSUE THREAD

**Issue by vir2lboy** [semperfiwebdesign/all-in-one-seo-pack#2944]
Hello AIO team,
I installed the Social Meta extension and I did a test on Twitter, everything works out great except for the "Description" text, it's outputting the text from the Post's description instead of the description that I typed in manually for that given post, which I always do just to better highlight the details of the post's content.
Any way we can force the Description to be pulled from the AIO description of the posts instead of what the users wrote in their post?

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/
