### ISSUE TITLE
Schema.org phone number should include +

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2945]
Reported by Tim via email.
-------- 

According to https://developers.google.com/search/docs/data-types/corporate-contact#definitions, the country code should include a "+". 
If this is the case, we should enforce this on our end.

Strangely, in example 2, this doesn't seem to be the case: https://schema.org/telephone

This needs to be verified, and if there's a change, we need to update our documentation to be more specific.

**Comment by arnaudbroes** [comment]
This should take care of this - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2764

**Comment by michaeltorbert** [comment]
I've posted my comment on the other issue.
