### ISSUE TITLE
robots.txt file altered when cloning?

### ISSUE THREAD

**Issue by card1concepts** [semperfiwebdesign/all-in-one-seo-pack#2946]
Hello, 

I have a site set up with a staging site in a subdirectory labeled "staging" on my host server.

I am using the host software called Installitron to clone the staging site to a production site.

In my staging site I have a disallow rule set up for the staging directory.
example -  Disallow: /staging/

When I clone the site and inspect the robots.txt settings in the All In One SEO plugin this rule is being changed from Disallow: /staging/   to   Disallow: /   which as you can imagine is not good thing.

If I had to guess, the scripts that are cloning the site from the staging directory to the root directory are replacing any instance of /staging/ with just / in the database?

Would you have any thoughts or solutions to this issue? 

Thank you for your time.

**Comment by michaeltorbert** [comment]
You've come to the development repository for All in One SEO Pack.
Unfortunately we aren't able to provide assistance with third party software.  I recommend contacting that software's developers for assistance, or else your hosting company.
