### ISSUE TITLE
indexing protected content

### ISSUE THREAD

**Issue by popi33370** [semperfiwebdesign/all-in-one-seo-pack#2949]
Hi,
All in One SEO Pack 3.2.8 over WP 4.9.7
The content of my WP site posts/pages is protected so only logged users can read it = indexation robots cannot.
So my question is : using your plugin how may i allow robots to access your SEO meta datas to be able to index my content ?
Thanks for your help to find a solution.
paul.opitz@free.fr

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. 

If you would like access to our Premium Support team, you can purchase an All in One SEO Pack Pro license: https://semperplugins.com/all-in-one-seo-pack-pro-version/
