### ISSUE TITLE
Check all links to settings pages for hard coded links

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#295]
for instance, the link to set your license is hardcoded "...all-in-one-seo-pack-pro/..." which breaks if their directory is named something different... 
We need to check free and pro

**Comment by michaeltorbert** [comment]
Actually this is in all_in_one_seo_pack.php on line 178 
$aioseop_update_checker->options_page = 'all-in-one-seo-pack-pro/aioseop_class.php';

**Comment by michaeltorbert** [comment]
related to #296

**Comment by michaeltorbert** [comment]
If someone's directory isn't named correctly, that could mess up some links to settings pages.

**Comment by michaeltorbert** [comment]
Fixed this for pro as well https://github.com/semperfiwebdesign/aioseop-pro/issues/76

**Comment by wpsmort** [comment]
This is tested and is good.
