### ISSUE TITLE
"Maximum Posts per Sitemap Page" occurs when "enable sitemap" is disabled

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2953]
Reported here: https://wordpress.org/support/topic/set-maximum-posts-per-sitemap-page-to-1000-banner-problem/

**Comment by arnaudbroes** [comment]
Closing this as it is a duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2756.
