### ISSUE TITLE
XML Sitemaps enable index documentation for 1000 instead of 50k

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2954]
Reported here: https://wordpress.org/support/topic/set-maximum-posts-per-sitemap-page-to-1000-banner-problem/

The documentation still says 50k

**Comment by arnaudbroes** [comment]
This concerns the tooltip for "Sitemap Indexes". Also make sure to check elsewhere.
