### ISSUE TITLE
Schema.org - Add filter for custom Person markup

### ISSUE THREAD

**Issue by Pikamander2** [semperfiwebdesign/all-in-one-seo-pack#2962]
We'd like to add a `jobTitle` to the `Person` structured data that's being generated by the All In One SEO pack.

At a glance, it looks like the fields are hardcoded and don't allow for any modification. Here are lines 64-70 of `wp-content/plugins/all-in-one-seo-pack/inc/schema/graphs/graph-person.php`:

```
$rtn_data = array(
	'@type'  => $this->slug,
	'@id'    => $author_url . '#' . $hashtag,
	'name'   => $author_name,
	'sameAs' => $this-> get_user_social_profile_links( $user_id )
);
```

If I modify that code to be:

```
$rtn_data = array(
	'@type'  => $this->slug,
	'@id'    => $author_url . '#' . $hashtag,
	'name'   => $author_name,
	'sameAs' => $this-> get_user_social_profile_links( $user_id ),
	'jobTitle' => 'Job title goes here'
);
```

Then it outputs exactly what we want it to, albeit with placeholder info.

A more proper way to do it would be to apply a filter, which would allow you to modify the array data as needed:

```
$rtn_data = array(
	'@type'  => $this->slug,
	'@id'    => $author_url . '#' . $hashtag,
	'name'   => $author_name,
	'sameAs' => $this-> get_user_social_profile_links( $user_id )
);
		
$rtn_data = apply_filters('aioseop_person_data', $rtn_data);
```

By doing that, I can now modify the array data from my `functions.php` file:

```
function addAuthorJobTitle($person_data)
{
	$person_data["jobTitle"] = "Job title goes here";
	return $person_data;
}

add_filter('aioseop_person_data', 'addAuthorJobTitle');
```

**Comment by Pikamander2** [comment]
If everything there looks good, then the same change could be made on the other ~8 schema files.

**Comment by arnaudbroes** [comment]
@Pikamander2 thank you for the PR and code examples you've submitted. I like the idea and I think we should definitely add this to the plugin (also for the other schemes we currently support). We'll go ahead and review your PR soon and hopefully we can still include this in the next version of the plugin (which should be out next week).

**Comment by wpsmort** [comment]
I've added documentation for this filter here - https://semperplugins.com/documentation/filter-schema-markup-for-person/

**Comment by EkoJR** [comment]
This is already possible, and can be done the exact same way as...

```
function prefix_aioseop_schema_person( $data ) {
	$data['jobTitle'] = 'Job title goes here';
	return $data;
}
add_filter( 'aioseop_schema_class_data_AIOSEOP_Graph_Person', 'prefix_aioseop_schema_person' );
```

**Comment by wpsmort** [comment]
I've tested the filter above and confirmed it works.  I've updated our API documentation on semperplugins.com
