### ISSUE TITLE
Blog post image not showing on Facebook

### ISSUE THREAD

**Issue by checkthealternative** [semperfiwebdesign/all-in-one-seo-pack#2970]
Hey! I need help getting my blog post to show the image I have saved on Wordpress blog page. On facebook when I enter my blog page, there's no image, just a gray blank looking image.
Help!

Thank you, 

Christina 

https://checkthealternative.com

**Comment by michaeltorbert** [comment]
This is a development repository, not a support forum. If you would like us to troubleshoot this issue, you'll need to upgrade to a Pro license here 
If you'd like to troubleshoot it yourself, you can find documentation here: https://semperplugins.com/all-in-one-seo-pack-pro-version/https://semperplugins.com/documentation/troubleshooting-incorrect-social-meta-when-sharing-or-publishing-content/
