### ISSUE TITLE
Verify that the warning about two versions of AIOSEOP active is working

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#30]
When you try to activate Pro and Free at the same time you should get this warning:

All in One SEO Pack detected a conflict; please deactivate the plugin located in /home/internal/public_html/smortiboy/wp-content/plugins/all-in-one-seo-pack-pro/.

We need to make this warning more friendly and helpful and we need to verify it's working correctly.

**Comment by wpsmort** [comment]
The warning works if you have Pro active and you try to activate the free plugin.

The warning does not work if you have free active and you try to activate Pro.  Instead you get this message - 

Plugin could not be activated because it triggered a fatal error.
Fatal error: Cannot redeclare sfwd_add_action_links() (previously declared in /home/internal/public_html/smortiboy/wp-content/plugins/all-in-one-seo-pack/all_in_one_seo_pack.php:188) in /home/internal/public_html/smortiboy/wp-content/plugins/all-in-one-seo-pack-pro/all_in_one_seo_pack.php on line 222

This is a bug that needs to be fixed.

**Comment by wpsmort** [comment]
Please fix the bug in Pro where the Fatal Error is displayed when activating Pro and free is already active.  

Instead of this fatal error, the plugin should be displaying this message - 

All in One SEO Pack Pro detected a conflict; please deactivate the plugin located in /wp-content/plugins/all-in-one-seo-pack/.

**Comment by mrtorbert** [comment]
I removed that message, and not pro just deactivates free when activated

**Comment by mrtorbert** [comment]
Both pro and free have been updated and need testing.

**Comment by wpsmort** [comment]
I found one issue during testing:

This works fine when activating Pro on a site where free is active.

However, if you try to activate free on a site where Pro is active then you just get the message - 

Plugin activated.

Pro remains active, free remains inactive.  Not sure if this is by design because we don't think you'd want to activate free if you already have Pro active.

See screenshot.

![screen shot 2016-03-16 at 5 33 51 pm](https://cloud.githubusercontent.com/assets/17548525/13829484/a45fcd4a-eb9d-11e5-84bf-be9814ed7f40.png)

**Comment by mrtorbert** [comment]
That's by design.

**Comment by mrtorbert** [comment]
@wpsmort That's by design.
