### ISSUE TITLE
SEO pack doesn't work in Spacious theme

### ISSUE THREAD

**Issue by agnishka** [semperfiwebdesign/all-in-one-seo-pack#3000]
Hello,
I have set all SEO titles, descriptions and keywords in my website (see attached), but nothing goes to Google. Is it because of particular theme?
![seo](https://user-images.githubusercontent.com/38765279/68083641-4a977700-fe2b-11e9-9355-d72dd5902824.PNG)
Is is actually doesn't work even for main page (see attached).
![seo2](https://user-images.githubusercontent.com/38765279/68083666-96e2b700-fe2b-11e9-98dd-8bdc94b40fb0.PNG)

**Comment by arnaudbroes** [comment]
This will be caused by either a conflicting plugin or theme, and is definitely not a bug.
