### ISSUE TITLE
Bug - Nextgen Gallery images don't show up in XML Sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#3005]
https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1214/files
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3004

**Comment by michaeltorbert** [comment]
We added it in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1546 for Classic, but now it doesn't work in that either.

**Comment by arnaudbroes** [comment]
@wpsmort same as for https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3004, can you check if this has something to do with a shortcode?

**Comment by wpsmort** [comment]
I found that this was caused by the fact that only the [ngg_images] shortcode is present in our sitemap code.  Adding the [ngg] shortcode resolves the problem.
