### ISSUE TITLE
Bug - First parameter must either be an object or the name of an existing class in aioseop-robots-meta.php:132

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#3014]
Reported here: 
https://wordpress.org/support/topic/error-after-updating-plugin-9/
here https://wordpress.org/support/topic/warning-first-parameter-must-either-be-an-object-or-the-name-of-an-existing-cla/

> I am getting the below errors on the subsequent pages (2nd, 3rd, 4th.. pages) of my main website (scroll to bottom and click “older entries”).
Warning: First parameter must either be an object or the name of an existing class in /****/****/********/eatandtravelwithus.com/wp-content/plugins/all-in-one-seo-pack/inc/general/aioseop-robots-meta.php on line 132

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/c2719c881f155e359878c9b1961275793e4b525f/inc/general/aioseop-robots-meta.php#L132

**Comment by arnaudbroes** [comment]
Reported again here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3017

**Comment by arnaudbroes** [comment]
Related or the same as https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3015/.

**Comment by arnaudbroes** [comment]
Reported again here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3018

**Comment by OlafMoeller** [comment]
Will this be fixed or do I need to do something on my website?

**Comment by arnaudbroes** [comment]
@OlafMoeller this is an issue on our end. If you don't mind giving us access to your website, then please fill in our support form here - https://semperplugins.com/contact/support-login-information/. Allowing us access will help us resolve the issue faster (we won't make any changes to your website).

**Comment by Yuki8886** [comment]
Moi aussi j'ai ce problème :/ Comment faire pour revenir à la version précédente ?
I too have this problem: / How to go back to the previous version?

**Comment by Yuki8886** [comment]
J'ai télécharger la version précédente dans l'attente d'une mise à jour stable.
https://downloads.wordpress.org/plugin/all-in-one-seo-pack.3.2.10.zip

**Comment by arnaudbroes** [comment]
I've reproduced this. It's occuring on paginated homepages.

**Comment by Yuki8886** [comment]
Yes just  paginated homepages.

**Comment by bigollycat** [comment]
version：3.3.1.1，aliyun warning webshell
![webshell](https://user-images.githubusercontent.com/31915430/68728710-082c2200-0603-11ea-8269-f1aebdce7068.jpg)

**Comment by arnaudbroes** [comment]
@bigollycat that's a false-positive. There's even barely any code in that file.

**Comment by bigollycat** [comment]
> @bigollycat that's a false-positive. There's even barely any code in that file.

ok，thank you
