### ISSUE TITLE
My website URL is not working on Facebook

### ISSUE THREAD

**Issue by Sharxzy** [semperfiwebdesign/all-in-one-seo-pack#3016]
Pls my website URL is not working of Facebook. Pls assist me on this............... Thanks
![Screenshot_20191112-043541_Messenger](https://user-images.githubusercontent.com/49528707/68639818-19433900-0506-11ea-83d4-3bca3cc1c3fe.jpg)

**Comment by arnaudbroes** [comment]
@Sharxzy first of all, this a development repository; not a support forum. Second, we can't help you if Facebook is blocking one of your URL's. I'd suggest that you reach out to them instead.
