### ISSUE TITLE
New Issue after Update

### ISSUE THREAD

**Issue by OlafMoeller** [semperfiwebdesign/all-in-one-seo-pack#3018]
![Fehler Website](https://user-images.githubusercontent.com/57663089/68660861-414c8f80-053a-11ea-9435-f4472e608299.JPG)

Hi, I have these errors after Updating recently the "All in one SEO Pack" - both WP and the plugin are using the most updated versions. Any idea what is wrong?

Thank you!

**Comment by arnaudbroes** [comment]
Reported again here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3018

**Comment by arnaudbroes** [comment]
@OlafMoeller thank you for reporting this. We are aware of the issue and hope to get a bug fix soon. If you don't mind giving us access to your website so we can have a quick look and see what's causing this, then please send us an admin login here - https://semperplugins.com/contact/support-login-information/

Also, you should be able to remove the warning from your homepage by setting WP_DEBUG to false in your wp-config.php file. You'll have to FTP to your web server to make that change.

**Comment by OlafMoeller** [comment]
Hi Arnaud

I checked the setting of WP_DEBUG in my wp-config.php file – it was already set to „FALSE“?

[cid:image001.png@01D5994D.B90260D0]

Mit freundlichen Grüßen
Olaf Möller
Möller Werbeartikel
Langenkamp 20, 22880 Wedel
Tel. 04103-703 99 29
Fax 04103-703 99 09
olaf@moeller-hamburg.de<mailto:olaf@moeller-hamburg.de>
[cid:image002.jpg@01D5994D.B90260D0]<https://www.1kcloud.com/ep1wtlUO/#0>


Von: Arnaud Broes [mailto:notifications@github.com]
Gesendet: Dienstag, 12. November 2019 11:18
An: semperfiwebdesign/all-in-one-seo-pack
Cc: Olaf Möller; Mention
Betreff: Re: [semperfiwebdesign/all-in-one-seo-pack] New Issue after Update (#3018)


@OlafMoeller<https://github.com/OlafMoeller> thank you for reporting this. We are aware of the issue and hope to get a bug fix soon. If you don't mind giving us access to your website so we can have a quick look and see what's causing this, then please send us an admin login here - https://semperplugins.com/contact/support-login-information/

Also, you should be able to remove the warning from your homepage by setting WP_DEBUG to false in your wp-config.php file. You'll have to FTP to your web server to make that change.

**Comment by Yuki8886** [comment]
I too have this problem: / How to go back to the previous version?

**Comment by michaeltorbert** [comment]
Closed as a duplicate of #3014
