### ISSUE TITLE
Bug- Full content appearing in Preview Snippet and Description placeholder

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#3023]
Reported here: https://wordpress.org/support/topic/error-autogenerate-descriptions/

> when i activate Autogenerate Descriptions, it generate the complete post in description box NOT the first 160 characters! see the screenshots below:
> screen 1: https://yadi.sk/i/DZDOJDD_zasxzg
> screen 2: https://yadi.sk/i/1vgN-mCm9qkJaA
> 
>

**Comment by arnaudbroes** [comment]
The character count is based/relies on the preview snippet so this would be an issue with the latter.

**Comment by arnaudbroes** [comment]
Reported again here - https://wordpress.org/support/topic/autogenerate-descriptions-error/#post-12149551

**Comment by wpsmort** [comment]
@arnaudbroes I've now been able to get access to a site to troubleshoot and reproduce this.

The full content from a post appears in the Preview Snippet and Description field placeholder only when using the Classic block. This only happens with certain type of formatted content.

This bug first occurs in AIO v3.3.2.

Here are the steps to reproduce:

1. Install AIO v3.3.2 on a new site and enable Autogenerate Descriptions
2. Create a new post using the Block editor
3. Add the Classic block and enter a large amount of text
4. Publish the post and check the Preview Snippet and Description field placeholder, both should show the content truncated to around 160 characters which is correct behavior
5. Edit the post and add some additional text to the Classic block and style it as a blockquote
6. Check the Preview Snippet and Description field placeholder, both should show the full content not truncated.

This only seems to happen with certain formatted text, such as blockquotes, aligned (left, center, right) text, headings and preformatted text.
