### ISSUE TITLE
Problem after last update 

### ISSUE THREAD

**Issue by NaszeSzlaki** [semperfiwebdesign/all-in-one-seo-pack#3024]
Ther is somethin wrong with the All in One Seo Pack. 
https://www.dropbox.com/s/vq3n4xugr0ip1sa/Adnotacja%202019-11-12%20182414.png?dl=0
What I can do with that ?
Thx and all the best !

**Comment by michaeltorbert** [comment]
Duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3014
