### ISSUE TITLE
Ошибка после обновления

### ISSUE THREAD

**Issue by Jocker10** [semperfiwebdesign/all-in-one-seo-pack#3031]
Здравствуйте! После обновления плагина All in ONE SEO Pack появилась ошибка: 1. В разделе "Заголовок" при создании статьи и написании текста не считает количество символов. 2. То же самое происходит в разделе "Описание". 3. Так же не отображается вводимый текст в предпросмотре сниппета.
![Снимок экрана (126)_LI](https://user-images.githubusercontent.com/57711548/68761586-6e29a100-0625-11ea-80e8-946a1e1e086c.jpg)

**Comment by arnaudbroes** [comment]
@Jocker10 are there errors in the console (F12)? Also, if you don't mind, then please send us an admin login here so we can access your website and troubleshoot the issue - https://semperplugins.com/contact/support-login-information/

**Comment by arnaudbroes** [comment]
@Jocker10 we fixed this with an update yesterday.

**Comment by Jocker10** [comment]
Спасибо большое за оперативную работу, но теперь по умолчанию в графе "заголовок" установлено 12 символов)
![Снимок экрана (154)_LI](https://user-images.githubusercontent.com/57711548/68856550-d8a81300-06f1-11ea-83c8-3eb8eb736f86.jpg)

**Comment by arnaudbroes** [comment]
@Jocker10 that is correct behaviour although I understand why it is confusing. Those are the characters of your title format (see the preview of your title). In a future update I'll make sure that the placeholder reflects that too.
