### ISSUE TITLE
Add Google Tag Manager to Pro features list

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#3039]

**Comment by wpsmort** [comment]
This is done. I've updated the Features and Benefits section, the Connect with Google and Bing section, and the Common Questions section.  I've also updated the FAQ on the difference between free an Pro here - https://semperplugins.com/faqs/what-is-the-difference-between-the-free-version-of-all-in-one-seo-pack-and-the-pro-version/
