### ISSUE TITLE
track outbound links and enhanced ecommerce hidden since 3.3

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#3042]
In https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2985 we added 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/d25f722899d60f2e3521e594b2f2b31c991735f3/aioseop_class.php#L568-L572

and 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/d25f722899d60f2e3521e594b2f2b31c991735f3/aioseop_class.php#L599-L603

which have the effect of hiding the options. Was this intentional or a bug?

**Comment by arnaudbroes** [comment]
Intentional, see https://github.com/semperfiwebdesign/aioseop-pro/issues/534#issuecomment-474511164. There are a few other options we hide as well.
