### ISSUE TITLE
Google indexing lost after upgrade to All In One SEO 3.3.3

### ISSUE THREAD

**Issue by osteocare23** [semperfiwebdesign/all-in-one-seo-pack#3067]
Maybe I have got too relaxed with plugin updates as I have never had an issue -- until 3 days ago when I updated this SEO plugin and completely lost google indexing of my homepage -- interestingly just google, bing is till OK -- I am still top of page 1. So what is happening, I have no idea. I called various people for support to rollback to the previous version, but apparently my hosting backups do not backup plugins or wordpress !!! whats the point then ?? They told me that I need to back up my own wordpress files. Yipee I have another plugin called Wordpress Database Backup that sends me a weekly .gz file but what do I do with this -- no instructions or options in the plugin to restore, just to back up -- fat lot of use if you back up but cant restore. Then someone told me that I need to import the back up file but where is the guidance from the plugin authors to restore the files; and more importantly, why did updating the SEO version cause this issue, and why just on google -- all ideas gratefully received as going steadily crazy here.

**Comment by arnaudbroes** [comment]
@osteocare23 this is not a support forum but a development repository. I'm afraid that we only provide support to customers who have a license for All in One SEO Pack Pro. You can purchase a license here if you'd like to - https://semperplugins.com/all-in-one-seo-pack-pro-version/

Also, we're not able to provide much help if you don't share the URL of your website with us. In any case, you can download earlier releases of the plugin here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/releases
