### ISSUE TITLE
Ошибка для отдельного описания страницы

### ISSUE THREAD

**Issue by n91111** [semperfiwebdesign/all-in-one-seo-pack#3068]
Здравствуйте. Не сохраняются отдельные описания для страниц
![2019-12-03_03-26-59](https://user-images.githubusercontent.com/33281951/70006096-f47a3880-157c-11ea-9485-13b1cfcb4c08.jpg)

В настройках установлено
![2019-12-03_03-29-13](https://user-images.githubusercontent.com/33281951/70006139-1e335f80-157d-11ea-809e-157916851334.jpg)
![2019-12-03_03-35-26](https://user-images.githubusercontent.com/33281951/70006396-fabce480-157d-11ea-9fbc-90143c651ed5.jpg)

Это подходит мне для рубрик и записей.
Пробовал установить настройки хотя бы на главной странице
![2019-12-03_03-36-24](https://user-images.githubusercontent.com/33281951/70006451-42dc0700-157e-11ea-9505-c54edc838514.jpg)

Но внутренний код на отдельных страницах (не страницах с записями) имеет описания из этих настроек!
![2019-12-03_03-33-31 (2)](https://user-images.githubusercontent.com/33281951/70006567-bc73f500-157e-11ea-95c6-36294e7ca11f.jpg)

Как это победить?

**Comment by arnaudbroes** [comment]
@n91111 I'm afraid that we do not have any Russian speaking staff and that Google Translate isn't doing a great job at translating what you said. Would you be able to explain your issue to us in English?

**Comment by n91111** [comment]
I can’t set <meta name = "description" for a single page (and even for the main page). Everything is configured, but the <meta name = "description" for the pages is generated from the general "description" settings.

**Comment by n91111** [comment]
I can’t set <meta name = "description" for a single page (and even for the main page). Everything is configured, but the <meta name = "description" for the pages is generated from the general "description" settings.

**Comment by n91111** [comment]
![2019-12-03_03-33-31 (3)](https://user-images.githubusercontent.com/33281951/70037407-91fa5a00-15c7-11ea-8a21-b0b432a0e396.jpg)
![2019-12-03_03-26-59 (2)](https://user-images.githubusercontent.com/33281951/70037412-9292f080-15c7-11ea-95dc-f448ae8f66b4.jpg)
![2019-12-03_03-36-24 (2)](https://user-images.githubusercontent.com/33281951/70037413-932b8700-15c7-11ea-9e69-8afa2cd8634b.jpg)
![2019-12-03_03-29-13 (2)](https://user-images.githubusercontent.com/33281951/70037414-932b8700-15c7-11ea-8ff5-3693ba14780f.jpg)

**Comment by arnaudbroes** [comment]
@n91111 looks like this a support issue; not a bug. You need to use the `%description%` macro in the Description Format field in the General Settings menu for your description to show up correctly.

**Comment by n91111** [comment]
Super! thanks!!!
