### ISSUE TITLE
Making Redirect Attachments to Post Parent Turned on by Default (Perhaps)

### ISSUE THREAD

**Issue by consumingtech** [semperfiwebdesign/all-in-one-seo-pack#3073]
I have recently read about the setting "Redirect Attachments to Post Parent" and what it does. 

I have noticed many of my images floating around in search results and always wondered if I were doing something incorrectly because the pages did appear obviously thin for a blog. 

To the best of my SEO knowledge, which is close to ten years of blogging experience now, Google does in fact assess the overall quality of your website, and thus these pages with nothing but images on them could in fact negatively affect a website's rankings should they get traffic from search engines such as Google. 

Subsequently, it would be my recommendation to perhaps make this setting turned on by default. As a blogger myself, and as someone who has scrolled through the list of options your wonderful plugin presents, it did not occur to me what that setting was. I assume there are countless other bloggers who had a similar fate. 

Cordially,
Mathew

**Comment by wpsmort** [comment]
@consumingtech Thank you for your feedback, however, enabling this by default could have a negative affect on many of our users sites.  As this could cause problems for many users, we will need to leave this option as disabled by default.

With regards to Media Attachment pages, our recommendation is that, if you're not using them for a specific purpose then, you should set these as noindex (https://semperplugins.com/documentation/noindex-settings/) and exclude them from the XML Sitemap (https://semperplugins.com/documentation/xml-sitemaps-module/).

**Comment by consumingtech** [comment]
Thanks for the reply.

It is my understanding that setting them as noindex would also result in the images not appearing in search results for images.

For clarity, "search results for images" is referring to navigating to **Google.com** and clicking **Images** for example. 

Would you agree or do I have that wrong?

If that is the case, I would not advise anyone to set their images to noindex as they can provide traffic.

**Comment by wpsmort** [comment]
Your images would not be affected.  This only affects the Media Attachment pages which are a special post type in WordPress and which, for most people, hold zero value.

**Comment by consumingtech** [comment]
Interesting. Thanks for the information **wpsmart**.
