### ISSUE TITLE
robots.txt not working properly

### ISSUE THREAD

**Issue by beauty99** [semperfiwebdesign/all-in-one-seo-pack#3075]
Hi I can see the robots.txt, not working properly is blocking my website pages, I removed from wp manager, but I cant remove from all 1 seo, see bellow;
could you please remove sitemap?
thanks

User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php

Sitemap: https://www.relaxingmassagetherapy.co.uk/sitemap.xml

**Comment by wpsmort** [comment]
This is not a support forum, it is a development repository and we do not provide support here.  Please refer to the the Default Rules section in the documentation here - https://semperplugins.com/documentation/robots-txt-module/
