### ISSUE TITLE
Bug - Product picture does not unfold to full-screen

### ISSUE THREAD

**Issue by d75168** [semperfiwebdesign/all-in-one-seo-pack#3077]
https://centrumdom.ru/products/33778905/    after the update, when you click on the product picture, it does not unfold in full screen.  help please

**Comment by arnaudbroes** [comment]
@d75168 if the issue doesn't occur when All in One SEO Pack is deactivated, then I'd recommend you check for a conflict using these steps - https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/. Unfortunately there's not much we can do if you are not able to provide us with more information.

**Comment by arnaudbroes** [comment]
Closing this as there has been no response.
