### ISSUE TITLE
Incorrect Noindex meta output code. Additional meta tag inside content attribute.

### ISSUE THREAD

**Issue by esquivels** [semperfiwebdesign/all-in-one-seo-pack#3079]
Selecting the following **All in One SEO Pack** page options: 

- NOINDEX this page/post, 

- NOFOLLOW this page/post and

- Disable on this page/post

Outputs the following meta tag on the page:

```<meta name="robots" content="<meta name="robots" content="noindex,nofollow" />```

Notice how a duplicate robots meta tag is added inside the content attribute of the main robots meta tag.

**Comment by arnaudbroes** [comment]
Thanks, I've opened an issue for it so I'll go ahead and close this one since it's a duplicate.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3079

**Comment by esquivels** [comment]
@arnaudbroes Thanks! One thing I noticed, that may help with troubleshooting, is that the combination of selecting "Disable on this page/post" with any of the options NoINDEX or NOFOLLOW causes the issue. Selecting both NOINDEX and NOFOLLOW without "Disable on this page/post" does not cause the issue mentioned above. The issue may be originating from the "Disable on this page/post" setting
