### ISSUE TITLE
WooCommerce woocommerce_get_page_id has been deprecated

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#308]
replaced with wc_get_page_id

**Comment by michaeltorbert** [comment]
This code doesn't seem to do much... maybe related to #96 and #154?

**Comment by michaeltorbert** [comment]
Since the code is being used, we need to make sure the deprecated function is replaced.

**Comment by michaeltorbert** [comment]
These instances deal with determining the doc title and meta description for WooCommerce shop pages. 
For testing, we need to make sure they're the same as they were before and there are no new bugs added.

**Comment by wpsmort** [comment]
This is tested and is good.
