### ISSUE TITLE
Bug - Duplicate robots meta tag inside robots meta tag when SEO for Post is disabled

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#3080]
Reported here - https://wordpress.org/support/topic/be-careful-with-product-pages/
 
To reproduce this, disable SEO for the Post and toggle either NOINDEX, NOFOLLOW or both.

**Comment by arnaudbroes** [comment]
Reported again here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3095

I'm bumping this to 3.3.5 since it's been reported a few times now.

**Comment by wpsmort** [comment]
Reported again by Romain by email today.
