### ISSUE TITLE
Warning on webpage

### ISSUE THREAD

**Issue by clicianaldoni** [semperfiwebdesign/all-in-one-seo-pack#3083]
Hi, my website is having some problems because of the all-in-one SEO.
[Site](http://nonadablog.com/en/articles/)

> Warning: include_once(/home3/clicia/public_html/wp-includes/class-wp-oembed.php): failed to open stream: No such file or directory in /home3/clicia/public_html/wp-content/plugins/all-in-one-seo-pack-pro/pro/video_sitemap.php on line 60
> 
> Warning: include_once(): Failed opening '/home3/clicia/public_html/wp-includes/class-wp-oembed.php' for inclusion (include_path='.:/opt/php70/lib/php') in /home3/clicia/public_html/wp-content/plugins/all-in-one-seo-pack-pro/pro/video_sitemap.php on line 60
> 

I will disable the plugin, but I would like to tell about the problem, since I paid the pro.

Kind regards,
Clicia

**Comment by arnaudbroes** [comment]
@clicianaldoni thank you for reporting this. We are aware of this warning and have already developed a fix for it, which will be out soon.

There's no need to disable the plugin as this is just a warning; not an error. You can prevent these warnings from appearing on the front-end of your website by setting the WP_DEBUG rule to false in your wp-config.php file (located in the root directory of your WordPress website).
