### ISSUE TITLE
オールインワンパックについて

### ISSUE THREAD

**Issue by nisimura810** [semperfiwebdesign/all-in-one-seo-pack#3086]
いつもお世話になっております。
本日2019年12月21日アップデートしました。
しかしバグなのかwordpress内の記事作成でエデッターが追尾ししない。
画像が挿入できないなどのバグ発生です。

原因はオールインワンパックをアップデートしたからです。
しかし、外すわけにはいなかないので何とかできないでしょうか？

**Comment by wpsmort** [comment]
@nisimura810 Please provide full details of the bug you are reporting along with screenshots and steps to reproduce the problem.

**Comment by arnaudbroes** [comment]
Closing this as there has been no response.
