### ISSUE TITLE
class-oembed.php is deprecated since version 5.3.0

### ISSUE THREAD

**Issue by messynaman22** [semperfiwebdesign/all-in-one-seo-pack#3087]
Whenever I activate your plugin on my site then I see this notice. 

Notice: class-oembed.php is deprecated since version 5.3.0! Use wp-includes/class-wp-oembed.php instead. in /var/web/site/public_html/wp-includes/functions.php on line 4802

This is greatly impacting the speed of the site and taking up lot of resources from the site. I will appreciate if you can fix the same asap else I might have to plan to move to different SEO plugin.

**Comment by wpsmort** [comment]
@messynaman22 A fix for this was released yesterday in version 3.3.4.

**Comment by messynaman22** [comment]
I have updated the same and the issue seems to be resolved. After the recent release, I noticed my website is slowed down when I use your plugin. Seems like your plugin is taking up lot of resources or has some confliction with Divi Theme. I already had word with Divi Support Team and they said the issue is connected with the plugin and they won't be able to provide support for that. Can you check your plugin compatibility with Divi Themes?
