### ISSUE TITLE
There is a bug version 3.34

### ISSUE THREAD

**Issue by DAIKI03** [semperfiwebdesign/all-in-one-seo-pack#3088]
It doesn't work media upload button when active version 3.34. Can I fix it work well?

**Comment by wpsmort** [comment]
Please make sure to clear ALL caching and CDN, log out of your site and clear the browser cache. Users have reported that this fixes the JavaScript issues they’ve seen.

If you need further support please post in our support forums here - https://semperplugins.com/support/
