### ISSUE TITLE
Bug - Google Search Console failed to process sitemap

### ISSUE THREAD

**Issue by sizar2** [semperfiwebdesign/all-in-one-seo-pack#3091]
Google Search Console: Failed to process Sitemap which was made by All in One SEO. 
Website https://xn--80adbkk5brl7a.xn--p1ai/
Sitemap: https://xn--80adbkk5brl7a.xn--p1ai/sitemap.xml

What to do?

**Comment by arnaudbroes** [comment]
Your sitemap is 100% valid. Is the error still there? If so, is there any other information being displayed in Google Search Console? I'm afraid the above is not much to go on.

**Comment by sizar2** [comment]
Unfortunately, the problem is still there. Please find screenshots attached. Thanks.  09.01.2020, 17:30, "Arnaud Broes" <notifications@github.com>:Your sitemap is 100% valid. Is the error still there? If so, is there any other information being displayed in Google Search Console? I'm afraid the above is not much to go on.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by arnaudbroes** [comment]
> Unfortunately, the problem is still there. Please find screenshots attached. Thanks. 

You'll need to log into GitHub to post screenshots. We can't see them.

**Comment by sizar2** [comment]
Right, sorry. :) 
Attached.

![Sitemap1](https://user-images.githubusercontent.com/51336243/72438268-864ca680-37b5-11ea-8420-8b04b6e92359.JPG)
![Sitemap2](https://user-images.githubusercontent.com/51336243/72438269-864ca680-37b5-11ea-85d9-0b763a6008eb.JPG)

**Comment by arnaudbroes** [comment]
@wpsmort do you have any idea why the Russian characters in his domain name are being encoded to the Latin alfabet and whether that would have an impact on sitemap verification?

**Comment by wpsmort** [comment]
@arnaudbroes I can't imagine that domain names in Russian characters would be a problem.  As for encoding, I can't say whether that would affect sitemap verification.  I can't see anything wrong with the XML Sitemap and would say that this is a Google Search Console problem and recommend @sizar2 contact Google via their support forums here - https://support.google.com/webmasters/community.  Hopefully one of the experts in there can help.

**Comment by arnaudbroes** [comment]
Agreed.
