### ISSUE TITLE
Social Meta - Remove findmyfbid.com from help text

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#3092]
Remove the reference to http://findmyfbid.com/ from the help tooltip for the Facebook Admin ID setting.

<img width="605" alt="Screen Shot 2020-01-02 at 4 16 00 PM" src="https://user-images.githubusercontent.com/17548525/71693910-a7f06b80-2d7b-11ea-8ae2-005dd814edbc.png">

**Comment by tonyzeoli** [comment]
Maybe replace with this:

You can get the ID yourself by going to the profile, right click with your mouse and click "View page source", then search for the value "entity_id", "fb://profile/", "fb://group/" or "fb://page/. The number that you see after it is your numeric Facebook ID.

**Comment by wpsmort** [comment]
I've updated the documentation here - https://semperplugins.com/documentation/social-meta-module/
