### ISSUE TITLE
Click on Facebook Debugger in category landing page redirects back to WordPress edit view

### ISSUE THREAD

**Issue by tonyzeoli** [semperfiwebdesign/all-in-one-seo-pack#3094]
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Provide the relevant URL(s) here**
https://qigongawareness.com/workshop-calendar/category/workshops/

**Describe the bug**
When you click on the Facebook Debugger button in the Category edit view, it does not go to Facebook's Sharing Debugger page. It loops back to itself and reloads the Category edit view. 

**To Reproduce**
1. Using Events Calendar, add a category
3. Edit the category and open the AIOSEO social meta module
4. Click on the Facebook Debugger button
5. Observe page loop back to itself, does not open new window

**Expected behavior**
Should open Facebook Share Debugger in a new window

**Screenshots**
No screenshot taken.

**Version Info (please complete the following information):**
 - WordPress version: 5.3.2
 - All in One SEO Pack version: 3.3.4
 - PHP version: 7.3

**Additional context**

**Comment by arnaudbroes** [comment]
Thank you for reporting this, Tony.

I've reproduced the issue and will move this issue over to the Pro repository since SEO for Categories is a premium feature.
