### ISSUE TITLE
Noindex - media files bug

### ISSUE THREAD

**Issue by kulagin-ilya** [semperfiwebdesign/all-in-one-seo-pack#3095]
Hello, when I enable this feature - http://prntscr.com/qjmwpx , the Noindex meta tag is added incorrectly in such format - http://prntscr.com/qjmxfo . On other pages like "Use noindex for the 404 page" it is added correctly - http://prntscr.com/qjmxyw .

So please correct it. 

Version: 3.3.4

**Comment by arnaudbroes** [comment]
@kulagin-ilya thank you for reporting this. We already have an issue open for this here and hope to get a fix out soon - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3080
