### ISSUE TITLE
How do we do that ?

### ISSUE THREAD

**Issue by jackytruong77** [semperfiwebdesign/all-in-one-seo-pack#3098]
Hello, how do we add this part on the seo ?? I can't find the name of this part...
![screen1](https://user-images.githubusercontent.com/59645977/71988786-cdc0b900-3230-11ea-93ba-a79b0272fc76.png)

**Comment by wpsmort** [comment]
You can find the answer to this here - https://semperplugins.com/documentation/how-do-i-get-google-to-show-sitelinks-for-my-site/
