### ISSUE TITLE
Bug - Twitter card image doesn't show up

### ISSUE THREAD

**Issue by bantikuamr** [semperfiwebdesign/all-in-one-seo-pack#3100]
i have summary large image tag...but thumbnail not showing?
Look at: 

`INFO:  Page fetched successfully
INFO:  21 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully`
And look into the screenshot:-
![Screenshot_2020-01-09-08-10-38-81](https://user-images.githubusercontent.com/55180604/72033192-91846b80-32b7-11ea-9e35-5c7a35a0a73b.png)

@semperfiwebdesign

**Comment by arnaudbroes** [comment]
@bantikuamr this is not a bug. The image isn't displayed because Twitter has previously fetched the page and cached it.
