### ISSUE TITLE
update option is not working

### ISSUE THREAD

**Issue by jessie8808** [semperfiwebdesign/all-in-one-seo-pack#3101]
Hi there,

I tried like to modify the GA code,
but whenever I typed the new GA code and click update option, it's not working.
Looks like it worked, but when I refresh the page, it still shows the old GA code..

**Comment by arnaudbroes** [comment]
@jessie please clear both your browser & server cache and try again. This is often reported, but almost never turns out to be a bug. It's usually caused by aggressive caching.
