### ISSUE TITLE
Webmaster Verification...

### ISSUE THREAD

**Issue by WildToddMan** [semperfiwebdesign/all-in-one-seo-pack#3109]
I am looking into switching from some other plugins that handle SEO.

I have been trying out All-In-One SEO and so far I prefer it to all others, but when setting up the Webmaster Verification section, I am not able to get any of the Bing information based on your documentation since the Bing was imported from my Google account.

I am also only able to get my Google information for the sites that I verified through HTML instead of DNS TXT. But the documentation for All-In-One only provides how to get this information when first setting up your sites.

So how do I do it with sites that have been using Google and Bing for some time now without having to delete and re-verify?

Thanks!

**Comment by arnaudbroes** [comment]
@WildToddMan this is a development repository; not a support forum. Unfortunately I can't provide you with much support here but typically you just need to enter/output the same unique ID like you were doing before (with whatever plugin you're using). If you'd like to switch over from DNS TXT then you need to delete and re-verify your website.
