### ISSUE TITLE
Title for homepage isn't working

### ISSUE THREAD

**Issue by Carly557** [semperfiwebdesign/all-in-one-seo-pack#3112]
Hi there! I've used all-in-one for years, and suddenly this summer, it will no longer populate a title on my homepage. No matter what I type in, what I select or unselect, if I delete the Wordpress homepage title, anything, it only will now display the web address. I'm stumped! 

The only thing that has changed is I had an SSL installed; then, I noticed my site no longer displays the title. If I disable the all-in-one plugin, things work fine and a title displays from my Wordpress settings.

I'd love to keep using all-in-one though! Any ideas? Thank you!

**Comment by wpsmort** [comment]
@Carly557 This is a development repository; not a support forum. We can't provide you with support here, support for customers who have purchased All in One SEO Pack Pro is available here - https://semperplugins.com/contact/
