### ISSUE TITLE
XML Sitemap - Unsafe attempt to load URL when loading XSL file (not related to WPML)

### ISSUE THREAD

**Issue by tasnad** [semperfiwebdesign/all-in-one-seo-pack#3115]
Hi,
This is probably highly related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/337 and https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/687 but does not involve WPML.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/133 is probably also related.

**Describe the bug**
I have a site wich resolves correctly if called as www.mysite.example.org and mysite.example.org. 
I have set WP to redirect to the non-www version and I have an apache redirect from http to https.

The google search console sais one should enter all versions of the site (http / https www / non-www) and also upload sitemaps. That works with https://mysite.example.com and http://mysite.example.com, but fails for the www versions http://www.mysite.example.com and https://www.mysite.example.com. The reason is the same as in the linked issues and can be resolved with

`add_filter('aioseop_sitemap_xsl_url', function($xslUrl) {
    return preg_replace('#(https?://)[^/]+(/.*)#', '${1}' . $_SERVER['HTTP_HOST'] . '${2}', $xslUrl);
});`

However, that's a workaround and not a real fix. It would probably be better to have all links adjusted also *in* the sitemaps, not just the stylesheet.

**To Reproduce**
See the output of `curl 'https://www.yoursite.example.com/sitemap.xml'`.
It will include https://yoursite.example.com/sitemap.xsl' without www.

**Version Info (please complete the following information):**
 - WordPress version: 5.3.2 
 - All in One SEO Pack version: 3.3.4
 - PHP version: 7.3.14
- Twentynineteen theme with very minor tweaks (likely completely unrelated)

**Comment by wpsmort** [comment]
@tasnad Because you're redirecting the www version to non-www (which is correct) you wouldn't submit the www version to Google because it's being redirected.  I realize that Google says you should submit all versions, but you only do this if you don't have a redirect in place.  You don't need to submit a www version of your site to Google when there's redirect in place.

**Comment by tasnad** [comment]
I see, that's quite valuable information I did not find anywhere (in contrast to a variation of the code snippet I wrote). Would it be possible to add it in the documentation? I'm really not the first guy wondering why I shoulld add all variants.

**Comment by arnaudbroes** [comment]
@tasnad good idea.

@wpsmort would you be able to add a note [here ](https://semperplugins.com/documentation/submitting-an-xml-sitemap-to-google/) explaining users that they should submit all versions of their sitemap but not if they have redirects in place.

**Comment by wpsmort** [comment]
I don't see anywhere on the Sitemap Report in GSC regarding adding XML Sitemaps for all versions of a site, and there wouldn't be.  The only place you're going to see this is when you fist add a new site to GSC, which this is covered by Google's help here - https://support.google.com/webmasters/answer/34592?hl=en&authuser=0.  

As Google already has an article on this, and bearing in mind that the web as a whole has been trying to phase out WWW and HTTP, I don't know that we need to add anything to our docs.  I have linked to that Google help from our GSC verification doc.
