### ISSUE TITLE
Custom Canonical URLs do not reflect correct protocol

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#312]
If you set the protocol for canonical URLs to HTTPS (http://semperplugins.com/documentation/general-settings/#set-protocol-for-canonical-urls) then this does not affect any custom canonical URLs if the custom canonical URL has been hand coded with http.  

For example, if I enter http://aioseop:8888/custom-canonical-url/ as my custom canonical URL on a page or post, then the protocol is hard coded to HTTP.  

We should strip out any protocol entered in the Custom Canonical URL field for a page or post and then add the correct protocol based on the setting in All in One SEO > General Settings.

<img width="762" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/15900559/e638f040-2d6d-11e6-855a-31fd0773dbd3.png">

<img width="590" alt="screen-capture-1" src="https://cloud.githubusercontent.com/assets/17548525/15900565/ea760da0-2d6d-11e6-9eb4-e4c21ea51b8f.png">

**Comment by michaeltorbert** [comment]
@wpsmort This one should be good, needs testing. Try to break it. :)

**Comment by wpsmort** [comment]
Tested and works well.
