### ISSUE TITLE
Sitemap & SEO Title are not showing or in serps (Possible conflict with pegasaas-accelerator)

### ISSUE THREAD

**Issue by Aaronb-net** [semperfiwebdesign/all-in-one-seo-pack#3129]
Site: https://www.bangingtoolbox.com/

I have noticed my traffic drop over the last few days, and have noticed that my post title+sitename is showing in SERPs instead of my SEO title.

I think there might be a compatibility issue with a new speed optimization plugin - pegasaas-accelerator, as activating it makes the sitemap have the following error -

XML Parsing Error: not well-formed
Location: https://www.bangingtoolbox.com/sitemap.xsl
Line Number 1, Column 749:

But even if I deactivate - pegasaas-accelerator the SEO title is not showing in the head of the webpage "tab" instead the post title is.

Pretty keen to keep the speed optimization plugin - pegasaas, any help on the issue would be awesome, Thanks Aaron.

**Comment by arnaudbroes** [comment]
This is not a support forum, it is a development repository. Support for customers with a valid license for All in One SEO Pack Pro is available here - https://semperplugins.com/contact/
