### ISSUE TITLE
activating/deactivating a module refreshes the screen

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#317]
It always did that for free, but used to not refresh on Pro. 
We need to test on each version of Pro and figure out when that broke, then fix it for both free and pro.

**Comment by michaeltorbert** [comment]
Ok so changing  all-in-one-seo_page_all-in-one-seo-pack-pro-aioseop_feature_manager  to all-in-one-seo_page_all-in-one-seo-pack-pro-modules-aioseop_feature_manager in aioseop_module.js line 293 fixes it for pro... that *may be a simple change to add the functionality for free as well...

As a separate issue... what the heck does line 289 do, and is whatever it's supposed to do actually work?

**Comment by michaeltorbert** [comment]
The screen refresh has been fixed in free (still need to apply the updates to pro and test there) but the notification isn't positioned appropriately.

**Comment by wpsmort** [comment]
This is tested in free and is fixed.

**Comment by wpsmort** [comment]
This is tested in Pro and is fixed.
