### ISSUE TITLE
Feature Manager - RTL formatting is broken

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#319]
We need to have someone review the Feature Manager in RTL language and fix the style and layout issues.

**Comment by wpsmort** [comment]
@arnaudbroes: nadhirboukhe is our contact for RTL support.

**Comment by michaeltorbert** [comment]
@arnaudbroes  https://www.fiverr.com/nadhirboukhe did it for us last time and did a great job.

**Comment by arnaudbroes** [comment]
Contacted Nadhir, seems he isn't available though. I'll give him 24h to respond, otherwise I'll search someone else to do it.

**Comment by michaeltorbert** [comment]
@arnaudbroes So does it look like this is something that was working in the current release, but we've broken in the dev version?

**Comment by arnaudbroes** [comment]
@michaeltorbert I think so, downloaded the master branch and that seemed to be working fine, the development branch however was broken. Latest release (sent u a picture on Facebook) also seemed to work.

**Comment by michaeltorbert** [comment]
Ok I'd broken it. 
It should be fixed now. :)
