### ISSUE TITLE
Remove unused CSS

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#326]
For instance, in aioseop_module.css, the following doesn't seem to do anything. We don't have anything in .postarea (post edit screen), and these don't actually seem to apply to .aioseop_options_wrapper (settings pages). But verify this particular example rather than taking my word for it.

We need to go through ALL CSS and see what isn't being used and clean it up.

.aioseop_options_wrapper .postarea {
    border-color: #DFDFDF;
    -moz-box-shadow: inset 0 1px 0 #fff;
    -webkit-box-shadow: inset 0 1px 0 #fff;
    box-shadow: inset 0 1px 0 #fff;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
}

**Comment by arnaudbroes** [comment]
We'll redo the UI.
