### ISSUE TITLE
extra apostrophes

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#328]
Are these apostrophes (after the word author) inside the strings intentional?
<img width="893" alt="screen shot 2016-06-12 at 6 39 30 pm" src="https://cloud.githubusercontent.com/assets/17364998/15994224/199200d2-30cd-11e6-852f-c2f78184bf66.png">

**Comment by wpsmort** [comment]
Upon review we found that these apostrophes have always been there.

**Comment by michaeltorbert** [comment]
I asked Peter and he said there was probably some copy/paste involved.

**Comment by arnaudbroes** [comment]
Those strings have been worded differently some time ago.
