### ISSUE TITLE
XML Sitemap - If Jetpack is installed, make sure we're using our xml sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#336]
Related to #362

**Comment by michaeltorbert** [comment]
We have a new compatibility class. Eventually we'll move all existing (and new) compatibility code (when reasonably technically possible) there. 
With this new commit, Jetpack's sitemap will never run if AIOSEOP is activated.

**Comment by wpsmort** [comment]
This is tested and is fine.
