### ISSUE TITLE
XML Sitemap - Issue with loading stylesheet across domains with SSL

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#337]
This was reported by Alcides Cremonezi by email dated 17th Jun.  

Alcides is running WPML with different TLDs for his different languages.  He is also using SSL.  The XML Sitemap on some sites doesn't display properly in human readable format, although the XML Sitemap is fine when you look at the source code.

The error message returned in the browser console is this:

Unsafe attempt to load URL https://vulcanet.com.br/wp-content/plugins/all-in-one-seo-pack-pro/sitemap.xsl from frame with URL https://vulcanet.com.mx/sitemap.xml. Domains, protocols and ports must match.

SSL is preventing the XSL stylesheet from loading because the source domain vulcanet.com.br is different from the site domain vulcanet.com.mx.

The XSL stylesheet does exist on both domains:

https://vulcanet.com.br/wp-content/plugins/all-in-one-seo-pack-pro/sitemap.xsl
https://vulcanet.com.mx/wp-content/plugins/all-in-one-seo-pack-pro/sitemap.xsl

**Comment by wpsmort** [comment]
@michaeltorbert: I have replicated this on stevemortiboy.com using the domain stevemortiboy.co.uk.

If you go to stevemortiboy.co.uk/sitemap.xml you'll get a blank screen and if you look at the browser error console you'll see this error:

Unsafe attempt to load URL http://stevemortiboy.com/sitemap.xsl from frame with URL http://stevemortiboy.co.uk/sitemap.xml. Domains, protocols and ports must match.

**Comment by wpsmort** [comment]
@michaeltorbert: The setting in WPML for this is WPML > Languages > Language URL format > A different domain per language

**Comment by michaeltorbert** [comment]
This should work in the latest WPML.

**Comment by wpsmort** [comment]
This is tested and is fine.
