### ISSUE TITLE
Bad Bot Blocker Module - Bad bot blocker appears to be blocking bots not in our list of bad bots

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#34]
We've had two forum posts about Bad Bot Blocker blocking bots that are not in our list and that should not be blocked.  Please refer to these forum posts - 

https://wordpress.org/support/topic/bad-bot-blocker-a-few-questions
http://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/bad-bot-blocker-blocking-stripe-merchant-processor-requests/

In the cases above, Bad Bot Blocker appears to be blocking the user agents DoCoMo/2.0 and Stripe/1.0.  The first one is a valid GoogleBot and the second is for Stripe Payment Gateway.  In both cases the users report that deactivating our Bad Bot Blocker module resolves the problem.

We need a code review of the Bad Bot Blocker to ensure that we're not unintentionally blocking bots.

**Comment by dougalcampbell** [comment]
Didn't mean to close.

**Comment by dougalcampbell** [comment]
Note: The code fix will apply to new installs , but people who already had the Bad Bot module active will still have `DOC` in their settings, unless they remove it from the User-Agent Blocklist, or they reset to default settings, then re-enable and save the options.

**Comment by mrtorbert** [comment]
@dougalcampbell Can you just have it remove DOC in the next version? Now that we have the version saved to the db.

**Comment by dougalcampbell** [comment]
Good point. That can be the first test of the version update processing. :)

**Comment by mrtorbert** [comment]
@dougalcampbell Has this been done yet to remove for people who already had the module active?

**Comment by dougalcampbell** [comment]
Suggested testing method:
1) Install older version of plugin on fresh WP install (or otherwise wipe the aioseop_options entry from the db)
2) Turn on bad robots options, including htaccess generation
3) Verify that 'DOC' entry **does** exist in options and in .htaccess rules
4) Install new version and visit Dashboard
5) Verify that 'DOC' entry **does not** exist in options and in .htaccess rules

**Comment by wpsmort** [comment]
I followed the test method provided but the DOC entry was still present in the list of blocked bots and in the database.  I even tried deactivating and deleting the plugin and installing the new version but that did not work.  The only thing that works is if I click the Reset Settings button in the Bad Bot Blocker module.

**Comment by dougalcampbell** [comment]
I'll double-check things. I'm re-working the feature update handling anyways, because we realized that there are other conditions that we need to track to handle various combinations of AIOSEOP Free vs Pro, WordPress core version, etc.

**Comment by wpsmort** [comment]
This has been tested and is working as expected.
