### ISSUE TITLE
Social Meta Module - Disable jetpack opengraph

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#346]

**Comment by michaeltorbert** [comment]
Looks like we have code for this, but it's not working? It looks like the old code.

**Comment by michaeltorbert** [comment]
@wpsmort Unless I'm going crazy, it seems to not be showing up anymore, and removing 			add_filter( 'jetpack_enable_open_graph', '__return_false' );
 from aioseop_opengraph.php doesn't seem to matter.

**Comment by wpsmort** [comment]
Confirmed, I can no longer replicate this issue.
