### ISSUE TITLE
XML Sitemap - Format should follow correct XML schema

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#348]
This was first reported by Cordes Owen in an email dated 06/21/2016.

The correct XML schema for a sitemap should be (http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd):

<loc>http://semperfiwebdesign.com/</loc>
<lastmod>2016-06-14T20:56:28Z</lastmod>
<changefreq>daily</changefreq>
<priority>0.7</priority>

Our format has the <loc> in the wrong place.

**Comment by michaeltorbert** [comment]
the changes that should be made according to the sitemap schema (http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd). If there is anything else I can help you with, please feel free to ask!

Currently:

<lastmod>2016-06-14T20:56:28Z</lastmod>
<changefreq>daily</changefreq>
<priority>0.7</priority>
<loc>http://freshimagecenter.com/fresh-living/common-myths-about-dermal-fillers/</loc>

Should be:

<loc>http://freshimagecenter.com/fresh-living/common-myths-about-dermal-fillers/</loc>
<lastmod>2016-06-14T20:56:28Z</lastmod>
<changefreq>daily</changefreq>
<priority>0.7</priority>

**Comment by wpsmort** [comment]
This is tested and is fine.
