### ISSUE TITLE
XML Sitemap - Load sitemap.xsl dynamically

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#349]

**Comment by michaeltorbert** [comment]
Also maybe related to #337 #137 #133

**Comment by wpsmort** [comment]
@michaeltorbert I tested and got these errors as soon as I tried to visit the XML Sitemap after installing this branch:

PHP Notice:  Undefined index: aiosp_sitemap_prio_blog in /home/internal/public_html/smortiboy/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php on line 1349
PHP Notice:  Undefined index: aiosp_sitemap_freq_blog in /home/internal/public_html/smortiboy/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php on line 1349

**Comment by michaeltorbert** [comment]
@wpsmort Ok this should be fixed now

**Comment by wpsmort** [comment]
@michaeltorbert: The dynamic XSL does not load if you're using Sitemap Indexes. See screednshot:

<img width="1261" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/16283775/359e6622-389c-11e6-8175-f445d91e8e6a.png">

I will continue testing and update this issue if I find any other instances where this does not load.

**Comment by michaeltorbert** [comment]
I think this works now

**Comment by wpsmort** [comment]
@michaeltorbert: I'm getting this error in my log file:

PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/internal/public_html/smortiboy/wp-content/plugins/all-in-one-seo-pack-dynamic-xsl/admin/aioseop_module_class.php:427) in /home/internal/public_html/smortiboy/wp-includes/pluggable.php on line 937

**Comment by wpsmort** [comment]
Dynamic XSL works fine with normal sitemap and sitemap indexes.

Still need to test with WPML and WP Multisite

**Comment by wpsmort** [comment]
This has been tested with WPML and WP Multisite and works.
