### ISSUE TITLE
XML Sitemap - Additional pages for sitemaps needs to force a leading slash on the way in

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#351]

**Comment by michaeltorbert** [comment]
The slash leading the URL's path should show up now in the sitemap.xml file.

**Comment by wpsmort** [comment]
This is tested and is fine.

**Comment by michaeltorbert** [comment]
Just to be clear, this is doing it on the way out, not the way in. We can change that, but we'd need to modify anything currently stored.
