### ISSUE TITLE
XML Sitemap - Remove noindex sitemap option - make it always noindex

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#352]
If somebody asks for it, we can add a hook to change this.

**Comment by michaeltorbert** [comment]
related to #353

**Comment by michaeltorbert** [comment]
This is done, and also only for dynamic. I recommend not worrying about it either for static.

**Comment by wpsmort** [comment]
This is tested and is fine.
