### ISSUE TITLE
XML Sitemap - Add a hook to statically serve the XSL file

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#354]
We need a hook and filter for small percentage of users who select Static XML Sitemap and where the dynamic XSL file won't work.

**Comment by michaeltorbert** [comment]
Done and ready for testing... https://semperplugins.com/documentation/aioseop_sitemap_xsl_url/

**Comment by wpsmort** [comment]
@michaeltorbert: I test and found one issue with this.  If you change back from Static sitemap to Dynamic sitemap but don't remove the filter then the dynamic sitemap still uses your custom static XSL file, not the dynamic XSL.

**Comment by wpsmort** [comment]
If the filter is being used then we respect it regardless of whether they are using Dynamic or Static sitemap generation.
