### ISSUE TITLE
Add code to noindex dofollow RSS feeds

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#356]
This enhancement was requested here https://wordpress.org/support/topic/noindex-rss-feed

**Comment by michaeltorbert** [comment]
If we go with this, noindex, follow would work here. We should decide if we want this as a hook, default behavior, or an option.

**Comment by wpsmort** [comment]
See also #353 and #352

**Comment by wpsmort** [comment]
@michaeltorbert: I tested this and don't see any noindex tag in my RSS feed http://stevemortiboy.com/feed/.  I checked the feed for my blog and a category archive too.

**Comment by michaeltorbert** [comment]
I put it in as an HTTP header. Both follow and noindex
<img width="506" alt="screen shot 2016-06-27 at 4 42 42 pm" src="https://cloud.githubusercontent.com/assets/17364998/16395105/5bc65c54-3c86-11e6-95f6-42a4681568cb.png">

**Comment by wpsmort** [comment]
This is tested and is fine.
