### ISSUE TITLE
on a new install, the menus aren't showing until after a pageload

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#357]
<img width="1382" alt="screen shot 2016-06-23 at 2 48 56 pm" src="https://cloud.githubusercontent.com/assets/17364998/16315782/b4af1bcc-3951-11e6-984f-47d0d680520f.png">

**Comment by michaeltorbert** [comment]
And strangely, performance seems active by default
<img width="823" alt="screen shot 2016-06-23 at 2 49 58 pm" src="https://cloud.githubusercontent.com/assets/17364998/16315811/cfcf8752-3951-11e6-8029-539c18659290.png">

**Comment by wpsmort** [comment]
@arnaudbroes: Can you test this and see if it only happens on a brand new WordPress site that has never had All in One SEO Pack installed before, or if it also happens on sites where All in One SEO Pack was once installed, and deactivated then updated, or deleted and reinstalled.

**Comment by arnaudbroes** [comment]
@wpsmort what branch should I use, Development or just Master?

**Comment by wpsmort** [comment]
@arnaudbroes you can use the current live version from WordPress.org

**Comment by arnaudbroes** [comment]
@wpsmort 
Issue applies to fresh install on a new site.
Does not occur after updating to a newer version or reinstalling the plugin.

**Comment by arnaudbroes** [comment]
Issue broke when the plugin was updated from 2.3 to 2.3.1.

**Comment by michaeltorbert** [comment]
This is from moving the add_cap( 'aiosp_manage_seo' ) into add_hooks() which fires on init. That may be too late for the menus to load (which require the cap). 
We can see if this can run sooner, otherwise we could either a) load the menus with either that cap or some other admin cap (can you send an array of caps on the add_menu?) or b) figure out if we're being newly activated and if so load the menus separately (and possibly the rest of the install stuff like default settings) This is very likely related to 332

**Comment by michaeltorbert** [comment]
This should be fixed, but needs to be verified. (xsl branch at the moment)

**Comment by wpsmort** [comment]
This is tested and confirmed to be fixed for new installs of AIOSEOP on a site
