### ISSUE TITLE
XML Sitemap - Testing updating to the new version

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#360]
When testing that the new dynamic xsl file is being called, we need to test that the sitemap gets rebuilt (showing the new URL) immediately after clicking update to 2.3.6, and doesn't require any intervention from the user. 
This should only apply to static sitemaps, and needs to be tested with and without indexes, pagination, and compression.

-The code for this hasn't been written yet.

**Comment by wpsmort** [comment]
@michaeltorbert I have tested and found that the dynamic XSL only shows after the user clicks the Update Sitemap button.

**Comment by michaeltorbert** [comment]
@wpsmort Yeah, notice where I wrote "The code for this hasn't been written yet".
I guess this was meant as a reminder to write it.

**Comment by michaeltorbert** [comment]
Ok when AIOSEOP is updated, the static XML sitemap should be rebuilt.

**Comment by wpsmort** [comment]
This is tested and works fine.
