### ISSUE TITLE
Sitemap help string is wrong for dynamic option

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#361]
in aioseop_sitemap.php there is:

'rewrite'         => __( 'Places a link to the sitemap file in your virtual Robots.txt file which WordPress creates.', 'all-in-one-seo-pack' ),
<img width="978" alt="screen shot 2016-06-23 at 7 41 47 pm" src="https://cloud.githubusercontent.com/assets/17364998/16323685/b47193b4-397a-11e6-8ec1-b3419f73a525.png">

**Comment by wpsmort** [comment]
This is done and tested.
