### ISSUE TITLE
Contact Jetpack devs about remaining conflicting modules

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#362]
We need to contact them to ask that sitemaps, opengraph, and anything else conflicting is disabled on their end when either free or pro is active.

They check for some things but not everything and not for both plugins. Currently I think we're disabling their opengraph, and 2.3.6 will have code to disable their sitemap, but I'd rather it come from their end eventually.

@wpsmort Do you know who we've talked to there in the past?

**Comment by michaeltorbert** [comment]
Related to #336

**Comment by wpsmort** [comment]
@michaeltorbert: Our contacts in the past was George Stephanis - georgestephanis@automattic.com @georgestephanis on Slack

**Comment by wpsmort** [comment]
@michaeltorbert I've forwarded email history of when we worked with George to have them check for AIOSEOP Pro to remove their OG meta

**Comment by georgestephanis** [comment]
Everything we do in Jetpack is controlled by filters and we'll documented.

Ideally, y'all would use those to deactivate Jetpack's functionality
conditionally if yours is configured, as our way is brute force -- if
plugin is active, nuke it.

**Comment by wpsmort** [comment]
This is closed.
