### ISSUE TITLE
Possible issue with pages loading when translated

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#368]
https://wordpress.org/support/topic/xml-sitemap-page-broken?replies=5#post-8577239

A user has reported that when switching to pt-BR, the sitemap settings page doesn't load.
If we can verify this, depending on what the problem is, we may need to test other languages as well.

**Comment by michaeltorbert** [comment]
So far, I'm unable to reproduce this. In 2.3.5.1 with the latest pt-BR, all my pages load correctly.

**Comment by michaeltorbert** [comment]
@arnaudbroes When you get a chance, can you switch to each language, then browse through each of the settings pages and see if you can reproduce this issue? Use 2.3.5.1 from https://wordpress.org/plugins/all-in-one-seo-pack/, not from github

**Comment by michaeltorbert** [comment]
@arnaudbroes Nevermind. :)

**Comment by michaeltorbert** [comment]
Ok so basically if the host server ever has a problem with remote get requests, the WP Error object gets in the way of things, and crashes the rest of the page, on the translation request section. That's why it was only happening in non-English languages for him... when WP was reaching out to wordpress.org for translation information.
I have I have some rough code so far to at least avoid the page getting destroyed, I'll figure out the rest later and try to ship it with 2.3.6. @wpsmort Fun times. :)

**Comment by michaeltorbert** [comment]
Ok this is fixed, in that the page loads now for people who can't make HTTP (or at least HTTPS) GET requests. We'll do a more elegant solution later.

**Comment by wpsmort** [comment]
This is tested and confirmed fixed.
