### ISSUE TITLE
XML Sitemap - Add sitemap support for AMP pages

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#37]
Add sitemap support for pages created using the AMP plugin - https://wordpress.org/plugins/amp/

Pages created using this plugin should be listed in our XML sitemap.

**Comment by mrtorbert** [comment]
It's actually just posts at the moment.

**Comment by wpsmort** [comment]
https://support.google.com/webmasters/answer/6340290?hl=en
http://technicalseo.com/seo-tools/amp/

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1458

**Comment by wpsmort** [comment]
Updated information from John Mueller at Google where he states that an XML Sitemap is not needed for AMP pages, the rel=amphtml link is enough - https://twitter.com/JohnMu/status/786588362706673664
