### ISSUE TITLE
We need a way for users to add in extra Google Analytics code

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#371]
We need a filter or a field in the UI for users to add in extra Google Analytics code that we don't yet support and have it be included in the tracking code we output.

**Comment by wpsmort** [comment]
This has been requested multiple times by many users, the latest was from Mathias Priebe by email on 06/30/2016

**Comment by michaeltorbert** [comment]
We actually already have a filter hook for this https://semperplugins.com/documentation/filter-all-in-one-seo-pack-google-analytics/
I'll add an action hook as well.

**Comment by michaeltorbert** [comment]
We not have an action hook to add stuff after https://semperplugins.com/documentation/add-code-after-google-analytics-in-all-in-one-seo-pack/

So they can use whichever they want.

**Comment by wpsmort** [comment]
This is tested and is working.
