### ISSUE TITLE
XML Sitemap - Static sitemap maybe not updating with post changes

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#375]
In 2.3.6, we changed it so that static sitemaps were updated immediately upon adding, deleting, or changing (the url of) a post. Now it seems this isn't happening in all cases... Even when manually clicking to rebuild the sitemap.

**Comment by michaeltorbert** [comment]
I'm having a hard time reproducing this... it seemed to only be happening when updating to 2.3.6

**Comment by wpsmort** [comment]
I tested this in the development version of 2.3.10 when we removed the Build sitemap link and was not able to reproduce the problem.  The static sitemap updated when I published, modified and deleted a post/page.
