### ISSUE TITLE
Change AIOSEOP_Updates class name to match the appropriate casing

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#378]
This last minute change is why db migrations (or rebuilding of the sitemap) wouldn't have happened the last update.

**Comment by michaeltorbert** [comment]
For testing purposes, test that updates fire. (yandex, sitemap rebuild, etc)

**Comment by wpsmort** [comment]
This is tested and is fine.
