### ISSUE TITLE
illegal string offset warning in 2.3.6

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#379]
Reported here: https://wordpress.org/support/topic/errors-on-save-1?replies=2#post-8602767

**Comment by michaeltorbert** [comment]
I can't reproduce this, and I'm not sure why it's an issue to begin with by looking at the code.

**Comment by arnaudbroes** [comment]
I'm not able to reproduce this either. I'm closing this issue since it's been so long since the initial report.
