### ISSUE TITLE
Social Meta Module - Strip the URL from the twitter:creator meta tag

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#38]
This was first reported here - https://wordpress.org/support/topic/twitter-meta-twittercreator-should-filter-out-protocol-and-host

We use the Twitter field in the user profile (Users, Your Profile) to add the twitter:creator tag.  However, most people paste the URL for their Twitter profile in that field like so https://twitter.com/wpsmort

This results in the meta tag being created as this:

<meta name="twitter:creator" content="@https://twitter.com/wpsmort" />

We need to strip the first part of the URL so that the meta tag looks like this:

<meta name="twitter:creator" content="@wpsmort" />

See screenshot.

![screen shot 2016-03-17 at 9 31 57 am](https://cloud.githubusercontent.com/assets/17548525/13847361/4199ee76-ec23-11e5-8cd6-ed28ba76c40d.png)

**Comment by michaeltorbert** [comment]
@vmarinov2013 This won't work unless they enter the URL perfectly. A regular expression would be better.

**Comment by michaeltorbert** [comment]
@wpsmort Do we want to only strip/validate when we're displaying to the screen or do we want to validate when we save to the database (which would require a db upgrade to fix ones already entered).

**Comment by wpsmort** [comment]
@michaeltorbert I feel that the best approach is to validate and strip incorrect entries when we save to the database.  That way we can ensure anyone who has incorrectly entered their Twitter handle.

**Comment by wpsmort** [comment]
I've opened a new issue to validate two other fields - #139

**Comment by nishant981** [comment]
We are working on this issue

**Comment by wpsmort** [comment]
This is tested and works in free and Pro.
