### ISSUE TITLE
Possible memory issue with a lot of posts

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#380]
Use a plugin like Fakerpress (https://wordpress.org/plugins/fakerpress/) to generate a lot of posts (this user has almost 40,000) and see if we get any memory issues.

For testing purposes, testers should probably have all plugins turned off while creating the posts (it's pretty resource intensive), and then turn on AIOSEOP, along with the Sitemap module. Try both dynamic and static.

Reported here: https://wordpress.org/support/topic/blank-admin-section-after-update-to-236?replies=9#post-8603099

**Comment by michaeltorbert** [comment]
On his site, the memory issue only seems to apply to static sitemaps. Dynamic is fine, except when I switch it to use indexes, clicking on an index redirects back to sitemap.xml.

**Comment by wpsmort** [comment]
We found the issue with the indexes redirecting was caused by code in his .htaccess file.  Testing this with a copy of his site here locally did not produce any issues.

**Comment by arnaudbroes** [comment]
I'm testing it but not encountering issues as well.

**Comment by michaeltorbert** [comment]
It looks like it's mainly pages doing it, and not posts or any other post type.

**Comment by michaeltorbert** [comment]
Closing this as it can't reliably be reproduced. The only problem would probably be when building static sitemaps with 10s of thousands of posts... but you should be using dynamic.
