### ISSUE TITLE
XML Sitemap - Image support for sitemaps

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#386]
We should discuss whether to do like (I think) Jetpack does and include them (in the source) for featured images or in a separate sitemap.
Benefits of the first way include a) not having to scan posts for images, then figure out if they're locally hosted, etc (possible, just may take a lot of resources) b) including all uploaded media may not be good, since many sites have media that isn't part of a published post
Benefits of doing it the second way including keeping everything more organized, displaying it as a prominent feature instead of hidden away, etc

**Comment by wpsmort** [comment]
PR #978 adds support for images in the main XML Sitemap and adds a column that displays the number of images for each sitemap entry.  

We have discussed whether images should be in a separate sitemap or in the main sitemap and decided to include them in the main sitemap as this appears to be what Google expects (https://support.google.com/webmasters/answer/178636?hl=en).  

We have also discussed whether this should be a part of the new Image SEO module which will be a Pro only feature and decided that this should remain as part of the free XML Sitemap functionality.

**Comment by wpsmort** [comment]
I tested the new image sitemap functionality with a large photography site and here are the results:

A sitemap that has 7,509 URLs with 11,280 images took 10 seconds using the current live plugin (v2.3.16) and 14 seconds with the new image sitemap in v2.4.
