### ISSUE TITLE
safe_mode

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#399]
We're just detecting safe_mode for the Performance Module, but make sure there are no problems on PHP 7, and see if we even really need to do this anymore, since this is an ancient feature.

FILE: /home/dq/public_html/wp-app/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_performance.php
--------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------
172 | ERROR | INI directive 'safe_mode' is deprecated from PHP 5.3 and forbidden from PHP 5.4.

**Comment by wpsmort** [comment]
Ran the PHP Compatibility Checker and it found no errors.
