### ISSUE TITLE
Make user profile meta fields always show up

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#40]
Remove the option and just have them show up for everyone. related to #39

**Comment by wpsmort** [comment]
There are three options that display/hide fields on the Edit User screen, these are:

All in One SEO > General Settings > Google Settings > Disable Google Plus Profile
All in One SEO > Social Meta > Facebook Settings > Show Facebook Author on Articles
All in One SEO > Social Meta > Twitter Settings > Show Twitter Author

**Comment by iko-dev** [comment]
We forked first time while working on issue 2, this time we cloned that and updated our code in. Created new branch iko-dev_issue39-1 and pushed
