### ISSUE TITLE
PHP Notice: Array to string conversion

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#403]
Reported here: https://wordpress.org/support/topic/php-notice-array-to-string-conversion-5?replies=2#post-8632543

`PHP "Array to string conversion" notices in aioseop_class.php on line 3973 and aioseop_module_class.php on line 148. I was able to narrow down the issue to how you register your output buffer in aioseop_class.php on line 3492. You register an array with the class and the output_callback_for_title method, but your check on line 3959 is for All_in_One_SEO_Pack::output_callback_for_title.

Replacing ob_start( array( $this, 'output_callback_for_title' ) ); with ob_start( 'All_in_One_SEO_Pack::output_callback_for_title' ); on line 3492 fixes the issue.`

**Comment by michaeltorbert** [comment]
Hi Carl,

Thank you for your pull request. Can you change the base branch to development instead of master?

**Comment by carlalexander** [comment]
Here you go!

**Comment by michaeltorbert** [comment]
@carlalexander Thank you for the patch. Unfortunately this won't work to statically call a class method. I'm not sure how you'd be getting array to string from aioseop_module_class.php on line 148.
Is this a new notice or had you been getting it for a while? Do you know what version it started?
It would help if I can know how to reproduce it.

**Comment by carlalexander** [comment]
It's a notice that we're getting with HHVM. But why do you say that it won't work? This is a valid [callable](http://php.net/manual/en/language.types.callable.php) since PHP 5.2.3.

**Comment by amostajo** [comment]
From a simple review, `All_in_One_SEO_Pack::output_callback_for_title` would only work if `output_callback_for_title` is static, which it isn't.

On line 3419 it is passed with a class reference for the same purpose.

This is also clarified on the php [documentation](http://php.net/manual/en/language.types.callable.php) @carlalexander shared:
```php
// Type 4: Static class method call (As of PHP 5.2.3)
call_user_func('MyClass::myCallbackMethod');
```
Though I will test this locally just to confirm.

**Comment by amostajo** [comment]
Test ran:
https://gist.github.com/amostajo/96ec1f80af77faf95593b61298d881fa

This will result on a faltal error:
```bash
( ! ) Strict standards: call_user_func() expects parameter 1 to be a valid callback, non-static method Test::non_static() should not be called statically in C:\Users\Alejandro\Documents\www\test\callables.php on line 66
Call Stack
#	Time	Memory	Function	Location
1	0.0005	254736	{main}( )	..\callables.php:0
2	0.0005	255200	call_user_func:{C:\Users\Alejandro\Documents\www\test\callables.php:66} ( )	..\callables.php:66

( ! ) Fatal error: Using $this when not in object context in C:\Users\Alejandro\Documents\www\test\callables.php on line 19
Call Stack
#	Time	Memory	Function	Location
1	0.0005	254736	{main}( )	..\callables.php:0
2	0.0005	255200	call_user_func:{C:\Users\Alejandro\Documents\www\test\callables.php:66} ( )	..\callables.php:66
3	0.0167	255752	Test::non_static( )	..\callables.php:66

```

**Comment by amostajo** [comment]
We reopened the ticket with @michaeltorbert just to make sure line 3960 on aioseop_class.php was functioning right and it is, the callable `'All_in_One_SEO_Pack::output_callback_for_title'` is rightly compared and validated to generate the flush the way it is set in the code.
