### ISSUE TITLE
Test for PHP 5.2 compatibility

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#408]
In Simplemap 2.4.9, we inadvertently introduced a PHP 5.3 requirement. We need to do full testing of AIOSEOP in PHP 5.2 to ensure compatibility.

**Comment by wpsmort** [comment]
I tested AIOSEOP with PHO 5.2.4 and there were no issues and no errors in the debug log.
