### ISSUE TITLE
Remove our current Schema.org markup

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#413]
We currently add two lines of Schema.org markup to the HTML tag as follows:

```
<html lang="en-US"
    itemscope 
    itemtype="http://schema.org/WebSite" 
    prefix="og: http://ogp.me/ns#"  class="no-js">
```

These two lines need to be removed:
    itemscope 
    itemtype="http://schema.org/WebSite" 

This will leave the HTLM tag looking like this:

`<html lang="en-US" prefix="og: http://ogp.me/ns#" class="no-js">`

We will be replacing this with the new JSON+LD markup, refer to issue #72 and #73  for this.

**Comment by wpsmort** [comment]
This is now causing issues with the AMP markup validator, reported here - https://wordpress.org/support/topic/problem-with-amp-plugin/

**Comment by wpsmort** [comment]
When we remove this, we need to remove the code added under issue #575 to detect the AMP plugin.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1911 (as this is related to #407)

**Comment by michaeltorbert** [comment]
@wpsmort Does this need to be done at the same time as  #72 and #73 or is it fine to push this out prior to those?
