### ISSUE TITLE
Force Facebook to refresh the cache

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#414]
https://wordpress.org/plugins/facebook-url-linter-for-posts/

http://stackoverflow.com/questions/19836618/how-do-i-debug-a-crawled-cached-link-without-facebooks-url-linter

**Comment by michaeltorbert** [comment]
Ok this should work for any post type that is enabled for social when a post is updated. Testing should include that a) it works and b) it only works on appropriate post types

**Comment by michaeltorbert** [comment]
Now it also works when the post_status changes to "publish" (ie when a scheduled post goes live). This should be tested as well.

**Comment by wpsmort** [comment]
@michaeltorbert I tested this and get a 500 error on post actions including publish, update and delete post. Here's the error from my debug log:

PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Post as array in /all-in-one-seo-pack/modules/aioseop_opengraph.php:677

**Comment by wpsmort** [comment]
This is tested and is good.
