### ISSUE TITLE
 Possible good crawler on Bad Bot Blocklist

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#418]
One of our translators reported that he thinks AIOSEO has a crawler on the Bad Bot Blocklist that shouldn't be blocked: SeznamBot (www.seznam.cz). 

Click image URL for more info.
http://image.prntscr.com/image/10a34ffe21ec4aabbc74fc10bb09e8e9.jpeg

**Comment by wpsmort** [comment]
This is confirmed, by default we are blocking SeznamBot

**Comment by wpsmort** [comment]
@michaeltorbert When I update from the current live version to the latest from dev branch, the SeznamBot is not removed from the .htaccess file or the database table

**Comment by wpsmort** [comment]
This is tested and is now working fine.
