### ISSUE TITLE
Remove setting for sitemap ping frequency 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#425]
Set the default to weekly, but with a filter hook to change it.

Possible way to do it:

First check for filter hook override.
Then check if old database entry exists.
If neither exists, default to weekly.

**Comment by wpsmort** [comment]
According to the best practices document on Google, we should probably just set this frequency to daily and then I don't believe we'd need a filter - 

https://webmasters.googleblog.com/2014/10/best-practices-for-xml-sitemaps-rssatom.html

This should also take care of issue #359 as we wouldn't need to ping after each post update.  In future we could consider adding the RSS/Atom method for more frequent updates.

**Comment by wpsmort** [comment]
See also #550

**Comment by arnaudbroes** [comment]
@michaeltorbert should this issue still be open since we already removed this setting?

**Comment by michaeltorbert** [comment]
This option has already been removed.
