### ISSUE TITLE
Look into pings for Yandex and Baidu

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#426]
Any other major search engines we want to do?

Related to #424

**Comment by wpsmort** [comment]
There's an article about this here - http://techinfoknow.com/ping-sitemaps-google-bing-baidu-yandex

**Comment by arnaudbroes** [comment]
Looks like Yandex used to have it but no longer does, and Baidu supports something for blog feeds but not for sitemaps. I'll go ahead and close this.
