### ISSUE TITLE
possible canonical URL issue

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#437]
Reported here: https://wordpress.org/support/topic/wrong-canonical-1?replies=1#post-8764788

_
_The WordPress has a bug, when page with non-existed subpage is a copy from main page.
Example: http://morrock.com/casino-games/32423 is the same as http://morrock.com/casino-games/

But the problem is that page is indexed by Google and is a duplicate of main page, because the canonical URL is http://morrock.com/casino-games/32423/.
Some websites fix this bug just replacing http://morrock.com/casino-games/*SUBPAGE*/ to http://morrock.com/casino-games/

404 page exist, so some pages like 222 or 333 always open same page. On all websites that use _wordpress__
_

**Comment by michaeltorbert** [comment]
This can be reproduced by adding numbers at the end of a real page... https://semperplugins.com/all-in-one-seo-pack-pro-version/123/

It's not a "subpage" but WP apparently thinks it's a page with pagination and so in this example, the 123rd page.

**Comment by michaeltorbert** [comment]
This actually may be a new issue. We need to test going back years if it always existed. There's a report that it worked in 2014.

**Comment by michaeltorbert** [comment]
This should also be tested not just for pages, but for posts, terms, etc.

**Comment by wpsmort** [comment]
This worked in v2.0 and broke in v2.0.1.

**Comment by michaeltorbert** [comment]
@wpsmort Is this supposed to be closed?

**Comment by wpsmort** [comment]
@michaeltorbert No this should not be closed. I have changed this to the milestone for all canonical URL related issues.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1481
