### ISSUE TITLE
Possible bug in bad bot blocker

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#439]
Reported here: https://wordpress.org/support/topic/bad-bot-blocker-problem-in-aiosp-238?replies=5#post-8775732

I'm not sure all the details of what's happening, but when you start from scratch, and enable all checkboxes, both the agent and referrer section in .htaccess have what should only go into the agent section. Then, if you save the settings again, it corrects itself.

I've been able to (inconsistently) reproduce the reported 404 error.

**Comment by michaeltorbert** [comment]
For the 404 error, it seems that if you reset bad bots to defaults, then check everything and save, you get a 404 error when trying to save the performance module settings until you click save again in bad bots.

**Comment by wpsmort** [comment]
@michaeltorbert: This bug has always been present in Bad Bot Blocker ever since that module was introduced in v2.2.7.

**Comment by michaeltorbert** [comment]
Let's see if this is related to the other issues.

**Comment by michaeltorbert** [comment]
This was fixed in #480
