### ISSUE TITLE
Review implementation of the article:author Open Graph tag

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#44]
Pinterest want the article:author tag to be a name, whereas OGP and Facebook state it should be a profile (URL).  We need to test and see whether changing this to accommodate both with work.

See these forum posts - 
https://wordpress.org/support/topic/ogauthor-not-showing
https://wordpress.org/support/topic/questions-about-the-open-graph-meta-propertyarticleauthor-tag-in-jetpack-28

**Comment by mrtorbert** [comment]
@wpsmort The only thing I can think of to do would be to detect the Pinterest crawler user agent and show it differently. The problem here is caching. One would get cached and shown incorrectly to the other.

**Comment by wpsmort** [comment]
I tested whether we can support multiple article:author tags as per the Open Graph standard but Facebook returns errors when it sees the additional tags and it breaks sharing on Facebook.  This is just not possible at this time.
