### ISSUE TITLE
Verify plugin works in mu-plugins

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#441]
(must use)

**Comment by arnaudbroes** [comment]
It wouldn't because of the following two reasons:

> - Activation hooks are not executed in plugins added to the must-use plugins folder. These hooks are used by many plugins to run installation code that sets up the plugin initially and/or uninstall code that cleans up when the plugin is deleted. Plugins depending on these hooks may not function in the mu-plugins folder, and as such all plugins should be carefully tested specifically in the mu-plugins directory before being deployed to a live site.
> 
> - WordPress only looks for PHP files right inside the mu-plugins directory, and (unlike for normal plugins) not for files in subdirectories. 

This also means we can't make it work as a must-use plugin, nor do I think we should anyway.
