### ISSUE TITLE
Auto set protocol for canonical URLs

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#443]
We currently have an option for Set Protocol for Canonical URLs.  

We should remove this option and replace it with the aioseop_canonical_url filter or a new filter hook (aioseop_canonical_protocol).  

However, before we do this we need to make sure that we auto detect the protocol for the site by checking the Home URL / Site URL or possibly what WordPress thinks the permalink should be (see if WordPress knows the correct protocol in all circumstances). If we can auto detect the protocol then we can just provide a filter for changing what's auto detected.

Maintain checks for HTTP / HTTPS if it was previously set in an old version of AIOSEOP. Make sure to include in the PHP comments that its a legacy non-existent setting.

See also #374 and #437

**Comment by michaeltorbert** [comment]
@wpsmort We're not actually detecting with auto at the moment. Auto just uses what's already there. (The built-in is_ssl() function is able to tell in most cases.) 
All we're doing is if someone chooses http or https we replace what was there with that.

I'm not sure what checking is_ssl() will really do, since we don't seem to be getting it wrong as far as I know.

**Comment by michaeltorbert** [comment]
Also, we should decide if we want to respect the legacy setting. 
I really really don't want to, as it would 
1) greatly simplify the code 
2) probably almost nobody is using this anyway

but,
If someone is, this could really screw them up to lose it and not know it.

**Comment by wpsmort** [comment]
We discussed this and decided to remove the option and not respect the previous setting.

**Comment by michaeltorbert** [comment]
Ok Canonical URL settings and all functionality is removed, except for the changes made for #312 in 2.3.5.
This function checks for the setting and matches it against the custom canonical URL. We could either just remove this and trust people to use the correct protocol for their custom canonical URLs, or else we could leave this in there and check against is_ssl.

**Comment by wpsmort** [comment]
@michaeltorbert As discussed, let's add a filter here which can be used if someone needs it to set the protocol on their custom canonical URLs.

Side note, the reason we added the code in#312 was because we had the option for Set protocol for canonical URL where you could force AIOSEOP to use a specific protocol.  But then this setting had no effect on custom canonical URLs which was deemed a bug because if you give someone a setting to force a specific protocol then any canonical URL we output (custom or otherwise) should be forced to that protocol.  Now that we're removing the ability to force a specific protocol we don't need to be concerned with what's entered in a custom canonical URL field.

**Comment by michaeltorbert** [comment]
The filter hook to change the canonical URL protocol is aioseop_canonical_protocol
This is specifically for custom canonicals, but will apply to all of them. It accepts either https or http (case-sensitive), all other values will be ignored.

**Comment by wpsmort** [comment]
This is tested and all works.  I also tested the new filter hook and confirmed that works.  I added a document for this here - https://semperplugins.com/documentation/filter-to-change-canonical-url-protocol/
