### ISSUE TITLE
Edit SEO link in Admin Bar points to wrong location for dynamic homepage

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#444]
Reported here - https://wordpress.org/support/topic/seo-settings-editing-online-latest-blog-post?replies=2#post-8787523

**Comment by wpsmort** [comment]
This bug is confirmed.  If you have your homepage set to display your latest posts then the Edit SEO link in the Admin bar takes you to the latest post.

**Comment by michaeltorbert** [comment]
"Edit SEO" *should be removed now for a dynamic homepage (and hopefully nowhere else).
Did we want it to point somewhere or just remove it?

**Comment by wpsmort** [comment]
@michaeltorbert I tested and this has been removed when the homepage is a static page as well.  I think it should only be removed when the homepage is a dynamic page.

**Comment by michaeltorbert** [comment]
This should be working now.

**Comment by wpsmort** [comment]
This is tested and works.
