### ISSUE TITLE
Pinterest verification error

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#453]
reported: https://wordpress.org/support/topic/problem-verifying-pinterest?replies=1#post-8808301

I've verified the issue, although we're definitely using the appropriate meta field according to Pinterest's latest instructions. It seems like a problem on their end.

**Comment by arnaudbroes** [comment]
This works fine, so you were probably right that it was an issue on their end.
![image](https://user-images.githubusercontent.com/18156697/52921964-03a93600-331d-11e9-91f6-92ff6ee21479.png)
