### ISSUE TITLE
Social Meta Module - Add a filter to set which image size is used for OG Image

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#455]
This was first raised here - https://wordpress.org/support/topic/featured-image-too-small-in-all-in-one-seo

We should have a filter so that you can set which image size is used for OG image.  That way, if the featured image or other image is too small and there's a larger size for that image, the user can choose to use that larger size.

**Comment by michaeltorbert** [comment]
@wpsmort  By size, does this mean thumbnail, medium, large, or whatever custom image sizes have been added?

**Comment by michaeltorbert** [comment]
Ok two filter hooks have been added.  One for the thumbnail/featured image and one for the attachment image.

https://semperplugins.com/documentation/opengraph-image-size/
https://semperplugins.com/documentation/opengraph_attachment_size/

**Comment by wpsmort** [comment]
These are tested and work.
