### ISSUE TITLE
Redirect Attachment to Parent Post doesn't work in WooCommerce products

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#456]
If you embed an image in a WooCommerce product in either the main content area or the Product Short Description and link it to the attachment page then our Redirect Attachment to Parent Post does not redirect correctly.

On my test site, both the image in the main content area and the image in the short description section redirected to my About page which is the page those images are attached to.

**Comment by michaeltorbert** [comment]
@wpsmort I'm not sure what isn't working about it then if they redirected to the about page. Is that not their post parent?

**Comment by wpsmort** [comment]
I have confirmed that this is working fine.  I created a new product and uploaded an image to the login description and short description and both redirected to the parent product.
