### ISSUE TITLE
Use only Universal Analytics

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#463]
Universal Analytics is now the operating standard. We should remove this as an option. Now is probably a good time to verify our scripts.

Reported: https://wordpress.org/support/topic/universal-analytics-13/

See:
https://support.google.com/analytics/answer/3450662?hl=en
https://developers.google.com/analytics/devguides/collection/analyticsjs/
https://support.google.com/analytics/answer/2790010?hl=en

We can consider allowing the old ga.js via a hook if for some reason someone wants it. We need to make sure to include this in the release blog post.

**Comment by michaeltorbert** [comment]
https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by michaeltorbert** [comment]
See if we can check if they had the old analytics in place... did we have a value if they didn't check it?

**Comment by michaeltorbert** [comment]
@wpsmort This should be working. When testing, make sure to test all the various combinations of analytics settings to see that I didn't break anything. Check the source for each.

**Comment by wpsmort** [comment]
@michaeltorbert This is tested and all is fine except that the 'allowLinker': true variable has been removed. I see the commit for that but I don't think it should have been removed because it's required for cross-domain tracking. I've opened issue #467 for this.
