### ISSUE TITLE
Add back the code for 'allowLinker': true

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#467]
This was removed in this commit https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/ec156fc48e6dbbb9602c1f08df5b370e81e8adf9 but it's still required for cross-domain tracking.

**Comment by michaeltorbert** [comment]
This should be good now.

**Comment by wpsmort** [comment]
This is tested and is fine.
