### ISSUE TITLE
Determine correct class for orange buttons

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#473]
On our Welcome panel we added our own class for the orange button but there should be a class in WordPress for an orange button.  See if we can figure out what that class is and change our orange button to use it.

**Comment by arnaudbroes** [comment]
@wpsmort I'm not able to find such a class in \wp-includes\css\buttons.css.

**Comment by wpsmort** [comment]
@arnaudbroes I believe you are correct.  It looks like there is only .button-primary and .button-secondary now.  I'm therefore closing this as I don't believe we need to make any change to the current button or CSS class.
