### ISSUE TITLE
Incorrect link in welcome panel 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#485]
Reported here: https://www.facebook.com/photo.php?fbid=10154444790582071&set=o.118018874899420&type=3&theater

_"Hi. I possibly found a mistake in All in One SEO Pack 2.3.9.2.
When I click on "Submit an XML Sitemap to Google" it actually takes me to this url:
https://semperplugins.com/documentation/quality-guidelines-for-seo-titles-and-descriptions/
But I guess it should take me to something like this:
https://semperplugins.com/documentation/submitting-an-xml-sitemap-to-google/"_

![](https://scontent-iad3-1.xx.fbcdn.net/t31.0-8/14257612_10154444790582071_4550299719646195177_o.jpg)

**Comment by wpsmort** [comment]
This has been fixed.
