### ISSUE TITLE
typo in documentation 

### ISSUE THREAD

**Issue by dawatorbert** [semperfiwebdesign/all-in-one-seo-pack#487]
Translators Contributors and Translation Editors should be "Translation contributors and translation editors".

![screen shot 2016-09-08 at 6 44 21 pm](https://cloud.githubusercontent.com/assets/18234064/18369546/5d170cdc-75f4-11e6-9c82-e1e7e17e0ae3.png)

**Comment by wpsmort** [comment]
This typo has been fixed.
