### ISSUE TITLE
one more typo in documentation 

### ISSUE THREAD

**Issue by dawatorbert** [semperfiwebdesign/all-in-one-seo-pack#488]
this sentence should be " there are many ways you can help support All in One SEO Pack"

![screen shot 2016-09-08 at 6 48 15 pm](https://cloud.githubusercontent.com/assets/18234064/18369634/0319b21a-75f5-11e6-93e2-6c976e90fc71.png)

**Comment by wpsmort** [comment]
This typo has been fixed
