### ISSUE TITLE
Welcome panel appears in modal windows

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#494]
When you update AIOSEOP to v2.3.9.2 and the second click opens a modal window then the Welcome panel appears in the modal window.  Here are the steps to reproduce:
1. Go to Dashboard > Updates and ensure you have multiple plugins to update.
2. Update just AIOSEOP to v2.3.9.2
3. Click on the Return to WordPress Updates page link after the plugin has updated. This is click number 1
4. Now click on the View version x details of another plugin to launch the modal window.  This is click number 2 and the Welcome panel should appear in this modal.  See screenshots below:

![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/18442015/2488e930-78dd-11e6-9dfa-93a32d88aa08.png)

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/18442019/27a537b8-78dd-11e6-99a1-45e3e4e1b4cd.png)

**Comment by arnaudbroes** [comment]
The welcome screen has already been redone and is no longer a modal.
