### ISSUE TITLE
Bad Bot Blocker - Consider externally hosting the bad bots list

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#499]
This was first reported here - https://wordpress.org/support/topic/problems-updating-plugin-on-yourhosting-nl/

This particular server set up did not like the bot list included in \admin\aioseop_module_class.php

**Comment by michaeltorbert** [comment]
I'm not sure how a separate file would help, since it would still be included in the plugin.

**Comment by michaeltorbert** [comment]
Closing this until we get some more info.
