### ISSUE TITLE
Schema.org - Add JSON-LD Schema for AMP

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#506]
Google supports different JSON-LD markup for AMP articles than normal articles.  When we add support for AMP (See issues #211 and #37) we will need to add the JSON-LD for AMP articles.

https://developers.google.com/search/docs/data-types/article#amp - See Markup for AMP

**Comment by wpsmort** [comment]
Note: The AMP plugin already outputs this Schema markup.

**Comment by wpsmort** [comment]
The official AMP plugin (https://wordpress.org/plugins/amp/) outputs its own Schema markup on AMP pages.  Therefore, we should discuss whether we:

1. Output our own Schema markup to extend what the AMP plugin outputs
2. See if we can hook into the AMP plugin and remove what they output and replace it with our own markup
3. Have a filter hook that can be used to hook into our markup

**Comment by wpsmort** [comment]
As discussed with @EkoJR, I tested by adding our schema markup to an AMP post so that it supplemented the schema markup output by the AMP plugin to see if it caused conflicts.  

I didn't get any errors from the Google Structured Data Testing Tool but it did return two detected schema types.  This is because the AMP plugin outputs the BlogPosting schema type and we output the Article schema type.  I don't know that this would cause problems in Google but it's something we should be aware of depending on how we move forward with this.

I'm bumping this to v3.3. so that we can discuss it first without holding up the main schema dev work in v3.2.

**Comment by arnaudbroes** [comment]
We'll strip away whatever the official AMP plugin is using and replace it with our own.
