### ISSUE TITLE
Schema.org - Add an option to add more company contacts

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#509]
This is reference to #72 where we are adding a new Phone Number field and Contact Type dropdown.

Google supports being able to specify multiple contact numbers each with a different contact type - https://developers.google.com/search/docs/data-types/corporate-contacts

For example, you can have a contact phone number for sales and a different contact phone number for support.  You can also specify different phone numbers such as toll-free, local or international.

We should add support for this.  We'll need to discuss the best UI for this.

**Comment by michaeltorbert** [comment]
This needs documentation.

**Comment by wpsmort** [comment]
The filter is already in place, we just need to test it and add documentation.

**Comment by wpsmort** [comment]
@arnaudbroes I have tested the filter for this and drafted documentation.  Please review the documentation here https://semperplugins.com/?post_type=documentation&p=5091.  If it's good then go ahead and publish it.

**Comment by arnaudbroes** [comment]
Looks good so I'm publishing the doc. and closing this issue.

**Comment by Garconis** [comment]
FYI: 

> Corporate Contact markup for Google knowledge panels is deprecated. We now automatically discover corporate contact information to include in Google knowledge panels.

https://developers.google.com/search/docs/data-types/corporate-contact

**Comment by michaeltorbert** [comment]
@Garconis I’ve created a new issue since this one is closed.
