### ISSUE TITLE
Bug with character counter

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#51]
The character counter is showing the number of characters for HTML codes in the Site Title rather than the number of characters for that character (i.e. &amp; shows as 5 characters when & is only one character)

The screenshot below shows an & in my Site Title:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14112890/9379a932-f59e-11e5-9c8c-064b83bd0af8.png)

The screenshot below shows the character counter thinks the site title is 33 characters instead of 28:

![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/14112909/a940b328-f59e-11e5-97cb-6d45c834b880.png)

**Comment by wpsmort** [comment]
See also this forum post where the user has double quotes in his Site Title which is throwing the character count off - https://wordpress.org/support/topic/error-calculating-title

**Comment by nishant981** [comment]
we are working on Bug with character counter.

**Comment by nishant981** [comment]
This issue is not because of html that is being counted in the length. This is because of All in one SEO Pack taking the length of the separator between the site title and page title. As you can see in the screenshot it is showing 3 even when there is no title as shown in screenshot. e.g. We have the title including website name and page title 'WN | Shop' , here length will be 9 including separator

![blank-title](https://cloud.githubusercontent.com/assets/13958896/14347765/670c16fc-fcd6-11e5-82ac-5c7b16d89a6e.png)
![title with extra length](https://cloud.githubusercontent.com/assets/13958896/14347775/6c46178a-fcd6-11e5-8880-25c8c7fab999.png)

**Comment by debabratakarfa** [comment]
Hi,
The 3 Count is coming for %page_title% | %blog_title% setting at All In One SEO Setting

1 for %page_title%, another 1 for | and last for %blog_title%

If set %page_title% or nothing to Page Title Format, you will find 0 count on Each page

Thanks
![edit page wordpress 3](https://cloud.githubusercontent.com/assets/2614495/14353932/e5f26f6c-fcf8-11e5-93d3-2ec43f60d183.png)
![general settings wordpress 1](https://cloud.githubusercontent.com/assets/2614495/14353933/e5f58a76-fcf8-11e5-9169-c8f12ace25b4.png)

**Comment by wpsmort** [comment]
@nishant981, that's not the bug.  The bug is with HTML characters included in the Site Title field in WordPress.  Here are the steps to replicate this bug:

1). Go to Settings > General in WordPress and set the Site Title as A & B
2). Create a page called Test and scroll down to the All in One SEO Pack meta box and set the Title as ABC
3). You should see that the character counter shows 15 characters when it should show 11 characters
4). View the source code of this page and you'll see that the Title tag is output as this - <title>ABC | A &amp; B</title>.  You'll see that the & symbol is output in the source code as the HTML code &amp; which is why the character count is 15 characters:

This is 15 characters:  ABC | A &amp; B
But this is 11 characters:  ABC | A & B

This is only a bug when someone uses special characters in their Site Title and they set a Title in All in One SEO Pack.

**Comment by nishant981** [comment]
Thanks for explaining, We will check it again and apply the fixes.

**Comment by nishant981** [comment]
I have uploaded my code to git, please check and let me know it is fine and I can follow the same steps further

**Comment by wpsmort** [comment]
I found that this bug was fixed in v2.4
