### ISSUE TITLE
run phpdocumentor

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#510]
https://www.phpdoc.org/docs/latest/welcome.html
https://tommcfarlin.com/install-phpdocumentor/
http://www.therobbiedshow.com/web-dev-notes/2012/2/8/how-to-use-phpdocumentor-on-wordpress-on-mac.html

**Comment by arnaudbroes** [comment]
We should do this ourself.
