### ISSUE TITLE
Remove settings for remove from admin bar and move menu to bottom

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#513]
It's just junking up the general options page. We can just replace these with either a constant for wp-config.php or else some sort of hook.

**Comment by wpsmort** [comment]
We can completely remove the Display Settings box as none of the three options are required.  

The SEO columns we add to the All Posts / All Pages screens can already be hidden using the Screen Options pull down on those screens.

**Comment by wpsmort** [comment]
We need to test whether removing the option from the class file whether this changes/removes the entry from the options field in the database.

**Comment by wpsmort** [comment]
@michaeltorbert I tested whether removing options from the main class file changes or removes anything from the array stored in wp_options.  I confirmed that it does not affect the array in the database.

Here's how the option stored for the Display Menu At The Top checkbox looks when the box is checked (default setting):

s:23:"aiosp_custom_menu_order";s:2:"on";

Here's how it looked after I unchecked it:

s:23:"aiosp_custom_menu_order";s:0:"";

Here's how it looked after I removed the setting from the main class file:

s:23:"aiosp_custom_menu_order";s:0:"";

I tested clicking the Update Options and deactivating and reactivating the plugin and this had no effect on the array.

**Comment by michaeltorbert** [comment]
@wpsmort Did you test by making actual changes to the options page then clicking Update Options? I'd recommend testing doing that with this option having been previously both checked and unchecked just to make certain.

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/remove-all-in-one-seo-pack-from-top-of-menu/

**Comment by michaeltorbert** [comment]
@wpsmort Currently we are not respecting previous settings (code burden)... should we?

**Comment by michaeltorbert** [comment]
This entire settings section has been removed, enabled by default, and replaced with filter hooks.

**Comment by wpsmort** [comment]
@michaeltorbert I think the only setting where we need to respect is the Display Menu At The Top option.  We know that generated a lot of complaints when we introduced it so if we don't respect the previous setting here we can expect a similar number of complaints.

**Comment by wpsmort** [comment]
This is tested and is good.
