### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#517]
I recently changed the URL for some of the documentation, and didn't realize it would break the link from AIOSEOP. :)

Reported via email:

"Your documentation link in plugin interface was broked... sent me to a 404 page. ;)
http://semperplugins.com/documentation/advanced-settings/#additional-post-headers"

**Comment by wpsmort** [comment]
I have fixed this and tested it.
