### ISSUE TITLE
Filter to remove GA tracking code from specific page

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#518]
Requested here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/how-to-remove-only-google-analytic-tracking-number-from-one-specific-page/#p5793

We could add a filter to remove GA code which users can use to remove from specific pages, posts, categories, etc.

**Comment by michaeltorbert** [comment]
@wpsmort Do we need something different than https://semperplugins.com/documentation/filter-all-in-one-seo-pack-google-analytics/ added in #371?

**Comment by wpsmort** [comment]
@michaeltorbert No, I don't believe we need anything different as the existing filter works just fine.

Note: To remove GA tracking code from a specific page use the filter here - https://semperplugins.com/documentation/filter-all-in-one-seo-pack-google-analytics/
