### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#524]
We may have mixed content for the mailchimp form. Let's see if this can be https
![img_0060](https://cloud.githubusercontent.com/assets/17364998/19024283/7813d1f4-88ce-11e6-848c-97c4503ba3ea.JPG)

**Comment by michaeltorbert** [comment]
The five support links in the right sidebar are http as well

**Comment by wpsmort** [comment]
I have confirmed the issue and fixed it by changing HTTP to HTTPS for all links.
