### ISSUE TITLE
Drag tool for Home Description text box makes character count text disappear behind Home Keywords

### ISSUE THREAD

**Issue by tonyzeoli** [semperfiwebdesign/all-in-one-seo-pack#525]
In Chrome for Mac, when you drag the Home Description text box down using the drag tool on the corner. All the character count text is hidden behind the Home Keywords below it.

See screenshots:

Normal: https://cloudup.com/ciFuHIPCmhU

After grab and drag: https://cloudup.com/cQR6BKOm-lG

**Comment by michaeltorbert** [comment]
I've confirmed this bug. It also happens on the edit post screen.

**Comment by wpsmort** [comment]
This has been fixed by increasing the max-height on that div.

**Comment by tonyzeoli** [comment]
Thanks! Glad I could report that one!
