### ISSUE TITLE
Remove the Capitalize Tag and Search Titles option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#530]
We should remove this option and replace it with a filter hook.  

We should respect the current setting.

**Comment by wpsmort** [comment]
We discussed this today and decided to remove all functionality related to capitalizing tag titles and search titles.

We'll be doing the same for capitalizing category titles (Issue #1006).

**Comment by michaeltorbert** [comment]
We'll also need to update the documentation. Code that can achieve much of the same thing:

`add_filter('aioseop_title','change_seo_title', 10, 1);

function change_seo_title( $title ){	
	static $charset = null;
				if ( $charset == null ) {
					$charset = get_bloginfo( 'charset' );
				}	
	if ( function_exists( 'mb_convert_case' ) ) {
					// Breaks for acronymns like SEO.
						$mytitle = mb_convert_case( $title, MB_CASE_TITLE, $charset );
					} else {
						$mytitle = ucwords( $title );
					}
	
	$title['title'] = $mytitle;
	return $title;
}`

**Comment by wpsmort** [comment]
This is tested and is good.
