### ISSUE TITLE
Remove the Capitalize Category Titles option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#531]
We should remove this option and replace it with a filter hook.  

We should respect the current setting.

**Comment by michaeltorbert** [comment]
To test this, we need to verify the expected behavior for a) both pre-existing installs and b) new installs. For a, we need to verify it works as intended whether it was previously checked or unchecked. For b, it's filter hook only.

**Comment by michaeltorbert** [comment]
API Filter Hook: https://semperplugins.com/documentation/capitalize-category-titles/

**Comment by wpsmort** [comment]
This is tested and works fine.  This was actually released in version 2.3.10 but didn't get marked as that milestone.
