### ISSUE TITLE
XML Sitemap module - Remove the Create Compressed Sitemap option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#534]
**_Because this has issues on nginx_**, this option can be completely removed.  There is no need for a filter.  This should be enabled for all.

**Comment by wpsmort** [comment]
See #945

**Comment by michaeltorbert** [comment]
When would someone not want this available? We just need to make sure they know it exists (in the new indicator).

Is it one or the other... is this checked, is there still a non-compressed version?

**Comment by wpsmort** [comment]
I don't believe there's a case where someone would not want this available.  It's something we should just do and then indicate that it's been done.

**Comment by michaeltorbert** [comment]
I think we should remove this option, and it should be "enabled" in that if someone views your ...com/sitemap.xml.gz they get the compressed version, and if they visit ...com/sitemap.xml they get the uncompressed version, which I think is basically how it works now.
We're having so many issues with compression, we should make the default sitemap the non-compressed version, but where they can provide Google with the compressed link if they prefer.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+compressed
https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+compression

**Comment by michaeltorbert** [comment]
What we discussed is that we'll remove the option and all checks for it, and leave the functionality such that either the compressed or uncompressed URL works. We'll just explicitly supply the uncompressed version though, and update the documentation to make it clear we offer both.

**Comment by michaeltorbert** [comment]
Considering we're moving in the direction of indexes, we should probably just remove all compression functionality since it doesn't really benefit us at all.
