### ISSUE TITLE
XML Sitemap module - Remove the Link From Virtual Robots.txt option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#535]
We should remove this option.  

~~We should respect the users setting.~~

It should be enabled by default and we should have a filter to disable this.

**Comment by michaeltorbert** [comment]
> Is there any reason we want this to be optional? If we remove it, we just need to make it clear it happens... or do we?

> I'm thinking something like:

> [green light] Added to virtual robots.txt
[green light] Some other thing we do
etc

**Comment by michaeltorbert** [comment]
Just adding a reminder that there should be some indication that this is happening.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1909

**Comment by arnaudbroes** [comment]
So here's what we need to happen:

1. Sitemap URL is added automatically to the virtual robots.txt file
2. XML Sitemap menu indicates whether or not the link is present in the virtual robots.txt file
3. Filter hook (can be a simple boolean) needs to be added so that users can disable this setting if they want to

**Comment by contactashish13** [comment]
Filter to use:

```
add_filter( 'aiosp_sitemap_link_to_robots', '__return_false' );
add_filter( 'aiosp_video_sitemap_link_to_robots', '__return_false' );
```

**Comment by michaeltorbert** [comment]
Playing devil's advocate, why exactly do we want to respect the old setting? This is something that helps, and can not hurt, SEO. If someone for some crazy reason doesn't want the link to their sitemap in the robots.txt, do we really want to code burden to allow the previous setting, for a setting that doesn't even exist anymore?

**Comment by wpsmort** [comment]
I don't see any reason to respect the old setting for this option.  There's no downside to including the sitemap URL in the robots.txt and therefore there's no damage if someone had this option disabled and we enable it by default for them.  

If someone had this option disabled then they would see the red X indicating that it's disabled which isn't helpful and is likely to create a support burden from users wondering why it's there.  

I'm therefore in favor of enabling this by default and not respecting the previous setting.
