### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#537]
Warnings from the PHP compatibility checker:

FILE: /app/public/wp-content/plugins/all-in-one-seo-pack/admin/display/postedit.php

FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.

FILE: /app/public/wp-content/plugins/all-in-one-seo-pack/inc/aiosp_calc_desc.php

FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.

FILE: /app/public/wp-content/plugins/all-in-one-seo-pack/inc/aiosp_calc_title.php

FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.

**Comment by wpsmort** [comment]
@michaeltorbert The PHP Compatibility Checker plugin throws warnings about these three empty files.  This may just be FYI.

**Comment by michaeltorbert** [comment]
This should be fixed now.

**Comment by wpsmort** [comment]
This has been tested and is good.
