### ISSUE TITLE
XML Sitemap module - Detecting static sitemap.xml files

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#539]
When we look to see if a static sitemap.xml file exists on the server, we are checking for a file with content in it.  This means we miss any file that is empty.  

To prove this, upload a sitemap.xml file that is empty and then visit the XML Sitemap module.  You won't get a warning message stating that there's a conflicting file.

Then upload a sitemap.xml file with a single character in it and visit the XML Sitemap module.  You will now get the warning message.

**Comment by michaeltorbert** [comment]
We can now detect and delete empty sitemap files with naming conflicts. This still requires clicking the button to delete or rename them.

**Comment by wpsmort** [comment]
This is tested and works.
