### ISSUE TITLE
Remove message/button to build sitemap - at least for dynamic

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#542]
Do we actually need this message? It seems confusing. I'm not sure if it's needed for static, but I'm 99% certain it isn't at all useful for dynamic. Should we remove it for at least dynamic? Is it needed for static?

> "Please review your settings below and click Update Sitemap to build your sitemap"

**Comment by wpsmort** [comment]
I agree that we should remove the message and link for dynamic sitemap.

**Comment by michaeltorbert** [comment]
What about for static? Can we confirm whether clicking to "build" the sitemap is needed?

**Comment by michaeltorbert** [comment]
I've removed it for both dynamic and static. In testing we need to make sure it absolutely isn't needed for either.

**Comment by wpsmort** [comment]
I have tested this with both dynamic and static and with sitemap indexes and everything is working fine.
