### ISSUE TITLE
Remove Run Shortcodes In Autogenerated Descriptions option

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#545]
We should remove this option.  Standard behavior should always be to run any shortcodes when auto generating the title tag or meta description.

We could have a filter if someone wants to change this behavior.

**Comment by michaeltorbert** [comment]
Closing as we definitely won't be doing this. See #787

Shortcodes are too unpredictable to run them by default. This should be considered advanced functionality and should remain an option that's disabled by default.
