### ISSUE TITLE
Social Meta module - Remove Run Shortcodes options

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#546]
We should remove both the Run Shortcodes in Title option and Run Shortcodes in Description option.  Standard behavior should always be to run any shortcodes when auto generating the OG title or OG description.

We could have a filter if someone wants to change this behavior.

**Comment by michaeltorbert** [comment]
Closing as we definitely won't be doing this. See #787

Shortcodes are too unpredictable to run them by default. This should be considered advanced functionality and should remain an option that's disabled by default.
