### ISSUE TITLE
Never ping search engines if site is set to not public

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#549]

**Comment by michaeltorbert** [comment]
This is finished... I'm not sure if it's something that can really be tested better than what I've already done.

**Comment by wpsmort** [comment]
I can't see a way other than checking the information window in the XML Sitemap module.  That displays the Successfully notified Google and Bing message when Search Engine Visibility is turned off and doesn't display the message when it's turned on.
