### ISSUE TITLE
Display autogenerated OG title and description as placeholders

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#55]
Display the auto generated OG title and description in the Title and Description fields of the Social Settings tab in the AIOSEOP meta box of the Edit Post screen just like we do with SEO title and description.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14112680/ad9cd9de-f59d-11e5-959a-3af078daf222.png)

This is how the auto generated title and description appears on the Main Setting tab:

![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/14112718/e1c5deae-f59d-11e5-9767-11ffef7330b4.png)

**Comment by michaeltorbert** [comment]
@wpsmort I've merged this into the development branch. Once you're 100% satisfied it works in the development branch, go ahead and close the ticket.

**Comment by wpsmort** [comment]
I found one issue with this. 

We have two Autogenerate Descriptions settings in AIOSEOP.  One is for auto generating SEO meta descriptions and can be found under Advanced Settings.  The other is for auto generating OG description and can be found in the Social Meta module under General Settings.

Unchecking and checking these boxes does not have the required results with regards to the placeholder text in the OG description field on the Edit Post screen.  

I think we should just remove the option for Autogenerate OG Descriptions in the Social Meta module and just let the other setting for Autogenerate Descriptions control this.

**Comment by wpsmort** [comment]
I tested the latest development branch and this works fine.
