### ISSUE TITLE
Review when we should ping search engines

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#550]
Currently, we ping search engines only when someone clicks "update sitemap" (options). We should discuss other times to ping them.

*More specifically, whenever do_sitemaps() runs.

**Comment by wpsmort** [comment]
@michaeltorbert Here's what Google recommends:

For a single XML sitemap: update it at least once a day (if your site changes regularly) and ping Google after you update it.

For a set of XML sitemaps: maximize the number of URLs in each XML sitemap. The limit is 50,000 URLs or a maximum size of 10MB uncompressed, whichever is reached first. Ping Google for each updated XML sitemap (or once for the sitemap index, if that's used) every time it is updated. A common mistake is to put only a handful of URLs into each XML sitemap file, which usually makes it harder for Google to download all of these XML sitemaps in a reasonable time.

https://webmasters.googleblog.com/2014/10/best-practices-for-xml-sitemaps-rssatom.html

**Comment by michaeltorbert** [comment]
Duplicate of #359
