### ISSUE TITLE
log sitemap ping failures and memory usage to WP debug log

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#557]

**Comment by michaeltorbert** [comment]
Related to #556

**Comment by wpsmort** [comment]
@michaeltorbert I tested this and saw ping failures but no memory usage info in the debug log.  In addition to seeing ping failures, I also saw ping success messages.  Do we want to log those?

**Comment by michaeltorbert** [comment]
@wpsmort What are the success messages you're seeing? 
Are some of those old messages from when you were logging the wp_error object?

As far as I know, memory usage only ever got logged with static.

**Comment by wpsmort** [comment]
I tested again and this is now working as expected.  Only ping failures are logged and memory usage is logged when you use static sitemaps.
