### ISSUE TITLE
XML Sitemap module - Add support for RSS/Atom updates

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#561]
We should look into adding support for Google's RSS/Atom feed notification updates described here - https://webmasters.googleblog.com/2014/10/best-practices-for-xml-sitemaps-rssatom.html

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1432

I've tried to follow what https://wordpress.org/plugins/www-xml-sitemap-generator-org/ does for this - the RSS feeds are provided in 2 ways: one is the full sitemap in RSS form and another is the 20 latest posts where 20 can be changed by a filter. The full sitemap is called 

```
<filename>.rss
```
and the sitemap that contains the 20 latest posts is called
```
<filename>latest.rss
```
