### ISSUE TITLE
Remove Show Column Labels for Post Types

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#562]
This is redundant, since they can be hidden using the Screen Options pull down on those screens.

**Comment by michaeltorbert** [comment]
Originated in #513

**Comment by michaeltorbert** [comment]
When testing, we need to make sure columns show up for all post types (except obviously media as that no longer applies with the modern WP UI), including custom post types.
At this point, all post types and custom post types will default to having SEO columns.

**Comment by wpsmort** [comment]
This is tested and works fine.
