### ISSUE TITLE
Add filter hook to remove admin bar

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#567]
related to #513

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/disable-seo-in-admin-bar/

**Comment by wpsmort** [comment]
@michaeltorbert I tested this on my Pressmatic site running the latest dev branch and Twenty Sixteen and it did not work.  The SEO menu item was still on the Admin Bar.

**Comment by wpsmort** [comment]
Same with this filter - https://semperplugins.com/documentation/remove-all-in-one-seo-pack-from-top-of-menu/

**Comment by wpsmort** [comment]
Ignore these comments, this is working fine, it was a problem with where I was SVN'd to.
