### ISSUE TITLE
Welcome screen won't go away on some hosts on upgrading

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#571]
Specifically WPEngine's wp-admin caching

**Comment by michaeltorbert** [comment]
This commit may or may not help with WPEngine's caching. Unfortunately I can't reliably reproduce it.

**Comment by wpsmort** [comment]
This has been marked for 2.3.11 so we can review if we've had any more issues reported.

**Comment by michaeltorbert** [comment]
According to this it happens with siteground too. I may open a shared hosting account. https://wordpress.org/support/topic/all-my-websites-dashboard-is-now-stuck-on-welcome-to-all-in-one-seo-pack-2-3-10/#post-8278720

**Comment by michaeltorbert** [comment]
We should take a look at plugins like cloudways migrator, buddypress, etc to see if they do anything different.

**Comment by michaeltorbert** [comment]
BTW Siteground claims they have no extra wp-admin caching, but I haven't confirmed this personally.

**Comment by michaeltorbert** [comment]
Ok so this is ready for testing on our WPE site. Unfortunately we probably can't conclusively test anything.

**Comment by dougalcampbell** [comment]
I had a idea to test in one last attempt to replicate. I'm wondering if this problem could be triggered when upgrading from a pre-welcome-screen version of the plugin. 

Suggested test procedure for WP Engine:

1. Deactivate and delete AIOSEOP plugin
2. Use WPE settings to flush all caches
3. Manually delete database entries using phpMyAdmin: `options/aioseop_options`, and `usermeta/aioseop_seen_about_page`
4. Upload the version 2.3.8 version of the plugin .zip file, and activate
5. Save options.
6. Upload the version 2.3.10.1 version of the plugin .zip file
7. See if we get the redirect loop

/cc @wpsmort

**Comment by dougalcampbell** [comment]
If that *does* trigger the loop, then try again, but instead of version 2.3.10.1 for the upgrade, use a .zip of the `welcome-redirect` branch. See if those changes fixed the loop.

**Comment by wpsmort** [comment]
@dougalcampbell I tested this twice but could not replicate the redirect loop.

**Comment by michaeltorbert** [comment]
Ok these changes are merged into the dev branch.

We *think we may have fixed it, so welcome redirects are now turned back on for updates to the new version.
@wpsmort Test and make sure you don't find any problems with installing this version from scratch or from updating to this version.

**Comment by wpsmort** [comment]
@michaeltorbert I tested installing the dev branch from scratch and got this error:

PHP Parse error:  syntax error, unexpected 'to' (T_STRING), expecting ',' or ';' in all-in-one-seo-pack-development/admin/display/general-metaboxes.php on line 42

**Comment by wpsmort** [comment]
I have tested this and it works fine when installing from scratch (the Welcome screen shows once) and when updating from current live version (the Welcome screen does not show).
