### ISSUE TITLE
Remove prefix from HTML tag when AMP detected

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#577]
Originally reported here - https://wordpress.org/support/topic/problem-with-amp-plugin/#post-8277493

As of 2.3.10.1 we detect the presence of the AMP plugin and remove our Schema.org markup from the HTML tag.  This was because the AMP Validator returned errors for that markup.

The AMP Validator (https://validator.ampproject.org/) also returns an error because of the prefix="og: http://ogp.me/ns#" line we add to the HTML tag.

We should remove the code below from the HTML tag when the AMP plugin is detected:

prefix="og: http://ogp.me/ns#"

**Comment by wpsmort** [comment]
This prefix is part of Open Graph although I can see no issues with social sharing when I remove the prefix.  The prefix is still specified in documentation from Facebook and Google - 

https://developers.facebook.com/docs/reference/opengraph/object-type/website/
https://developers.google.com/web/fundamentals/discovery-and-monetization/social-discovery/

**Comment by wpsmort** [comment]
We are able to detect an AMP page by using a query_var and created some code users can put in their theme that will remove this.  You can find this code here - https://wordpress.org/support/topic/problem-with-amp-plugin/#post-8278051

**Comment by michaeltorbert** [comment]
amp_post_template_head and amp_query_var are probably better

**Comment by wpsmort** [comment]
This is tested and is good.
