### ISSUE TITLE
XML Sitemap module - Add exception for sitemap-news.xml

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#583]
First reported here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/sitemap-xml-versus-sitemap-news-xml/

If you have a plugin installed that is generating a news XML sitemap with the filename sitemap-news.xml then AIOSEOP outputs the conflict warning prompting you to rename or delete that file.  

We need to ignore the filename sitemap-news.xml.

**Comment by michaeltorbert** [comment]
@wpsmort The problem with this is that our code looks for [sitemapname]*.xml... so with default settings, anything named sitemapSOMETHING.xml will get flagged.

The only ways I can think of to fix this are to
a) figure out every single filename we may be creating (which could be a lot with indexes) and don't flag anything else, or
b) whitelist sitemap-news.xml (until we make our own), or
c) make a whitelist filter hook

**Comment by wpsmort** [comment]
@michaeltorbert I think the best option right now is to whitelist sitemap-news.xml and sitemap_news.xml, and to have a whitelist filter hook.  

Google doesn't explicitly say but from what I've read, they prefer the news sitemap to be called either sitemap-news.xml or sitemap_news.xml.  I can check, but I think most XML News Sitemap plugins create a sitemap with either of these two names.  The filter hook can be for any non-standard names.

**Comment by wpsmort** [comment]
@michaeltorbert In testing I found the following inconsistent behavior: 

- we automatically remove the sitemap_news.xml file if it's empty - Correct behavior
- we do not remove the sitemap-news.xml file if it's empty - Incorrect behavior
- we prompt to rename/delete the sitemap_news.xml file - Incorrect behavior
- we ignore the sitemap-news.xml file - Correct behavior

**Comment by michaeltorbert** [comment]
The sitemap_news one was a typo which is why it's still prompting. That's also why it's being deleted if it's empty, since that isn't something we care about for these two files as they currently don't conflict with anything we're doing.

**Comment by wpsmort** [comment]
This is now working correctly and we are ignoring both filenames.
