### ISSUE TITLE
Display Menu At The Top needs to respect previous setting

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#585]
In version 2.3.10 we removed the option for Display Menu At The Top.  Issue #513 refers.

When we did this we did not respect the users setting for this option which resulted in negative feedback from our users.

We need to respect the users setting stored in the database for this option.

**Comment by michaeltorbert** [comment]
In testing, we need to verify the behavior upgrading from old installs with it checked, old installs with it unchecked, and that the default behavior (shows up) exists for new installs. We also need to verify that the API filter hook overrides it all.

**Comment by wpsmort** [comment]
I have tested all variations and they are all good.

**Comment by wpsmort** [comment]
This is tested and is good.
