### ISSUE TITLE
Remove SEO columns from All Posts screens for all user

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#587]
In version 2.3.10 we removed the option for Show Column Labels for Custom Post Types.  Issue #562 refers.

User feedback was that if you run multiple sites, a network of sites, or have a lot of admin users on a site, you want to be able to disable these columns for all.  Under the new solution of using Screen Options in WordPress, you'd have to log into every site with every account to disable the columns for each post type.  The burden on the admin is too high.

The SEO columns show for Administrators, Editors, Authors and Contributors.

We have a filter but it's not easy to use for all, especially if you want to disable columns for only certain post types.

We need a better solution. This issue is for discussing options and determining the best way forward for all users.

**Comment by michaeltorbert** [comment]
My vote is to put the option back until we figure out something better.
This is related to #590

**Comment by EkoJR** [comment]
Could be missing user role `aiosp_manage_options`.
