### ISSUE TITLE
Filter to remove SEO dashboard widget for all users

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#588]
We added an SEO News widget in v2.3.10.  Issue #497 refers.

User feedback was that if you run multiple sites, a network of sites, or have a lot of admin users on a site, you want to be able to disable this widget for all. Currently you'd have to use Screen Options in WordPress to do this which means you'd have to log into every site with every admin account to disable the widget. The burden on the admin is too high.

The widget only shows for Administrators.

At the minimum we need a filter to remove the widget for all admins.  

We could consider having an option for AIOSEOP Pro users to remove this.

**Comment by michaeltorbert** [comment]
This was reported here: https://wordpress.org/support/topic/seo-news/#post-8282623
I agree that it was an oversight on our part to inadvertently burden people who manage many client sites and want to provide them with a scaled-down interface, each site with possibly with many administrators.

At a minimum, we could create a one-line filter hook to copy/paste into a theme's functions.php (or a custom plugin).
The other alternative is to provide a checkbox This could be a pro-only feature as one of the benefits of Pro is to remove all ads and much of the extraneous branding for pro-use. (Keeping in mind that the primary purpose of this widget isn't commercial promotion.) 
The downside of the latter is that we add more clutter to the options pages, which is what we're actively trying to reduce (and admittedly failed at in this release) by removing, not adding, options. However, one thought is that pro users of the Pro version _want_ the additional options.

**Comment by PointandStare** [comment]
Personally I would prefer it as a PRO option.
I totally agree that you're not looking to push people to buy the plugin, but, as technically these are ads then a checkbox on the PRO version would get my vote.

**Comment by michaeltorbert** [comment]
@PointandStare Agreed.

**Comment by michaeltorbert** [comment]
https://github.com/semperfiwebdesign/aioseop-pro/issues/119

**Comment by michaeltorbert** [comment]
aioseo_show_seo_news is the filter to remove, just return false.

I'm working on the checkbox in the Pro repository.

**Comment by michaeltorbert** [comment]
This checkbox has been added to Pro for the next release https://github.com/semperfiwebdesign/aioseop-pro/issues/119

**Comment by michaeltorbert** [comment]
Related to https://github.com/semperfiwebdesign/aioseop-pro/issues/120 where we add the remove from admin bar and demote menu settings back to display settings in Pro.

**Comment by wpsmort** [comment]
This filter is tested and is good.  I have added documentation here - https://semperplugins.com/documentation/remove-seo-news-dashboard-widget/?lang=en
