### ISSUE TITLE
Multiple admin notices on install

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#589]
I noticed this today when testing on a brand new site.  When you activate the plugin you get an admin notice popup, and then when you click on All in One SEO you get two more admin notice popups.  See screenshot.

<img width="1269" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/19321485/32dc95f0-9083-11e6-8467-a0d363d6cc0d.png">

**Comment by michaeltorbert** [comment]
While we need to fix this, it isn't new. We'll see if we can get to it for 2.3.11 but I'm marking it as low priority.

**Comment by michaeltorbert** [comment]
Admin pointers should never show up now. We can leave it like this until we figure out something better.
For testing, we need to make sure that on a new install on a fresh install of core they don't show up, and that they don't show up on updates.

**Comment by wpsmort** [comment]
This is tested and confirmed for new installs and updates.
