### ISSUE TITLE
i18n - Localize JavaScript strings

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#59]
Localize JavaScript https://codex.wordpress.org/I18n_for_WordPress_Developers

**Comment by arnaudbroes** [comment]
I'll review this and see if there are any strings that can be localized.

**Comment by arnaudbroes** [comment]
I confirmed that we have no strings in our JavaScript that appear in the UI, so there's nothing we need to localize.
