### ISSUE TITLE
Remove blank sitemap automatically

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#592]
We need to figure out when to do this... either on update, when you attempt to visit the sitemap.xml file (may not be possible?), or when you visit the sitemap options page.
See when the code looking for conflicts runs. Possibly we could just look for blanks ones in the construct of the sitemap class.

**Comment by michaeltorbert** [comment]
Blank sitemap files are removed automatically when browsing to the sitemap options page.

**Comment by michaeltorbert** [comment]
And now when updating.

**Comment by michaeltorbert** [comment]
When testing, make sure nothing isn't removed that shouldn't be, and that everything that should be removed is, both on the update and when visiting the sitemap options page.

**Comment by wpsmort** [comment]
This is tested and is good.
