### ISSUE TITLE
XML Sitemap - sitemap.xml not always reachable if site is non-www

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#595]
Where other URLs redirect to non-www, the sitemap URL does not. 
This was reported here https://wordpress.org/support/topic/sitemap-taking-too-much-time/#post-8292098 and confirmed on semperplugins.com.
Is this an issue with how the individual site is doing a redirect or are we doing something wrong?
The sitemap doesn't redirect to non-www, and has a blank page (though the sitemap is viewable in the source)

**Comment by michaeltorbert** [comment]
I'm punting this for now, as it's not a huge issue since people should be giving google consistent URLs (ideally non-www).
This may have something to do with the method sites use to redirect www to non-www in htaccess or whatever?

**Comment by michaeltorbert** [comment]
related to or dupe of #133

**Comment by arnaudbroes** [comment]
@michaeltorbert I'm guessing this can be closed? Feel free to reopen this if I'm incorrect.
