### ISSUE TITLE
Add SEO columns back to Media Library

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#598]
We removed the SEO columns from the Media Library in v2.3.10.2 but have had requests to add them back in.  
<img width="1336" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/19388636/a7905244-91ee-11e6-86d4-00e8c01eaf20.png">

**Comment by michaeltorbert** [comment]
@wpsmort We never removed these. I'd created #564 but we never actually took them out.
Remember, they aren't enabled in General Settings by default and never were. 

Where is this request?

**Comment by wpsmort** [comment]
This was reported in the comments of this post by George - https://semperplugins.com/new-release-for-all-in-one-seo-pack-version-2-3-10/

However, I have tested with both free and Pro starting at v2.x.9.2 and updating to each release and cannot replicate this.
