### ISSUE TITLE
XML Sitemap - Cannot exclude blog from sitemap

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#602]
First reported by Mary Chizhova by email on 10/18/2016.

Cannot exclude the blog page from the XML sitemap using any of the methods.

**Comment by michaeltorbert** [comment]
This is the case with home the page as well.

**Comment by michaeltorbert** [comment]
Ok the page for posts can now be removed by adding the slug or ID to the settings page, or else checking the box of the SEO section of the page.

Static homepages and post pages are handled differently by WordPress, which is the reason for this behavior.
I doubt anyone would want to remove the homepage from the sitemap, but if so we can add an issue for that.

**Comment by michaeltorbert** [comment]
@wpsmort For testing, we need to watch for any errors/notices when saving the Sitemap options or viewing the sitemap in all combinations of things... 

static page for posts/homepage, 
posts page = homepage,
remove posts page by id/slug,....

**Comment by wpsmort** [comment]
This is tested and is good.
