### ISSUE TITLE
Add a filter to disable All in One SEO Pack

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#605]
Requested by email from Bruno Cantuaria dated 17th Oct 2016.

Add a filter to disable All in One SEO Pack completely so this can be used with the conditional tag is_page_template()

**Comment by michaeltorbert** [comment]
Documentation https://semperplugins.com/documentation/filter-to-disable-all-in-one-seo-pack/

**Comment by wpsmort** [comment]
This is tested and works.

**Comment by l4ci** [comment]
Sorry to open this again, but the filter doesnt seem to work for me.

```
function disable_aioseop(){
            return true;
}
add_filter( 'aiosp_disable', 'disable_aioseop', 10, 1 );
```
in my page specific template`page-test.php` file. Even before the `wp_head()` is called. No matter if the function returns true or false - all in one seo is still enabled.
