### ISSUE TITLE
Icons for quick edit are missing on Semper Plugins

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#610]
Icons are missing.  Check for a plugin conflict.  See screenshot:

<img width="1588" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/19612862/0cdba2b6-97b7-11e6-8eef-0e69971b6f15.png">

**Comment by arnaudbroes** [comment]
@michaeltorbert Could you send me a screenshot with the list of plugins that are installed on SemperPlugins? It's a compatibility issue.

**Comment by wpsmort** [comment]
@arnaudbroes Here is the list of active plugins with their version numbers:

Advanced Custom Fields 4.4.11
Advanced Custom Fields: Repeater Field 1.1.1
Advanced Custom Fields: Row Field 1.0.1
Akismet 3.2
All In One SEO Pack Pro 2.4.10.2.1
AMP 0.4.2
BackupBuddy 7.2.0.8
Cart66 Professional 1.5.8.1
Create Users .1
Edit Flow 0.8.2
Google Analytics Dashboard for WP 4.9.3.2
Gravity Forms 2.0.7.6
Gravity Forms Authorize.Net Add-On 2.3
Gravity Forms User Registration Add-On 3.4.5
Members 1.1.2
OptinMonster API 1.1.5.7
Redirection 2.4.5
Responsive Social Sharing Buttons 0.1
SFWD Store 1.1.2
Simple:Press 5.7.2
The Events Calendar 4.3.1.1
VaultPress 1.8.5
WP-Mail-SMTP 0.9.5
WP Affiliate Platform 6.0.1.1
WPML Multilingual CMS 3.5.3.1
WPML String Translation 2.4.2.1
WPML Translation Management 2.2.4.1

**Comment by michaeltorbert** [comment]
@wpsmort Can you just troubleshoot deactivate/activate on the test server to narrow it down?

**Comment by arnaudbroes** [comment]
@wpsmort @michaeltorbert: I checked it on the test site. Edit Flow is causing the issue.

**Comment by wpsmort** [comment]
@michaeltorbert I did some further testing and confirmed that Edit Flow appears to change a class that is added by JavaScript to one of our divs as follows:

class="aioseop_mpc_admin_meta_options editing" changes to class="aioseop_mpc_admin_meta_options hidden" when Edit Flow is active

Edit Flow seems to to be replacing the class of "editing" which is added via JS when you click the paperclip icon to "hidden".  This removes CSS assigned to the editing class which results in the icons to save and cancel being pushed below the next table row.  

I tested this on a new site with versions of AIOSEOP going back 18 months and versions of Edit Flow going back 3 years.  The results are the same each time.  

Screenshot with Edit Flow inactive:
![screen-capture](https://cloud.githubusercontent.com/assets/17548525/19904750/5924a942-a04a-11e6-8937-c949c2f741f1.png)

Screenshot with Edit Flow active:
![screen-capture-1](https://cloud.githubusercontent.com/assets/17548525/19904755/5ace8f74-a04a-11e6-8895-a9635b0dfe06.png)

**Comment by wpsmort** [comment]
This is tested and is good.
