### ISSUE TITLE
Upgrade url should be https

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#613]
http://semperplugins.com/upgrade_plugins.php should change to https

**Comment by michaeltorbert** [comment]
For testing, we need to make sure that all PRO update functionality works.

**Comment by michaeltorbert** [comment]
Related to #296

**Comment by wpsmort** [comment]
@michaeltorbert The following links on the Plugins page need to be changed to HTTPS:

Upgrade to Pro link
Documentation link
Support Forum link
Michael Torbert link

**Comment by wpsmort** [comment]
This is tested and is good.
