### ISSUE TITLE
Change URLs in aioseop_sitemap.php from http to https

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#617]

**Comment by michaeltorbert** [comment]
Changed the following URLs:

-various semperplugins.com/documentation links
-inline documentation link to the wp.org codex
-changed the google and bing sitemap ping links to https (need to verify these still work)

**Comment by michaeltorbert** [comment]
Related to #296

**Comment by wpsmort** [comment]
This is tested and is good.
