### ISSUE TITLE
Switch http to https in aioseop_class.php

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#625]

**Comment by michaeltorbert** [comment]
Changed several semperplugins documentation links and pro upgrade links. This should also solve #296

**Comment by wpsmort** [comment]
@michaeltorbert The link to the Google blog post in the help text for Canonical URLs is broken.  My link currently goes to this - http://aioseop.dev/'https://googlewebmastercentral.blogspot.com/2009/02/specify-your-canonical.html/'

**Comment by michaeltorbert** [comment]
@wpsmort Interestingly, this was already broken.

**Comment by michaeltorbert** [comment]
@wpsmort It's because we don't need to be escaping the ' with a slash... should we just take out that link altogether from the contextual help and add it to the docs on semperplugins?

**Comment by wpsmort** [comment]
@michaeltorbert I'm good with removing the link.  We already have the link in our documentation but I've made it more prominent.

**Comment by wpsmort** [comment]
This is tested and is good.
