### ISSUE TITLE
Update google tool link 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#627]
In aioseop_functions.php, on line 566 we have a URL for http://www.google.com/webmasters/tools/richsnippets

When you visit that URL, it redirects to https://search.google.com/structured-data/testing-tool/u/0/

Should we change this URL to the new one or is that a different tool?

**Comment by wpsmort** [comment]
The Google testing tool for Open Graph meta has gone away.  I have therefore removed the reference to Google and this URL.

**Comment by michaeltorbert** [comment]
@wpsmort Is the tool at the URL it redirects to at all helpful with this? https://search.google.com/structured-data/testing-tool/u/0/

**Comment by wpsmort** [comment]
@michaeltorbert No, I just checked and it does not check Open Graph meta

**Comment by wpsmort** [comment]
I have tested this by installing other plugins that add OG meta, run the Scan for duplicates tool and it works and outputs the correct message and links.
