### ISSUE TITLE
Remove title attribute for menus

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#628]
For many years, we've given the option to add a title attribute in menus.
We should discuss whether to remove it.

**Comment by michaeltorbert** [comment]
Argument for: 
-giving contextual information to users visually

Arguments against:
-ZERO SEO value
-useless for touch devices
-not used by most screenreaders (accessibility)
-can cause other accessibility issues
-advised against by http://www.w3.org/TR/WCAG20-TECHS/H33.html

silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/
highrankings.com/useless-seo-tactics-303
ezinearticles.com/?Do-Alt-and-Title-Attributes-Help-With-SEO?&id=432783
mrwweb.com/the-title-attribute-and-why-its-almost-useless/
searchenginejournal.com/how-to-use-link-title-attribute-correctly/

**Comment by wpsmort** [comment]
@michaeltorbert I am perfectly fine with removing this option.  We have two options on the Edit Page screen - Title Attribute and Menu Label.  I believe both can be removed.

**Comment by michaeltorbert** [comment]
All traces of the menu label and title attribute should be gone from the code. 
(Any database entries are untouched though.)

**Comment by wpsmort** [comment]
This is tested and is good.
