### ISSUE TITLE
Put back Schema and OG Prefix on non-AMP pages

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#629]
In issues #575 and #577 we removed Schema.org and Open Graph markup on the opening HTML tag if we detect the AMP plugin is activated.  

We need to put this back and only remove it on AMP posts.

The markup is as follows: 

```
<html lang="en-US"
	itemscope 
	itemtype="http://schema.org/Article" 
	prefix="og: http://ogp.me/ns#"  class="no-js">
```

**Comment by michaeltorbert** [comment]
Since the AMP plugin is just wiping all language_attributes, we can just add them back as normal without checking for the AMP plugin.

https://github.com/Automattic/amp-wp/pull/531
https://github.com/Automattic/amp-wp/pull/537

**Comment by wpsmort** [comment]
This is tested and is good.
