### ISSUE TITLE
Remove donation request area

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#631]
These strings, besides the 'upgrade to pro' link, aren't included in the translation:

General Settings:
![image](https://cloud.githubusercontent.com/assets/18156697/19772038/368ffb7c-9c65-11e6-87bc-ecc58a07c0ac.png)

**(You were thinking about deleting this in the future)**

**Comment by michaeltorbert** [comment]
Good catch @arnaudbroes 
I'm updating the title of this issue to just remove the donation request area. People can better support development by joining the community of All in One SEO Pack Pro users.

**Comment by michaeltorbert** [comment]
BTW this includes removing it in the plugin action links

**Comment by arnaudbroes** [comment]
@michaeltorbert Did you also delete the "I like this plugin and have donated' checkbox on the General Settings tab?

**Comment by michaeltorbert** [comment]
@arnaudbroes Yep. 👍

**Comment by wpsmort** [comment]
This is tested and is good.
