### ISSUE TITLE
Add information about benefits of Pro to side metabox

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#634]
related to #631 

IE, if they have WooCommerce installed, have a message about increased support for WooCommerce

**Comment by michaeltorbert** [comment]
This could probably use some sprucing up, but I've put in the basic info.

*If they have WooCommerce installed, it mentions that. Otherwise, it just says "e-commerce".

**Comment by wpsmort** [comment]
@michaeltorbert I got the following PHP Deprecated Notice which I believe is related to this code:

PHP Deprecated:  Non-static method aiosp_metaboxes::pro_meta_content() should not be called statically in /all-in-one-seo-pack/admin/display/general-metaboxes.php on line 54

**Comment by michaeltorbert** [comment]
@wpsmort Oops. That's fixed now.

Let's review the new metabox and see how it can be improved... Wording, styling, etc

**Comment by wpsmort** [comment]
This is good and we've agreed the wording and appearance is fine for now.
