### ISSUE TITLE
Possible URL issue with settings link on welcome page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#646]
Reported here. https://wordpress.org/support/topic/my-experience-with-aioseo/

**Comment by michaeltorbert** [comment]
I'm closing this as we've been unable to reproduce the problem.

**Comment by wpsmort** [comment]
I have tested this and cannot replicate the problem.  The URL is always correct, regardless of where WP is installed or the directory name for AIOSEOP.
