### ISSUE TITLE
quickedit.js gets cached through updates

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#649]
In 2.3.11 specifically, when we changed the class name for the quickedit buttons to avoid the naming conflict with the Edit Flow plugin, the js file gets cached by the browser. Versioning the call will bust this cache on update for the future.

**Comment by michaeltorbert** [comment]
Interestingly, we already had this for js, but not for css. I've opened an issue for css here #716

**Comment by michaeltorbert** [comment]
For testing all the js/css issues, just make sure that everything involving CSS/JS seems to show up and work.

**Comment by wpsmort** [comment]
I have tested updating from v2.3.10 to the latest dev version and found no issues with cached JS.  I tested in Chrome and FF.
