### ISSUE TITLE
Missing Chinese strings for aioseo

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#651]
@dawatorbert @michaeltorbert 

Hi Dawa
If you could take a look at the waiting, untranslated and fuzzy strings for the Chinese locale of aioseo, that would be great. About 5 minutes of your time, no rush though.

https://translate.wordpress.org/locale/zh-cn/default/wp-plugins/all-in-one-seo-pack

**Comment by dawatorbert** [comment]
done. @arnaudbroes 


https://translate.wordpress.org/locale/zh-cn/default/wp-plugins/all-in-one-seo-pack

**Comment by arnaudbroes** [comment]
@dawatorbert 
Great, thank you!
