### ISSUE TITLE
Blocked bad bots are logged regardless of setting

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#654]
They're logged either way, the log just doesn't appear on the settings page unless the option is checked.
We should a) not log if the option isn't selected and ~~b) switch to logging in the error log instead of db and c) remove the log section from the db~~ (b and c are covered in #660)

...We should probably make issues for each of these.

**Comment by wpsmort** [comment]
@michaeltorbert I tested this and when the option to Track Blocked Bots is checked and I visit the site using a blocked User Agent, I don't see a log entry in the DB or on the screen for that blocked bot.

**Comment by michaeltorbert** [comment]
@wpsmort  In this test were you actually blocked? (You'll see a white screen.) You need to be logged out in order to be blocked by HTTP.

**Comment by wpsmort** [comment]
@michaeltorbert Yes, I was testing in an Incognito window and got a 403 Forbidden screen each time I checked with a blocked user agent.

**Comment by michaeltorbert** [comment]
If you're getting a 403 that's from htaccess. HTTP does 503.
If you have htaccess turned on as well, that catches you first and you never get blocked. We don't have any method of logging htaccess blocking.

**Comment by michaeltorbert** [comment]
This has been tested and verified by both me and @wpsmort
