### ISSUE TITLE
Remove all htaccess functionality from Bad Bots module

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#657]
We're removing this as there's too much potential for bugs either in our code or else in what users type, and it's technically duplicate functionality since we have the .htaccess editor.

related to #653

**Comment by michaeltorbert** [comment]
For testing, make sure that 
a) there's no htaccess functionality in the bad bots module... nothing should get added or removed at all (anyone who previously had an entry in .htaccess will still have it) and that 
b) we didn't break the http blocking

**Comment by wpsmort** [comment]
@michaeltorbert: I have tested and confirmed that the setting for Block using htaccess is gone from the UI but remains in the options table.

However, on a new install with latest dev branch and all four boxes checked in the Bad Bot Blocker, I am not blocked from the site when using a User Agent that is in the User Agent Blocklist.

To reproduce this, use latest dev branch with a new install of WordPress, check all four boxes in the Bad Bot Blocker and then browse to the site with a user agent that it in the blocklist. You should see the site which is incorrect. Correct behavior is to get a 503 error.

**Comment by michaeltorbert** [comment]
@wpsmort Make sure you're logged out.

**Comment by wpsmort** [comment]
When logged out, this works correctly.
