### ISSUE TITLE
Filter blank line crashes in bots/referrers

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#658]
Related to #439

**Comment by michaeltorbert** [comment]
Even if a blank line is added and is stored in the database, it should get filtered out on the fly when checking the list against the current referrer or agent.

**Comment by michaeltorbert** [comment]
During testing, we still want to make sure that bad agents and referrers get filtered out AND that any other agent/referrer not on the list does not (you should be able to modify your agent and referrer via chrome and/or chrome plugins).

**Comment by wpsmort** [comment]
@michaeltorbert This works fine if the blank line is at the end of the User Agent Blocklist or the Referer Blocklist but it if the blank line is in the middle of either list then I still get a 403 Forbidden error.

To replicate, add a blank line in middle of either blocklist, click Update Options and then browse to another page in WP Admin.

**Comment by michaeltorbert** [comment]
During testing, we still want to make sure that bad agents and referrers get filtered out AND that any other agent/referrer not on the list does not (you should be able to modify your agent and referrer via chrome and/or chrome plugins).

**Comment by wpsmort** [comment]
This is tested and is good.  Known bad agents get blocked and good bots do not.
