### ISSUE TITLE
New plugin description of 15 words

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#663]
As seen here:

![screenshot_1](https://cloud.githubusercontent.com/assets/18156697/20576867/007b7122-b1c0-11e6-9c71-7bcb512371b4.png)

**EDIT: we need to further reduce the description length because the new Plugin Directory uses a shorter description (as Steve reported earlier).

**Comment by michaeltorbert** [comment]
@wpsmort  can you take a look at the new wording and let us know what you think?

**Comment by arnaudbroes** [comment]
New wording:
One of the most downloaded WordPress plugins (over 30 million downloads since 2007). Use All in One SEO Pack to optimize your site for Search Engines.

**Comment by wpsmort** [comment]
@michaeltorbert: The new wording looks fine.  However, it looks like we may need to reduce the number of characters even more when WordPress rolls out the new plugin directory - https://wordpress.org/plugins-wp/browse/popular/.  The excerpt in the new directory looks like this: 

One of the most downloaded WordPress plugins (over 30 million downloads since 2007). Use All…

**Comment by arnaudbroes** [comment]
I talked to Dominik Schilling and Pascal Casier about this because no one seems to know what the exact new limit is for the description that shows up in the plugin snippet. I'm guessing it's 100 characters though. 

Here are some suggestions that fit this limit:

- All in One SEO Pack is a powerful plugin that helps you optimize on-page SEO for your site.
- Optimize on-page SEO and rank your site higher in the search results by using All in One SEO Pack. 
- Use All in One SEO Pack as one of the most popular plugins to optimize your site's SEO.
- All in One SEO Pack optimizes your site’s SEO and helps you rank higher in search engines.
- All in One SEO Pack is one of the most downloaded plugins that helps you optimize your site’s SEO.

**Comment by michaeltorbert** [comment]
I think it should be something that sets us apart... something like "The original SEO plugin, downloaded over 30,000,000 times since 2007"

**Comment by arnaudbroes** [comment]
@michaeltorbert 
I just spoke to someone from the Meta team, the limit is set at 15 words (and not characters). 
Your description seems fine, but like this?
"The original SEO plugin for WordPress, downloaded over 30.000.000 times since 2007."
Imo it looks a little bit better if we use all the space.

**Comment by michaeltorbert** [comment]
@arnaudbroes That's fine, but make sure to use commas in the number.

**Comment by arnaudbroes** [comment]
Has been added to Development for new release.
