### ISSUE TITLE
Double pipe

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#664]
We've had a couple reports of titles with reportedly default settings resulting in a double pipe.
I haven't been able to reproduce this so far. We may need to log into someone's site who is reporting the issue and take a look at their environment and rule out a plugin/theme conflict.

**Comment by arnaudbroes** [comment]
Perhaps related to #1408.

**Comment by arnaudbroes** [comment]
I've fixed this a long time ago.
