### ISSUE TITLE
See if we can turn off Twitter plugin meta 

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#666]
Currently, there's a conflict with the official Twitter plugin in that it outputs duplicate meta.
https://wordpress.org/plugins/twitter/

Reported here: https://twitter.com/_ConstantFlux/status/787315208641474560

**Comment by michaeltorbert** [comment]
We should be removing the Twitter plugin's meta if our Social Module is active.

**Comment by wpsmort** [comment]
This is tested and I have confirmed that the meta from the Twitter plugin is removed correctly.
