### ISSUE TITLE
SEO News feed still attempts to access it even when disabled via screen options

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#670]
~~When the feed is unavailable, this causes the dashboard to load slowly.~~ moved this comment to #670

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1433. I've tested #676 and I'm unable to reproduce it.
