### ISSUE TITLE
In social settings for a post, attached image is still selected even with a custom image

### ISSUE THREAD

**Issue by dawatorbert** [semperfiwebdesign/all-in-one-seo-pack#673]
This makes it confusing to essentially have two "selected" images
![screen shot 2016-12-06 at 7 36 53 pm](https://cloud.githubusercontent.com/assets/18234064/20950087/7500da5c-bbeb-11e6-93ac-84a646436cbe.png)

**Comment by wpsmort** [comment]
We should remove radial selection when a custom image has been added.

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1587
