### ISSUE TITLE
Consider what to do if global $post doesn't exist / isn't set

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#678]
In aioseop_class.php on line 1624, we have 

global $post;
$post_id = $post->ID;

Reported here, https://wordpress.org/support/topic/trying-to-get-property-of-non-object-35, there could be conditions in certain edge cases where there's no $post
We could consider checking if $post has anything, and if not, maybe bail out of the function gracefully?

For dev and testing, we'd need a theme that displays the posts without there being global $post.

**Comment by wpsmort** [comment]
Dupe of #1616.  I'm copying the comment above to the other issue.
