### ISSUE TITLE
Custom Post Type Settings - Remove options from Custom Post Type Settings section 

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#68]
Completely remove the following options from the Custom Post Type Settings meta box:

SEO for Custom Post Type Settings
Enable Advanced Options
Custom Titles

These should be enabled by default for all.  

Completely remove the Posts and Pages checkboxes from the SEO on only these post types option.    Again, this should be enabled by default for all.

No filters are required here.

**Comment by nishant981** [comment]
we have done with above task.
![4](https://cloud.githubusercontent.com/assets/13958896/14354921/c3e05728-fcfc-11e5-89ed-889e463f9321.png)

**Comment by michaeltorbert** [comment]
@nishant981 Submit the code as a pull request to the nishant branch.

**Comment by wpsmort** [comment]
Updates to this issue:

1). Let's get rid of the Custom Post Type Settings section completely.
2). Let's check for only custom post types that are public (i.e. 'public' => true).
3). Let's add a filter so that users can add other custom post types if they want.

**Comment by wpsmort** [comment]
See also #226

**Comment by wpsmort** [comment]
When we get rid of this we need to ensure it does not affect the NOINDEX for taxonomies under Noindex Settings.  Currently this field only appears when you select Enable Advanced Options.
