### ISSUE TITLE
Bad Bot Blocker - Strip blank line at beginning of blocklist

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#680]
This is a follow on from #658 where we removed blank spaces and lines from the middle or end of the User Agent and Referrer Blocklists.  

We need to do the same for blank lines at the beginning of either Blocklist as these trigger a 403 Forbidden error.

**Comment by michaeltorbert** [comment]
It looks as though all textarea boxes in the plugin's settings get the first line stripped out. This is probably in the module_class somewhere.

**Comment by wpsmort** [comment]
@stanislavsa I tested pull request #840 and I can still replicate the 503 HTTP error by placing three spaces and three blank lines in the User Agent Blocklist field before the first line of text.

**Comment by stanislavsa** [comment]
@wpsmort yeah, I see. The problem is that three spaces is not an empty string. Therefore I added a 'trim' function.

**Comment by michaeltorbert** [comment]
@stanislavsa Are you still working on this or is it ready for a PR?

**Comment by stanislavsa** [comment]
It is ready for PR

**Comment by wpsmort** [comment]
This is tested and is good.  This is ready for the code review.
