### ISSUE TITLE
Social Meta Module - Prepopulate the Associated Name field with the Site Title

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#686]
Under All in One SEO > Social Meta > Social Profile Links > Associated Name we should prepopulate this with a placeholder that uses the Site Title (We do this for the Set Preferred Site Name under General Settings).

**Comment by michaeltorbert** [comment]
@wpsmort How would this look exactly? Can you post a mockup?

**Comment by michaeltorbert** [comment]
On a related topic: https://github.com/semperfiwebdesign/semperpluginstore/issues/286

**Comment by wpsmort** [comment]
@michaeltorbert: Here is a mockup

<img width="1438" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/21998305/02509b46-dc02-11e6-91e9-90be4a7c8172.png">

We actually do this already for the Preferred Site Name under All in One SEO > Google Settings.  If you check the box next to Set Preferred Site Name you'll see a text field with placeholder text that shows the Site Name.

<img width="586" alt="screen-capture-1" src="https://cloud.githubusercontent.com/assets/17548525/21998329/284b48c8-dc02-11e6-83d9-1326ccfe65b6.png">

**Comment by wpsmort** [comment]
This should be done at the same time as #73

**Comment by wpsmort** [comment]
This field is being removed and replaced with a new field for Organization Name under #72
