### ISSUE TITLE
XML Sitemap - Unsafe attempt to load URL when loading XSL file

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#687]
Reported by Marco Tiggelaar via email today.

When using WPML with different TLDs and HTTPS, the XSL doesn't load because of this error:

Unsafe attempt to load URL https://www.example.com/sitemap.xsl from frame with URL https://www.example.nl/sitemap.xml. Domains, protocols and ports must match.

**Comment by wpsmort** [comment]
See also #337

**Comment by michaeltorbert** [comment]
Just as an update to here and #337, it's working on our stevemortiboy.com and .co.uk on cloudways... https://wpml.org/errata/home_url-not-filtered-correctly-breaking-plugins-like-wp-seo-when-using-languages-in-domains-nginx-only/ blames nginx, but it was broken on the hostmonster install... we're moving it back to hostmonster for testing

**Comment by wpsmort** [comment]
After moving back to Hostmonster it was also working fine with v2.4.11.1.1 of AIOSEOP Pro and v3.6.2 of WPML.  Now testing older versions of both plugins to see if this got fixed somewhere.

**Comment by wpsmort** [comment]
I've tested with AIOSEOP v2.3.6 which is when we introduced the new dynamic XSL feature and with WPML v3.4.0 which is from around June 2016 when we released v2.3.6 and I cannot replicate the problem.

**Comment by wpsmort** [comment]
I found that this problem existed with WPML versions prior to v3.2 which was released on June 12th, 2015.  The problem was fixed in v3.2.

**Comment by michaeltorbert** [comment]
@wpsmort Try it in nginx

**Comment by wpsmort** [comment]
I have this set up with nginx and without an SSL certificate and I have confirmed that we do get the error with this configuration on nginx.

I'm running AIOSEOP Pro v 2.4.11.1.1 and WPML v3.6.2 which are the latest versions.

**Comment by wpsmort** [comment]
@amostajo I tested this and here are my results:

This works for the options in WPML for Different languages in directories and for A different domain per language. However, it breaks if you select the option for Language name added as a parameter.

Neither the default language sitemap show or the other languages. This is the URL for the XSL file for the default language:

http://stevemortiboy.comsitemap.xsl

This is the URL for the XSL file for the French language:

http://stevemortiboy.com/?lang=frsitemap.xsl

**Comment by amostajo** [comment]
@wpsmort I am still trying to figure it out where are you getting those XSL urls from.

After looking at the code and researching on the topic, I have now a more clear knowledge of what XSL is for, these are just for styling the XML sitemap file.

By looking at the XML sitemaps generated on stevemortiboy (using WPML), both are referencing to the right XSL file, look at their source codes:
* [stevemortiboy.com](view-source:http://stevemortiboy.com/sitemap.xml)
* [stevemortiboy.co.uk](view-source:http://stevemortiboy.co.uk/sitemap.xml)

I did found an attribute that was missing on the XSL template though, this solves issues when rendering the XSL template on Chrome, I will push that fix.

My localhost also points the right XSL url.

**Comment by wpsmort** [comment]
@amostajo Yes, the XSL is only for styling.  Typically when it doesn't load you see a empty screen when you view the XML Sitemap, but if you look at the source code of the page you'll see all the XML code is there, it's just not being displayed to humans because the XSL didn't load.

With regards to this specific problem - In WPML under Languages > Language URL Format there are three possible settings:

1). Different languages in directories 
English: http://stevemortiboy.com/
French - http://stevemortiboy.com/fr/

2). A different domain per language
English - http://stevemortiboy.com
French - http://stevemortiboy.co.uk

3). Language name added as a parameter 
French - http://stevemortiboy.com?lang=fr

Its this last one that doesn't work with our XML Sitemap.  If you go to http://stevemortiboy.com/sitemap.xml/?lang=fr then you'll see that the screen is blank and when you look at the source code view-source:http://stevemortiboy.com/sitemap.xml/?lang=fr you'll see the XSL link is returning a 404 error.

Hopefully this will help.

**Comment by amostajo** [comment]
@wpsmort Yup it did. Know I get what you are saying, thank you very much.

Sitemap should be pointing to: http://stevemortiboy.com/sitemap.xml?lang=fr

**Comment by amostajo** [comment]
@wpsmort I have tested it using multiple configurations and seems to working fine. Please review.

**Comment by wpsmort** [comment]
This is tested with all three language options in WPML and confirmed that all three now work.  This needs a code review.

**Comment by wpsmort** [comment]
This is tested in 2.3.12.3 development and is confirmed to be fixed.

**Comment by wpsmort** [comment]
I found the same error when viewing the robots.txt file generated by WordPress.  Our XML Sitemap URL is being displayed incorrectly as:

Sitemap: http://stevemortiboy.com/?lang=frsitemap.xml

Instead it should be displayed as:

Sitemap: http://stevemortiboy.com/sitemap.xml?lang=fr

**Comment by wpsmort** [comment]
This is tested and is now all working correctly.
