### ISSUE TITLE
Call to undefined function remove_submenu_page()

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#688]
Reported by Julius Bull via contact form.

There is recurring fault when deactivating the plugin:

Fatal error: Call to undefined function remove_submenu_page() in /wp-content/plugins/all-in-one-seo-pack/admin/display/welcome.php on line 42

**Comment by michaeltorbert** [comment]
I've made a change that *may fix this, but I'm not certain as I was unable to reproduce it to begin with.
During testing, try to reproduce it. If it a) can't be reproduced or b) can be reproduced and has been fixed, it should be closed.
If c) it can be reproduced and hasn't been fixed, we should leave it open.

**Comment by wpsmort** [comment]
I have tested and am unable to reproduce this.
