### ISSUE TITLE
redirect issue with WPML String Translation

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#689]
Reported here:
https://wordpress.org/support/topic/cant-navigate-admin-site-after-install-of-all-in-one-seo/

When using WPML String Translation + the "nice hotel" theme, the welcome page redirect won't go away.

**Comment by michaeltorbert** [comment]
It doesn't seem to have anything to do with siteground as best I can tell, since we can reproduce it from a backup of the user's site elsewhere.

**Comment by michaeltorbert** [comment]
My guess is that it has to do with caching. I can reproduce it on our cloudways backup, but not from a backup locally using pressmatic/local... We may want to try different methods of checking before doing the redirect.

**Comment by michaeltorbert** [comment]
This may be related to #571

**Comment by michaeltorbert** [comment]
We should see if this is fixed by our recent changes as well.

**Comment by wpsmort** [comment]
@michaeltorbert I tested this on a clone of the site we have on Cloudways where we can replicate the issue.  When I updated the plugin from v2.3.11.1 which is on his site to this branch by uploading the new plugin via FTP, the welcome screen was displayed once and went away after I dismissed it.

However, if I then deactivated and reactivated the plugin or installed it again after wiping our options from the database, the welcome screen did not appear.  So far I've not been able to do anything to make the welcome screen appear.

**Comment by michaeltorbert** [comment]
@wpsmort  Remember the welcome screen code looks in the database for both the last active version entry as well as the seen about page entry. It won't show up if either is the current version of AIOSEOP

**Comment by wpsmort** [comment]
@michaeltorbert Understood, that's why I wiped anything from the wp_options table related to AIOSEOP to do a fresh install but upon activation there was no welcome screen.  However, when I installed this branch on a fresh new install the welcome screen did appear.

I believe that as I've been able to replicate the original bug and then test the fix on a clone of that site and it worked that this issue can be closed.

**Comment by michaeltorbert** [comment]
@wpsmort Sorry, aioseop_seen_about_page is user meta, not an option.

**Comment by wpsmort** [comment]
I carried out further testing on our Cloudways site where we could replicate the problem.  I installed the branch with the fix and switched between the old version of AIOSEOP where the redirect was happening and the new fixed branch and the problem went away as soon as I switched to the fixed version of AIOSEOP.
