### ISSUE TITLE
Title Settings - Remove the Rewrite Titles setting under Title Settings

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#69]
Completely remove the Rewrite Titles setting under Title Settings and make sure this option is set to Enabled for all users.  

See screenshot.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14112352/678b4cce-f59c-11e5-9c20-ed34ccce4d2b.png)

**Comment by arnaudbroes** [comment]
#2244 might be relevant.

**Comment by michaeltorbert** [comment]
When removing this issue, we need to look and see what functionality this will affect. According to #1391 it doesn't actually enable/disable the title rewriting, but we should see what it does actually do.

**Comment by michaeltorbert** [comment]
Looking at the code, this doesn't really do anything useful, except other options conditionally depend on it. 
It's used in:
aioseop_class.php
aioseop_performance.php
class-aioseop-helper.php

**Comment by michaeltorbert** [comment]
I've merged the code in, but @arnaudbroes will make another PR to address the grunt issues.
