### ISSUE TITLE
duplicate title tags for buddypress profile and member pages

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#693]
Reported here:
https://wordpress.org/support/topic/disable-for-buddypress/

This needs to be verified.

**Comment by arnaudbroes** [comment]
I'll check it in a couple of hours.

**Comment by arnaudbroes** [comment]
I tested this on a fresh install but didn't see the error showing up in the source code.

Extended profile page:
![image](https://cloud.githubusercontent.com/assets/18156697/21596375/9dbe6ec8-d13a-11e6-8463-00f5ecc835eb.png)

Member page:
![image](https://cloud.githubusercontent.com/assets/18156697/21596385/b0ec096a-d13a-11e6-872c-17bc520af7c9.png)

@wpsmort 
Michael asked if you could verify these findings once more and see if you are able to reproduce this.

**Comment by wpsmort** [comment]
I have verified that on a test site with just BuddyPress and AIOSEOP active, the title tag is output correctly on BuddyPress profile pages.
