### ISSUE TITLE
XML Sitemap - Last changed date for pages containing static content

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#695]
Requested by Brian Williams by email today.

I have pages and posts that dynamically change every time someone accesses the page. These display homes for sale through and IDX plugin (not an iFrame). The publish date and time never change. So, the XML sitemap thinks that the data is static and indicates that the page seldom changes frequency. I suspect that this tells crawlers not to check the page very often. Can this be overcome in a way that the crawlers will look at the page often and see that the data changes?

See also #262

**Comment by michaeltorbert** [comment]
My reply to him :

_You can change the frequency in your All in One SEO Pack -> XML SiteMap settings under “Frequencies”.


If you really really want the date in the sitemap to change... WordPress stores the date a post/page was last modified in a database column called post_modified (different from the post published date). Another thing to do in this case if you really want the date to change may be to have code to update the post_modified field in the WordPress database when the IDX plugin modifies a post._

**Comment by michaeltorbert** [comment]
What we may want to do is just put some filters in the code so people can change things however they like.

**Comment by michaeltorbert** [comment]
Also, we should make sure “last change” in the code is the date updated, not published…. make sure saving again changes this date in the sitemap
