### ISSUE TITLE
XML Sitemap - Add a filter to exclude password protected content

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#696]
Requested here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/sitemap-exclude-password-protected-posts-and-pages/#p6097

Add a filter to enable users to exclude all password protected content (using the WordPress password protect feature) from the XML Sitemap.

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/password-protected-posts-in-xml-sitemaps/
https://semperplugins.com/documentation/remove-password-protected-posts-from-xml-sitemap/

**Comment by wpsmort** [comment]
This is tested and is good.
