### ISSUE TITLE
XML Sitemap - Update the static XML sitemap when posts are published, modified or deleted

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#70]
Add an option to update static XML sitemap when posts are published, modified or deleted.

Currently the static XML sitemap updates via a cron job every 24 hours. Users expect that the static XML sitemap will include a new post when it’s published.  Users also expect that the XML sitemap would be updated when a page or post is updated or deleted.  

We need to add an option to enable automatic updates for the static XML sitemap.  This checkbox would only be displayed if the option for Dynamically Generate Sitemap is unchecked, as shown in the screenshot below.

If this new option is checked, the static XML sitemap will be updated whenever a post/page is published, modified or deleted.  The cron job could still be used as a backup.

![picture1](https://cloud.githubusercontent.com/assets/17548525/14110433/6830768e-f594-11e5-9bcd-4d4ddf777ab5.png)

**Comment by michaeltorbert** [comment]
@wpsmort Are we in agreement that there's no new option here?

**Comment by wpsmort** [comment]
@michaeltorbert Yes, this is a change to the code only

**Comment by michaeltorbert** [comment]
@wpsmort This is in the xsl branch

**Comment by wpsmort** [comment]
This is tested and works.
