### ISSUE TITLE
Create filter hook to noindex password protected pages

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#707]

**Comment by michaeltorbert** [comment]
https://semperplugins.com/documentation/noindex-password-protected-posts/

For testing, obviously it's important to make sure we're ONLY noindexing the desired posts (password-protected ones in this case) when using this filter hook. Make absolutely certain that nothing else inadvertently gets noindexed. 

The logic used in the code checks for three things:
1) is_singular() - checks that it's a single post (any post type, including attachments)
2) whether the global post object has an non-empty post_password
3) if the aiosp_noindex_password_posts filter is true (defaults to false)

**Comment by wpsmort** [comment]
This is tested and is good.
