### ISSUE TITLE
undefined error - social name

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#708]
If something has been entered into the social profile links, but not the social name, social name gives an undefined error.

**Comment by wpsmort** [comment]
@michaeltorbert I cannot replicate the original undefined error when I enter something in the Social Profile Links field but leave the Associated Name field empty.  I tested with v2.3.10 and the current live version of AIOSEOP.

**Comment by michaeltorbert** [comment]
@wpsmort The error is on the front-end when trying to display the social links/name, not the settings page.

**Comment by wpsmort** [comment]
This error is being displayed on the front end for my site with the current live version and I have confirmed that there is not error on the front end for me site running the latest dev branch.
