### ISSUE TITLE
Add version to css and js to bust cache

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#716]

**Comment by michaeltorbert** [comment]
CSS
aioseop_module.css
aioseop_module-rtl.css
aiosp_admin.css
welcome.css

JS
aioseop_module.js
quickedit_functions.js
welcome.js

**Comment by michaeltorbert** [comment]
For testing all the js/css issues, just make sure that everything involving CSS/JS seems to show up and work.

**Comment by wpsmort** [comment]
I have tested all modules and screens and found no caching issues, CSS or JS issues.
