### ISSUE TITLE
Add new Schema.org markup for company information

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#72]
Google now supports additional Schema.org markup for company information.  This includes company logo, contact type, phone number, etc.  This information is used for Knowledge Graph cards.

Their documentation can be found at https://developers.google.com/structured-data/customize/contact-points and https://developers.google.com/structured-data/customize/logos

We currently output some of this JSON-LD markup when someone enters information in the Social Profile Links section of the Social Meta module. Here's how our current markup looks:

```
<script type="application/ld+json">
{ "@context" : "http://schema.org",
  "@type" : "Organization",
  "name" : "Steve Mortiboy Associated Name",
  "url" : "http://aioseop.dev",
  "sameAs" : [
    "https://www.facebook.com/smortiboy",
    "https://twitter.com/wpsmort"
  ] 
}
</script>
```

We need to add fields for the following:
- Logo image URL (or select/upload image)
- Phone number with country code
- Contact type dropdown – The values for this dropdown are listed here https://developers.google.com/search/docs/data-types/corporate-contacts

These new fields can be added in the Social Profile Links section after the current fields. A mockup of how this will look with the new fields is shown below.

We then need to output this information in our JSON-LD markup in accordance with the example markup provided in this issue.

This is in reference to the forum post here https://wordpress.org/support/topic/feature-request-416

<img width="788" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/18602731/a1709574-7c39-11e6-989f-36b03d8d3ace.png">

**Comment by wpsmort** [comment]
See also #73

**Comment by dcfairwi** [comment]
Looking forward to this being implemented

**Comment by dcfairwi** [comment]
Any recent updates or planned implementation date?

**Comment by wpsmort** [comment]
Requested again by R. Thompson (email)

**Comment by wpsmort** [comment]
Requested again by David Young (email)

**Comment by arnaudbroes** [comment]
@wpsmort is this still needed now that the markup for Google Knowledge Graphs has been deprecated?

**Comment by wpsmort** [comment]
@arnaudbroes I've opened a new issue regarding removing just the markup for social profiles (#2694).
