### ISSUE TITLE
Social Meta Module - Twitter image on homepage is incorrect

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#720]
When you have your home page set to display latest posts, the twitter:image for the homepage is displaying the Twitter Image set on the latest post, not the Open Graph image set under Social Meta > Home Page Settings > Home Image.

This code was only added in v2.3.9 from Aug 2016.

This bug was identified while test issue #684

**Comment by michaeltorbert** [comment]
@wpsmort Which commit added this code? I don't see it.

**Comment by wpsmort** [comment]
@michaeltorbert I've confirmed that I can replicate this issue and I've found that it was this commit that broke this - https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/483a7f95356346bb03da2878133bdd1c81986284

To replicate this, set your homepage to display latest posts, view the source code for your homepage and check the twitter:image, then go to All in One SEO > Social Meta > Home Page Settings and change the Home Image.  The OG:Image and metaprop image should change but the twitter:image does not.

**Comment by wpsmort** [comment]
Michael still couldn't replicate this so I tried to replicate it and show him but I could not replicate this either.

**Comment by michaeltorbert** [comment]
Closing this for now, as nobody can seem to reproduce it.
