### ISSUE TITLE
Add upgrade to pro link in menu

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#724]

**Comment by michaeltorbert** [comment]
<img width="159" alt="screen shot 2017-03-02 at 11 06 44 am" src="https://cloud.githubusercontent.com/assets/17364998/23515497/5943afb6-ff38-11e6-8c35-95a5f4e69d63.png">

**Comment by wpsmort** [comment]
@michaeltorbert Is there any way to make the link open in a new tab?

**Comment by michaeltorbert** [comment]
@wpsmort Yes but only with javascript. Create a new issue for that.

**Comment by wpsmort** [comment]
I've opened a new issue for the open in new tab - #773
