### ISSUE TITLE
"Uploaded to this post" missing from media page dropdown

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#726]
Reported here: https://wordpress.org/support/topic/update-problem-41/
http://imgur.com/BlVC2ht

We need to verify that this problem exists. So far I've been unable to reproduce it.

**Comment by michaeltorbert** [comment]
I've been able to verify the issue on the user's site, and am creating a local installation for further investigation.

**Comment by michaeltorbert** [comment]
The theme is what actually breaks it and can be used for testing the fix.
What we needed to do was change wp_enqueue_media() to the admin_enqueue_scripts action instead of admin_print_scripts. We also need to look at our other scripts and styles and do the same with some or all of them.

**Comment by wpsmort** [comment]
I was able to reproduce this on a new site and was able to verify that it is fixed in the development branch.  

Do we want the milestone as 2.3.12.1 or 2.3.11.3?
