### ISSUE TITLE
Add support for SEOPressor to our SEO Data Importer

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#729]
Requested by Jock Brocas by email on Jan 25, 2017.

Add support for importing SEO data from SEOPressor.

**Comment by wpsmort** [comment]
@michaeltorbert: I tested this and found one issue.  The SEO meta is imported across but when you look at the SEO meta fields in SEOPressor they are empty.  If you then deactivate AIOSEOP then there's no meta in SEOPressor.  Its behaving like we're moving their meta to our plugin rather than copying it and leaving it in place.

**Comment by michaeltorbert** [comment]
@wpsmort Isn't that the behavior that's always been in the SEO Data Importer/Migrator?

**Comment by wpsmort** [comment]
This is standard behavior. We do migrate SEO meta data from the source plugin to our plugin.  Therefore, this is tested and is working fine.
