### ISSUE TITLE
Add OG meta to AMP pages

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#733]
As per the AMP specs (https://www.ampproject.org/docs/reference/spec) "It is encouraged that AMP HTML documents are annotated with standardized metadata: Open Graph Protocol, Twitter Cards, etc."

**Comment by khaledMohammed000** [comment]
Great !

**Comment by michaeltorbert** [comment]
@khaledMohammed000 Awesome! You're welcome to contribute code here as well if you like.

**Comment by michaeltorbert** [comment]
@khaledMohammed000 https://github.com/semperfiwebdesign/all-in-one-seo-pack/search?q=amp&type=Issues&utf8=%E2%9C%93 are the currently open issues that mention AMP.
For integration with your plugin, it would be best if you use AIOSEOP filters, actions, functions. Any that are missing can be added.

**Comment by wpsmort** [comment]
This is tested and is good.
