### ISSUE TITLE
Update of JM Twitter Cards causes tab issues with All in One SEO Pack

### ISSUE THREAD

**Issue by chrisaldrich** [semperfiwebdesign/all-in-one-seo-pack#736]
With the recent update to JM Twitter Cards to stable on WordPress.org 5 hours ago (v7.7) a change somewhere in the code is causing problems in the admin interface with the All in One SEO Pack.

In particular one can't switch between the two tabs in AIOSP interface "Main Settings" and "Social Settings". Only the details on the "Main Settings" tab can be seen and attempting to switch to "Social Settings" only changes the url (which then ends with <code>&action=edit#aioseop_opengraph_settings</code>. Attempting to switch back does nothing but change the URL to <code>&action=edit#aiosp</code>.

Disabling JM Twitter Cards and refreshing the post admin interface allows AIOSP to work properly and reenabling JMTC causes it to break again.

Thoughts?  

Also cross-posting to JMTC which may be the source of the problem.

**Comment by wpsmort** [comment]
I've tested this on a clean install of WordPress v4.7.2 with AIOSEOP v2.3.11.3 and JM Twitter Cards v7.7 and the default Twenty Sixteen theme.  I cannot replicate this problem on the Edit Post screen or Edit Page screen.  I can switch between the tabs and there are no browser console errors.
