### ISSUE TITLE
Social Meta Module - Auto generated OG description is incorrect when post excerpt is present

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#739]
Reported here - https://wordpress.org/support/topic/open-graph-description-bug/

When you have Autogenerate OG Description enabled and you set an excerpt on a post, we correctly display the excerpt in the Description field of the Edit Post screen but we incorrectly display the content as the og:description and twitter:description in the source code.

**Comment by wpsmort** [comment]
I tested all the way back to version 2.1 where we introduced the Social Meta module and found this bug has always been present.

**Comment by michaeltorbert** [comment]
@wpsmort  Are we supposed to do the excerpt instead of the content? The help text says "Check this and your Open Graph descriptions will be auto-generated from your content" whereas the Docs say it will make it from the excerpt.
What should be the behavior? check social desc, then seo desc, then excerpt, then content (and update the help text)?

The problem is that if we change it, people could be expecting the content, not the excerpt to show up for social... which again, is what the help text says will happen.

**Comment by wpsmort** [comment]
@michaeltorbert: So the help text is wrong and should have been written like the help text for Autogenerate Descriptions (under General Settings > Advanced Settings).  The documentation for this setting is correct, it says we create the auto generated OG description from the Excerpt or the content if you don't have an excerpt.  

The correct behavior is supposed to match autogenerated SEO descriptions where we use the excerpt then fall back to the content if there's no excerpt. As you say, changing this could now affect peoples sites especially WooCommerce stores where the Excerpt in the Product Short Description.

Ideally, I'd like to see us remove this option completely and just have the one Autogenerate Descriptions option which controls all descriptions.

**Comment by wpsmort** [comment]
We discussed this at length today and agreed on a way forward for this that is best for all new users as well as ensuring backwards compatibility.  

We decided to rename the current Autogenerate OG descriptions option to Use content for autogenerated OG descriptions.  See #762

We decided to then rename that meta box from General Settings to Advanced Settings and move it to the bottom of the screen.  See #761

**Comment by michaeltorbert** [comment]
In summary:

-All sites, regardless of settings, should now autogenerate descriptions. (make sure this is made clear in the changelog)
-Autogenerated descriptions should pull from manually entered > excerpt > post content

-This option should ONLY have the functionality of using the post content if it exists, then excerpt

**Comment by michaeltorbert** [comment]
The commit comment is incomplete. In addition to defaulting to excerpt then content, this commit also autogenerates OG descriptions for everyone.

**Comment by michaeltorbert** [comment]
For testing, we need to test BOTH home page and posts (and other types). All we're concerned about here is whether anything new is broken. If it was broken before, just make a new issue for it.

We need to test every combination of these:
-option is checked and unchecked
-homepage, posts, and other post types
-empty and not empty excerpt and content

**Comment by wpsmort** [comment]
This is tested and is good.  I found one bug and opened a new issue #782

**Comment by artevodesign** [comment]
Hi there! I notice a variation of the same bug. **The meta description doesn't exists while the og:description and twitter:description is autogenerated although the autogen checkbox is off**. I'm using the free v2.5 on WP v4.9.5.

![tpp1](https://user-images.githubusercontent.com/31805784/38838594-93b06a50-41df-11e8-977c-b7cf1f36500e.png)
![tpp2](https://user-images.githubusercontent.com/31805784/38838595-93c9f25e-41df-11e8-8c26-66ac6a9c6ead.png)

Thank you!

**Comment by artevodesign** [comment]
**PS:** The above issue is manifested on a single page. All the other pages are not affected. None of them have any specific settings.

**Comment by arnaudbroes** [comment]
@artevodesign thank you for reporting this, I created a new issue here and we'll look into it - #1656

**Comment by artevodesign** [comment]
My pleasure!

Let me know if more details on the subject are needed.

Best regards!

**Comment by artevodesign** [comment]
Hi again!

I have found another website, also recently done, with the same problem 
(see attachments with settings and plugins installed).

Thank you!

**Comment by michaeltorbert** [comment]
I'm locking this issue, as it's been resolved. All conversation about another issue should be in the appropriate place.
