### ISSUE TITLE
Bad Bot Blocker Module - Deactivating the Bad Bot Blocker module should remove the .htaccess entry.

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#74]
When deactivating the Bad Bot Blocker module in Feature Manager, any code we add to the .htaccess file should be removed.

**Comment by michaeltorbert** [comment]
@wpsmort I think we fixed this in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/77 for 2.3.3 but it needs to be verified

**Comment by michaeltorbert** [comment]
I'm closing this as we're removing the htaccess functionality.
