### ISSUE TITLE
An element's ID must be unique in the DOM

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#743]
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_html_02

![Uploading Screen Shot 2017-02-03 at 9.57.28 AM.png…]()

**Comment by arnaudbroes** [comment]
Too general of an issue. I'll make sure we have semantic HTML when we redo the UI.
