### ISSUE TITLE
XML Sitemap - Add a filter to exclude taxonomy terms by ID

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#746]
Requested by Hakan Mitts by email on 2/9/2017

User has requested a way to exclude only certain categories by ID from the XML sitemap.  This includes being able to exclude certain tax terms by ID.  For example, exclude only certain product categories.

**Comment by michaeltorbert** [comment]
My recommendation is that this is a filter hook.

**Comment by contactashish13** [comment]
@michaeltorbert @wpsmort I believe this is related to https://github.com/semperfiwebdesign/aioseop-pro/issues/240 and is resolved by https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1419

**Comment by wpsmort** [comment]
@contactashish13 Yes, this is related to https://github.com/semperfiwebdesign/aioseop-pro/issues/240 and I've updated that issue with my comments.  Can you confirm whether there is a filter for this (in addition to the new option) and can you provide an example of how that filter can be used to exclude specific terms from a custom taxonomy.

**Comment by contactashish13** [comment]
@wpsmort please check https://github.com/semperfiwebdesign/aioseop-pro/issues/240#issuecomment-421278189

**Comment by wpsmort** [comment]
@contactashish13 Please provide examples of how to use these filters.

**Comment by arnaudbroes** [comment]
After going through the code, I found we already have a filter for this, but no documentation. 
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/bdd97e94ae953ef85f894da6f4230217d5693223/modules/aioseop_sitemap.php#L4165-L4168

I've removed some unnecessary arguments and created a doc for it.
