### ISSUE TITLE
Better support for multiple fb:admins

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#749]
Multiple fb:admin should be on separate lines: http://ogp.me/#array

Reported here:
https://wordpress.org/support/topic/error-on-facebook-sharing-debugger-about-fbadmins-meta-tag/

> when inserting multiple admins id’s to the “Facebook Admin ID” field, the output on the front end will be single meta tag of fb:admins with multiple admins id’s separate with comma.
maybe in the past it was the way to do it but it seems like Facebook Sharing Debugger has change the way it works and i’m getting “parser Mismatched Metadata” error about fb:admins…it should be fb:admins meta tag for each admin id.

**Comment by michaeltorbert** [comment]
For testing, we need to make sure it works without errors for no fb:admins, one, and multiple.

**Comment by wpsmort** [comment]
This is tested and is good.
