### ISSUE TITLE
Add hook to filter return of get_tax_args function

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#752]
Reference: https://wordpress.org/support/topic/sitemap-all-taxonomiy-terms/

In aioseop_sitemap.php, we should add a filter to get_tax_args() on line 2598 so users can manipulate the arguments https://developer.wordpress.org/reference/functions/get_terms/#parameters

We could either a) just filter the return $args array, or b) add our own individual filters for each argument or c) both.

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1430

**Comment by michaeltorbert** [comment]
@contactashish13 Why are we adding  $page, $this->options as additional arguments?

**Comment by contactashish13** [comment]
I tend to add any parameter that might be useful for the hook - in this case I can see options being useful for sure to determine taxonomy behavior on the basis of the settings. Can't think of a pressing case for `$page`.

**Comment by wpsmort** [comment]
@contactashish13 I tested this but it doesn't appear that the get_tax_args function is being called.  Can you test and make sure the function is being called and provide a working example of how to use this filter.

**Comment by contactashish13** [comment]
@wpsmort the functions gets called. You can test it by adding just an `error_log`.

The filter is

`apply_filters( 'aiosp_sitemap_tax_args', $args, $page, $sitemap_options )`

You can use the below snippet for removing the taxonomy exclusions:

```
add_filter( 'aiosp_sitemap_tax_args', 'aiosp_sitemap_tax_args', 10, 1 );
function aiosp_sitemap_tax_args( $args ) {
    unset( $args['exclude'] );
    return $args;
}
```

**Comment by arnaudbroes** [comment]
@contactashish13 I'm currently drafting documentation for this filter. From what I understand, this filter allows you to filter taxonomy terms. 

Could you please let me know what these arguments exactly are and what they're used for -

- $args
- $page (is this the page ID?)
- $sitemap_options
