### ISSUE TITLE
Possibly unused WooCommerce product archive code

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#755]
The following code doesn't seem to be used in any way (comments are mine, added recently):

```
// This seems to provide WooCommerce product archive functionality, but doesn't seem to actually do anything.
        // $opts and $posts overwritten later, and it's not clear that anything is added to $this->meta_opts that isn't already there.
		if ( function_exists( 'wc_get_page_id' ) && is_post_type_archive( 'product' ) && ( $post_id = wc_get_page_id( 'shop' ) ) && ( $post = get_post( $post_id ) ) ) {
			global $posts;
			$opts    = $this->meta_opts = $this->get_current_options( array(), 'aiosp', null, $post );
			$posts   = array();
			$posts[] = $post;
		}
```
We should see if this can be deleted.

**Comment by michaeltorbert** [comment]
For testing (remove-wc-code branch), we need to verify there's no missing functionality for WooCommerce product archive pages in free or pro (the only change for this is in aioseop_class.php).

**Comment by wpsmort** [comment]
@michaeltorbert: I tested this on a duplicate site with the only difference being that I had the remove-wc-code branch installed.  I then checked the WooCommerce Shop page and here are the issues I found in the source code of the site running the remove-wc-code branch:

- The meta keywords was missing some keywords (not something we should be concerned with)
- The meta robots were not output (i.e. noindex, nofollow, etc.)
- The custom canonical URL did not work

Here's a screenshot of the two sites (left side is running dev branch, right side is running remove-wc-code branch):

<img width="2411" alt="screen shot 2017-03-02 at 4 32 42 pm" src="https://cloud.githubusercontent.com/assets/17548525/23527934/ea6f1692-ff65-11e6-969c-103543b0c757.png">

**Comment by wpsmort** [comment]
After testing this code we found that it is being used.  It outputs the robots meta tags and the custom canonical URL.  We are therefore leaving this code in the plugin as it is needed.
