### ISSUE TITLE
Remove all options for NOODP

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#758]
With effect from March 14th, DMOZ ODP will go away (http://searchengineland.com/rip-dmoz-open-directory-project-closing-270291/).

This means we can remove all options for NOODP.   Currently there are options here:

- In the AIO meta box on Edit Post screen (Robots Meta NOODP)
- Under General Settings > Noindex Settings > Default to NOODP
- Under General Settings > Noindex Settings > Exclude site from the Open Directory Project

**Comment by michaeltorbert** [comment]
For testing, we need to make sure index/noindex and follow/nofollow works exactly the same as 2.3.12.1 stable.

**Comment by wpsmort** [comment]
I have tested this comparing with my control site and everything works fine for all Noindex and Follow settings.  I have also tested by upgrading a site that had the Noodp options enabled and that works fine, only the Noodp tags are removed.
