### ISSUE TITLE
Remove all options for NOYDIR

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#759]
The Yahoo Directory shut down in 2014.  This means we can remove all options for NOYDIR.   Currently there are options here:

- In the AIO meta box on Edit Post screen (Robots Meta NOYDIR)
- Under General Settings > Noindex Settings > Default to NOYDIR
- Under General Settings > Noindex Settings > Exclude site from Yahoo! Directory

**Comment by michaeltorbert** [comment]
For testing, we need to make sure index/noindex and follow/nofollow works exactly the same as 2.3.12.1 stable.

**Comment by wpsmort** [comment]
I have tested this comparing with my control site and everything works fine for all Noindex and Follow settings.  I have also tested by upgrading a site that had the Noydir options enabled and that works fine, only the Noydir tags are removed.
