### ISSUE TITLE
Social Meta Module: Remove Run Shortcodes In Description

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#764]
Remove this option after first determining the following:

- Determine whether to respect these settings or run shortcodes for everyone
- Determine if there's a performance hit if we run shortcodes for everyone
- Determine if we fail gracefully if we cannot run a shortcode

**Comment by michaeltorbert** [comment]
Closing as we definitely won't be doing this. See #787

Shortcodes are too unpredictable to run them by default. This should be considered advanced functionality and should remain an option that's disabled by default.
