### ISSUE TITLE
Jetpack publicize breaks when autogenerate OG descriptions is turned on

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#766]
Reported here: gulftobayweb.com/jetpack-publicize-not-posting-image-or-wrong-image-to-facebook/

I doubt this is happening, but we should verify it before we turn on the option for everyone.

**Comment by wpsmort** [comment]
I've not been able to replicate this and I've confirmed that JetPack Publicize picks up the OG meta we output and uses that when you publish a post.
