### ISSUE TITLE
Remove reference to blog in short description in readme.txt

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#772]
**All in One SEO Pack** Optimizes your WordPress blog for SEO (**Search Engine Optimization**).
is what we currently have. It may be confusing for some people who may think we only do blog posts, and not other post types such as pages, products, etc.

**Comment by michaeltorbert** [comment]
@wpsmort Do you want to take a look at our changes and see what you think?

**Comment by wpsmort** [comment]
These changes look good.
