### ISSUE TITLE
Premium upgrade links should open in new tab

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#773]
There are two links to upgrade to Pro that open in the same tab, they are:

- Upgrade to Pro link on Plugins screen
- Upgrade to Pro link in AIOSEOP menu

Ideally we should make these open in a new tab using JavaScript.

**Comment by arnaudbroes** [comment]
Doesn't need JavaScript, just an HTML attribute.

**Comment by michaeltorbert** [comment]
We need to verify that the referrer info is still passed. Check every browser (Chrome, Firefox, Safari, Opera, etc). 

For testing, change the URL to one you can control and add in something to show you what, if any, referrer is passed.
For example:
`if ( isset( $_SERVER['HTTP_REFERER'] ) ) {
	echo "referrer: " . $_SERVER['HTTP_REFERER'];
}else{
	echo 'no referrer';
}`

**Comment by arnaudbroes** [comment]
I tested this on Windows for Chrome, Firefox, Edge and Internet Explorer and the URL is still passed on. 
@wpsmort can you test this in Safari? Just install the plugin, click either of the upgrade links and once you land on the plugin page, enter the document.referrer command into the JavaScript console.

**Comment by wpsmort** [comment]
I tested this in Chrome, Firefox, Safari and Opera on Mac and the referrer was passed each time.
