### ISSUE TITLE
Support for themes and plugins that do queries wrong

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#777]
Some themes and plugins mishandle secondary queries. For these, we need to make sure we're always in the main query, and change it back when we've finished.

**Comment by wpsmort** [comment]
I've tested this with 25 of the most popular themes and have not seen any issues.

**Comment by wpsmort** [comment]
I've confirmed that this fixes the issue reported by our user in issue #774

**Comment by wpsmort** [comment]
I tested this with 25 of the most popular themes and didn't find any problems.
