### ISSUE TITLE
Social Meta Module - generate_descriptions descriptions off by default

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#779]
The generate_descriptions used to be for Autogenerate OG descriptions, which now happens regardless of settings for everyone. 
This option is now being repurposed in #739 to use the post content instead of the (default) excerpt.

We need to have this option disabled by default for new installs.

**Comment by wpsmort** [comment]
This is tested on a new site with a new install as well as with an existing site updating to the latest dev branch.  It's confirmed working on both.
