### ISSUE TITLE
Add filter hook to remove AMP description

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#785]
Related to #732

**Comment by michaeltorbert** [comment]
The existing aioseop_amp_description filter can now be used to disable the functionality by using __return_false.

**Comment by wpsmort** [comment]
This is tested and is good.

I've added the documentation for this filter here - https://semperplugins.com/documentation/disable-meta-description-on-amp-pages/
