### ISSUE TITLE
Add filter hook to remove AMP social meta

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#786]
Related to #733

**Comment by michaeltorbert** [comment]
The filter hook is aioseop_enable_amp_social_meta
__return_false should disable our social meta for AMP.

**Comment by wpsmort** [comment]
This is tested and is good.  

I've added the documentation for this filter here - https://semperplugins.com/documentation/disable-open-graph-meta-on-amp-pages/
