### ISSUE TITLE
Option to hide "hidden" WooCommerce products from the XML Sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#788]
Requested by Arjen via email

> The XML sitemap contains WooCommerce products which are (in woocommerce terms) hidden.
> Unfortunately WooCommerce doesn't use the regular post fields for that, but rather has a _visibility meta field.
> To clean up your query result set, you need to do roughly the following LEFT JOIN:
> 
> SELECT p.post_type,p.post_name,pm.meta_value
> FROM wp_posts p
> LEFT JOIN wp_postmeta pm ON (p.id=pm.post_id AND pm.meta_key='_visibility')
> WHERE p.post_status='publish' AND (pm.meta_value IS NULL OR pm.meta_value = 'visible')
> 
> If there is no such meta key the item can be regarded as visible
> If the meta key exists and is 'visible', then the product should be in the sitemap.
> Other possible values are 'search' and 'hidden'.
> You could restrict all this to products only but it's probably safe enough.

**Comment by michaeltorbert** [comment]
My first thought is this seems like a good candidate for a Pro option.

**Comment by arjenlentz** [comment]
thanks Michael.

**Comment by michaeltorbert** [comment]
Notes: WooCommerce has "catalog, search, catalog+search, hidden" (as opposed to the WP public, private, password protected)

**Comment by michaeltorbert** [comment]
Closing as this is a pro feature.
