### ISSUE TITLE
Move Social Media buttons in About section down

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#792]
It would probably look better if we move the Social Media buttons below the last paragraph.

![image](https://cloud.githubusercontent.com/assets/18156697/23626876/be70594c-02ae-11e7-84bd-65ee93345efe.png)

**Comment by wpsmort** [comment]
Rather than move the icons, I have added a CSS class to the translation text and added a margin to provide space between the text and the icons.
