### ISSUE TITLE
Make language placeholder translatable

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#793]
The language placeholder is replaced by the English term when you're using a different language.
Dutch example:

![image](https://cloud.githubusercontent.com/assets/18156697/23627950/fb44386c-02b2-11e7-8d3d-9ad54f15fafd.png)

(general-metaboxes.php line 80)

Related to #790.
(leave me assigned, I'd like to see how this is solved)

**Comment by wpsmort** [comment]
This is tested and confirmed fixed.

@arnaud Can you test as well please.

**Comment by michaeltorbert** [comment]
Sorry @arnaudbroes 
@wpsmort has replaced you with @arnaud

**Comment by arnaudbroes** [comment]
The more, the merrier. ;-)

**Comment by arnaudbroes** [comment]
@wpsmort @michaeltorbert 
I confirm this is fixed. Closing the issue.
![image](https://cloud.githubusercontent.com/assets/18156697/23811317/c1412f1e-05d5-11e7-982c-a0e18aa49f50.png)
