### ISSUE TITLE
Accommodating for custom queries breaks if we return early from wp_head

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#801]
Reported here: https://wordpress.org/support/topic/problem-with-woocommerce-product-archive/

Related to: #777

**Comment by michaeltorbert** [comment]
The problem is that just after reseting the query, we have a couple of conditional returns without setting the query back to the old one.

**Comment by michaeltorbert** [comment]
For testing, just make sure #777 works on various types of pages... home page, post, post archive, page, CPT, CPT archive.

**Comment by wpsmort** [comment]
I've tested with various types of pages and have not been able to replicate the original problem with v2.3.12 and have found nothing wrong with titles, descriptions and other meta in v2.3.12.1

**Comment by wpsmort** [comment]
I discussed this with Michael and we agreed that it could be a setting that was changed on our dev site prior to me taking a backup.  We agreed that this issue can be closed.
