### ISSUE TITLE
Help icon doesn't look right

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#807]
The Help icon for pages and posts looks a bit out of shape:

![image](https://cloud.githubusercontent.com/assets/18156697/23729618/3f2597ea-0463-11e7-9ca4-1e126acd936f.png)

If this is because of it scaling down, then I would suggest using a different icon in these corners.
Perhaps a small instance of the All in One SEO plug logo.

**Comment by wpsmort** [comment]
I recommend we remove our help icon and instead use the WordPress dashicon here - https://developer.wordpress.org/resource/dashicons/#editor-help

**Comment by michaeltorbert** [comment]
Agreed re: editor-help

**Comment by wpsmort** [comment]
PR #1171
