### ISSUE TITLE
Filter to disable All in One SEO Pack not working

### ISSUE THREAD

**Issue by l4ci** [semperfiwebdesign/all-in-one-seo-pack#809]
Issue related to #605 

The mentioned filter doesn't seem to work for me.

I have the following code in my page specific template file, even before `wp_head()`is called.
```
function disable_aioseop(){
            return true;
}
add_filter( 'aiosp_disable', 'disable_aioseop', 10, 1 );
```
No matter if the function returns true or false - all in one seo is always enabled and replaces the title/meta tags.

**Comment by michaeltorbert** [comment]
Closing as this is a support issue / general WP API question.
