### ISSUE TITLE
Text too long for Social Meta module activation window

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#810]
Some translations are longer than the original one and push the button down (padding or margin?).
![image](https://cloud.githubusercontent.com/assets/18156697/23773157/403fc964-051e-11e7-8342-95db5d44ffb5.png)

We could either shorten the text or fix it so that the button isn't pushed downwards.

Perhaps we should change the text from "Activate this feature" to "Add Social Meta data" or "Add OG:graph data" anyhow because the former is quite obvious and isn't used in any of the other module windows.

**Comment by wpsmort** [comment]
The wording has been shortened. I have tested this and confirmed it fixes the issue shown in Arnaud's screenshot.
