### ISSUE TITLE
Change NOFOLLOW/NOINDEX string 

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#811]
@wpsmort  suggested that, since we are planning to delete the options for the Yahoo! Directory we could change the remaining NOFOLLOW/NOINDEX strings from "Robots Meta NOFOLLOW/NOINDEX" to something like:

"NOINDEX this post" / "NOFOLLOW this post". The current string is rather confusing for beginners.

We could make it so that it automatically detects if the user is editing a post/page or custom post type.

**Comment by michaeltorbert** [comment]
Agreed.

**Comment by michaeltorbert** [comment]
This can go out in 2.3.12.1 if it's ready, but it should be the very last thing after all other 2.3.12.1 issues have been developed and tested. Otherwise, it's fine for 2.3.13.

**Comment by wpsmort** [comment]
PR #1076 is done and tested.
