### ISSUE TITLE
Not compatible with php 7.0.

### ISSUE THREAD

**Issue by paaljoachim** [semperfiwebdesign/all-in-one-seo-pack#815]
Hi

I just downloaded the SiteGround SG Optimize. It offers three features:
SuperCacher Config
HTTPS Config
PHP Config - 

PHP Config
This tool will allow you to check if your website is compatible with the recommended by SiteGround PHP version and switch to it with a click. It is highly advisable to keep your WordPress running on the recommended PHP for best security and performance.

Notice: checking your site for PHP 7.0 compatibility....

One of the plugins not compatible is All In One SEP Pack Pro.

Error message:
FILE: /home/easyweb7/public_html/easywebdesigntutorials.com/wp-content/plugins/all-in-one-seo-pack-pro/pro/video_sitemap.php
----------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------------------------------------------------------------
 209 | ERROR | Using 'break' outside of a loop or switch structure is invalid and will throw a fatal error since PHP 7.0
 223 | ERROR | Using 'break' outside of a loop or switch structure is invalid and will throw a fatal error since PHP 7.0
----------------------------------------------------------------------------------------------------------------------------

**Comment by michaeltorbert** [comment]
Hi @paaljoachim 

Thank you for letting us know. This is actually a false positive (break is absolutely used inside a loop) but we'll change the code so it doesn't trigger the alert in the next version.

**Comment by paaljoachim** [comment]
Thanks Michael!
