### ISSUE TITLE
update of strings for translation

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#823]
I'm linking all cleaned up commits to this issue.
Related to #790.

**Comment by michaeltorbert** [comment]
@wpsmort For testing, check out https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/a4a058933a46cb75e4fa2131c8de2d719e307339 and you'll see where some option information is now translatable. 
We need to make sure that these are all appropriate to be translated, and don't break options for people. 
For example, the 404_title_format default is now translatable... is that something we want?

Also in the import/export, "General Settings" and "Post Data" are translatable. Will that break exporting/importing for people using a different language? What about if they export with one language and then import with another?
Same with the opengraph image options.

**Comment by wpsmort** [comment]
@michaeltorbert I have tested this and everything looks fine.  There are no problems with the import/export feature and I believe its fine to translate the text string in the 404 Title Format field
