### ISSUE TITLE
fix missing spaces for translation

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#825]
Right now some strings start with a space, but these are not visible on the translation platform, causing some strings to be pasted together and look like this: (click hereto upgrade to Pro).

We should correct these for:

**aioseop_sitemap.php** line 480 & 481
' Post Type'
' Taxonomy'

**aioseop_sitemap.php** line 620 & 622
' Your sitemap has been created'
' and changes are automatically submitted to search engines'

**general-metaboxes.php** line 42
' to upgrade to Pro Version and get:'

**Comment by arnaudbroes** [comment]
I believe we can either 

(1) add non-breaking space HTML entities (&nbsp;) to partial strings so that our translators take these into account; 

or (2) remove the spaces from those partial strings and concatenate them as separate strings (for example "I am" . " " . "Arnaud Broes" or "I am" . "&nbsp;" . "Arnaud Broes"). This makes the code a little messier but also ensures translators can't make any mistakes.

@michaeltorbert what do you think?

**Comment by michaeltorbert** [comment]
Probably best to use placeholders https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders
