### ISSUE TITLE
multiple sitemaps

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#828]
Requested here: https://wordpress.org/support/topic/sitemap-404-at-nginx/page/2/#post-8926313

More info: https://moz.com/blog/multiple-xml-sitemaps-increased-indexation-and-traffic

**Comment by herculesnetwork** [comment]
It would be a great improvement on the sitemaps feature :-) Great!

**Comment by wpsmort** [comment]
We do already have this feature in our plugin.  It can be enabled by clicking the Enable Sitemap Indexes.  This creates a sitemap index which lists each individual sitemap.  We then generate individual sitemaps for each post type and taxonomy. See screenshots:

<img width="787" alt="screen shot 2017-03-17 at 1 34 04 pm" src="https://cloud.githubusercontent.com/assets/17548525/24055454/7b2b9a00-0b16-11e7-811e-46eec62ec8bc.png">
<img width="768" alt="screen shot 2017-03-17 at 1 34 30 pm" src="https://cloud.githubusercontent.com/assets/17548525/24055453/7b043bb8-0b16-11e7-94c6-c4d3e603be37.png">

When we add our Image XML Sitemap and News XML Sitemap then we can include those in the sitemap index.

I've opened a new issue 201 under Pro to include the URL for our Video XML Sitemap in the sitemap index.
