### ISSUE TITLE
Pro link in menu shows up for everyone

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#833]
Reported here: https://wordpress.org/support/topic/admin-panel-left-menu-link/#post-8944675

I've tested and confirmed this.

**Comment by michaeltorbert** [comment]
We can just put a check in the AIOSEOPAdminMenus class contructor for our capability.

**Comment by wpsmort** [comment]
This is tested and is good.
