### ISSUE TITLE
Open Graph Description field shows HTML markup for WooCommerce products

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#837]
This is related to #672 

The same problem as reported in the above issue also happens with the Description field on the Social Settings tab.  See screenshot:

<img width="1147" alt="screen shot 2017-03-27 at 7 11 51 pm" src="https://cloud.githubusercontent.com/assets/17548525/24381945/41ecf33e-1321-11e7-9347-149e2547f8ad.png">

**Comment by wpsmort** [comment]
@stanislavsa Is this ready for a PR?

**Comment by stanislavsa** [comment]
This issue has the same fix as in #672 issue.
#835 PR fixed both this issues.

**Comment by wpsmort** [comment]
@stanislavsa This needs a new PR so I can test it.

**Comment by stanislavsa** [comment]
Fix for #837 is presented in the 835 PR.
Firstly I made two fixes for #672 and #837, but then I added some changes to #672 and it also fixed issue #837 so no need in PR for 837 issue.

**Comment by wpsmort** [comment]
This is tested and is good but it does need it's own PR.

**Comment by wpsmort** [comment]
PR #860
