### ISSUE TITLE
Duplicates Content from My Plugin

### ISSUE THREAD

**Issue by georgegijo** [semperfiwebdesign/all-in-one-seo-pack#852]
My plugin is in conflict with the social meta feature. The plugin shortcode creates content twice. If I comment the code inside do_opengraph, it works correctly. Is there anything I have to take care with my plugin to avoid this conflict?

**Comment by michaeltorbert** [comment]
Please stop spamming us. We can't possibly debug your plugin's problem without seeing your plugin.

**Comment by georgegijo** [comment]
Sorry for that. I am attaching the code. Hope it helps. Thanks
[mcosms.zip](https://github.com/semperfiwebdesign/all-in-one-seo-pack/files/892896/mcosms.zip)

**Comment by georgegijo** [comment]
I resolved this issue by adding add_action('wp_head','myfunction') in my plugin to invoke the plugin execution. Now the issue seems to be resolved although I don't know the implications.

**Comment by michaeltorbert** [comment]
Looks fine to me.

<img width="315" alt="screen shot 2017-04-05 at 9 52 05 am" src="https://cloud.githubusercontent.com/assets/17364998/24708686/983cf642-19e5-11e7-8b90-a79dd5ad9597.png">
<img width="555" alt="screen shot 2017-04-05 at 9 51 28 am" src="https://cloud.githubusercontent.com/assets/17364998/24708685/983b48e2-19e5-11e7-9dcb-2f1c6485597f.png">
<img width="354" alt="screen shot 2017-04-05 at 9 51 11 am" src="https://cloud.githubusercontent.com/assets/17364998/24708689/99cc96c0-19e5-11e7-8cf5-2b1b27649d12.png">
