### ISSUE TITLE
Fatal error: Uncaught Error in PHP 7.1

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#853]
Reported here: https://wordpress.org/support/topic/php-7-1-problem/

I'm not exactly sure what's prompting this, but I don't think this has to do with PHP 7.1. My guess is that the edit array key simply doesn't exist already for some reason. 
It may be as simple as checking for it first.

		unset( $actions['edit'] );

**Comment by michaeltorbert** [comment]
We need to try and reproduce this.

**Comment by michaeltorbert** [comment]
Update: the user reported that the conflict is with the wp-editor plugin. https://wordpress.org/support/plugin/wp-editor

**Comment by michaeltorbert** [comment]
So far I'm not able to reproduce it.

**Comment by arnaudbroes** [comment]
I'm going to close this issue based on the fact that we're 100% compatible now.
