### ISSUE TITLE
Social Meta Module - Incorrect auto generated OG Description when Use content is enabled

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#859]
This affects Posts and WooCommerce Products (anything that has an Excerpt).

The placeholder text in the Open Graph Description field is incorrect when auto-generate descriptions is enabled.

There are two settings that affect the auto-generated OG descriptions, they are:

- Use Content For Autogenerated Descriptions under All in One SEO > General Settings > Advanced Settings
- Use Content For Autogenerated OG Descriptions under All in One SEO > Social Meta > Advanced Settings

The bug occurs when you have these two settings set differently.  For example:

If you enable "Use Content For Autogenerated Descriptions" **but not** "Use Content For Autogenerated OG Descriptions" then the OG Description placeholder text shows the content **not**  the excerpt.

If you enable "Use Content For Autogenerated OG Descriptions" **but not** "Use Content For Autogenerated Descriptions" then the OG Description placeholder text shows the excerpt **not**  the content.

This only affects the placeholder text seen in the Description field of the Edit Post / Edit Product screen.  It does not affect the meta data output in the source code which is always correct.

It appears that what's happening is that the placeholder text in the OG Description is being copied from whatever is in the SEO Description, and the "Use Content For Autogenerated OG Descriptions" option is ignored.

**Comment by amostajo** [comment]
@wpsmort Added a small fix so placeholder reflects what is set on settings.

Please review.

**Comment by wpsmort** [comment]
This is tested and is good.  It is ready for a code review.
