### ISSUE TITLE
Internally used custom post types should be hidden

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#866]
Two internally used custom post types have recently start showing up in the plugin:
- custom CSS
- changesets

![image](https://cloud.githubusercontent.com/assets/18156697/24778394/9ef9f11a-1b2a-11e7-8f39-95c1cf36280f.png)

We should hide these in our settings.

**Comment by michaeltorbert** [comment]
These were added in a recent version of WordPress

https://github.com/WordPress/WordPress/commit/1ccd9e7a6c7bc4a0f9ffae670c526f9420a3edeb#diff-ab88b030116a886cb5530713d3fd4bf2

https://github.com/WordPress/WordPress/commit/f1ba1918c925510822a48fb83c1e74d22d7f0c46#diff-ab88b030116a886cb5530713d3fd4bf2

**Comment by wpsmort** [comment]
@michaeltorbert These post types need to be removed from Social Meta > Facebook Settings > Enable Facebook Meta For as well.  See screenshot.

<img width="922" alt="screen shot 2017-05-01 at 10 42 01 am" src="https://cloud.githubusercontent.com/assets/17548525/25582354/d8d39a1a-2e5a-11e7-8bbb-c718246ac362.png">

**Comment by wpsmort** [comment]
This is tested and is confirmed fixed.
