### ISSUE TITLE
Robots.txt Module - Add a View Robots.txt File button

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#87]
We need to add a button for View Robots.txt File next to the Delete Robots.txt File button.

When this button is clicked it should open the robots.txt file in a new browser tab.

**Comment by nishant981** [comment]
we have done with above issue
![3](https://cloud.githubusercontent.com/assets/13958896/14354848/824c1608-fcfc-11e5-84f3-b66eed72a9a8.png)

**Comment by michaeltorbert** [comment]
@nishant981 Each time you've finished, submit a pull request with your changes tot he nishant branch.

**Comment by nishant981** [comment]
I have uploaded my code to git, please check and let me know it is fine and I can follow the same steps further

**Comment by wpsmort** [comment]
@contactashish13 Please hold off on this issue until Issues #214 and #596 have been completed and tested.

**Comment by wpsmort** [comment]
This should no longer be required once we complete #1647
