### ISSUE TITLE
Add Yandex and Baidu Webmaster Tools verification

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#875]
and any others we're missing including:

Baidu

**Comment by wpsmort** [comment]
Requested by kemal durmu by email today.

**Comment by RUSxDeviL1979** [comment]
please tell me when will add Yandex webmaster ?

**Comment by wpsmort** [comment]
@RUSxDeviL1979 This is on our roadmap but we don't have a release date as yet.  We'll update this issue when we do have one.

FYI... you can add the HTML code for Yandex Webmaster verification in the Additional Headers fields under All in One SEO > General Settings > Advanced Settings - https://semperplugins.com/documentation/all-in-one-seo-pack-advanced-settings/
