### ISSUE TITLE
Quickedit Functions JS linked with extra slash

### ISSUE THREAD

**Issue by jhned** [semperfiwebdesign/all-in-one-seo-pack#878]
I'm seeing the quickedit functions link built as:

"/wp-content/plugins/all-in-one-seo-pack//js/quickedit_functions.js?ver=2.3.12.2.1"

in the current version of the plugin. The extra slash before JS is causing my server to respond 403 forbidden, for whatever reason.

**Comment by michaeltorbert** [comment]
Hi jhned,

Thank you for reporting this. Strangely, Chrome on my computer seems to ignore the extra slash, which I suspect is why it wasn't caught. We'll make sure this is fixed for the next version.
Out of curiosity, what browser/OS/etc are you using?

**Comment by jhned** [comment]
I'm using macOS Sierra 10.12.3 and Chrome 57.0.2987.133, though I suspect
it's a server issue-- I believe the site is hosted on Rackspace using
Apache, not nginx.
