### ISSUE TITLE
Add Noindex and Nofollow to Quick Edit on All Posts

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#882]
Requested here - https://wordpress.org/support/topic/nofollow-multiple-selection/

Consider adding the ability to select multiple posts on the All Posts screen and use the Quick Edit feature in WordPress to set Noindex or Nofollow for the selected posts.

**Comment by michaeltorbert** [comment]
This wouldn't do what he was wanting. He wanted a bulk editor, not a quick edit.
What would be better for him is to use a custom fields bulk editor (if such a thing exists).

This issue as written is still fine for inclusion though.

**Comment by wpsmort** [comment]
Requested again here - https://semperplugins.com/support/feature-requests-all-in-one-seo-pack-pro/add-noindex-capability-to-quick-edit/

**Comment by michaeltorbert** [comment]
Ok, we're still conflating three things. 

1) Add noindex/nofollow to quick edit
2) Add noindex and nofollow columns
3) Add noindex and nofollow to a custom bulk action (requires WP 4.7)

**Comment by michaeltorbert** [comment]
We're still conflating three things in this issue.

Add noindex/nofollow to quick edit
Add noindex and nofollow columns
Add noindex and nofollow to a custom bulk action (requires WP 4.7)

**Comment by michaeltorbert** [comment]
Closing this in favor of #2275 #2276 #2277
