### ISSUE TITLE
Social Meta Module - Add og:type meta tag to homepage when front page displays posts

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#883]
Reported here - https://wordpress.org/support/topic/facebook-like-button-warning/

We don't output the og:type tag on the homepage when Front Page is set to display posts under Settings > Reading.  We should output the og:type tag for blog as follows:

`<meta property="og:type" content="blog" />`

**Comment by michaeltorbert** [comment]
@wpsmort What follows?

**Comment by wpsmort** [comment]
@michaeltorbert I forgot the backticks so the HTML code would show.

**Comment by amostajo** [comment]
@wpsmort Should this always be type `blog`?

What happens if the blog page has some modifications to its template so it displays more information aside for posts to actually make it look like a landing page?

**Comment by wpsmort** [comment]
@amostajo We have a filter hook to change this - https://semperplugins.com/documentation/aiosp_opengraph_meta/

**Comment by wpsmort** [comment]
Michael and I discussed this today and agreed that the og:type should in fact be set to website because blog is no longer a valid type.  See OGP protocol documentation - http://ogp.me/#types

**Comment by wpsmort** [comment]
See also related issue #1011

**Comment by michaeltorbert** [comment]
Ok so in this commit, og type will be website on either the home page (regardless of whether it's the blog archive, and on the page for posts it will also.

**Comment by wpsmort** [comment]
This is tested and is good.
