### ISSUE TITLE
XML Sitemap - Blank sitemap pages with WPML

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#884]
This was identified whilst testing prior to release of 2.3.12.3.

When you are using WPML to translate content and you have sitemap indexes and pagination enabled, we are creating empty sitemap pages.

For example:

If you have 6 pages in English and pagination is set to 3 URLs per page, you get 2 pages populated with the 6 URLs (3 per page).  However, you also get a number of blank pages as well.  This happens for each language.  See screenshots:

<img width="967" alt="screen shot 2017-09-12 at 4 48 34 pm" src="https://user-images.githubusercontent.com/17548525/30347500-492c2384-97da-11e7-82bf-424f285123ed.png">
<img width="988" alt="screen shot 2017-09-12 at 4 48 52 pm" src="https://user-images.githubusercontent.com/17548525/30347499-4929d0c0-97da-11e7-8402-03d802abcf4f.png">

**Comment by contactashish13** [comment]
@wpsmort @arnaudbroes @michaeltorbert can I get a copy of the WPML plugin to reproduced and fix this?

**Comment by arnaudbroes** [comment]
@contactashish13 Sending it on Slack.

**Comment by contactashish13** [comment]
@arnaudbroes I followed Steve's suggestions and configured WPML with French an the additional language. When I view the sitemap in default as well as the /fr/ URLs, I get the same number of pages and not the additional pages he mentions. Maybe my settings are not identical to reproduce the issue. Could you please check?

**Comment by arnaudbroes** [comment]
@contactashish13 I was able to reproduce this issue with the settings that Steve mentioned above. Sending credentials for the test site on Slack that you can use to verify the issue.

**Comment by contactashish13** [comment]
@arnaudbroes PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1358. Have also made changes to the test site and tested there. 

@michaeltorbert there were a few bits of messy and redundant code that I've removed to improve readability. Have left comments as well.

**Comment by contactashish13** [comment]
@wpsmort I was able to reproduce the issue on my dev instance and have fixed this. 

PS - Can you please add comments to the issue instead of the PR so that all comments are in one place?

**Comment by wpsmort** [comment]
@contactashish13 I tested with your latest code and it still creates a blank sitemap file.  It also now doesn't include the custom post types such as WooCommerce products.  See screenshot below:

<img width="1881" alt="screen shot 2018-02-06 at 1 31 04 pm" src="https://user-images.githubusercontent.com/17548525/35877180-a1cf9af8-0b42-11e8-803e-eaf7e5464c42.png">

**Comment by contactashish13** [comment]
@wpsmort The plugin "All In One SEO Pack-884" does not seem to have my latest changes.

Please compare https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1358/commits/ad4f494c6d1e7516a83171d1d2bc775e00289d29 with the below screenshot from the plugin editor, where I can still see the old code.

![image](https://user-images.githubusercontent.com/12953439/35908675-65706ec2-0c17-11e8-8236-0688aecf988d.png)

**Comment by wpsmort** [comment]
@contactashish13 I tested the latest code from PR #1358 which includes the code from commit https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/ad4f494c6d1e7516a83171d1d2bc775e00289d29 and it's still not including custom post types.  It does include custom taxonomies.

The blank sitemap issue is fixed in the latest code from your PR.

**Comment by contactashish13** [comment]
@wpsmort have fixed this.
