### ISSUE TITLE
"Uploaded to this post" missing from media page dropdown

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#888]
We broke this again in 2.3.12.3 with the wp_enqueue_media added to enqueue_scripts(). It was previously broken and fixed in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/726

Reported here: https://wordpress.org/support/topic/update-problem-41/#post-8686351

**Comment by michaeltorbert** [comment]
On first glance, it appears to be caused by enqueue_metabox_scripts() not loading until the admin_print_scripts hook...
 then this function use the admin_print_scripts hook (makes no sense) and admin_enqueue_scripts hook (maybe too late??)

**Comment by wpsmort** [comment]
This is tested and is good.   It fixes the issue reported on the WP.org forums.
