### ISSUE TITLE
Translation comments in documentation are showing

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#889]
Something looks off about this. :)

<img width="1015" alt="screen shot 2017-05-02 at 1 13 38 pm" src="https://cloud.githubusercontent.com/assets/17364998/25629904/39cebbfe-2f39-11e7-84f8-f75fd7e150c1.png">

**Comment by arnaudbroes** [comment]
Related to #871.

**Comment by arnaudbroes** [comment]
![image](https://cloud.githubusercontent.com/assets/18156697/25630906/fb4cb6ca-2f6e-11e7-9d3b-34f59a938322.png)

Looks fixed, needs final review.
