### ISSUE TITLE
WordPress 4.5 compatibility

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#89]
This may need to be separated out into multiple issues

reference: https://make.wordpress.org/core/2016/03/30/wordpress-4-5-field-guide/

Things to keep an eye on and test:

1.
Term Edit Page! –‼️ Backward Incompatible change‼️
The term edit screen has been separated out from the term list screen. This brings greater consistency to how the admin generates screens for terms and posts but at the cost of the need to change how you register scripts and how you detect that you are on a term edit screen.
https://make.wordpress.org/core/2016/03/07/changes-to-the-term-edit-page-in-wordpress-4-5/

2.
Overall, 372 bugs have been marked as fixed in WordPress 4.5 (so far). There are also dozens of new hooks and dozens of hooks that have received additional parameters. It’s entirely possible that one or more has caused a regression, so please make sure to test your code deeply
https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=closed&status=new&status=reopened&status=reviewing&type=defect+(bug)&resolution=fixed&milestone=4.5&col=id&col=summary&col=milestone&col=status&col=type&col=owner&col=priority&order=priority

**Comment by michaeltorbert** [comment]
@wpsmort Are we satisfied with all of this?

**Comment by wpsmort** [comment]
@michaeltorbert Yes, I am satisfied that we've not experienced any other issues with WP 4.5.
