### ISSUE TITLE
Update the translations link in readme.txt

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#892]
It should be https://translate.wordpress.org/projects/wp-plugins/all-in-one-seo-pack, not sfwd

**Comment by arnaudbroes** [comment]
@michaeltorbert Is this still relevant? I don't see a link to the translation page in the readme.txt.
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/readme_%23892/readme.txt

**Comment by arnaudbroes** [comment]
This is no longer needed and has been removed from the readme.txt.
