### ISSUE TITLE
Strip out oEmbed videos from auto-generated descriptions

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#898]
When a video is embedded in the content of a page or post using oEmbed, the video URL shows up in the auto-generated SEO and OG descriptions.  oEmbed URLs need to be stripped out of auto generated descriptions.  See screenshot.

<img width="837" alt="screen shot 2017-05-16 at 5 42 07 pm" src="https://cloud.githubusercontent.com/assets/17548525/26129645/1663fb26-3a5f-11e7-8db9-185ee9847d91.png">

**Comment by amostajo** [comment]
Will add fixes to the pull-request of #899.

**Comment by amostajo** [comment]
@wpsmort I have added the rule so it strips out any url placed.
This will strip out oEmbed, or any other url not filtered by stripping tags.
Your thoughts?

**Comment by wpsmort** [comment]
@amostajo I tested this and it does strip out the URL from the placeholder text in the OG Description field but does not strip it from the og:description and twitter:description in the source code.  See screenshot.

<img width="1195" alt="screen shot 2017-05-22 at 12 55 51 pm" src="https://cloud.githubusercontent.com/assets/17548525/26319710/0f2039c2-3eee-11e7-889a-5b8ab6a0fb67.png">

**Comment by wpsmort** [comment]
This is tested and is good.  This is ready for a code review.
