### ISSUE TITLE
Non-breaking spaces appearing in auto-generated descriptions

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#899]
When a non-breaking space is left at the end of content it shows up in the auto generated SEO and OG descriptions in the source code like this - 

`<meta name="description"  content="This is my post content. This content ends here. &nbsp;" />`

**Comment by amostajo** [comment]
@wpsmort ready for review.

I have added a generic filter for head `meta` values, maybe we can use this in the future for the likes of og:descriptions and such.

Regards,

**Comment by amostajo** [comment]
Seems like HTML entities are allowed in meta descriptions ([read here](https://webmasters.stackexchange.com/questions/76522/are-html-encoded-symbols-allowed-in-meta-description)). So I changed my PR so it only removes `&nbsp;` for the time being.

**Comment by wpsmort** [comment]
@amostajo I tested this and I am still getting an &nbsp; on the end of my og:description. See screenshot.

<img width="983" alt="screen shot 2017-05-22 at 12 41 42 pm" src="https://cloud.githubusercontent.com/assets/17548525/26319239/335de43a-3eec-11e7-86e7-dd903f435fef.png">

**Comment by amostajo** [comment]
@wpsmort I added this already when I was working on issue #859; I have moved my changes to this pull-request so everything is related.

Please test again.

**Comment by wpsmort** [comment]
@amostajo I have tested this and it works for posts.

I tested with WooCommerce products and found that it does not work if your Product Short Description field has a non-breaking space at the end.  See screenshot.

<img width="902" alt="screen shot 2017-05-22 at 2 25 50 pm" src="https://cloud.githubusercontent.com/assets/17548525/26322827/a616ebe4-3efa-11e7-9bd8-c1d1b811d79a.png">

This affects both the SEO Description field and the OG Description field.  The meta tags in the source code are fine.

Please note that we have two other PRs related to this for stripping HTML markup, please check out the commits done under PRs #839 and #860.  I want to make sure you're aware of these so you're not changing code affected by those PRs.

**Comment by wpsmort** [comment]
@amostajo I have confirmed that this also affects Post Excerpts where there is a non-breaking space after the excerpt.

**Comment by amostajo** [comment]
It appears that this only affects placeholders and snippets. Filter is applied to the meta correctly.

**Comment by amostajo** [comment]
@wpsmort Fixed. I have refactored my code so it matches existing filters.

Proceed with final review, hopefully this is the last.

**Comment by wpsmort** [comment]
@amostajo I have updated PR #901 with the results of my latest testing.
