### ISSUE TITLE
Conflict with Woocommerce Errors

### ISSUE THREAD

**Issue by alichakery** [semperfiwebdesign/all-in-one-seo-pack#905]
Today I noticed that after installing AIOSEO Woocommerce errors do not show any more.

For example in MyAccount login page if you leave Login/Password empty and click on login button, the page would only gets reloaded and no error appears.

My site details : 

WP: 4.7.5
WooC: 3.0.7
AIOSEO: 2.3.12.5
Webserver: LiteSpeed
PHP: 5.6

thank you

**Comment by michaeltorbert** [comment]
If you're referring to the "Error: Username is required" message, I get that on my test site with both WooCommerce and AIOSEOP active.

**Comment by wpsmort** [comment]
I cannot reproduce the specific problem reported with the My account login page. I had no issues with generating errors in WooCommerce when All in One SEO Pack is active.  I could generate errors on the Account Details page by not completing the form correctly.

**Comment by arnaudbroes** [comment]
Same here:
![woocommerce error_censored](https://cloud.githubusercontent.com/assets/18156697/26378352/73ae49de-4014-11e7-9f5d-e6633cad9cb1.jpg)

**Comment by alichakery** [comment]
Maybe its a conflict with the theme but when I disable AIOSEO errors are shown.

I also found a similar report which is not exactly like mine : 
https://wordpress.org/support/topic/woocommerce-account-not-showing-messages/

I am using Genesis Theme with Envy child theme.

**Comment by arnaudbroes** [comment]
@alichakery 
Are you able to provide me with the .zip file of the Envy theme? 
We've already got Genenis but we also need Envy to find out whether the theme is causing issues.
Please send it to me at abroes@semperfiwebdesign.

**Comment by alichakery** [comment]
Yes sure.

But I am using a very customized version of envy. And the only thing that I forgot to mention is that I am using cloudflare and a plugin called woocommerce categories as subdomain.

I will send you my theme as soon as I get home.

Thank you

**Comment by michaeltorbert** [comment]
@alichakery 

Does the problem go away if you switch to the default theme (Twenty Seventeen)?

**Comment by arnaudbroes** [comment]
@alichakery 
I tested this with the latest unmodified build of the Envy theme that I received from Jon Baratt (developer) and it caused no issues. 
You also stated on the free forum (https://goo.gl/91f5lR) that you already tested this by deactivating all plugins besides WooCommerce and All in One SEO Pack, so there's nothing going there as well. 
The only viable explanation is that your customizations to the theme are causing the errors, which we unfortunately can't help you with.
