### ISSUE TITLE
Possible duplicate function with moved PHPDoc block

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#909]
Noticed we have two functions doing the exact same thing: 
![image](https://cloud.githubusercontent.com/assets/18156697/26589602/b9f8e2d4-4558-11e7-850d-15315defac86.png)

Originally only the xml_string_to_array function existed. Later the html_string_to_array function was added and it seems like the PHPDoc block from xml_string_to_array got moved to html_string_to_array.

**Comment by michaeltorbert** [comment]
At a glance... looks like they're used for different purposes, one for html strings and one for xml strings... but that in practice the same code is able to be used for both.

So either a) we could combine them into one or b) leave them as separate in case in the future one needs something the other doesn't

**Comment by arnaudbroes** [comment]
I've moved the PHPDoc back from html_string_to_array because I'm sure this belongs to the xml_string_to_array function.

**Comment by contactashish13** [comment]
follow up to remove duplicate code but retain the 2 functions: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1593

**Comment by michaeltorbert** [comment]
FYI, html_string_to_array is used once, and xml_string_to_array isn't used at all (old code in the "deprecated" file which can probably be deleted). 
Maybe we should just remove it instead of calling one function with the other. @contactashish13 Thoughts?

**Comment by contactashish13** [comment]
have removed the file `deprecated.php` as well as the function `xml_string_to_array`

**Comment by michaeltorbert** [comment]
@contactashish13  Where is the commit/PR?
