### ISSUE TITLE
Standalone comment block should probably be merged

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#911]
This standalone comment block should probably be merged with either the function above or below it.
I'm not sure to which one it applies.

Lines 146-149 in meta_import.php.

```
/**
 * This function displays feedback to the user about compatible conversion
 * elements and the conversion process via the admin_alert hook.
 */
```

**Comment by michaeltorbert** [comment]
@arnaudbroes Good catch. I suspect a function was deleted or merged with another and this got orphaned.
