### ISSUE TITLE
Performance Module - Remove Check for Updates button

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#913]
On the Performance screen in the System Status box is a Check for updates button which we can remove.

<img width="1250" alt="screen shot 2017-05-31 at 4 04 50 pm" src="https://cloud.githubusercontent.com/assets/17548525/26652190/0d1b5ae0-461d-11e7-9110-e537b66d8758.png">

**Comment by michaeltorbert** [comment]
For testing, just copy and overwrite modules/aioseop_performance.php to Pro locally on your computer/server.

**Comment by wpsmort** [comment]
This is tested and is good.
