### ISSUE TITLE
Single blank space in og:description when non-breaking space it present

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#914]
This relates to #901.  Whilst testing that PR, I found that when you have an excerpt that ends with a non-breaking space (&nbsp;) then the non-breaking space is stripped but replaced with a single blank space.  I notified @amostajo about this so he could investigate.  

PR #901 has now been closed and merged into the development branch hence this new issue which will require a new PR.

**Comment by amostajo** [comment]
@wpsmort please test this.

**Comment by wpsmort** [comment]
This is tested and is fixed.  It is ready for a code review - PR #915
