### ISSUE TITLE
Manually entered links are stripped from descriptions

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#916]
This is related to #910 

When you manually enter a link in the SEO Description or OG Description fields, the HTML and link text is stripped.  We should only strip the HTML, not the link text.  For example:

`<a href="https://google.com/" target="_blank">Link text</a>`

should become:

Link text

**Comment by amostajo** [comment]
@wpsmort ready for review.

**Comment by wpsmort** [comment]
This is tested and is good.  PR #927 is ready for code review.
