### ISSUE TITLE
Fatal error: all-in-one-seo-pack/admin/aioseop_module_class.php on line 506

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#918]
Reported here - https://wordpress.org/support/topic/fatal-error-all-in-one-seo-packadminaioseop_module_class-php-on-line-506/

This was reported immediately after the release of v2.3.13.

**Comment by wpsmort** [comment]
This only affects users on PHP v5.4 and earlier.  When testing with PHP v5.5 and later, no fatal error was produced.

**Comment by wpsmort** [comment]
To reproduce, check the first three boxes in Bad Bot Blocker and then save.  Visiting any page on the site will generate the fatal error.

**Comment by wpsmort** [comment]
This was introduced by the commit in #680.

**Comment by michaeltorbert** [comment]
https://secure.php.net/manual/en/function.empty.php

> "Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In 

> other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false."

This was broken in #680 from @stanislavsa
