### ISSUE TITLE
add %post_date% post title format

### ISSUE THREAD

**Issue by davidhyland** [semperfiwebdesign/all-in-one-seo-pack#920]
Using your plugin for the first time having switched from Yoast as it's been getting rather bloaty. Love the simplicity but I would love to see an option for adding %post_date% as a post title format. 

More specifically separate %post_year% and %post_month% tags would be awesome!

Thanks dude

**Comment by michaeltorbert** [comment]
This is added for both page, post, and CPT titles and descriptions (with autogenerate turned on)

**Comment by wpsmort** [comment]
This is tested and is good.

**Comment by davidhyland** [comment]
Thank you so much for this update, really appreciate it! Have a good one wherever you are.
