### ISSUE TITLE
Track Outbound Links doesn't appear to be functioning

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#921]
This can be confirmed on our own sites where no outbound links show up since about April or May of 2014.

We should have an event category "Outbound Links" with the action being the URL in google analytics, but it's not there.

https://support.google.com/analytics/answer/1136920?hl=en

**Comment by wpsmort** [comment]
The documentation provided by Google here https://support.google.com/analytics/answer/1136920?hl=en requires the onclick attribute is added to all links which we can't do.  I believe that we came up with a different solution using JavaScript when this feature was implemented.  It's possible that this JavaScript no longer does what we think it should.  

However, theres code called Autotrack which we could use - see the note from Google (https://developers.google.com/analytics/devguides/collection/analyticsjs/events) below:

Developers wanting to track outbound links and forms can use autotrack, which includes the outboundLinkTracker and outboundFormTracker plugins that handle these complexities for you. See the autotrack documentation for usage and installation instructions.

Here's the link to autotrack - https://github.com/googleanalytics/autotrack

**Comment by wpsmort** [comment]
Here's the current JavaScript we output for outbound link tracking.   @amostajo is going to review this and see if there's something wrong with this and see if Autotrack will work instead.

```
<script type="text/javascript">
						function recordOutboundLink(link, category, action) {
														ga('send', 'event', category, action);
														if (link.target == '_blank') return true;
							setTimeout('document.location = "' + link.href + '"', 100);
							return false;
						}
						/* use regular Javascript for this */
						function getAttr(ele, attr) {
							var result = (ele.getAttribute && ele.getAttribute(attr)) || null;
							if (!result) {
								var attrs = ele.attributes;
								var length = attrs.length;
								for (var i = 0; i < length; i++)
									if (attr[i].nodeName === attr) result = attr[i].nodeValue;
							}
							return result;
						}

						function aiosp_addLoadEvent(func) {
							var oldonload = window.onload;
							if (typeof window.onload != 'function') {
								window.onload = func;
							} else {
								window.onload = function () {
									if (oldonload) {
										oldonload();
									}
									func();
								}
							}
						}

						function aiosp_addEvent(element, evnt, funct) {
							if (element.attachEvent)
								return element.attachEvent('on' + evnt, funct);
							else
								return element.addEventListener(evnt, funct, false);
						}

						aiosp_addLoadEvent(function () {
							var links = document.getElementsByTagName('a');
							for (var x = 0; x < links.length; x++) {
								if (typeof links[x] == 'undefined') continue;
								aiosp_addEvent(links[x], 'onclick', function () {
									var mydomain = new RegExp(document.domain, 'i');
									href = getAttr(this, 'href');
									if (href && href.toLowerCase().indexOf('http') === 0 && !mydomain.test(href)) {
										recordOutboundLink(this, 'Outbound Links', href);
									}
								});
							}
						});
					</script>
```

**Comment by amostajo** [comment]
@wpsmort that piece of code is enabled only if two settings are on.., `aiosp_ga_advanced_options` and `aiosp_ga_track_outbound_links`, I looked at the plugin settings and wasn't able to find them, do you know where I can activate them?

**Comment by wpsmort** [comment]
@amostajo You can find both options under All in One SEO > General Settings > Google Settings.  The first is Advanced Analytics Options which is a radial.  Once this is set to Enabled you'll see the second which is Track Outbound Links.

https://semperplugins.com/documentation/advanced-google-analytics-settings/

**Comment by wpsmort** [comment]
This PR #931 adds a number of new options to the Google Settings section.  We discussed on Slack whether these should be included or be held back.  I believe they should be held and just the option for Track Outbound Links should be included for now.

**Comment by michaeltorbert** [comment]
@wpsmort Should this still be assigned to me for code review or is it back to @amostajo?

**Comment by wpsmort** [comment]
@amostajo I have updated PR #931 with some comments.

**Comment by amostajo** [comment]
@wpsmort fixes and changes applied ready for testing.

I have created a pro PR for this as well. Please test.
https://github.com/semperfiwebdesign/aioseop-pro/pull/340

**Comment by wpsmort** [comment]
@amostajo I have tested both PRs and they are both good.
I have one very minor change for you.  The closing HTML comment for All in One SEO Pack should appear on it's own line in the source code but now it's appearing on the same line as the last script like so:

`<script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.0/autotrack.js"></script><!-- /all in one seo pack pro -->`

Can you change this so it looks like this with the correct indenting as well:

```
        <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.0/autotrack.js"></script>
<!-- /all in one seo pack pro -->
```

**Comment by amostajo** [comment]
@wpsmort Let me know if the indent pushed works

**Comment by wpsmort** [comment]
@amostajo Thanks, this is tested and is good.
