### ISSUE TITLE
Edit SEO url is at the bottom of every page on the site when logged in

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#922]
Reported here:
https://wordpress.org/support/topic/error-after-update-99/
https://wordpress.org/support/topic/odd-edit-url-on-pages-when-logged-in/
https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/line-of-code-appears-below-the-footer
https://wordpress.org/support/topic/bug-in-footer/

**Comment by michaeltorbert** [comment]
This was broken in #902 and should be fixed now

**Comment by wpsmort** [comment]
This is tested and confirmed that it fixes the bug.
