### ISSUE TITLE
Fatal Error - www.sherrikayaks.com

### ISSUE THREAD

**Issue by DerrickAm** [semperfiwebdesign/all-in-one-seo-pack#924]
Our client's website is now showing...

Warning: require_once(/home/sherrik/public_html/wp-content/plugins/all-in-one-seo-pack/inc/aioseop_functions.php): failed to open stream: No such file or directory in /home/sherrik/public_html/wp-content/plugins/all-in-one-seo-pack/all_in_one_seo_pack.php on line 381

Fatal error: require_once(): Failed opening required '/home/sherrik/public_html/wp-content/plugins/all-in-one-seo-pack/inc/aioseop_functions.php' (include_path='.:/opt/php54/lib/php') in /home/sherrik/public_html/wp-content/plugins/all-in-one-seo-pack/all_in_one_seo_pack.php on line 381

This happened after an automatic update.  I have tried changing the name of the directory in ftp, deleting the directory, reinstalling, etc.. 

The version is 2.3.13.1 and it shows no updates available.

**Comment by michaeltorbert** [comment]
@DerrickAm This is almost certainly a server caching issue.
