### ISSUE TITLE
All in One SEO Pack 

### ISSUE THREAD

**Issue by RUSxDeviL1979** [semperfiwebdesign/all-in-one-seo-pack#926]
Hello everyone I want to share one bug after updating plugin All in One SEO Pack appeared error https://bi-glass.ru/wp-admin/post.php?post=1271&action=edit it is only visible in the admin panel if you go to the site it is not visible
---------------------------------------------------

всем привет спешу поделиться одним багом после обновления плагина All in One SEO Pack появилась ошибка https://bi-glass.ru/wp-admin/post.php?post=1271&action=edit  она видна только в админ панели если выйти с сайта она не видна  https://yadi.sk/i/7unntEii3JmiNv

**Comment by michaeltorbert** [comment]
@RUSxDeviL1979 This is fixed in 2.3.13.2 which was released today.

**Comment by RUSxDeviL1979** [comment]
Спасибо ))
