### ISSUE TITLE
Double quotes not escape in meta descriptions

### ISSUE THREAD

**Issue by fahmi182** [semperfiwebdesign/all-in-one-seo-pack#928]
Hi, i'm your member aio PRO, our problem is, double quotes in meta description not escape, that cause error our html format, can you check please?

Thanks!

**Comment by wpsmort** [comment]
Reported here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/meta-descriptions-double-quotes-not-escape/#p6643

**Comment by wpsmort** [comment]
Duplicate of #593
