### ISSUE TITLE
AMP errors

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#936]
Possible AMP errors > 2.3.12.5

Reported here: https://wordpress.org/support/topic/amp-errors-explosion/

**Comment by nextpulse** [comment]
Not just AMP pages. I am seeing this on regular pages too.

**Comment by michaeltorbert** [comment]
@nextpulse What are you seeing?

**Comment by nextpulse** [comment]
Example:

For FB og and twitter description:

2.3.12.5 : 
"Richard Claxton &quot;Dick&quot; Gregory ....

2.3.13.2:
"Richard Claxton "Dick" Gregory....

**Comment by michaeltorbert** [comment]
@wpsmort @amostajo Is this related to #929 and/or #593 
If so, was it fixed in https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/3f579ce3cb1f456d8d0d93ccefccb678751906f1 ?

**Comment by amostajo** [comment]
@michaeltorbert The latest PRs I have developed convert any equivalent and charcode of double quotes, single quote or similar into html entities enabled for in searches and social tags.

**Comment by michaeltorbert** [comment]
Closing as this is fixed in the upcoming release.
