### ISSUE TITLE
link to XML sitemap in robots.txt isn't https

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#937]
https://semperplugins.com/robots.txt and https://semperfiwebdesign.com/robots.txt are http, although strangely https://michaeltorbert.com/robots.txt is https

**Comment by michaeltorbert** [comment]
Also, the one at semperplugins doesn't link to the video sitemap

**Comment by michaeltorbert** [comment]
This may be fixed in 2.7 free/2.8 pro?

**Comment by wpsmort** [comment]
I have confirmed that this was fixed in the new Robots.txt module released in v2.7
