### ISSUE TITLE
Sitemap.xml Additional Pages break with no date entered

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#940]
reported here: https://wordpress.org/support/topic/sitemap-xml-additional-pages/
_ not manually entered a Last Modified date that the options stored in the db ended up empty.

In the aioseop_sitemap.xml the date conversion around line 2272 when used with an empty date string returns 1970-01-01. We had entered a lot of URLs before I released so I implemented a temporary solution adding a basic check

$mod = (empty($mod) ? date(“Y-m-d”) : $mod);

just above this line

$mod = date( ‘Y-m-d\TH:i:s\Z’, mysql2date( ‘U’, $mod ) );_

**Comment by contactashish13** [comment]
@michaeltorbert I believe all the 4 parameters are mandatory. We should have a date selector as well as validate the values and reject values that do not have all 4 parameters. Thoughts?


![image](https://user-images.githubusercontent.com/12953439/32874371-d6f9cfe4-cab7-11e7-9bd2-60530e1e6f34.png)

**Comment by michaeltorbert** [comment]
@contactashish13 Agreed.

**Comment by contactashish13** [comment]
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1364

I can't seem to get rid of codeclimate's false positives. Is there a code directive that I can use in the future to make it ignore specific lines?

**Comment by michaeltorbert** [comment]
We don't want it to ignore specific lines, instead we should use the config file to fine tune it. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/.codeclimate.yml

**Comment by michaeltorbert** [comment]
@contactashish13  We don't want it to ignore specific lines, instead we should use the config file to fine tune it. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/.codeclimate.yml
