### ISSUE TITLE
Compressed sitemaps return 404 when using NGINX

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#945]
Using NGINX, compressed sitemaps return a 404.

Can something be changed in the rewrite rules to support this?
https://semperplugins.com/documentation/all-in-one-seo-pack-xml-sitemap-404-nginx/

Otherwise, we may want to consider having compression off by default.

**Comment by arnaudbroes** [comment]
@contactashish13 are you able to see if we can resolve this issue?

In order to reproduce the issue, please follow these steps:

1. Set up an NGINX test server with WordPress
2. Install AIOSEOP and activate the XML Sitemap module
3. Check if Sitemap Compression is enabled
4. Go to yourdomainname.com/sitemap.xml.gz and you should get a 404 page

**Comment by michaeltorbert** [comment]
How about we do both compressed and not compressed at the same time. We link to the uncompressed in the module, but if someone were to hit the compressed version that would work too (assuming it actually works).
That doesn't fix this issue, but for most people that would at least get their sitemap working from their perspective.

**Comment by michaeltorbert** [comment]
Well... on nginx on Local by Flywheel, even without compression, I'm getting a 404.

**Comment by tonyzeoli** [comment]
If you're thinking it's a WP Engine / NGINX issue, it's happened on all of my WP Engine sites, so I think it's got to be the culprit.

**Comment by tonyzeoli** [comment]
Oh, wait. I forgot. Bookstr is on Pantheon, not on WP Engine. But most of my sites on WP Engine have this problem anyway. So, it could be NGINX at Pantheon, as well.

**Comment by arnaudbroes** [comment]
@tonyzeoli it is. I checked using the WhatRuns extension for Chrome.

**Comment by arnaudbroes** [comment]
Steve and I suspect this has something to do with the rewrite rules.

**Comment by michaeltorbert** [comment]
Steve and Arnaud believe it may have to do with the rewrite rules.

**Comment by wpsmort** [comment]
We found that the NGINX rewrite rules in our documentation were missing the appropriate rules for the gzipped files.  These rules work fine:

```
	# Rewrites for AIOSEOP XML Sitemap
	rewrite ^/sitemap.xml$ /index.php?aiosp_sitemap_path=root last;
	rewrite ^/sitemap_(.+)_(\d+).xml$ /index.php?aiosp_sitemap_path=$1&aiosp_sitemap_page=$2 last;
	rewrite ^/sitemap_(.+).xml$ /index.php?aiosp_sitemap_path=$1 last;
	
	rewrite ^/sitemap.xml.gz$ /index.php?aiosp_sitemap_path=root.gz last;
	rewrite ^/sitemap_(.+)_(\d+).xml.gz$ /index.php?aiosp_sitemap_path=$1.gz&aiosp_sitemap_page=$2 last;
	rewrite ^/sitemap_(.+).xml.gz$ /index.php?aiosp_sitemap_path=$1.gz last;
```

These rules are taken from our function get_rewrite_rules in the aioseop_sitemap.php file.

**Comment by wpsmort** [comment]
@EkoJR Now that we know what rewrite rules are needed for nginx users, can you see if there's any way we can incorporate this into the plugin because many hosting companies don't allow custom rules to be added to the nginx.conf file on their servers.
