### ISSUE TITLE
Character counter counts ampersands as 4 characters

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#951]
Reported here - https://wordpress.org/support/topic/meta-description-gets-cut-short/

I tested with the same description and whilst the description is only 151 characters, we seem to be treating it as longer.  I believe this is because we're counting the & sign as four characters, i.e. &amp

**Comment by wpsmort** [comment]
I tested and found that the & sign is actually treated as 4 characters &amp

**Comment by wpsmort** [comment]
I noticed today whilst testing with AIOSEOP v2.3.14.2 that apostrophes in the Site Title are being counted as 6 characters in autogenerated titles.  For example, if you set your Site Title in WordPress to Steve's Site, the autogenerated title on the Edit Post screen shows 20 characters even though "Steve's Site" is only 12 characters.  This is because it's counting the apostrophe as 6 characters for `&#039;`

**Comment by amostajo** [comment]
I am not a SEO savvy, but I have a question here, do the character count affect SEO in some sort of way or is it just to make sure that the text will display well on search engine results?

Because if it does matter, then it should be counted right?

As much as I know, the count was just to make sure snippets will look clean, the have not much influence when indexing on Google, if this is right then yes, the count should be altered so it does not count all charactore in html entities codes.
https://stackoverflow.com/questions/891977/do-html-entities-in-meta-tags-influence-indexing 

What are your thoughs @wpsmort @michaeltorbert ?

**Comment by wpsmort** [comment]
@amostajo The character count is to ensure a clean snippet in SERPs that does not exceed the number of characters allowed, resulting in an ellipses cutting off the title or description.  If Google counts an ampersand or apostrophe as a single character then we should too.

**Comment by amostajo** [comment]
@wpsmort  So this only happens for auto-generated?

**Comment by wpsmort** [comment]
@amostajo Yes, it only happens with the auto generated titles.  The easiest way to test this is to set your Site Title to abc' and then leave your post title empty.  The character count for the title should show 12 which breaks down as:

3 for the space | space
3 for the abc
6 for the `&#039;`

You can do the same with the ampersand to get a count of 11 (5 for the `&amp;`)

**Comment by amostajo** [comment]
Ready for testing.

**Comment by wpsmort** [comment]
@amostajo I've tested this and found one problem:

If you enable the Use Content For Autogenerated Descriptions and the content includes an ampersand then the meta description is shortened.  It is not shortened if you disable that option.

The content I'm using is below which is exactly 160 characters but it gets shortened to 150 characters in my meta description:

C&23456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789

**Comment by amostajo** [comment]
@wpsmort Ready for testing

**Comment by wpsmort** [comment]
PR #1031 is tested and is good.
