### ISSUE TITLE
Add column for image count to XML Sitemap

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#954]
Examples:
<img width="107" alt="screen shot 2017-07-11 at 4 56 35 pm" src="https://user-images.githubusercontent.com/17364998/28090404-2006c330-665a-11e7-82d9-534600e17a84.png">
<img width="872" alt="screen shot 2017-07-11 at 4 59 53 pm" src="https://user-images.githubusercontent.com/17364998/28090471-65741eb8-665a-11e7-8a0f-30640942074b.png">

**Comment by wpsmort** [comment]
@michaeltorbert I think this is a good idea.  I have opened a similar issue under Pro (https://github.com/semperfiwebdesign/aioseop-pro/issues/275) to add a column for video count.

**Comment by contactashish13** [comment]
@michaeltorbert Just to clarify, you need a column to show in the post listing which should display the number of images. The images should include the images in the post content + the featured image, basically all images after the_content filter is applied. Is that correct?

![image](https://user-images.githubusercontent.com/12953439/28199775-dec918c2-6885-11e7-80fe-7dae4f3ad23b.png)

**Comment by wpsmort** [comment]
@contactashish13 No, this is for the XML Sitemap.  We need a column added to the human readable XML Sitemap that shows the number of images found for each URL.  

See screenshot of an XML Sitemap with this image column below:

<img width="1035" alt="screen shot 2017-07-14 at 5 35 08 pm" src="https://user-images.githubusercontent.com/17548525/28231731-04e0b378-68bb-11e7-9989-ef124acdb123.png">

**Comment by contactashish13** [comment]
@wpsmort this must sound like a dumb question, but by human readable sitemap are you referring to the tabular structure shown on the browser while accessing the sitemap?

**Comment by wpsmort** [comment]
@contactashish13 Yes, that is correct. This is not part of the XML format for sitemaps so it should only be part of the human readable sitemap and not part of the XML that gets submitted to search engines.

**Comment by contactashish13** [comment]
@wpsmort I'm confused. From what I understand, the browser automatically displays the XML as an HTML. And you want someway to introduce an element in the XML so that it shows in the HTML but not in XML?

**Comment by contactashish13** [comment]
@wpsmort actually I think I understand what needs to be done. Ignore my previous message :)

**Comment by contactashish13** [comment]
@wpsmort I assume this change is required in both the free and pro versions - the code for displaying the html sitemap is present in both.

**Comment by michaeltorbert** [comment]
@contactashish13 Development of shared code is done in the free repository. Once we're ready to release, I'll copy it over to the Pro repository. (Not a great system, but it's what we have for now).

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/978

**Comment by wpsmort** [comment]
@contactashish13 I tested PR #978 and got the following warnings:

PHP Warning:  DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 14 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632
PHP Warning:  DOMDocument::loadHTML(): Tag figcaption invalid in Entity, line: 14 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632
PHP Warning:  DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 16 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632
PHP Warning:  DOMDocument::loadHTML(): Tag figcaption invalid in Entity, line: 16 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632
PHP Warning:  DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 20 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632
PHP Warning:  DOMDocument::loadHTML(): Tag figcaption invalid in Entity, line: 20 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632
PHP Warning:  DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 22 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632
PHP Warning:  DOMDocument::loadHTML(): Tag figcaption invalid in Entity, line: 22 in /all-in-one-seo-pack--954/modules/aioseop_sitemap.php on line 2632

**Comment by contactashish13** [comment]
@wpsmort I've addressed this. You should not see these warnings now.

**Comment by wpsmort** [comment]
@contactashish13 Thanks, that fixed those.  I think we should remove the 0 from categories, tags, custom taxonomies, date archives, author archives and any other types of archives where we're not going to be detecting images.

**Comment by contactashish13** [comment]
@wpsmort can you show me a sample sitemap to help me understand where to exclude the count? also, do you want to show -- or N/A or something else besides 0?

**Comment by wpsmort** [comment]
@contactashish13 Here's a screenshot of an XML Sitemap that has posts, pages, products, categories, tags, product categories and product tags.  You can see that we output a zero next to all the categories, tags, and product categories and tags.  

We should first try to if the archive page has an image (for example in WooCommerce you can set a product category image) and if there is an image(s) then we output the number, and if it doesn't then we should not output anything (like you see with the Last Change column which is empty).  

My reasoning is that users may find it confusing when they look at a category archive and see the featured images from the posts in that category.  But those images are in the posts not the category, the category is an archive so it doesn't have an image (there's no image field when you edit a category or tag).   This applies to all archives - categories, tags, date, author, custom tax, etc.

Let me know if this doesn't make sense. 

<img width="1205" alt="screen shot 2017-07-24 at 6 09 59 pm" src="https://user-images.githubusercontent.com/17548525/28547298-43085172-709c-11e7-8a6f-6fb81d387c0e.png">

**Comment by contactashish13** [comment]
@wpsmort have made my changes to support this

**Comment by wpsmort** [comment]
@contactashish13 Please extend this to remove the zeros next to date archives and author archives.  You can see these archives by checking the check boxes for Include Date Archive Pages and Include Author Pages (https://semperplugins.com/documentation/xml-sitemaps-module/#include-archive-pages).  See screenshot:

<img width="1135" alt="screen shot 2017-07-25 at 1 08 38 pm" src="https://user-images.githubusercontent.com/17548525/28584375-828ebd9c-713a-11e7-85c3-2ac52fc63ecf.png">

**Comment by wpsmort** [comment]
@contactashish13 I found a compatibility issue with Jetpack.  This commit https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/978/commits/732c399ea47240b35c7baf21c1cf4a8688a7639c has a change to line 2599 of the modules/aioseop_sitemap.php file.  That change results in a blank sitemap when Jetpack is active.

**Comment by contactashish13** [comment]
@wpsmort I activated jetpack on my instance and was able to view the sitemap without any problem. Maybe it is a particular setting of jetpack. Would you be able to tell me which setting causes this problem? Alternatively,  I can debug the issue on your test site

**Comment by contactashish13** [comment]
@wpsmort I feel the behavior of the sitemap is fine w.r.t the numbers showing against the URLs.  If you check, a blank is shown in the images column only when the last modified date is also blank. This only happens for archive type URLs.  And if the URL has images, like the date archive that shows 8, it shows against it.

**Comment by wpsmort** [comment]
@contactashish13 My problem here is that an archive is an archive of posts.  Archives by their nature don't have images so there shouldn't be a number in the image column.  Date archives and author archives are no different to category and tag archives. We should therefore treat them exactly the same and either display a number or not display a number.  

My question is therefore, can you detect the number of images in posts in a category or tag archive?  If you cannot then we should remove the numbers from date and author archives.

**Comment by contactashish13** [comment]
@wpsmort can you please check the PR again? I believe my recent changes should exclude everything except single posts/pages/CPTs

**Comment by contactashish13** [comment]
@wpsmort I've had to change the entire approach. Now I'm defining a custom XSD (attached) and the sitemap xml will contain a custom element namespaced to this XSD that will define the number of images. 

Can you please host the XSD on an appropriate URL and change the URLs here:
1. in the XSD
2. https://github.com/contactashish13/all-in-one-seo-pack/blob/%23954/modules/aioseop_sitemap.php#L1955
3. https://github.com/contactashish13/all-in-one-seo-pack/blob/%23954/inc/sitemap-xsl.php#L21


[aioseop.zip](https://github.com/semperfiwebdesign/all-in-one-seo-pack/files/1195953/aioseop.zip)

**Comment by wpsmort** [comment]
@contactashish13 I tested the latest code in PR #978 and it worked, however, Google rejects the XML Sitemap because the numImages tag is unrecognized by them.

Also, we won't want to host the XSD file on our servers, the XSD file should be part of the plugin.

**Comment by contactashish13** [comment]
@wpsmort according to the sitemap XSD, https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd I can include any other valid namespaced tag so I'm not sure why it is being rejected

![image](https://user-images.githubusercontent.com/12953439/28953210-34d838be-78f4-11e7-9bad-5cee035e033d.png)

**Comment by wpsmort** [comment]
@contactashish13 Here's a screenshot of what I get in Google Webmaster Tools:

<img width="1152" alt="screen shot 2017-08-04 at 4 34 39 pm" src="https://user-images.githubusercontent.com/17548525/28985965-fe9f47bc-7932-11e7-8a15-443641abf324.png">

The line numbers referred to in the test results matches each line where there's a `<aioseop:numImages>` tag.  As Google is returning errors here, they won't accept the XML Sitemap.

Hopefully you can find a way around this.

**Comment by contactashish13** [comment]
@wpsmort I assume you submitted the sitemap after hosting the XSD publicly and changing the urls in the 3 places I mentioned?

**Comment by wpsmort** [comment]
@contactashish13 Yes, I tried that but it did not work.  Here's my sitemap - http://stevemortiboy.com/sitemap.xml

Google just does not like that XML tag and rejects the sitemap because of it.

**Comment by contactashish13** [comment]
@wpsmort that's really strange. I found this that seems to suggest that this is not a problem

https://stackoverflow.com/questions/21853057/creating-a-valid-sitemap-with-custom-attributes/32628830#32628830

**Comment by wpsmort** [comment]
@contactashish13 I see that the answer you linked to on stackoverflow does state that Google Webmaster Tolls returns an error.  In our case, we cannot have GWT return errors or it will mean users won't trust our XML Sitemap so this needs to be fixed a different way.

**Comment by contactashish13** [comment]
@wpsmort if google refuses to recognize a valid protocol, I'm not sure I know of any other way to approach this problem. Any suggestions?

**Comment by wpsmort** [comment]
@contactashish13 Is there any way to hide that tag from the source code?  It doesn't need to appear in the source code, it only needs to appear in the human readable sitemap.

**Comment by contactashish13** [comment]
@wpsmort I don't think so because the HTML sitemap is created from the XML sitemap

**Comment by wpsmort** [comment]
@contactashish13 You had been doing this before and it worked.  It wasn't until you changed the XSD that the imageNum tag started to appear in the source code.

**Comment by contactashish13** [comment]
@wpsmort If you remember, the change was required because my earlier approach was to include blank image:image tags in the XML which google did not like either. I agree with google in that case because the XSD dictates that image:image tag cannot be empty. If it cannot be empty, then there is no way to separate an archive from a post that has 0 images.

**Comment by wpsmort** [comment]
@contactashish13 I have messaged you in Slack about this as it's better for us to continue the conversation there.

**Comment by wpsmort** [comment]
@contactashish13 I tested the latest changes to PR #978 and there were no errors returned by Google.  I did notice two things I'd like to see if you can improve:

1. When you have a static home page and there are image on that home page, we list the homepage URL in the XML Sitemap even if you don't have Pages checked under XML Sitemap > Post Types. However, the image count is zero.  To reproduce this, create a static home page and add some images.  Under XML Sitemap > Post Types uncheck Pages and then view the sitemap.  You'll see the homepage URL listed but the image count is zero.  Now check the box for Pages and view the sitemap and the image count should be correct.

2. The image count is zero for media attachment pages.  The image should always be 1 for media attachment pages because a media attachment page is an attachment page for an image.

**Comment by contactashish13** [comment]
@wpsmort you really think of every possible scenario :) have added support for these.

**Comment by wpsmort** [comment]
@contactashish13 Looks like I found two final bugs:  

The first is with product categories in WooCommerce when the category has an image.  The source code is incorrect:

```
<url>
	<loc>http://stevemortiboy.com/product-category/product-seo-category/</loc>
	<priority>0.3</priority>
	<changefreq>monthly</changefreq>
	<image:image>
	<image:image>http://stevemortiboy.com/wp-content/uploads/2017/05/a-post-with-a-mix-of-videos.jpg</image:image>
	</image:image>
</url>
```
It's wrapping the  image in an `<image:image>` tag instead of an `<image:loc>` tag.

The second is with media attachment pages where the source code is also incorrect:

```
<url>
	<loc>http://stevemortiboy.com/home/venice/</loc>
	<image:image>1</image:image>
	<lastmod>2017-08-10T11:34:45Z</lastmod>
	<changefreq>daily</changefreq>
	<priority>0.9</priority>
</url>
```
This is also missing the image:loc tag.

**Comment by wpsmort** [comment]
@contactashish13 I tested the latest code under PR #978 and the two bugs reported above still exist.  You can see this here - view-source:http://stevemortiboy.com/sitemap.xml

**Comment by contactashish13** [comment]
@wpsmort I've pushed in my changes and tested on your site as well.

**Comment by contactashish13** [comment]
@wpsmort I'm also getting this notification from aiseop-bot that says something about cyclomatic complexity. I tried to fix it but it only increased it from 12 to 13. It looks like a false positive but any suggestion would be great.

**Comment by wpsmort** [comment]
@contactashish13 @amostajo or @michaeltorbert might be able to help you with this.

**Comment by michaeltorbert** [comment]
Those notices should be disabled now. Both of the complexity checks were terrible.

**Comment by amostajo** [comment]
@contactashish13 I usually get this notifications too. As long as your code follows wordpress coding standards, I think this notification can be ignored right?

**Comment by wpsmort** [comment]
This is tested and is good.  I have confirmed that there are no errors when submitting the sitemap to Google via Webmaster Tools.

**Comment by wpsmort** [comment]
See also #386
