### ISSUE TITLE
ACF macro is being output in titles and meta descriptions

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#959]
When you use the ACF macro (https://semperplugins.com/documentation/advanced-custom-fields-integration-with-title-format-fields/) in the Title Format field or Description Format field then we output the macro when the custom field is empty.

For example, if you have an ACF custom field called short_description and you use the macro %cf_short_description% in either the Title Format field or Description format field then you get this result when the field is empty on any post:

```
<title>%cf_short_description% | My Test Site</title>
<meta name="description"  content="%cf_short_description%" />
```

This also affects OG and Twitter meta tags as well.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1488

**Comment by wpsmort** [comment]
This is tested and is good.
