### ISSUE TITLE
Meta descriptions aren't output when using ACF macro in Description Format

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#960]
When you use the ACF macro (https://semperplugins.com/documentation/advanced-custom-fields-integration-with-title-format-fields/) in the Description Format field then no meta description is output unless content exists on the post and Autogenerate Descriptions is enabled.

To reproduce this, create a custom post type and then use Advanced Custom Fields to create a field called Custom Description.
Next, create a post in your new CPT and complete only the Title field and the Custom Description field.
Next, change the Description Format in AIOSEOP to %cf_custom_description%.
Check you post and you should see no description.  Now enable Autogenerate Descriptions and there should be no change.
Finally, edit your post and add some content in the Editor.  Now check and you should see your custom field output as the meta description.

I believe what is happening here is that when we generate meta descriptions we run through to see if there is content and if there's no content we don't do anything.  What we need to do is check to see if there is a custom field before returning nothing.

See also #959

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1483
