### ISSUE TITLE
filter_title only runs on the site title

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#964]
Unless I'm missing something, filter_title() (and by extension, html_entity_decode and seo_entity_encode) only runs on the blog title (which is appended by default to post titles), not on the post-specific part of the title.

To reproduce this, make a blog title of something like Bob's website and a post with a title like Bob's post and view the doc title in the source.

<img width="411" alt="screen shot 2017-07-15 at 9 37 29 am" src="https://user-images.githubusercontent.com/17364998/28239765-44992262-6941-11e7-8e70-8acda1802402.png">

**Comment by amostajo** [comment]
@michaeltorbert I can not reproduce this.

Test results
```
<title>Issue 1079 \| Piru&#039;s Store</title>
```
Is this still an issue on your end?

**Comment by michaeltorbert** [comment]
This may have been fixed in a recent update. I'm getting  `&#039;s` for both now.

**Comment by michaeltorbert** [comment]
@amostajo  This may have been fixed in a recent update. I'm getting  `&#039;s` for both now.
