### ISSUE TITLE
&amp;apos;s output in OG meta

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#968]
Whilst testing the release for v2.3.14.1 with the fix for issue #961 I found that the OG title and Twitter title have the incorrect character encoding.  See source code below:

```
<title>Steve’s Post Title | Steve&apos;s Test Site</title>
<meta property="og:title" content="Steve’s Post Title | Steve&amp;apos;s Test Site" />
<meta property="og:site_name" content="Steve&#039;s Test Site" />
<meta name="twitter:title" content="Steve’s Post Title | Steve&amp;apos;s Test Site" />
```

The doc title and og:site_name are fine but the og:title and twitter:title are not.

**Comment by amostajo** [comment]
[PR:970](https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/970)
Can't seem to replicate issue.

![698](https://user-images.githubusercontent.com/1645908/28243595-e21ab96e-698d-11e7-91f1-63ce022a6723.jpg)

**Comment by wpsmort** [comment]
@michaeltorbert I cannot reproduce this either.  I tested back through the commits to 2.3.14.1 and 2.3.14.2 and it looks like PR #970 did fix this issue by replacing `&apos;` with `&#039;`

**Comment by michaeltorbert** [comment]
Closing this as it was fixed in the same version that broke it, pre-release.
