### ISSUE TITLE
Hyphens in doc title get converted to apostrophes

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#979]
Reported here - https://wordpress.org/support/topic/error-in-title-the-became/

When you use a hyphen in a post title it is displayed as an apostrophe in the doc title.  See screenshot:

<img width="1024" alt="screen shot 2017-07-19 at 10 59 19 am" src="https://user-images.githubusercontent.com/17548525/28373993-765be54a-6c71-11e7-9cfa-52e31c00ae8e.png">

**Comment by wpsmort** [comment]
@amostajo I tested this and found that in the doc title, og:title and twitter:title the hyphen is encoded as &#039; but in the meta description, og:description and twitter:description it is output as a hyphen -

**Comment by michaeltorbert** [comment]
The problem is that &#8211 is a dash, not an apostrophe, which we're checking for in aioseop_class.php.

**Comment by wpsmort** [comment]
This is tested and is good.  I tested all of the following special characters:

Exclamation! &quot;Quotes&quot; Hash# Dollar$ Percent% And &amp; Apostrophe&#039; (Parenthesis) Asterisk* Plus+ Comma, Hyphen &#8211; Period. Slash/ Colon: Semicolon; Less&lt; Greater&gt; Equal = Question? At @ [Brackets] Backslash\ Caret^ Underscore_ Grave` {Braces} Pipe | Tilde~
