### ISSUE TITLE
Making it easy to download the Pro pack from the web site

### ISSUE THREAD

**Issue by paaljoachim** [semperfiwebdesign/all-in-one-seo-pack#992]
Hey

It would be nice to login at https://semperplugins.com and then in the profile section or some other place and download the Pro plugin.

I found this page:
https://semperplugins.com/faqs/i-purchased-all-in-one-seo-pack-pro-version-where-is-the-download/

It would be better to make the Pro pack easier available for download through the site without having to dig through older e-mails and locate the correct link.

**Comment by michaeltorbert** [comment]
Hi @paaljoachim 

Thank you for your suggestion. 
This is something we're working on at the moment. An issue is open in our internal private repository.
